const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);

// KEY-based translations (match by dot-notation key, not by value)
const K={
// === EDITOR ===
"editor.paragraph":{en:"Paragraph",pt:"Parágrafo",fr:"Paragraphe",de:"Absatz",it:"Paragrafo",nl:"Alinea",ja:"段落",zh:"段落",ru:"Параграф",ar:"فقرة",hi:"अनुच्छेद",ko:"단락",tr:"Paragraf",pl:"Akapit",sv:"Stycke",id:"Paragraf",th:"ย่อหน้า"},
"editor.heading1":{en:"Heading 1",pt:"Título 1",fr:"Titre 1",de:"Überschrift 1",it:"Titolo 1",nl:"Kop 1",ja:"見出し1",zh:"标题1",ru:"Заголовок 1",ar:"عنوان 1",hi:"शीर्षक 1",ko:"제목 1",tr:"Başlık 1",pl:"Nagłówek 1",sv:"Rubrik 1",id:"Judul 1",th:"หัวข้อ 1"},
"editor.heading2":{en:"Heading 2",pt:"Título 2",fr:"Titre 2",de:"Überschrift 2",it:"Titolo 2",nl:"Kop 2",ja:"見出し2",zh:"标题2",ru:"Заголовок 2",ar:"عنوان 2",hi:"शीर्षक 2",ko:"제목 2",tr:"Başlık 2",pl:"Nagłówek 2",sv:"Rubrik 2",id:"Judul 2",th:"หัวข้อ 2"},
"editor.heading3":{en:"Heading 3",pt:"Título 3",fr:"Titre 3",de:"Überschrift 3",it:"Titolo 3",nl:"Kop 3",ja:"見出し3",zh:"标题3",ru:"Заголовок 3",ar:"عنوان 3",hi:"शीर्षक 3",ko:"제목 3",tr:"Başlık 3",pl:"Nagłówek 3",sv:"Rubrik 3",id:"Judul 3",th:"หัวข้อ 3"},
"editor.bold":{en:"Bold",pt:"Negrito",fr:"Gras",de:"Fett",it:"Grassetto",nl:"Vet",ja:"太字",zh:"粗体",ru:"Жирный",ar:"عريض",hi:"बोल्ड",ko:"굵게",tr:"Kalın",pl:"Pogrubienie",sv:"Fet",id:"Tebal",th:"ตัวหนา"},
"editor.italic":{en:"Italic",pt:"Itálico",fr:"Italique",de:"Kursiv",it:"Corsivo",nl:"Cursief",ja:"斜体",zh:"斜体",ru:"Курсив",ar:"مائل",hi:"तिरछा",ko:"기울임",tr:"İtalik",pl:"Kursywa",sv:"Kursiv",id:"Miring",th:"ตัวเอียง"},
"editor.underline":{en:"Underline",pt:"Sublinhado",fr:"Souligné",de:"Unterstrichen",it:"Sottolineato",nl:"Onderstreept",ja:"下線",zh:"下划线",ru:"Подчёркнутый",ar:"تحته خط",hi:"रेखांकित",ko:"밑줄",tr:"Altı çizili",pl:"Podkreślenie",sv:"Understrykning",id:"Garis bawah",th:"ขีดเส้นใต้"},
"editor.strikethrough":{en:"Strikethrough",pt:"Tachado",fr:"Barré",de:"Durchgestrichen",it:"Barrato",nl:"Doorgehaald",ja:"取り消し線",zh:"删除线",ru:"Зачёркнутый",ar:"يتوسطه خط",hi:"स्ट्राइकथ्रू",ko:"취소선",tr:"Üstü çizili",pl:"Przekreślenie",sv:"Genomstruken",id:"Coret",th:"ขีดทับ"},
"editor.list":{en:"List",pt:"Lista",fr:"Liste",de:"Liste",it:"Elenco",nl:"Lijst",ja:"リスト",zh:"列表",ru:"Список",ar:"قائمة",hi:"सूची",ko:"목록",tr:"Liste",pl:"Lista",sv:"Lista",id:"Daftar",th:"รายการ"},
"editor.orderedList":{en:"Ordered list",pt:"Lista numerada",fr:"Liste numérotée",de:"Nummerierte Liste",it:"Elenco numerato",nl:"Genummerde lijst",ja:"番号付きリスト",zh:"有序列表",ru:"Нумерованный список",ar:"قائمة مرقمة",hi:"क्रमांकित सूची",ko:"번호 목록",tr:"Sıralı liste",pl:"Lista numerowana",sv:"Numrerad lista",id:"Daftar berurutan",th:"รายการลำดับ"},
"editor.alignLeft":{en:"Left",pt:"Esquerda",fr:"Gauche",de:"Links",it:"Sinistra",nl:"Links",ja:"左",zh:"左",ru:"Слева",ar:"يسار",hi:"बाएं",ko:"왼쪽",tr:"Sol",pl:"Lewo",sv:"Vänster",id:"Kiri",th:"ซ้าย"},
"editor.alignCenter":{en:"Center",pt:"Centro",fr:"Centre",de:"Mitte",it:"Centro",nl:"Midden",ja:"中央",zh:"居中",ru:"По центру",ar:"وسط",hi:"केंद्र",ko:"가운데",tr:"Orta",pl:"Środek",sv:"Mitten",id:"Tengah",th:"กลาง"},
"editor.alignRight":{en:"Right",pt:"Direita",fr:"Droite",de:"Rechts",it:"Destra",nl:"Rechts",ja:"右",zh:"右",ru:"Справа",ar:"يمين",hi:"दाएं",ko:"오른쪽",tr:"Sağ",pl:"Prawo",sv:"Höger",id:"Kanan",th:"ขวา"},
"editor.insertLink":{en:"Insert link",pt:"Inserir link",fr:"Insérer un lien",de:"Link einfügen",it:"Inserisci link",nl:"Link invoegen",ja:"リンク挿入",zh:"插入链接",ru:"Вставить ссылку",ar:"إدراج رابط",hi:"लिंक डालें",ko:"링크 삽입",tr:"Bağlantı ekle",pl:"Wstaw link",sv:"Infoga länk",id:"Sisipkan tautan",th:"แทรกลิงก์"},
"editor.linkUrl":{en:"Link URL",pt:"URL do link",fr:"URL du lien",de:"Link-URL",it:"URL del link",nl:"Link-URL",ja:"リンクURL",zh:"链接URL",ru:"URL ссылки",ar:"رابط URL",hi:"लिंक URL",ko:"링크 URL",tr:"Bağlantı URL",pl:"URL linku",sv:"Länk-URL",id:"URL tautan",th:"URL ลิงก์"},
"editor.insertLinkButton":{en:"Insert",pt:"Inserir",fr:"Insérer",de:"Einfügen",it:"Inserisci",nl:"Invoegen",ja:"挿入",zh:"插入",ru:"Вставить",ar:"إدراج",hi:"डालें",ko:"삽입",tr:"Ekle",pl:"Wstaw",sv:"Infoga",id:"Sisipkan",th:"แทรก"},
"editor.removeLink":{en:"Remove link",pt:"Remover link",fr:"Supprimer le lien",de:"Link entfernen",it:"Rimuovi link",nl:"Link verwijderen",ja:"リンク削除",zh:"删除链接",ru:"Удалить ссылку",ar:"إزالة الرابط",hi:"लिंक हटाएं",ko:"링크 제거",tr:"Bağlantıyı kaldır",pl:"Usuń link",sv:"Ta bort länk",id:"Hapus tautan",th:"ลบลิงก์"},
"editor.insertImage":{en:"Insert image",pt:"Inserir imagem",fr:"Insérer une image",de:"Bild einfügen",it:"Inserisci immagine",nl:"Afbeelding invoegen",ja:"画像挿入",zh:"插入图片",ru:"Вставить изображение",ar:"إدراج صورة",hi:"छवि डालें",ko:"이미지 삽입",tr:"Görsel ekle",pl:"Wstaw obraz",sv:"Infoga bild",id:"Sisipkan gambar",th:"แทรกรูปภาพ"},
"editor.imageUrl":{en:"Image URL",pt:"URL da imagem",fr:"URL de l'image",de:"Bild-URL",it:"URL immagine",nl:"Afbeelding-URL",ja:"画像URL",zh:"图片URL",ru:"URL изображения",ar:"رابط الصورة",hi:"छवि URL",ko:"이미지 URL",tr:"Görsel URL",pl:"URL obrazu",sv:"Bild-URL",id:"URL gambar",th:"URL รูปภาพ"},
"editor.insertFromUrl":{en:"Insert from URL",pt:"Inserir de URL",fr:"Insérer depuis URL",de:"Von URL einfügen",it:"Inserisci da URL",nl:"Invoegen via URL",ja:"URLから挿入",zh:"从URL插入",ru:"Вставить по URL",ar:"إدراج من رابط",hi:"URL से डालें",ko:"URL에서 삽입",tr:"URL'den ekle",pl:"Wstaw z URL",sv:"Infoga från URL",id:"Sisipkan dari URL",th:"แทรกจาก URL"},
"editor.uploadFromDevice":{en:"Upload from device",pt:"Enviar do dispositivo",fr:"Télécharger depuis l'appareil",de:"Vom Gerät hochladen",it:"Carica dal dispositivo",nl:"Uploaden vanaf apparaat",ja:"デバイスからアップロード",zh:"从设备上传",ru:"Загрузить с устройства",ar:"رفع من الجهاز",hi:"डिवाइस से अपलोड",ko:"기기에서 업로드",tr:"Cihazdan yükle",pl:"Prześlij z urządzenia",sv:"Ladda upp från enhet",id:"Unggah dari perangkat",th:"อัปโหลดจากอุปกรณ์"},
"editor.insertEmoji":{en:"Insert emoji",pt:"Inserir emoji",fr:"Insérer un emoji",de:"Emoji einfügen",it:"Inserisci emoji",nl:"Emoji invoegen",ja:"絵文字挿入",zh:"插入表情",ru:"Вставить эмодзи",ar:"إدراج رمز تعبيري",hi:"इमोजी डालें",ko:"이모지 삽입",tr:"Emoji ekle",pl:"Wstaw emoji",sv:"Infoga emoji",id:"Sisipkan emoji",th:"แทรกอิโมจิ"},
"editor.quote":{en:"Quote",pt:"Citação",fr:"Citation",de:"Zitat",it:"Citazione",nl:"Citaat",ja:"引用",zh:"引用",ru:"Цитата",ar:"اقتباس",hi:"उद्धरण",ko:"인용",tr:"Alıntı",pl:"Cytat",sv:"Citat",id:"Kutipan",th:"อ้างอิง"},
"editor.codeBlock":{en:"Code block",pt:"Bloco de código",fr:"Bloc de code",de:"Codeblock",it:"Blocco codice",nl:"Codeblok",ja:"コードブロック",zh:"代码块",ru:"Блок кода",ar:"كتلة كود",hi:"कोड ब्लॉक",ko:"코드 블록",tr:"Kod bloğu",pl:"Blok kodu",sv:"Kodblock",id:"Blok kode",th:"บล็อกโค้ด"},
"editor.insertTable":{en:"Insert table",pt:"Inserir tabela",fr:"Insérer un tableau",de:"Tabelle einfügen",it:"Inserisci tabella",nl:"Tabel invoegen",ja:"表挿入",zh:"插入表格",ru:"Вставить таблицу",ar:"إدراج جدول",hi:"तालिका डालें",ko:"표 삽입",tr:"Tablo ekle",pl:"Wstaw tabelę",sv:"Infoga tabell",id:"Sisipkan tabel",th:"แทรกตาราง"},
"editor.undo":{en:"Undo",pt:"Desfazer",fr:"Annuler",de:"Rückgängig",it:"Annulla",nl:"Ongedaan maken",ja:"元に戻す",zh:"撤销",ru:"Отменить",ar:"تراجع",hi:"पूर्ववत",ko:"실행 취소",tr:"Geri al",pl:"Cofnij",sv:"Ångra",id:"Undo",th:"เลิกทำ"},
"editor.redo":{en:"Redo",pt:"Refazer",fr:"Rétablir",de:"Wiederherstellen",it:"Ripeti",nl:"Opnieuw",ja:"やり直す",zh:"重做",ru:"Повторить",ar:"إعادة",hi:"पुनः करें",ko:"다시 실행",tr:"Yinele",pl:"Ponów",sv:"Gör om",id:"Redo",th:"ทำซ้ำ"},
"editor.preview":{en:"Preview",pt:"Pré-visualizar",fr:"Aperçu",de:"Vorschau",it:"Anteprima",nl:"Voorbeeld",ja:"プレビュー",zh:"预览",ru:"Предпросмотр",ar:"معاينة",hi:"पूर्वावलोकन",ko:"미리보기",tr:"Önizleme",pl:"Podgląd",sv:"Förhandsvisa",id:"Pratinjau",th:"ดูตัวอย่าง"},
"editor.reply":{en:"Reply",pt:"Responder",fr:"Répondre",de:"Antworten",it:"Rispondi",nl:"Reageren",ja:"返信",zh:"回复",ru:"Ответить",ar:"رد",hi:"जवाब दें",ko:"답글",tr:"Yanıtla",pl:"Odpowiedz",sv:"Svara",id:"Balas",th:"ตอบกลับ"},
"editor.dictate":{en:"Dictate",pt:"Ditar",fr:"Dicter",de:"Diktieren",it:"Dettare",nl:"Dicteren",ja:"音声入力",zh:"听写",ru:"Диктовать",ar:"إملاء",hi:"डिक्टेट",ko:"받아쓰기",tr:"Dikte",pl:"Dyktuj",sv:"Diktera",id:"Dikte",th:"บอกตามคำ"},
"editor.attachFiles":{en:"Attach files",pt:"Anexar arquivos",fr:"Joindre des fichiers",de:"Dateien anhängen",it:"Allega file",nl:"Bestanden bijvoegen",ja:"ファイル添付",zh:"附加文件",ru:"Прикрепить файлы",ar:"إرفاق ملفات",hi:"फाइलें संलग्न करें",ko:"파일 첨부",tr:"Dosya ekle",pl:"Dołącz pliki",sv:"Bifoga filer",id:"Lampirkan file",th:"แนบไฟล์"},
"editor.placeholder":{en:"Write your content...",pt:"Escreva seu conteúdo...",fr:"Écrivez votre contenu...",de:"Schreiben Sie Ihren Inhalt...",it:"Scrivi il tuo contenuto...",nl:"Schrijf je inhoud...",ja:"内容を入力...",zh:"写下你的内容...",ru:"Напишите содержание...",ar:"اكتب محتواك...",hi:"अपनी सामग्री लिखें...",ko:"내용을 작성하세요...",tr:"İçeriğinizi yazın...",pl:"Napisz treść...",sv:"Skriv ditt innehåll...",id:"Tulis konten Anda...",th:"เขียนเนื้อหาของคุณ..."},
"editor.loginToUpload":{en:"You must sign in to upload images",pt:"Você deve entrar para enviar imagens",fr:"Connectez-vous pour télécharger des images",de:"Melden Sie sich an, um Bilder hochzuladen",it:"Accedi per caricare immagini",nl:"Log in om afbeeldingen te uploaden",ja:"画像をアップロードするにはログインが必要です",zh:"登录以上传图片",ru:"Войдите для загрузки изображений",ar:"يجب تسجيل الدخول لرفع الصور",hi:"छवियाँ अपलोड करने के लिए लॉगिन करें",ko:"이미지 업로드를 위해 로그인하세요",tr:"Görsel yüklemek için giriş yapın",pl:"Zaloguj się aby przesyłać obrazy",sv:"Logga in för att ladda upp bilder",id:"Masuk untuk mengunggah gambar",th:"เข้าสู่ระบบเพื่ออัปโหลดรูป"},
"editor.uploading":{en:"Uploading image...",pt:"Enviando imagem...",fr:"Téléchargement de l'image...",de:"Bild wird hochgeladen...",it:"Caricamento immagine...",nl:"Afbeelding uploaden...",ja:"画像アップロード中...",zh:"上传图片中...",ru:"Загрузка изображения...",ar:"جاري رفع الصورة...",hi:"छवि अपलोड हो रही है...",ko:"이미지 업로드 중...",tr:"Görsel yükleniyor...",pl:"Przesyłanie obrazu...",sv:"Laddar upp bild...",id:"Mengunggah gambar...",th:"กำลังอัปโหลดรูป..."},
"editor.uploadSuccess":{en:"Image uploaded successfully",pt:"Imagem enviada com sucesso",fr:"Image téléchargée avec succès",de:"Bild erfolgreich hochgeladen",it:"Immagine caricata con successo",nl:"Afbeelding succesvol geüpload",ja:"画像アップロード完了",zh:"图片上传成功",ru:"Изображение загружено",ar:"تم رفع الصورة بنجاح",hi:"छवि सफलतापूर्वक अपलोड",ko:"이미지 업로드 성공",tr:"Görsel başarıyla yüklendi",pl:"Obraz przesłany pomyślnie",sv:"Bild uppladdad",id:"Gambar berhasil diunggah",th:"อัปโหลดรูปสำเร็จ"},
"editor.uploadError":{en:"Error uploading image",pt:"Erro ao enviar imagem",fr:"Erreur de téléchargement",de:"Fehler beim Hochladen",it:"Errore caricamento immagine",nl:"Fout bij uploaden",ja:"画像アップロードエラー",zh:"上传图片出错",ru:"Ошибка загрузки изображения",ar:"خطأ في رفع الصورة",hi:"छवि अपलोड त्रुटि",ko:"이미지 업로드 오류",tr:"Görsel yükleme hatası",pl:"Błąd przesyłania obrazu",sv:"Fel vid uppladdning",id:"Error mengunggah gambar",th:"เกิดข้อผิดพลาดในการอัปโหลด"},
"editor.minCharacters":{en:"Minimum 10 characters. You can insert images by pasting or using the image button.",pt:"Mínimo 10 caracteres. Insira imagens colando ou usando o botão.",fr:"Minimum 10 caractères. Insérez des images en collant ou via le bouton.",de:"Mindestens 10 Zeichen. Bilder einfügen durch Einfügen oder Bild-Button.",it:"Minimo 10 caratteri. Inserisci immagini incollando o con il pulsante.",nl:"Minimaal 10 tekens. Voeg afbeeldingen in door te plakken of via de knop.",ja:"最低10文字。画像は貼り付けまたはボタンで挿入できます。",zh:"最少10个字符。可通过粘贴或图片按钮插入图片。",ru:"Минимум 10 символов. Вставляйте изображения, вставив их или используя кнопку.",ar:"الحد الأدنى 10 أحرف. يمكنك إدراج صور بالنسخ أو زر الصورة.",hi:"न्यूनतम 10 अक्षर। छवियाँ पेस्ट या बटन से डालें।",ko:"최소 10자. 이미지를 붙여넣기 또는 버튼으로 삽입하세요.",tr:"Minimum 10 karakter. Görselleri yapıştırarak veya butonla ekleyin.",pl:"Minimum 10 znaków. Wstaw obrazy wklejając lub używając przycisku.",sv:"Minst 10 tecken. Infoga bilder genom att klistra in eller använda knappen.",id:"Minimum 10 karakter. Sisipkan gambar dengan menempel atau tombol gambar.",th:"ขั้นต่ำ 10 ตัวอักษร สามารถแทรกรูปภาพด้วยการวางหรือปุ่มรูปภาพ"},
"editor.or":{en:"or",pt:"ou",fr:"ou",de:"oder",it:"o",nl:"of",ja:"または",zh:"或",ru:"или",ar:"أو",hi:"या",ko:"또는",tr:"veya",pl:"lub",sv:"eller",id:"atau",th:"หรือ"},
"editor.comingSoon":{en:"Coming soon",pt:"Em breve",fr:"Bientôt",de:"Demnächst",it:"Prossimamente",nl:"Binnenkort",ja:"近日公開",zh:"即将推出",ru:"Скоро",ar:"قريباً",hi:"जल्द आ रहा है",ko:"곧 출시",tr:"Yakında",pl:"Wkrótce",sv:"Kommer snart",id:"Segera hadir",th:"เร็วๆ นี้"},

// === VERIFICATION ===
"verification.title":{en:"Account verification",pt:"Verificação de conta",fr:"Vérification de compte",de:"Kontoüberprüfung",it:"Verifica account",nl:"Accountverificatie",ja:"アカウント認証",zh:"账户验证",ru:"Верификация аккаунта",ar:"التحقق من الحساب",hi:"खाता सत्यापन",ko:"계정 인증",tr:"Hesap doğrulama",pl:"Weryfikacja konta",sv:"Kontoverifiering",id:"Verifikasi akun",th:"การยืนยันบัญชี"},
"verification.description":{en:"Verify your identity to access private areas and gain trust",pt:"Verifique sua identidade para acessar áreas privadas",fr:"Vérifiez votre identité pour accéder aux zones privées",de:"Verifizieren Sie Ihre Identität für private Bereiche",it:"Verifica la tua identità per accedere alle aree private",nl:"Verifieer je identiteit voor privégebieden",ja:"プライベートエリアへのアクセスのため本人確認を行ってください",zh:"验证您的身份以访问私密区域",ru:"Подтвердите личность для доступа к закрытым разделам",ar:"تحقق من هويتك للوصول إلى المناطق الخاصة",hi:"निजी क्षेत्रों तक पहुंचने के लिए पहचान सत्यापित करें",ko:"비공개 영역 액세스를 위해 신원을 인증하세요",tr:"Özel alanlara erişim için kimliğinizi doğrulayın",pl:"Zweryfikuj tożsamość aby uzyskać dostęp do stref prywatnych",sv:"Verifiera din identitet för tillgång till privata områden",id:"Verifikasi identitas Anda untuk mengakses area pribadi",th:"ยืนยันตัวตนเพื่อเข้าถึงพื้นที่ส่วนตัว"},
"verification.verified":{en:"Verified account",pt:"Conta verificada",fr:"Compte vérifié",de:"Verifiziertes Konto",it:"Account verificato",nl:"Geverifieerd account",ja:"認証済みアカウント",zh:"已验证账户",ru:"Верифицированный аккаунт",ar:"حساب موثق",hi:"सत्यापित खाता",ko:"인증된 계정",tr:"Doğrulanmış hesap",pl:"Zweryfikowane konto",sv:"Verifierat konto",id:"Akun terverifikasi",th:"บัญชีที่ยืนยันแล้ว"},
"verification.verifiedDescription":{en:"Your account has been successfully verified",pt:"Sua conta foi verificada com sucesso",fr:"Votre compte a été vérifié avec succès",de:"Ihr Konto wurde erfolgreich verifiziert",it:"Il tuo account è stato verificato con successo",nl:"Je account is succesvol geverifieerd",ja:"アカウントが認証されました",zh:"您的账户已成功验证",ru:"Ваш аккаунт успешно верифицирован",ar:"تم التحقق من حسابك بنجاح",hi:"आपका खाता सफलतापूर्वक सत्यापित",ko:"계정이 성공적으로 인증되었습니다",tr:"Hesabınız başarıyla doğrulandı",pl:"Twoje konto zostało zweryfikowane",sv:"Ditt konto har verifierats",id:"Akun Anda berhasil diverifikasi",th:"บัญชีของคุณได้รับการยืนยันสำเร็จ"},
"verification.pending":{en:"Verification in review",pt:"Verificação em revisão",fr:"Vérification en cours",de:"Überprüfung wird geprüft",it:"Verifica in corso",nl:"Verificatie wordt beoordeeld",ja:"認証審査中",zh:"验证审核中",ru:"Верификация на рассмотрении",ar:"التحقق قيد المراجعة",hi:"सत्यापन समीक्षा में",ko:"인증 검토 중",tr:"Doğrulama inceleniyor",pl:"Weryfikacja w trakcie",sv:"Verifiering granskas",id:"Verifikasi sedang ditinjau",th:"การยืนยันอยู่ระหว่างตรวจสอบ"},
"verification.pendingDescription":{en:"Your request is being reviewed",pt:"Sua solicitação está sendo revisada",fr:"Votre demande est en cours d'examen",de:"Ihre Anfrage wird geprüft",it:"La tua richiesta è in revisione",nl:"Je verzoek wordt beoordeeld",ja:"リクエストを審査中です",zh:"您的请求正在审核中",ru:"Ваш запрос рассматривается",ar:"طلبك قيد المراجعة",hi:"आपका अनुरोध समीक्षा में है",ko:"요청이 검토 중입니다",tr:"Talebiniz inceleniyor",pl:"Twój wniosek jest rozpatrywany",sv:"Din begäran granskas",id:"Permintaan Anda sedang ditinjau",th:"คำขอของคุณกำลังถูกตรวจสอบ"},
"verification.request":{en:"Request verification",pt:"Solicitar verificação",fr:"Demander la vérification",de:"Verifizierung anfordern",it:"Richiedi verifica",nl:"Verificatie aanvragen",ja:"認証を申請",zh:"申请验证",ru:"Запросить верификацию",ar:"طلب التحقق",hi:"सत्यापन का अनुरोध",ko:"인증 요청",tr:"Doğrulama iste",pl:"Poproś o weryfikację",sv:"Begär verifiering",id:"Minta verifikasi",th:"ขอการยืนยัน"},
"verification.benefits":{en:"Verification benefits",pt:"Benefícios da verificação",fr:"Avantages de la vérification",de:"Vorteile der Verifizierung",it:"Vantaggi della verifica",nl:"Voordelen van verificatie",ja:"認証のメリット",zh:"验证的好处",ru:"Преимущества верификации",ar:"فوائد التحقق",hi:"सत्यापन के लाभ",ko:"인증 혜택",tr:"Doğrulama avantajları",pl:"Korzyści z weryfikacji",sv:"Fördelar med verifiering",id:"Manfaat verifikasi",th:"ประโยชน์ของการยืนยัน"},
"verification.benefit1":{en:"Access to private forum areas",pt:"Acesso a áreas privadas do fórum",fr:"Accès aux zones privées du forum",de:"Zugang zu privaten Forenbereichen",it:"Accesso alle aree private del forum",nl:"Toegang tot privégebieden",ja:"フォーラムのプライベートエリアへのアクセス",zh:"访问论坛私密区域",ru:"Доступ к закрытым разделам форума",ar:"الوصول إلى المناطق الخاصة",hi:"फ़ोरम के निजी क्षेत्रों तक पहुंच",ko:"포럼 비공개 영역 접근",tr:"Forum özel alanlarına erişim",pl:"Dostęp do prywatnych stref forum",sv:"Tillgång till privata forumområden",id:"Akses ke area pribadi forum",th:"เข้าถึงพื้นที่ส่วนตัวของฟอรั่ม"},
"verification.benefit2":{en:"Verification badge visible on your profile",pt:"Badge de verificação visível no perfil",fr:"Badge de vérification visible sur votre profil",de:"Verifizierungsbadge auf Ihrem Profil",it:"Badge di verifica visibile sul profilo",nl:"Verificatiebadge op je profiel",ja:"プロフィールに認証バッジ表示",zh:"个人资料上显示认证徽章",ru:"Значок верификации в профиле",ar:"شارة التحقق على ملفك الشخصي",hi:"प्रोफ़ाइल पर सत्यापन बैज",ko:"프로필에 인증 배지 표시",tr:"Profilinizdeki doğrulama rozeti",pl:"Odznaka weryfikacji na profilu",sv:"Verifieringsmärke på din profil",id:"Lencana verifikasi di profil",th:"แสดงป้ายยืนยันบนโปรไฟล์"},
"verification.benefit3":{en:"Greater community trust",pt:"Maior confiança da comunidade",fr:"Plus grande confiance de la communauté",de:"Größeres Vertrauen der Community",it:"Maggiore fiducia della comunità",nl:"Meer vertrouwen van de community",ja:"コミュニティからの信頼向上",zh:"更高的社区信任度",ru:"Большее доверие сообщества",ar:"ثقة أكبر من المجتمع",hi:"समुदाय का अधिक विश्वास",ko:"커뮤니티의 높은 신뢰",tr:"Daha fazla topluluk güveni",pl:"Większe zaufanie społeczności",sv:"Större förtroende i gemenskapen",id:"Kepercayaan komunitas yang lebih besar",th:"ความไว้วางใจจากชุมชนมากขึ้น"},
"verification.benefit4":{en:"Priority support",pt:"Suporte prioritário",fr:"Support prioritaire",de:"Prioritätsunterstützung",it:"Supporto prioritario",nl:"Prioritaire ondersteuning",ja:"優先サポート",zh:"优先支持",ru:"Приоритетная поддержка",ar:"دعم ذو أولوية",hi:"प्राथमिकता सहायता",ko:"우선 지원",tr:"Öncelikli destek",pl:"Priorytetowe wsparcie",sv:"Prioriterat stöd",id:"Dukungan prioritas",th:"การสนับสนุนระดับพิเศษ"},
"verification.step1":{en:"Step 1: Generate your code",pt:"Passo 1: Gere seu código",fr:"Étape 1 : Générez votre code",de:"Schritt 1: Code generieren",it:"Passo 1: Genera il codice",nl:"Stap 1: Genereer je code",ja:"ステップ1：コード生成",zh:"步骤1：生成代码",ru:"Шаг 1: Сгенерируйте код",ar:"الخطوة 1: أنشئ رمزك",hi:"चरण 1: अपना कोड जनरेट करें",ko:"1단계: 코드 생성",tr:"Adım 1: Kodunuzu oluşturun",pl:"Krok 1: Wygeneruj kod",sv:"Steg 1: Generera din kod",id:"Langkah 1: Buat kode Anda",th:"ขั้นตอน 1: สร้างรหัส"},
"verification.step2":{en:"Step 2: Take your photo",pt:"Passo 2: Tire sua foto",fr:"Étape 2 : Prenez votre photo",de:"Schritt 2: Foto aufnehmen",it:"Passo 2: Scatta la foto",nl:"Stap 2: Maak je foto",ja:"ステップ2：写真撮影",zh:"步骤2：拍照",ru:"Шаг 2: Сделайте фото",ar:"الخطوة 2: التقط صورتك",hi:"चरण 2: अपनी फ़ोटो लें",ko:"2단계: 사진 촬영",tr:"Adım 2: Fotoğrafınızı çekin",pl:"Krok 2: Zrób zdjęcie",sv:"Steg 2: Ta ditt foto",id:"Langkah 2: Ambil foto Anda",th:"ขั้นตอน 2: ถ่ายรูป"},
"verification.step3":{en:"Step 3: Upload your photo",pt:"Passo 3: Envie sua foto",fr:"Étape 3 : Téléchargez votre photo",de:"Schritt 3: Foto hochladen",it:"Passo 3: Carica la foto",nl:"Stap 3: Upload je foto",ja:"ステップ3：写真アップロード",zh:"步骤3：上传照片",ru:"Шаг 3: Загрузите фото",ar:"الخطوة 3: ارفع صورتك",hi:"चरण 3: अपनी फ़ोटो अपलोड करें",ko:"3단계: 사진 업로드",tr:"Adım 3: Fotoğrafınızı yükleyin",pl:"Krok 3: Prześlij zdjęcie",sv:"Steg 3: Ladda upp ditt foto",id:"Langkah 3: Unggah foto Anda",th:"ขั้นตอน 3: อัปโหลดรูป"},
"verification.generateCode":{en:"Generate code",pt:"Gerar código",fr:"Générer le code",de:"Code generieren",it:"Genera codice",nl:"Code genereren",ja:"コード生成",zh:"生成代码",ru:"Сгенерировать код",ar:"إنشاء الرمز",hi:"कोड जनरेट करें",ko:"코드 생성",tr:"Kod oluştur",pl:"Generuj kod",sv:"Generera kod",id:"Buat kode",th:"สร้างรหัส"},
"verification.copyCode":{en:"Copy",pt:"Copiar",fr:"Copier",de:"Kopieren",it:"Copia",nl:"Kopiëren",ja:"コピー",zh:"复制",ru:"Копировать",ar:"نسخ",hi:"कॉपी",ko:"복사",tr:"Kopyala",pl:"Kopiuj",sv:"Kopiera",id:"Salin",th:"คัดลอก"},
"verification.photoUrl":{en:"Photo URL",pt:"URL da foto",fr:"URL de la photo",de:"Foto-URL",it:"URL della foto",nl:"Foto-URL",ja:"写真URL",zh:"照片URL",ru:"URL фото",ar:"رابط الصورة",hi:"फ़ोटो URL",ko:"사진 URL",tr:"Fotoğraf URL",pl:"URL zdjęcia",sv:"Foto-URL",id:"URL foto",th:"URL รูปภาพ"},
"verification.submitRequest":{en:"Submit verification request",pt:"Enviar solicitação de verificação",fr:"Envoyer la demande de vérification",de:"Verifizierungsanfrage senden",it:"Invia richiesta di verifica",nl:"Verificatieverzoek indienen",ja:"認証リクエストを送信",zh:"提交验证请求",ru:"Отправить запрос на верификацию",ar:"إرسال طلب التحقق",hi:"सत्यापन अनुरोध भेजें",ko:"인증 요청 제출",tr:"Doğrulama talebi gönder",pl:"Wyślij wniosek o weryfikację",sv:"Skicka verifieringsförfrågan",id:"Kirim permintaan verifikasi",th:"ส่งคำขอยืนยัน"},
"verification.submitting":{en:"Submitting request...",pt:"Enviando solicitação...",fr:"Envoi de la demande...",de:"Anfrage wird gesendet...",it:"Invio richiesta...",nl:"Verzoek wordt verzonden...",ja:"リクエスト送信中...",zh:"正在提交请求...",ru:"Отправка запроса...",ar:"جاري إرسال الطلب...",hi:"अनुरोध भेज रहे हैं...",ko:"요청 제출 중...",tr:"Talep gönderiliyor...",pl:"Wysyłanie wniosku...",sv:"Skickar förfrågan...",id:"Mengirim permintaan...",th:"กำลังส่งคำขอ..."},
"verification.submitSuccess":{en:"Request submitted",pt:"Solicitação enviada",fr:"Demande envoyée",de:"Anfrage gesendet",it:"Richiesta inviata",nl:"Verzoek ingediend",ja:"リクエスト送信完了",zh:"请求已提交",ru:"Запрос отправлен",ar:"تم إرسال الطلب",hi:"अनुरोध भेजा गया",ko:"요청 제출됨",tr:"Talep gönderildi",pl:"Wniosek wysłany",sv:"Förfrågan skickad",id:"Permintaan terkirim",th:"ส่งคำขอแล้ว"},
"verification.submitSuccessDescription":{en:"The moderation team will review it soon",pt:"A equipe de moderação revisará em breve",fr:"L'équipe de modération l'examinera bientôt",de:"Das Moderationsteam wird es bald prüfen",it:"Il team di moderazione lo esaminerà presto",nl:"Het moderatieteam beoordeelt het binnenkort",ja:"モデレーションチームがまもなく確認します",zh:"审核团队将尽快审核",ru:"Команда модерации скоро проверит",ar:"سيراجعه فريق الإشراف قريباً",hi:"मॉडरेशन टीम जल्द समीक्षा करेगी",ko:"관리 팀이 곧 검토합니다",tr:"Moderasyon ekibi yakında inceleyecek",pl:"Zespół moderacji wkrótce go sprawdzi",sv:"Moderationsteamet granskar det snart",id:"Tim moderasi akan segera meninjau",th:"ทีมดูแลจะตรวจสอบเร็วๆ นี้"},
"verification.estimatedTime":{en:"Estimated review time: 24-48 hours",pt:"Tempo estimado de revisão: 24-48 horas",fr:"Temps de révision estimé : 24-48 heures",de:"Geschätzte Überprüfungszeit: 24-48 Stunden",it:"Tempo di revisione stimato: 24-48 ore",nl:"Geschatte beoordelingstijd: 24-48 uur",ja:"推定レビュー時間：24〜48時間",zh:"预计审核时间：24-48小时",ru:"Ожидаемое время рассмотрения: 24-48 часов",ar:"وقت المراجعة المقدر: 24-48 ساعة",hi:"अनुमानित समीक्षा समय: 24-48 घंटे",ko:"예상 검토 시간: 24-48시간",tr:"Tahmini inceleme süresi: 24-48 saat",pl:"Szacowany czas weryfikacji: 24-48 godzin",sv:"Uppskattad granskningstid: 24-48 timmar",id:"Perkiraan waktu tinjauan: 24-48 jam",th:"ระยะเวลาตรวจสอบโดยประมาณ: 24-48 ชั่วโมง"},
"verification.breadcrumb":{en:"Verification",pt:"Verificação",fr:"Vérification",de:"Verifizierung",it:"Verifica",nl:"Verificatie",ja:"認証",zh:"验证",ru:"Верификация",ar:"التحقق",hi:"सत्यापन",ko:"인증",tr:"Doğrulama",pl:"Weryfikacja",sv:"Verifiering",id:"Verifikasi",th:"การยืนยัน"},
"verification.subtitle":{en:"Verify your identity to access private areas and gain trust",pt:"Verifique sua identidade para acessar áreas privadas",fr:"Vérifiez votre identité pour accéder aux zones privées",de:"Verifizieren Sie Ihre Identität für private Bereiche",it:"Verifica la tua identità per aree private e fiducia",nl:"Verifieer je identiteit voor privégebieden en vertrouwen",ja:"プライベートエリアへのアクセスのため本人確認",zh:"验证身份以访问私密区域并获得信任",ru:"Подтвердите личность для доступа к закрытым разделам",ar:"تحقق من هويتك للوصول إلى المناطق الخاصة",hi:"निजी क्षेत्रों के लिए पहचान सत्यापित करें",ko:"비공개 영역 접근을 위해 신원 인증",tr:"Özel alanlara erişim için kimliğinizi doğrulayın",pl:"Zweryfikuj tożsamość dla stref prywatnych i zaufania",sv:"Verifiera din identitet för privata områden",id:"Verifikasi identitas untuk area pribadi dan kepercayaan",th:"ยืนยันตัวตนเพื่อเข้าถึงพื้นที่ส่วนตัว"},
"verification.codeCopied":{en:"Code copied",pt:"Código copiado",fr:"Code copié",de:"Code kopiert",it:"Codice copiato",nl:"Code gekopieerd",ja:"コードをコピーしました",zh:"代码已复制",ru:"Код скопирован",ar:"تم نسخ الرمز",hi:"कोड कॉपी किया गया",ko:"코드 복사됨",tr:"Kod kopyalandı",pl:"Kod skopiowany",sv:"Kod kopierad",id:"Kode disalin",th:"คัดลอกรหัสแล้ว"},
"verification.generateCodeFirst":{en:"Generate a verification code first",pt:"Gere um código de verificação primeiro",fr:"Générez d'abord un code de vérification",de:"Generieren Sie zuerst einen Code",it:"Genera prima un codice di verifica",nl:"Genereer eerst een verificatiecode",ja:"まず認証コードを生成してください",zh:"请先生成验证码",ru:"Сначала сгенерируйте код",ar:"أنشئ رمز التحقق أولاً",hi:"पहले सत्यापन कोड जनरेट करें",ko:"먼저 인증 코드를 생성하세요",tr:"Önce bir doğrulama kodu oluşturun",pl:"Najpierw wygeneruj kod",sv:"Generera en verifieringskod först",id:"Buat kode verifikasi terlebih dahulu",th:"สร้างรหัสยืนยันก่อน"},
"verification.enterPhotoUrl":{en:"Enter your verification photo URL",pt:"Insira a URL da sua foto de verificação",fr:"Entrez l'URL de votre photo de vérification",de:"Geben Sie die URL Ihres Verifizierungsfotos ein",it:"Inserisci l'URL della foto di verifica",nl:"Voer de URL van je verificatiefoto in",ja:"認証写真のURLを入力",zh:"输入验证照片的URL",ru:"Введите URL фото для верификации",ar:"أدخل رابط صورة التحقق",hi:"सत्यापन फ़ोटो URL दर्ज करें",ko:"인증 사진 URL을 입력하세요",tr:"Doğrulama fotoğrafı URL'sini girin",pl:"Wprowadź URL zdjęcia weryfikacyjnego",sv:"Ange din verifieringsfoto-URL",id:"Masukkan URL foto verifikasi Anda",th:"กรอก URL รูปภาพยืนยัน"},
"verification.submitError":{en:"Error submitting request",pt:"Erro ao enviar solicitação",fr:"Erreur d'envoi",de:"Fehler beim Senden",it:"Errore invio",nl:"Fout bij indienen",ja:"送信エラー",zh:"提交出错",ru:"Ошибка отправки",ar:"خطأ في الإرسال",hi:"भेजने में त्रुटि",ko:"제출 오류",tr:"Gönderme hatası",pl:"Błąd wysyłania",sv:"Sändningsfel",id:"Error mengirim",th:"เกิดข้อผิดพลาด"},
"verification.requestSent":{en:"Request sent",pt:"Solicitação enviada",fr:"Demande envoyée",de:"Anfrage gesendet",it:"Richiesta inviata",nl:"Verzoek verzonden",ja:"リクエスト送信済み",zh:"请求已发送",ru:"Запрос отправлен",ar:"تم إرسال الطلب",hi:"अनुरोध भेजा गया",ko:"요청 전송됨",tr:"Talep gönderildi",pl:"Wniosek wysłany",sv:"Förfrågan skickad",id:"Permintaan terkirim",th:"ส่งคำขอแล้ว"},
"verification.requestSentDesc":{en:"The moderation team will review it soon",pt:"A equipe de moderação revisará em breve",fr:"L'équipe de modération l'examinera bientôt",de:"Das Moderationsteam wird es bald prüfen",it:"Il team di moderazione lo esaminerà presto",nl:"Het moderatieteam beoordeelt het binnenkort",ja:"モデレーションチームが確認します",zh:"审核团队将尽快审核",ru:"Команда модерации рассмотрит",ar:"سيراجعه فريق الإشراف قريباً",hi:"मॉडरेशन टीम जल्द समीक्षा करेगी",ko:"관리 팀이 곧 검토합니다",tr:"Moderasyon ekibi inceleyecek",pl:"Zespół moderacji sprawdzi",sv:"Moderationsteamet granskar snart",id:"Tim moderasi akan meninjau",th:"ทีมดูแลจะตรวจสอบเร็วๆ นี้"},
"verification.unexpectedError":{en:"Unexpected error",pt:"Erro inesperado",fr:"Erreur inattendue",de:"Unerwarteter Fehler",it:"Errore imprevisto",nl:"Onverwachte fout",ja:"予期しないエラー",zh:"意外错误",ru:"Непредвиденная ошибка",ar:"خطأ غير متوقع",hi:"अप्रत्याशित त्रुटि",ko:"예상치 못한 오류",tr:"Beklenmeyen hata",pl:"Nieoczekiwany błąd",sv:"Oväntat fel",id:"Error tidak terduga",th:"ข้อผิดพลาดที่ไม่คาดคิด"},
"verification.loading":{en:"Loading...",pt:"Carregando...",fr:"Chargement...",de:"Laden...",it:"Caricamento...",nl:"Laden...",ja:"読み込み中...",zh:"加载中...",ru:"Загрузка...",ar:"جاري التحميل...",hi:"लोड हो रहा है...",ko:"로딩 중...",tr:"Yükleniyor...",pl:"Ładowanie...",sv:"Laddar...",id:"Memuat...",th:"กำลังโหลด..."},
"verification.accountVerified":{en:"Verified account",pt:"Conta verificada",fr:"Compte vérifié",de:"Konto verifiziert",it:"Account verificato",nl:"Account geverifieerd",ja:"認証済みアカウント",zh:"已验证账户",ru:"Аккаунт верифицирован",ar:"حساب موثق",hi:"खाता सत्यापित",ko:"인증된 계정",tr:"Doğrulanmış hesap",pl:"Konto zweryfikowane",sv:"Konto verifierat",id:"Akun terverifikasi",th:"บัญชีที่ยืนยันแล้ว"},
"verification.accountVerifiedDesc":{en:"Your account has been successfully verified",pt:"Sua conta foi verificada com sucesso",fr:"Votre compte a été vérifié",de:"Ihr Konto wurde verifiziert",it:"Il tuo account è stato verificato",nl:"Je account is geverifieerd",ja:"アカウント認証完了",zh:"账户已验证",ru:"Аккаунт верифицирован",ar:"تم التحقق من حسابك",hi:"खाता सत्यापित",ko:"계정 인증됨",tr:"Hesap doğrulandı",pl:"Konto zweryfikowane",sv:"Kontot verifierat",id:"Akun terverifikasi",th:"ยืนยันบัญชีแล้ว"},
"verification.fullAccess":{en:"You have full access to all forum areas, including private sections.",pt:"Você tem acesso completo a todas as áreas do fórum, incluindo seções privadas.",fr:"Vous avez accès à toutes les zones du forum, y compris privées.",de:"Sie haben vollen Zugang zu allen Forenbereichen.",it:"Hai accesso completo a tutte le aree del forum.",nl:"Je hebt volledige toegang tot alle forumgebieden.",ja:"プライベートエリアを含むすべてのフォーラムにアクセスできます。",zh:"您可以访问论坛的所有区域，包括私密区域。",ru:"У вас полный доступ ко всем разделам форума, включая закрытые.",ar:"لديك وصول كامل لجميع مناطق المنتدى.",hi:"आपको सभी फ़ोरम क्षेत्रों तक पूर्ण पहुंच है।",ko:"비공개 영역을 포함한 모든 포럼 영역에 접근할 수 있습니다.",tr:"Özel bölümler dahil tüm forum alanlarına erişiminiz var.",pl:"Masz pełny dostęp do wszystkich stref forum.",sv:"Du har full tillgång till alla forumområden.",id:"Anda memiliki akses penuh ke semua area forum.",th:"คุณมีสิทธิ์เข้าถึงพื้นที่ทั้งหมดของฟอรั่ม"},
"verification.inReview":{en:"Verification in review",pt:"Verificação em revisão",fr:"Vérification en cours",de:"Überprüfung wird geprüft",it:"Verifica in corso",nl:"Verificatie wordt beoordeeld",ja:"認証審査中",zh:"验证审核中",ru:"На рассмотрении",ar:"قيد المراجعة",hi:"समीक्षा में",ko:"검토 중",tr:"İnceleniyor",pl:"W trakcie weryfikacji",sv:"Under granskning",id:"Sedang ditinjau",th:"อยู่ระหว่างตรวจสอบ"},
"verification.inReviewDesc":{en:"Your request is being reviewed",pt:"Sua solicitação está sendo revisada",fr:"Votre demande est en cours",de:"Ihre Anfrage wird geprüft",it:"La tua richiesta è in revisione",nl:"Je verzoek wordt beoordeeld",ja:"審査中です",zh:"正在审核",ru:"Запрос рассматривается",ar:"طلبك قيد المراجعة",hi:"अनुरोध समीक्षा में",ko:"요청 검토 중",tr:"Talebiniz inceleniyor",pl:"Wniosek w trakcie",sv:"Din begäran granskas",id:"Permintaan sedang ditinjau",th:"คำขอกำลังถูกตรวจสอบ"},
"verification.inReviewInfo":{en:"Your verification request was submitted and is being reviewed by the moderation team. You'll be notified when approved.",pt:"Sua solicitação foi enviada e está sendo revisada pela equipe de moderação.",fr:"Votre demande a été envoyée et est en cours d'examen par l'équipe de modération.",de:"Ihre Verifizierungsanfrage wurde eingereicht und wird vom Moderationsteam geprüft.",it:"La tua richiesta è stata inviata ed è in fase di revisione dal team di moderazione.",nl:"Je verzoek is ingediend en wordt beoordeeld door het moderatieteam.",ja:"認証リクエストが送信され、モデレーションチームが審査中です。承認されると通知されます。",zh:"您的验证请求已提交，审核团队正在审核中。审核通过后将通知您。",ru:"Ваш запрос на верификацию отправлен и рассматривается модераторами. Вы получите уведомление.",ar:"تم إرسال طلب التحقق وهو قيد المراجعة. سيتم إبلاغك عند الموافقة.",hi:"सत्यापन अनुरोध भेजा गया और मॉडरेशन टीम द्वारा समीक्षा की जा रही है।",ko:"인증 요청이 제출되어 관리 팀이 검토 중입니다. 승인되면 알림을 받게 됩니다.",tr:"Doğrulama talebiniz gönderildi ve moderasyon ekibi tarafından inceleniyor.",pl:"Twój wniosek został wysłany i jest rozpatrywany przez zespół moderacji.",sv:"Din verifieringsbegäran har skickats och granskas av moderationsteamet.",id:"Permintaan verifikasi Anda telah dikirim dan sedang ditinjau oleh tim moderasi.",th:"คำขอยืนยันของคุณถูกส่งแล้วและกำลังถูกตรวจสอบโดยทีมดูแล"},
"verification.verificationCode":{en:"Verification code",pt:"Código de verificação",fr:"Code de vérification",de:"Verifizierungscode",it:"Codice di verifica",nl:"Verificatiecode",ja:"認証コード",zh:"验证码",ru:"Код верификации",ar:"رمز التحقق",hi:"सत्यापन कोड",ko:"인증 코드",tr:"Doğrulama kodu",pl:"Kod weryfikacyjny",sv:"Verifieringskod",id:"Kode verifikasi",th:"รหัสยืนยัน"},
"verification.requestVerification":{en:"Request verification",pt:"Solicitar verificação",fr:"Demander la vérification",de:"Verifizierung anfordern",it:"Richiedi verifica",nl:"Verificatie aanvragen",ja:"認証を申請",zh:"申请验证",ru:"Запросить верификацию",ar:"طلب التحقق",hi:"सत्यापन का अनुरोध",ko:"인증 요청",tr:"Doğrulama iste",pl:"Poproś o weryfikację",sv:"Begär verifiering",id:"Minta verifikasi",th:"ขอการยืนยัน"},
"verification.followSteps":{en:"Follow these steps to verify your account",pt:"Siga estes passos para verificar sua conta",fr:"Suivez ces étapes pour vérifier votre compte",de:"Befolgen Sie diese Schritte zur Verifizierung",it:"Segui questi passaggi per verificare il tuo account",nl:"Volg deze stappen om je account te verifiëren",ja:"以下の手順でアカウントを認証",zh:"按照以下步骤验证您的账户",ru:"Следуйте этим шагам для верификации",ar:"اتبع هذه الخطوات للتحقق من حسابك",hi:"अपना खाता सत्यापित करने के लिए इन चरणों का पालन करें",ko:"계정 인증을 위해 다음 단계를 따르세요",tr:"Hesabınızı doğrulamak için bu adımları izleyin",pl:"Wykonaj te kroki aby zweryfikować konto",sv:"Följ dessa steg för att verifiera ditt konto",id:"Ikuti langkah-langkah ini untuk memverifikasi akun Anda",th:"ทำตามขั้นตอนเหล่านี้เพื่อยืนยันบัญชี"},
"verification.step1Desc":{en:"Generate a unique code that you'll write on paper with your username (@{username}) and today's date.",pt:"Gere um código único para escrever em um papel com seu nome de usuário (@{username}) e a data de hoje.",fr:"Générez un code unique à écrire sur papier avec votre nom d'utilisateur (@{username}) et la date.",de:"Generieren Sie einen Code, den Sie mit Ihrem Benutzernamen (@{username}) und dem heutigen Datum aufschreiben.",it:"Genera un codice unico da scrivere su un foglio con il tuo username (@{username}) e la data di oggi.",nl:"Genereer een unieke code die je op papier schrijft met je gebruikersnaam (@{username}) en de datum.",ja:"ユーザー名（@{username}）と今日の日付を紙に書くユニークコードを生成します。",zh:"生成一个唯一代码，将其与您的用户名（@{username}）和今天的日期写在纸上。",ru:"Сгенерируйте уникальный код, который нужно написать на бумаге с вашим именем (@{username}) и сегодняшней датой.",ar:"أنشئ رمزاً فريداً ستكتبه على ورقة مع اسم المستخدم (@{username}) وتاريخ اليوم.",hi:"एक अनूठा कोड जनरेट करें जिसे आप कागज़ पर अपने उपयोगकर्ता नाम (@{username}) और आज की तारीख के साथ लिखेंगे।",ko:"사용자 이름(@{username})과 오늘 날짜와 함께 종이에 적을 고유 코드를 생성합니다.",tr:"Kullanıcı adınız (@{username}) ve bugünün tarihiyle kağıda yazacağınız benzersiz bir kod oluşturun.",pl:"Wygeneruj unikalny kod, który napiszesz na kartce ze swoją nazwą (@{username}) i dzisiejszą datą.",sv:"Generera en unik kod som du skriver på papper med ditt användarnamn (@{username}) och dagens datum.",id:"Buat kode unik yang akan Anda tulis di kertas dengan nama pengguna (@{username}) dan tanggal hari ini.",th:"สร้างรหัสเฉพาะที่คุณจะเขียนบนกระดาษพร้อมชื่อผู้ใช้ (@{username}) และวันที่วันนี้"},
"verification.yourCode":{en:"Your verification code",pt:"Seu código de verificação",fr:"Votre code de vérification",de:"Ihr Verifizierungscode",it:"Il tuo codice di verifica",nl:"Je verificatiecode",ja:"認証コード",zh:"您的验证码",ru:"Ваш код верификации",ar:"رمز التحقق الخاص بك",hi:"आपका सत्यापन कोड",ko:"인증 코드",tr:"Doğrulama kodunuz",pl:"Twój kod weryfikacyjny",sv:"Din verifieringskod",id:"Kode verifikasi Anda",th:"รหัสยืนยันของคุณ"},
"verification.copy":{en:"Copy",pt:"Copiar",fr:"Copier",de:"Kopieren",it:"Copia",nl:"Kopiëren",ja:"コピー",zh:"复制",ru:"Копировать",ar:"نسخ",hi:"कॉपी",ko:"복사",tr:"Kopyala",pl:"Kopiuj",sv:"Kopiera",id:"Salin",th:"คัดลอก"},
"verification.step2Desc":{en:"Take a clear photo where you appear holding a paper with:",pt:"Tire uma foto clara onde você apareça segurando um papel com:",fr:"Prenez une photo claire où vous apparaissez tenant un papier avec :",de:"Machen Sie ein klares Foto, auf dem Sie ein Papier halten mit:",it:"Scatta una foto chiara dove appari con un foglio con:",nl:"Maak een duidelijke foto waar je een papier vasthoudt met:",ja:"以下が書かれた紙を持った鮮明な写真を撮影してください：",zh:"拍一张清晰的照片，展示您手持写有以下内容的纸：",ru:"Сделайте чёткое фото, где вы держите бумагу с:",ar:"التقط صورة واضحة تظهر فيها ممسكاً بورقة تحتوي على:",hi:"एक स्पष्ट फ़ोटो लें जिसमें आप कागज़ पकड़े हों जिस पर लिखा हो:",ko:"다음이 적힌 종이를 들고 있는 선명한 사진을 촬영하세요:",tr:"Aşağıdakileri içeren bir kağıt tuttuğunuz net bir fotoğraf çekin:",pl:"Zrób wyraźne zdjęcie, na którym trzymasz kartkę z:",sv:"Ta ett tydligt foto där du håller ett papper med:",id:"Ambil foto yang jelas di mana Anda memegang kertas dengan:",th:"ถ่ายรูปที่ชัดเจนโดยคุณถือกระดาษที่เขียน:"},
"verification.yourCodeItem":{en:"Your code: {code}",pt:"Seu código: {code}",fr:"Votre code : {code}",de:"Ihr Code: {code}",it:"Il tuo codice: {code}",nl:"Je code: {code}",ja:"コード：{code}",zh:"你的代码：{code}",ru:"Ваш код: {code}",ar:"رمزك: {code}",hi:"आपका कोड: {code}",ko:"코드: {code}",tr:"Kodunuz: {code}",pl:"Twój kod: {code}",sv:"Din kod: {code}",id:"Kode Anda: {code}",th:"รหัสของคุณ: {code}"},
"verification.yourUserItem":{en:"Your username: @{username}",pt:"Seu usuário: @{username}",fr:"Votre utilisateur : @{username}",de:"Ihr Benutzername: @{username}",it:"Il tuo utente: @{username}",nl:"Je gebruiker: @{username}",ja:"ユーザー名：@{username}",zh:"用户名：@{username}",ru:"Ваш пользователь: @{username}",ar:"اسم المستخدم: @{username}",hi:"आपका उपयोगकर्ता: @{username}",ko:"사용자 이름: @{username}",tr:"Kullanıcı adınız: @{username}",pl:"Twój użytkownik: @{username}",sv:"Ditt användarnamn: @{username}",id:"Nama pengguna Anda: @{username}",th:"ชื่อผู้ใช้ของคุณ: @{username}"},
"verification.todayDate":{en:"Today's date: {date}",pt:"Data de hoje: {date}",fr:"Date du jour : {date}",de:"Heutiges Datum: {date}",it:"Data di oggi: {date}",nl:"Datum van vandaag: {date}",ja:"今日の日付：{date}",zh:"今天日期：{date}",ru:"Сегодняшняя дата: {date}",ar:"تاريخ اليوم: {date}",hi:"आज की तारीख: {date}",ko:"오늘 날짜: {date}",tr:"Bugünün tarihi: {date}",pl:"Dzisiejsza data: {date}",sv:"Dagens datum: {date}",id:"Tanggal hari ini: {date}",th:"วันที่วันนี้: {date}"},
"verification.step3Desc":{en:"Upload your photo to a service like Imgur, ImgBB or similar, and paste the URL here:",pt:"Envie sua foto para um serviço como Imgur, ImgBB ou similar, e cole a URL aqui:",fr:"Téléchargez votre photo sur un service comme Imgur, ImgBB ou similaire, et collez l'URL ici :",de:"Laden Sie Ihr Foto bei Imgur, ImgBB oder ähnlichem hoch und fügen Sie die URL hier ein:",it:"Carica la tua foto su un servizio come Imgur, ImgBB o simile e incolla l'URL qui:",nl:"Upload je foto naar een dienst als Imgur, ImgBB of vergelijkbaar en plak de URL hier:",ja:"Imgur、ImgBBなどのサービスに写真をアップロードし、URLを貼り付けてください：",zh:"将照片上传到Imgur、ImgBB等服务，然后在此处粘贴URL：",ru:"Загрузите фото на сервис вроде Imgur, ImgBB и вставьте URL сюда:",ar:"ارفع صورتك على خدمة مثل Imgur أو ImgBB والصق الرابط هنا:",hi:"अपनी फ़ोटो Imgur, ImgBB जैसी सेवा पर अपलोड करें और URL यहाँ पेस्ट करें:",ko:"Imgur, ImgBB 등의 서비스에 사진을 업로드하고 URL을 여기에 붙여넣으세요:",tr:"Fotoğrafınızı Imgur, ImgBB gibi bir servise yükleyin ve URL'yi buraya yapıştırın:",pl:"Prześlij zdjęcie na serwis jak Imgur, ImgBB i wklej URL tutaj:",sv:"Ladda upp ditt foto till en tjänst som Imgur, ImgBB och klistra in URL:en här:",id:"Unggah foto Anda ke layanan seperti Imgur, ImgBB dan tempel URL di sini:",th:"อัปโหลดรูปไปยังบริการเช่น Imgur, ImgBB แล้ววาง URL ที่นี่:"},
"verification.photoUrlLabel":{en:"Photo URL *",pt:"URL da foto *",fr:"URL de la photo *",de:"Foto-URL *",it:"URL della foto *",nl:"Foto-URL *",ja:"写真URL *",zh:"照片URL *",ru:"URL фото *",ar:"رابط الصورة *",hi:"फ़ोटो URL *",ko:"사진 URL *",tr:"Fotoğraf URL *",pl:"URL zdjęcia *",sv:"Foto-URL *",id:"URL foto *",th:"URL รูปภาพ *"},
"verification.submitVerification":{en:"Submit verification request",pt:"Enviar solicitação de verificação",fr:"Envoyer la demande de vérification",de:"Verifizierungsanfrage senden",it:"Invia richiesta di verifica",nl:"Verificatieverzoek indienen",ja:"認証リクエストを送信",zh:"提交验证请求",ru:"Отправить запрос на верификацию",ar:"إرسال طلب التحقق",hi:"सत्यापन अनुरोध भेजें",ko:"인증 요청 제출",tr:"Doğrulama talebi gönder",pl:"Wyślij wniosek o weryfikację",sv:"Skicka verifieringsförfrågan",id:"Kirim permintaan verifikasi",th:"ส่งคำขอยืนยัน"},
};

const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  // KEY-based matching
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Batch 4b done!');
