const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === MODERATION (part 1 - 60 keys) ===
"moderation.title":{en:"Moderation",pt:"Moderação",fr:"Modération",de:"Moderation",it:"Moderazione",nl:"Moderatie",ja:"モデレーション",zh:"管理",ru:"Модерация",ar:"الإشراف",hi:"मॉडरेशन",ko:"관리",tr:"Moderasyon",pl:"Moderacja",sv:"Moderering",id:"Moderasi",th:"การดูแล"},
"moderation.history":{en:"Moderation History",pt:"Histórico de Moderação",fr:"Historique de Modération",de:"Moderationsverlauf",it:"Cronologia Moderazione",nl:"Moderatiegeschiedenis",ja:"モデレーション履歴",zh:"管理历史",ru:"История модерации",ar:"سجل الإشراف",hi:"मॉडरेशन इतिहास",ko:"관리 이력",tr:"Moderasyon Geçmişi",pl:"Historia Moderacji",sv:"Modereringshistorik",id:"Riwayat Moderasi",th:"ประวัติการดูแล"},
"moderation.suspensions":{en:"Suspensions",pt:"Suspensões",fr:"Suspensions",de:"Sperrungen",it:"Sospensioni",nl:"Schorsingen",ja:"停止",zh:"暂停",ru:"Блокировки",ar:"الإيقافات",hi:"निलंबन",ko:"정지",tr:"Askıya Almalar",pl:"Zawieszenia",sv:"Avstängningar",id:"Penangguhan",th:"การระงับ"},
"moderation.ipBans":{en:"IP Bans",pt:"Bloqueios de IP",fr:"Blocages IP",de:"IP-Sperren",it:"Ban IP",nl:"IP-blokkades",ja:"IPブロック",zh:"IP封禁",ru:"Блокировки IP",ar:"حظر IP",hi:"IP प्रतिबंध",ko:"IP 차단",tr:"IP Yasakları",pl:"Blokady IP",sv:"IP-blockeringar",id:"Blokir IP",th:"แบน IP"},
"moderation.action":{en:"Action",pt:"Ação",fr:"Action",de:"Aktion",it:"Azione",nl:"Actie",ja:"アクション",zh:"操作",ru:"Действие",ar:"إجراء",hi:"कार्रवाई",ko:"작업",tr:"Eylem",pl:"Akcja",sv:"Åtgärd",id:"Tindakan",th:"การดำเนินการ"},
"moderation.reason":{en:"Reason *",pt:"Motivo *",fr:"Motif *",de:"Grund *",it:"Motivo *",nl:"Reden *",ja:"理由 *",zh:"原因 *",ru:"Причина *",ar:"السبب *",hi:"कारण *",ko:"사유 *",tr:"Sebep *",pl:"Powód *",sv:"Anledning *",id:"Alasan *",th:"เหตุผล *"},
"moderation.date":{en:"Date",pt:"Data",fr:"Date",de:"Datum",it:"Data",nl:"Datum",ja:"日付",zh:"日期",ru:"Дата",ar:"التاريخ",hi:"तारीख",ko:"날짜",tr:"Tarih",pl:"Data",sv:"Datum",id:"Tanggal",th:"วันที่"},
"moderation.targetUser":{en:"Target User",pt:"Usuário Alvo",fr:"Utilisateur Cible",de:"Zielbenutzer",it:"Utente Obiettivo",nl:"Doelgebruiker",ja:"対象ユーザー",zh:"目标用户",ru:"Целевой пользователь",ar:"المستخدم المستهدف",hi:"लक्षित उपयोगकर्ता",ko:"대상 사용자",tr:"Hedef Kullanıcı",pl:"Docelowy Użytkownik",sv:"Målanvändare",id:"Pengguna Target",th:"ผู้ใช้เป้าหมาย"},
"moderation.details":{en:"Details",pt:"Detalhes",fr:"Détails",de:"Details",it:"Dettagli",nl:"Details",ja:"詳細",zh:"详情",ru:"Детали",ar:"التفاصيل",hi:"विवरण",ko:"세부사항",tr:"Ayrıntılar",pl:"Szczegóły",sv:"Detaljer",id:"Detail",th:"รายละเอียด"},
"moderation.actions.warn":{en:"Warning",pt:"Advertência",fr:"Avertissement",de:"Verwarnung",it:"Avvertimento",nl:"Waarschuwing",ja:"警告",zh:"警告",ru:"Предупреждение",ar:"تحذير",hi:"चेतावनी",ko:"경고",tr:"Uyarı",pl:"Ostrzeżenie",sv:"Varning",id:"Peringatan",th:"คำเตือน"},
"moderation.actions.delete_post":{en:"Delete post",pt:"Excluir publicação",fr:"Supprimer publication",de:"Beitrag löschen",it:"Elimina pubblicazione",nl:"Bericht verwijderen",ja:"投稿を削除",zh:"删除帖子",ru:"Удалить публикацию",ar:"حذف المنشور",hi:"पोस्ट हटाएं",ko:"게시물 삭제",tr:"Gönderiyi sil",pl:"Usuń post",sv:"Ta bort inlägg",id:"Hapus postingan",th:"ลบโพสต์"},
"moderation.actions.delete_thread":{en:"Delete thread",pt:"Excluir tópico",fr:"Supprimer sujet",de:"Thema löschen",it:"Elimina thread",nl:"Onderwerp verwijderen",ja:"スレッドを削除",zh:"删除主题",ru:"Удалить тему",ar:"حذف الموضوع",hi:"थ्रेड हटाएं",ko:"스레드 삭제",tr:"Konuyu sil",pl:"Usuń wątek",sv:"Ta bort tråd",id:"Hapus thread",th:"ลบกระทู้"},
"moderation.actions.edit_post":{en:"Edit post",pt:"Editar publicação",fr:"Modifier publication",de:"Beitrag bearbeiten",it:"Modifica pubblicazione",nl:"Bericht bewerken",ja:"投稿を編集",zh:"编辑帖子",ru:"Редактировать публикацию",ar:"تعديل المنشور",hi:"पोस्ट संपादित करें",ko:"게시물 편집",tr:"Gönderiyi düzenle",pl:"Edytuj post",sv:"Redigera inlägg",id:"Edit postingan",th:"แก้ไขโพสต์"},
"moderation.actions.edit_thread":{en:"Edit thread",pt:"Editar tópico",fr:"Modifier sujet",de:"Thema bearbeiten",it:"Modifica thread",nl:"Onderwerp bewerken",ja:"スレッドを編集",zh:"编辑主题",ru:"Редактировать тему",ar:"تعديل الموضوع",hi:"थ्रेड संपादित करें",ko:"스레드 편집",tr:"Konuyu düzenle",pl:"Edytuj wątek",sv:"Redigera tråd",id:"Edit thread",th:"แก้ไขกระทู้"},
"moderation.actions.lock_thread":{en:"Lock thread",pt:"Bloquear tópico",fr:"Verrouiller sujet",de:"Thema sperren",it:"Blocca thread",nl:"Onderwerp vergrendelen",ja:"スレッドをロック",zh:"锁定主题",ru:"Заблокировать тему",ar:"قفل الموضوع",hi:"थ्रेड लॉक करें",ko:"스레드 잠금",tr:"Konuyu kilitle",pl:"Zablokuj wątek",sv:"Lås tråd",id:"Kunci thread",th:"ล็อกกระทู้"},
"moderation.actions.unlock_thread":{en:"Unlock thread",pt:"Desbloquear tópico",fr:"Déverrouiller sujet",de:"Thema entsperren",it:"Sblocca thread",nl:"Onderwerp ontgrendelen",ja:"スレッドのロックを解除",zh:"解锁主题",ru:"Разблокировать тему",ar:"فتح الموضوع",hi:"थ्रेड अनलॉक करें",ko:"스레드 잠금 해제",tr:"Konunun kilidini aç",pl:"Odblokuj wątek",sv:"Lås upp tråd",id:"Buka kunci thread",th:"ปลดล็อกกระทู้"},
"moderation.actions.pin_thread":{en:"Pin thread",pt:"Fixar tópico",fr:"Épingler sujet",de:"Thema anheften",it:"Fissa thread",nl:"Onderwerp vastpinnen",ja:"スレッドを固定",zh:"置顶主题",ru:"Закрепить тему",ar:"تثبيت الموضوع",hi:"थ्रेड पिन करें",ko:"스레드 고정",tr:"Konuyu sabitle",pl:"Przypnij wątek",sv:"Fäst tråd",id:"Sematkan thread",th:"ปักหมุดกระทู้"},
"moderation.actions.unpin_thread":{en:"Unpin thread",pt:"Desfixar tópico",fr:"Détacher sujet",de:"Thema lösen",it:"Rimuovi fissaggio thread",nl:"Onderwerp losmaken",ja:"スレッドの固定を解除",zh:"取消置顶",ru:"Открепить тему",ar:"إلغاء تثبيت الموضوع",hi:"थ्रेड अनपिन करें",ko:"스레드 고정 해제",tr:"Sabitlemeyi kaldır",pl:"Odepnij wątek",sv:"Lösgör tråd",id:"Lepas sematan thread",th:"เลิกปักหมุดกระทู้"},
"moderation.actions.ban":{en:"Ban",pt:"Expulsão",fr:"Bannissement",de:"Bann",it:"Espulsione",nl:"Verbanning",ja:"追放",zh:"封禁",ru:"Бан",ar:"حظر",hi:"प्रतिबंध",ko:"차단",tr:"Yasaklama",pl:"Ban",sv:"Avstängning",id:"Blokir",th:"แบน"},
"moderation.actions.unban":{en:"Unban",pt:"Remover expulsão",fr:"Lever le bannissement",de:"Bann aufheben",it:"Rimuovi espulsione",nl:"Verbanning opheffen",ja:"追放解除",zh:"解除封禁",ru:"Разбан",ar:"رفع الحظر",hi:"प्रतिबंध हटाएं",ko:"차단 해제",tr:"Yasağı kaldır",pl:"Odbanuj",sv:"Häv avstängning",id:"Buka blokir",th:"ยกเลิกแบน"},
"moderation.actions.suspend":{en:"Suspension",pt:"Suspensão",fr:"Suspension",de:"Sperrung",it:"Sospensione",nl:"Schorsing",ja:"停止",zh:"暂停",ru:"Блокировка",ar:"إيقاف",hi:"निलंबन",ko:"정지",tr:"Askıya alma",pl:"Zawieszenie",sv:"Avstängning",id:"Penangguhan",th:"การระงับ"},
"moderation.actions.unsuspend":{en:"Unsuspend",pt:"Remover suspensão",fr:"Lever la suspension",de:"Sperrung aufheben",it:"Rimuovi sospensione",nl:"Schorsing opheffen",ja:"停止解除",zh:"解除暂停",ru:"Разблокировать",ar:"رفع الإيقاف",hi:"निलंबन हटाएं",ko:"정지 해제",tr:"Askıyı kaldır",pl:"Przywróć",sv:"Häv avstängning",id:"Batalkan penangguhan",th:"ยกเลิกการระงับ"},
"moderation.actions.ip_ban":{en:"IP Ban",pt:"Bloqueio de IP",fr:"Blocage IP",de:"IP-Sperre",it:"Ban IP",nl:"IP-blokkade",ja:"IPブロック",zh:"IP封禁",ru:"Блокировка IP",ar:"حظر IP",hi:"IP प्रतिबंध",ko:"IP 차단",tr:"IP Yasağı",pl:"Blokada IP",sv:"IP-blockering",id:"Blokir IP",th:"แบน IP"},
"moderation.actions.ip_unban":{en:"Remove IP Ban",pt:"Remover bloqueio de IP",fr:"Lever le blocage IP",de:"IP-Sperre aufheben",it:"Rimuovi ban IP",nl:"IP-blokkade opheffen",ja:"IPブロック解除",zh:"解除IP封禁",ru:"Снять блокировку IP",ar:"رفع حظر IP",hi:"IP प्रतिबंध हटाएं",ko:"IP 차단 해제",tr:"IP Yasağını Kaldır",pl:"Usuń blokadę IP",sv:"Ta bort IP-blockering",id:"Hapus blokir IP",th:"ยกเลิกแบน IP"},
"moderation.actions.verify":{en:"Verify",pt:"Verificar",fr:"Vérifier",de:"Verifizieren",it:"Verifica",nl:"Verifiëren",ja:"認証",zh:"验证",ru:"Верифицировать",ar:"توثيق",hi:"सत्यापित करें",ko:"인증",tr:"Doğrula",pl:"Zweryfikuj",sv:"Verifiera",id:"Verifikasi",th:"ยืนยัน"},
"moderation.actions.unverify":{en:"Remove verification",pt:"Remover verificação",fr:"Retirer la vérification",de:"Verifizierung entfernen",it:"Rimuovi verifica",nl:"Verificatie verwijderen",ja:"認証を取り消す",zh:"取消验证",ru:"Снять верификацию",ar:"إزالة التوثيق",hi:"सत्यापन हटाएं",ko:"인증 취소",tr:"Doğrulamayı kaldır",pl:"Usuń weryfikację",sv:"Ta bort verifiering",id:"Hapus verifikasi",th:"ยกเลิกการยืนยัน"},
"moderation.actions.promote":{en:"Promote",pt:"Promover",fr:"Promouvoir",de:"Befördern",it:"Promuovi",nl:"Promoveren",ja:"昇格",zh:"提升",ru:"Повысить",ar:"ترقية",hi:"प्रमोट करें",ko:"승진",tr:"Yükselt",pl:"Awansuj",sv:"Befordra",id:"Promosikan",th:"เลื่อนตำแหน่ง"},
"moderation.actions.demote":{en:"Demote",pt:"Rebaixar",fr:"Rétrograder",de:"Herabstufen",it:"Retrocedi",nl:"Degraderen",ja:"降格",zh:"降级",ru:"Понизить",ar:"تخفيض",hi:"पदावनत करें",ko:"강등",tr:"Düşür",pl:"Degraduj",sv:"Degradera",id:"Turunkan",th:"ลดตำแหน่ง"},
"moderation.actions.delete_user":{en:"Delete user",pt:"Excluir usuário",fr:"Supprimer utilisateur",de:"Benutzer löschen",it:"Elimina utente",nl:"Gebruiker verwijderen",ja:"ユーザーを削除",zh:"删除用户",ru:"Удалить пользователя",ar:"حذف المستخدم",hi:"उपयोगकर्ता हटाएं",ko:"사용자 삭제",tr:"Kullanıcıyı sil",pl:"Usuń użytkownika",sv:"Ta bort användare",id:"Hapus pengguna",th:"ลบผู้ใช้"},
"moderation.suspension.title":{en:"Suspend User",pt:"Suspender Usuário",fr:"Suspendre l'Utilisateur",de:"Benutzer sperren",it:"Sospendi Utente",nl:"Gebruiker schorsen",ja:"ユーザーを停止",zh:"暂停用户",ru:"Заблокировать пользователя",ar:"إيقاف المستخدم",hi:"उपयोगकर्ता को निलंबित करें",ko:"사용자 정지",tr:"Kullanıcıyı Askıya Al",pl:"Zawieś Użytkownika",sv:"Stäng av Användare",id:"Tangguhkan Pengguna",th:"ระงับผู้ใช้"},
"moderation.suspension.permanent":{en:"Permanent",pt:"Permanente",fr:"Permanent",de:"Permanent",it:"Permanente",nl:"Permanent",ja:"永久",zh:"永久",ru:"Постоянная",ar:"دائم",hi:"स्थायी",ko:"영구",tr:"Kalıcı",pl:"Permanentne",sv:"Permanent",id:"Permanen",th:"ถาวร"},
"moderation.suspension.temporary":{en:"Temporary",pt:"Temporário",fr:"Temporaire",de:"Vorübergehend",it:"Temporanea",nl:"Tijdelijk",ja:"一時的",zh:"临时",ru:"Временная",ar:"مؤقت",hi:"अस्थायी",ko:"임시",tr:"Geçici",pl:"Tymczasowe",sv:"Tillfällig",id:"Sementara",th:"ชั่วคราว"},
"moderation.suspension.duration":{en:"Duration",pt:"Duração",fr:"Durée",de:"Dauer",it:"Durata",nl:"Duur",ja:"期間",zh:"期限",ru:"Длительность",ar:"المدة",hi:"अवधि",ko:"기간",tr:"Süre",pl:"Czas trwania",sv:"Varaktighet",id:"Durasi",th:"ระยะเวลา"},
"moderation.suspension.hours":{en:"Hours",pt:"Horas",fr:"Heures",de:"Stunden",it:"Ore",nl:"Uren",ja:"時間",zh:"小时",ru:"Часов",ar:"ساعات",hi:"घंटे",ko:"시간",tr:"Saat",pl:"Godziny",sv:"Timmar",id:"Jam",th:"ชั่วโมง"},
"moderation.suspension.days":{en:"Days",pt:"Dias",fr:"Jours",de:"Tage",it:"Giorni",nl:"Dagen",ja:"日",zh:"天",ru:"Дней",ar:"أيام",hi:"दिन",ko:"일",tr:"Gün",pl:"Dni",sv:"Dagar",id:"Hari",th:"วัน"},
"moderation.suspension.weeks":{en:"Weeks",pt:"Semanas",fr:"Semaines",de:"Wochen",it:"Settimane",nl:"Weken",ja:"週間",zh:"周",ru:"Недель",ar:"أسابيع",hi:"सप्ताह",ko:"주",tr:"Hafta",pl:"Tygodnie",sv:"Veckor",id:"Minggu",th:"สัปดาห์"},
"moderation.suspension.months":{en:"Months",pt:"Meses",fr:"Mois",de:"Monate",it:"Mesi",nl:"Maanden",ja:"ヶ月",zh:"月",ru:"Месяцев",ar:"أشهر",hi:"महीने",ko:"개월",tr:"Ay",pl:"Miesiące",sv:"Månader",id:"Bulan",th:"เดือน"},
"moderation.suspension.startsAt":{en:"Starts",pt:"Inicia",fr:"Commence",de:"Beginnt",it:"Inizia",nl:"Begint",ja:"開始",zh:"开始",ru:"Начало",ar:"يبدأ",hi:"शुरू",ko:"시작",tr:"Başlangıç",pl:"Rozpoczyna się",sv:"Börjar",id:"Mulai",th:"เริ่ม"},
"moderation.suspension.expiresAt":{en:"Expires",pt:"Expira",fr:"Expire",de:"Läuft ab",it:"Scade",nl:"Verloopt",ja:"有効期限",zh:"到期",ru:"Истекает",ar:"ينتهي",hi:"समाप्ति",ko:"만료",tr:"Bitiş",pl:"Wygasa",sv:"Upphör",id:"Berakhir",th:"หมดอายุ"},
"moderation.suspension.liftSuspension":{en:"Lift suspension",pt:"Levantar suspensão",fr:"Lever la suspension",de:"Sperrung aufheben",it:"Rimuovi sospensione",nl:"Schorsing opheffen",ja:"停止を解除",zh:"解除暂停",ru:"Снять блокировку",ar:"رفع الإيقاف",hi:"निलंबन हटाएं",ko:"정지 해제",tr:"Askıyı kaldır",pl:"Zdejmij zawieszenie",sv:"Häv avstängning",id:"Cabut penangguhan",th:"ยกเลิกการระงับ"},
"moderation.suspension.userSuspended":{en:"User suspended",pt:"Usuário suspenso",fr:"Utilisateur suspendu",de:"Benutzer gesperrt",it:"Utente sospeso",nl:"Gebruiker geschorst",ja:"ユーザー停止済み",zh:"用户已暂停",ru:"Пользователь заблокирован",ar:"المستخدم معلق",hi:"उपयोगकर्ता निलंबित",ko:"사용자 정지됨",tr:"Kullanıcı askıya alındı",pl:"Użytkownik zawieszony",sv:"Användare avstängd",id:"Pengguna ditangguhkan",th:"ผู้ใช้ถูกระงับ"},
"moderation.suspension.suspendedUntil":{en:"Suspended until",pt:"Suspenso até",fr:"Suspendu jusqu'au",de:"Gesperrt bis",it:"Sospeso fino al",nl:"Geschorst tot",ja:"停止期限",zh:"暂停至",ru:"Заблокирован до",ar:"معلق حتى",hi:"निलंबित",ko:"정지 기한",tr:"Askıya alınma bitiş",pl:"Zawieszony do",sv:"Avstängd till",id:"Ditangguhkan hingga",th:"ระงับจนถึง"},
"moderation.ipBan.title":{en:"Ban IP",pt:"Bloquear IP",fr:"Bloquer IP",de:"IP sperren",it:"Ban IP",nl:"IP blokkeren",ja:"IPをブロック",zh:"封禁IP",ru:"Блокировка IP",ar:"حظر IP",hi:"IP प्रतिबंध",ko:"IP 차단",tr:"IP Yasakla",pl:"Zablokuj IP",sv:"Blockera IP",id:"Blokir IP",th:"แบน IP"},
"moderation.ipBan.ipAddress":{en:"IP Address",pt:"Endereço IP",fr:"Adresse IP",de:"IP-Adresse",it:"Indirizzo IP",nl:"IP-adres",ja:"IPアドレス",zh:"IP地址",ru:"IP-адрес",ar:"عنوان IP",hi:"IP पता",ko:"IP 주소",tr:"IP Adresi",pl:"Adres IP",sv:"IP-adress",id:"Alamat IP",th:"ที่อยู่ IP"},
"moderation.ipBan.banIp":{en:"Ban IP",pt:"Bloquear IP",fr:"Bloquer IP",de:"IP sperren",it:"Blocca IP",nl:"IP blokkeren",ja:"IPをブロック",zh:"封禁IP",ru:"Заблокировать IP",ar:"حظر IP",hi:"IP प्रतिबंधित करें",ko:"IP 차단",tr:"IP Yasakla",pl:"Zablokuj IP",sv:"Blockera IP",id:"Blokir IP",th:"แบน IP"},
"moderation.ipBan.unbanIp":{en:"Unban IP",pt:"Desbloquear IP",fr:"Débloquer IP",de:"IP-Sperre aufheben",it:"Sblocca IP",nl:"IP deblokkeren",ja:"IPブロック解除",zh:"解除IP封禁",ru:"Разблокировать IP",ar:"رفع حظر IP",hi:"IP प्रतिबंध हटाएं",ko:"IP 차단 해제",tr:"IP Yasağını Kaldır",pl:"Odblokuj IP",sv:"Avblockera IP",id:"Buka blokir IP",th:"ยกเลิกแบน IP"},
"moderation.ipBan.permanent":{en:"Permanent",pt:"Permanente",fr:"Permanent",de:"Permanent",it:"Permanente",nl:"Permanent",ja:"永久",zh:"永久",ru:"Постоянный",ar:"دائم",hi:"स्थायी",ko:"영구",tr:"Kalıcı",pl:"Permanentny",sv:"Permanent",id:"Permanen",th:"ถาวร"},
"moderation.ipBan.temporary":{en:"Temporary",pt:"Temporário",fr:"Temporaire",de:"Vorübergehend",it:"Temporaneo",nl:"Tijdelijk",ja:"一時的",zh:"临时",ru:"Временный",ar:"مؤقت",hi:"अस्थायी",ko:"임시",tr:"Geçici",pl:"Tymczasowy",sv:"Tillfällig",id:"Sementara",th:"ชั่วคราว"},
"moderation.ipBan.activeBans":{en:"Active bans",pt:"Bloqueios ativos",fr:"Blocages actifs",de:"Aktive Sperren",it:"Ban attivi",nl:"Actieve blokkades",ja:"アクティブなブロック",zh:"活跃封禁",ru:"Активные блокировки",ar:"الحظر النشط",hi:"सक्रिय प्रतिबंध",ko:"활성 차단",tr:"Aktif yasaklar",pl:"Aktywne blokady",sv:"Aktiva blockeringar",id:"Blokir aktif",th:"การแบนที่ใช้งานอยู่"},
"moderation.ipBan.expiredBans":{en:"Expired bans",pt:"Bloqueios expirados",fr:"Blocages expirés",de:"Abgelaufene Sperren",it:"Ban scaduti",nl:"Verlopen blokkades",ja:"期限切れのブロック",zh:"已过期封禁",ru:"Истекшие блокировки",ar:"الحظر المنتهي",hi:"समाप्त प्रतिबंध",ko:"만료된 차단",tr:"Süresi dolmuş yasaklar",pl:"Wygasłe blokady",sv:"Utgångna blockeringar",id:"Blokir kedaluwarsa",th:"การแบนที่หมดอายุ"},
"moderation.noRecords":{en:"No moderation records",pt:"Nenhum registro de moderação",fr:"Aucun enregistrement de modération",de:"Keine Moderationseinträge",it:"Nessun record di moderazione",nl:"Geen moderatierecords",ja:"モデレーション記録なし",zh:"没有管理记录",ru:"Нет записей модерации",ar:"لا توجد سجلات إشراف",hi:"कोई मॉडरेशन रिकॉर्ड नहीं",ko:"관리 기록 없음",tr:"Moderasyon kaydı yok",pl:"Brak wpisów moderacji",sv:"Inga modereringsposter",id:"Tidak ada catatan moderasi",th:"ไม่มีบันทึกการดูแล"},
"moderation.confirmAction":{en:"Are you sure you want to perform this action?",pt:"Tem certeza de que deseja realizar esta ação?",fr:"Êtes-vous sûr de vouloir effectuer cette action ?",de:"Sind Sie sicher, dass Sie diese Aktion durchführen möchten?",it:"Sei sicuro di voler eseguire questa azione?",nl:"Weet je zeker dat je deze actie wilt uitvoeren?",ja:"この操作を実行してもよろしいですか？",zh:"您确定要执行此操作吗？",ru:"Вы уверены, что хотите выполнить это действие?",ar:"هل أنت متأكد من تنفيذ هذا الإجراء؟",hi:"क्या आप वाकई यह कार्रवाई करना चाहते हैं?",ko:"이 작업을 수행하시겠습니까?",tr:"Bu eylemi gerçekleştirmek istediğinizden emin misiniz?",pl:"Czy na pewno chcesz wykonać tę akcję?",sv:"Är du säker på att du vill utföra denna åtgärd?",id:"Apakah Anda yakin ingin melakukan tindakan ini?",th:"คุณแน่ใจหรือไม่ว่าต้องการดำเนินการนี้?"},
"moderation.warnings.title":{en:"Warnings",pt:"Advertências",fr:"Avertissements",de:"Verwarnungen",it:"Avvertimenti",nl:"Waarschuwingen",ja:"警告",zh:"警告",ru:"Предупреждения",ar:"التحذيرات",hi:"चेतावनियां",ko:"경고",tr:"Uyarılar",pl:"Ostrzeżenia",sv:"Varningar",id:"Peringatan",th:"คำเตือน"},
"moderation.warnings.newWarning":{en:"New Warning",pt:"Nova Advertência",fr:"Nouvel Avertissement",de:"Neue Verwarnung",it:"Nuovo Avvertimento",nl:"Nieuwe Waarschuwing",ja:"新しい警告",zh:"新警告",ru:"Новое предупреждение",ar:"تحذير جديد",hi:"नई चेतावनी",ko:"새 경고",tr:"Yeni Uyarı",pl:"Nowe Ostrzeżenie",sv:"Ny Varning",id:"Peringatan Baru",th:"คำเตือนใหม่"},
"moderation.warnings.reason":{en:"Reason",pt:"Razão",fr:"Raison",de:"Grund",it:"Motivo",nl:"Reden",ja:"理由",zh:"原因",ru:"Причина",ar:"السبب",hi:"कारण",ko:"사유",tr:"Sebep",pl:"Powód",sv:"Anledning",id:"Alasan",th:"เหตุผล"},
"moderation.warnings.description":{en:"Description",pt:"Descrição",fr:"Description",de:"Beschreibung",it:"Descrizione",nl:"Beschrijving",ja:"説明",zh:"描述",ru:"Описание",ar:"الوصف",hi:"विवरण",ko:"설명",tr:"Açıklama",pl:"Opis",sv:"Beskrivning",id:"Deskripsi",th:"คำอธิบาย"},
"moderation.warnings.active":{en:"Active",pt:"Ativa",fr:"Active",de:"Aktiv",it:"Attiva",nl:"Actief",ja:"有効",zh:"活跃",ru:"Активно",ar:"نشط",hi:"सक्रिय",ko:"활성",tr:"Aktif",pl:"Aktywne",sv:"Aktiv",id:"Aktif",th:"ใช้งานอยู่"},
"moderation.warnings.expired":{en:"Expired",pt:"Expirada",fr:"Expirée",de:"Abgelaufen",it:"Scaduta",nl:"Verlopen",ja:"期限切れ",zh:"已过期",ru:"Истекло",ar:"منتهي",hi:"समाप्त",ko:"만료됨",tr:"Süresi dolmuş",pl:"Wygasłe",sv:"Utgången",id:"Kedaluwarsa",th:"หมดอายุ"},
"moderation.warnings.expiresAt":{en:"Expires",pt:"Expira",fr:"Expire",de:"Läuft ab",it:"Scade",nl:"Verloopt",ja:"有効期限",zh:"到期",ru:"Истекает",ar:"ينتهي",hi:"समाप्ति",ko:"만료",tr:"Bitiş",pl:"Wygasa",sv:"Upphör",id:"Berakhir",th:"หมดอายุ"},
"moderation.warnings.issuedBy":{en:"Issued by",pt:"Emitida por",fr:"Émis par",de:"Ausgestellt von",it:"Emesso da",nl:"Uitgegeven door",ja:"発行者",zh:"发出者",ru:"Выдано",ar:"صدر من",hi:"द्वारा जारी",ko:"발행자",tr:"Veren",pl:"Wystawione przez",sv:"Utfärdad av",id:"Diterbitkan oleh",th:"ออกโดย"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2a (moderation part 1 - 60 keys) done!');
