const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === CONTACT ===
"contact.title":{en:"Contact Us",pt:"Contato",fr:"Contactez-nous",de:"Kontakt",it:"Contattaci",nl:"Contact",ja:"お問い合わせ",zh:"联系我们",ru:"Связаться с нами",ar:"اتصل بنا",hi:"संपर्क करें",ko:"문의하기",tr:"İletişim",pl:"Kontakt",sv:"Kontakta oss",id:"Hubungi Kami",th:"ติดต่อเรา"},
"contact.subtitle":{en:"We're here to help you",pt:"Estamos aqui para ajudá-lo",fr:"Nous sommes là pour vous aider",de:"Wir sind hier, um Ihnen zu helfen",it:"Siamo qui per aiutarti",nl:"Wij zijn hier om je te helpen",ja:"お気軽にお問い合わせください",zh:"我们随时为您提供帮助",ru:"Мы здесь, чтобы помочь",ar:"نحن هنا لمساعدتك",hi:"हम आपकी सहायता के लिए यहाँ हैं",ko:"도움을 드리겠습니다",tr:"Size yardımcı olmak için buradayız",pl:"Jesteśmy tu, aby pomóc",sv:"Vi finns här för att hjälpa dig",id:"Kami di sini untuk membantu Anda",th:"เราพร้อมช่วยเหลือคุณ"},
"contact.name":{en:"Name",pt:"Nome",fr:"Nom",de:"Name",it:"Nome",nl:"Naam",ja:"名前",zh:"姓名",ru:"Имя",ar:"الاسم",hi:"नाम",ko:"이름",tr:"Ad",pl:"Imię",sv:"Namn",id:"Nama",th:"ชื่อ"},
"contact.namePlaceholder":{en:"Your name",pt:"Seu nome",fr:"Votre nom",de:"Ihr Name",it:"Il tuo nome",nl:"Je naam",ja:"お名前",zh:"您的姓名",ru:"Ваше имя",ar:"اسمك",hi:"आपका नाम",ko:"이름",tr:"Adınız",pl:"Twoje imię",sv:"Ditt namn",id:"Nama Anda",th:"ชื่อของคุณ"},
"contact.email":{en:"Email",pt:"Email",fr:"Email",de:"E-Mail",it:"Email",nl:"E-mail",ja:"メール",zh:"邮箱",ru:"Электронная почта",ar:"البريد الإلكتروني",hi:"ईमेल",ko:"이메일",tr:"E-posta",pl:"Email",sv:"E-post",id:"Email",th:"อีเมล"},
"contact.emailPlaceholder":{en:"your@email.com",pt:"seu@email.com",fr:"votre@email.com",de:"ihre@email.com",it:"tua@email.com",nl:"jouw@email.com",ja:"your@email.com",zh:"your@email.com",ru:"ваш@email.com",ar:"your@email.com",hi:"your@email.com",ko:"your@email.com",tr:"email@adresiniz.com",pl:"twoj@email.com",sv:"din@email.com",id:"anda@email.com",th:"your@email.com"},
"contact.subject":{en:"Subject",pt:"Assunto",fr:"Sujet",de:"Betreff",it:"Oggetto",nl:"Onderwerp",ja:"件名",zh:"主题",ru:"Тема",ar:"الموضوع",hi:"विषय",ko:"제목",tr:"Konu",pl:"Temat",sv:"Ämne",id:"Subjek",th:"หัวข้อ"},
"contact.subjectPlaceholder":{en:"How can we help?",pt:"Como podemos ajudar?",fr:"Comment pouvons-nous vous aider ?",de:"Wie können wir helfen?",it:"Come possiamo aiutarti?",nl:"Hoe kunnen we helpen?",ja:"ご用件は？",zh:"有什么可以帮您的？",ru:"Чем можем помочь?",ar:"كيف يمكننا المساعدة؟",hi:"हम कैसे मदद कर सकते हैं?",ko:"어떻게 도와드릴까요?",tr:"Nasıl yardımcı olabiliriz?",pl:"Jak możemy pomóc?",sv:"Hur kan vi hjälpa?",id:"Bagaimana kami bisa membantu?",th:"เราช่วยอะไรได้บ้าง?"},
"contact.category":{en:"Category",pt:"Categoria",fr:"Catégorie",de:"Kategorie",it:"Categoria",nl:"Categorie",ja:"カテゴリ",zh:"类别",ru:"Категория",ar:"الفئة",hi:"श्रेणी",ko:"카테고리",tr:"Kategori",pl:"Kategoria",sv:"Kategori",id:"Kategori",th:"หมวดหมู่"},
"contact.selectCategory":{en:"Select a category",pt:"Selecione uma categoria",fr:"Sélectionnez une catégorie",de:"Kategorie wählen",it:"Seleziona una categoria",nl:"Selecteer een categorie",ja:"カテゴリを選択",zh:"选择类别",ru:"Выберите категорию",ar:"اختر فئة",hi:"श्रेणी चुनें",ko:"카테고리 선택",tr:"Kategori seçin",pl:"Wybierz kategorię",sv:"Välj en kategori",id:"Pilih kategori",th:"เลือกหมวดหมู่"},
"contact.catGeneral":{en:"General inquiry",pt:"Consulta geral",fr:"Demande générale",de:"Allgemeine Anfrage",it:"Richiesta generale",nl:"Algemene vraag",ja:"一般的なお問い合わせ",zh:"一般咨询",ru:"Общий вопрос",ar:"استفسار عام",hi:"सामान्य पूछताछ",ko:"일반 문의",tr:"Genel soru",pl:"Ogólne zapytanie",sv:"Allmän förfrågan",id:"Pertanyaan umum",th:"สอบถามทั่วไป"},
"contact.catTechnical":{en:"Technical support",pt:"Suporte técnico",fr:"Support technique",de:"Technischer Support",it:"Supporto tecnico",nl:"Technische ondersteuning",ja:"技術サポート",zh:"技术支持",ru:"Техническая поддержка",ar:"الدعم الفني",hi:"तकनीकी सहायता",ko:"기술 지원",tr:"Teknik destek",pl:"Wsparcie techniczne",sv:"Teknisk support",id:"Dukungan teknis",th:"ฝ่ายสนับสนุนด้านเทคนิค"},
"contact.catReport":{en:"Report a problem",pt:"Reportar um problema",fr:"Signaler un problème",de:"Problem melden",it:"Segnala un problema",nl:"Probleem melden",ja:"問題を報告",zh:"报告问题",ru:"Сообщить о проблеме",ar:"الإبلاغ عن مشكلة",hi:"समस्या की रिपोर्ट",ko:"문제 신고",tr:"Sorun bildir",pl:"Zgłoś problem",sv:"Rapportera ett problem",id:"Laporkan masalah",th:"แจ้งปัญหา"},
"contact.catSuggestion":{en:"Suggestion",pt:"Sugestão",fr:"Suggestion",de:"Vorschlag",it:"Suggerimento",nl:"Suggestie",ja:"提案",zh:"建议",ru:"Предложение",ar:"اقتراح",hi:"सुझाव",ko:"제안",tr:"Öneri",pl:"Sugestia",sv:"Förslag",id:"Saran",th:"ข้อเสนอแนะ"},
"contact.catVerification":{en:"Verification",pt:"Verificação",fr:"Vérification",de:"Verifizierung",it:"Verifica",nl:"Verificatie",ja:"認証",zh:"验证",ru:"Верификация",ar:"التحقق",hi:"सत्यापन",ko:"인증",tr:"Doğrulama",pl:"Weryfikacja",sv:"Verifiering",id:"Verifikasi",th:"การยืนยัน"},
"contact.catAdvertising":{en:"Advertising",pt:"Publicidade",fr:"Publicité",de:"Werbung",it:"Pubblicità",nl:"Advertenties",ja:"広告",zh:"广告",ru:"Реклама",ar:"إعلانات",hi:"विज्ञापन",ko:"광고",tr:"Reklam",pl:"Reklama",sv:"Annonsering",id:"Iklan",th:"โฆษณา"},
"contact.catOther":{en:"Other",pt:"Outro",fr:"Autre",de:"Sonstiges",it:"Altro",nl:"Anders",ja:"その他",zh:"其他",ru:"Другое",ar:"أخرى",hi:"अन्य",ko:"기타",tr:"Diğer",pl:"Inne",sv:"Övrigt",id:"Lainnya",th:"อื่นๆ"},
"contact.message":{en:"Message",pt:"Mensagem",fr:"Message",de:"Nachricht",it:"Messaggio",nl:"Bericht",ja:"メッセージ",zh:"留言",ru:"Сообщение",ar:"الرسالة",hi:"संदेश",ko:"메시지",tr:"Mesaj",pl:"Wiadomość",sv:"Meddelande",id:"Pesan",th:"ข้อความ"},
"contact.messagePlaceholder":{en:"Describe your inquiry in detail...",pt:"Descreva sua consulta em detalhes...",fr:"Décrivez votre demande en détail...",de:"Beschreiben Sie Ihre Anfrage im Detail...",it:"Descrivi la tua richiesta in dettaglio...",nl:"Beschrijf je vraag in detail...",ja:"お問い合わせ内容を詳しく記入してください...",zh:"详细描述您的问题...",ru:"Подробно опишите ваш вопрос...",ar:"اشرح استفسارك بالتفصيل...",hi:"अपनी पूछताछ का विस्तार से वर्णन करें...",ko:"문의 내용을 자세히 설명해주세요...",tr:"Sorunuzu detaylı açıklayın...",pl:"Opisz swoje zapytanie szczegółowo...",sv:"Beskriv din förfrågan i detalj...",id:"Jelaskan pertanyaan Anda secara detail...",th:"อธิบายรายละเอียดคำถามของคุณ..."},
"contact.send":{en:"Send message",pt:"Enviar mensagem",fr:"Envoyer le message",de:"Nachricht senden",it:"Invia messaggio",nl:"Bericht verzenden",ja:"メッセージを送信",zh:"发送消息",ru:"Отправить сообщение",ar:"إرسال الرسالة",hi:"संदेश भेजें",ko:"메시지 보내기",tr:"Mesaj gönder",pl:"Wyślij wiadomość",sv:"Skicka meddelande",id:"Kirim pesan",th:"ส่งข้อความ"},
"contact.sending":{en:"Sending...",pt:"Enviando...",fr:"Envoi...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"发送中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"भेज रहे हैं...",ko:"전송 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"contact.success":{en:"Message sent successfully",pt:"Mensagem enviada com sucesso",fr:"Message envoyé avec succès",de:"Nachricht erfolgreich gesendet",it:"Messaggio inviato con successo",nl:"Bericht succesvol verzonden",ja:"メッセージが送信されました",zh:"消息发送成功",ru:"Сообщение отправлено",ar:"تم إرسال الرسالة بنجاح",hi:"संदेश सफलतापूर्वक भेजा गया",ko:"메시지가 전송되었습니다",tr:"Mesaj başarıyla gönderildi",pl:"Wiadomość wysłana pomyślnie",sv:"Meddelande skickat",id:"Pesan berhasil dikirim",th:"ส่งข้อความสำเร็จ"},
"contact.successDescription":{en:"We'll respond as soon as possible",pt:"Responderemos o mais rápido possível",fr:"Nous vous répondrons dès que possible",de:"Wir werden so bald wie möglich antworten",it:"Risponderemo il prima possibile",nl:"We reageren zo snel mogelijk",ja:"できるだけ早くご返答いたします",zh:"我们会尽快回复",ru:"Мы ответим как можно скорее",ar:"سنرد في أقرب وقت ممكن",hi:"हम जल्द से जल्द जवाब देंगे",ko:"가능한 빨리 답변 드리겠습니다",tr:"En kısa sürede yanıt vereceğiz",pl:"Odpowiemy jak najszybciej",sv:"Vi svarar så snart som möjligt",id:"Kami akan merespons sesegera mungkin",th:"เราจะตอบกลับโดยเร็วที่สุด"},
"contact.error":{en:"Error sending message",pt:"Erro ao enviar mensagem",fr:"Erreur d'envoi",de:"Fehler beim Senden",it:"Errore di invio",nl:"Fout bij verzenden",ja:"送信エラー",zh:"发送出错",ru:"Ошибка отправки",ar:"خطأ في الإرسال",hi:"भेजने में त्रुटि",ko:"전송 오류",tr:"Gönderme hatası",pl:"Błąd wysyłania",sv:"Sändningsfel",id:"Error mengirim",th:"เกิดข้อผิดพลาดในการส่ง"},
"contact.errorDescription":{en:"Please try again later",pt:"Por favor, tente novamente mais tarde",fr:"Veuillez réessayer plus tard",de:"Bitte versuchen Sie es später erneut",it:"Riprova più tardi",nl:"Probeer het later opnieuw",ja:"後でもう一度お試しください",zh:"请稍后再试",ru:"Пожалуйста, попробуйте позже",ar:"يرجى المحاولة لاحقاً",hi:"कृपया बाद में पुनः प्रयास करें",ko:"나중에 다시 시도해주세요",tr:"Lütfen daha sonra tekrar deneyin",pl:"Spróbuj ponownie później",sv:"Försök igen senare",id:"Silakan coba lagi nanti",th:"กรุณาลองอีกครั้งในภายหลัง"},
"contact.requiredField":{en:"Required field",pt:"Campo obrigatório",fr:"Champ requis",de:"Pflichtfeld",it:"Campo obbligatorio",nl:"Verplicht veld",ja:"必須項目",zh:"必填项",ru:"Обязательное поле",ar:"حقل مطلوب",hi:"आवश्यक फ़ील्ड",ko:"필수 항목",tr:"Zorunlu alan",pl:"Pole wymagane",sv:"Obligatoriskt fält",id:"Bidang wajib",th:"ช่องที่จำเป็น"},
"contact.minMessage":{en:"Minimum 10 characters",pt:"Mínimo 10 caracteres",fr:"Minimum 10 caractères",de:"Mindestens 10 Zeichen",it:"Minimo 10 caratteri",nl:"Minimaal 10 tekens",ja:"10文字以上",zh:"最少10个字符",ru:"Минимум 10 символов",ar:"الحد الأدنى 10 أحرف",hi:"न्यूनतम 10 अक्षर",ko:"최소 10자",tr:"Minimum 10 karakter",pl:"Minimum 10 znaków",sv:"Minst 10 tecken",id:"Minimum 10 karakter",th:"ขั้นต่ำ 10 ตัวอักษร"},
"contact.sendAnother":{en:"Send another message",pt:"Enviar outra mensagem",fr:"Envoyer un autre message",de:"Weitere Nachricht senden",it:"Invia un altro messaggio",nl:"Nog een bericht sturen",ja:"別のメッセージを送信",zh:"发送另一条消息",ru:"Отправить ещё",ar:"إرسال رسالة أخرى",hi:"एक और संदेश भेजें",ko:"다른 메시지 보내기",tr:"Başka mesaj gönder",pl:"Wyślij kolejną wiadomość",sv:"Skicka ett till meddelande",id:"Kirim pesan lain",th:"ส่งข้อความอีก"},
"contact.responseTime":{en:"Average response time: 24-48 hours",pt:"Tempo médio de resposta: 24-48 horas",fr:"Temps de réponse moyen : 24-48 heures",de:"Durchschnittliche Antwortzeit: 24-48 Stunden",it:"Tempo di risposta medio: 24-48 ore",nl:"Gemiddelde reactietijd: 24-48 uur",ja:"平均応答時間：24〜48時間",zh:"平均响应时间：24-48小时",ru:"Среднее время ответа: 24-48 часов",ar:"متوسط وقت الرد: 24-48 ساعة",hi:"औसत प्रतिक्रिया समय: 24-48 घंटे",ko:"평균 응답 시간: 24-48시간",tr:"Ortalama yanıt süresi: 24-48 saat",pl:"Średni czas odpowiedzi: 24-48 godzin",sv:"Genomsnittlig svarstid: 24-48 timmar",id:"Waktu respons rata-rata: 24-48 jam",th:"เวลาตอบกลับเฉลี่ย: 24-48 ชั่วโมง"},
"contact.faqLink":{en:"Check our FAQ",pt:"Confira nossa FAQ",fr:"Consultez notre FAQ",de:"Schauen Sie in unsere FAQ",it:"Consulta le nostre FAQ",nl:"Bekijk onze FAQ",ja:"FAQを確認",zh:"查看常见问题",ru:"Смотрите FAQ",ar:"تحقق من الأسئلة الشائعة",hi:"हमारे FAQ देखें",ko:"FAQ 확인",tr:"SSS'mizi kontrol edin",pl:"Sprawdź nasze FAQ",sv:"Se våra vanliga frågor",id:"Lihat FAQ kami",th:"ดูคำถามที่พบบ่อย"},
"contact.faqDescription":{en:"Find quick answers to the most common questions",pt:"Encontre respostas rápidas às perguntas mais comuns",fr:"Trouvez des réponses rapides aux questions fréquentes",de:"Finden Sie schnelle Antworten auf häufige Fragen",it:"Trova risposte rapide alle domande più comuni",nl:"Vind snelle antwoorden op veelgestelde vragen",ja:"よくある質問への回答を見つける",zh:"快速查找常见问题的答案",ru:"Быстрые ответы на частые вопросы",ar:"ابحث عن إجابات سريعة للأسئلة الشائعة",hi:"सबसे आम सवालों के त्वरित उत्तर पाएं",ko:"자주 묻는 질문에 대한 빠른 답변",tr:"En sık sorulan sorulara hızlı yanıtlar",pl:"Znajdź szybkie odpowiedzi na najczęstsze pytania",sv:"Hitta snabba svar på vanliga frågor",id:"Temukan jawaban cepat untuk pertanyaan umum",th:"ค้นหาคำตอบเร็วสำหรับคำถามที่พบบ่อย"},

// === REPORT ===
"report.title":{en:"Report content",pt:"Reportar conteúdo",fr:"Signaler un contenu",de:"Inhalt melden",it:"Segnala contenuto",nl:"Inhoud rapporteren",ja:"コンテンツを報告",zh:"举报内容",ru:"Пожаловаться на контент",ar:"الإبلاغ عن محتوى",hi:"सामग्री की रिपोर्ट करें",ko:"콘텐츠 신고",tr:"İçerik bildir",pl:"Zgłoś treść",sv:"Rapportera innehåll",id:"Laporkan konten",th:"รายงานเนื้อหา"},
"report.selectReason":{en:"Select a reason",pt:"Selecione um motivo",fr:"Sélectionnez un motif",de:"Wählen Sie einen Grund",it:"Seleziona un motivo",nl:"Selecteer een reden",ja:"理由を選択",zh:"选择原因",ru:"Выберите причину",ar:"اختر سبباً",hi:"कारण चुनें",ko:"사유 선택",tr:"Bir neden seçin",pl:"Wybierz powód",sv:"Välj en anledning",id:"Pilih alasan",th:"เลือกเหตุผล"},
"report.details":{en:"Tell us why you think this content violates the community guidelines.",pt:"Explique por que você acha que este conteúdo viola as normas da comunidade.",fr:"Dites-nous pourquoi ce contenu viole les règles de la communauté.",de:"Erklären Sie, warum dieser Inhalt gegen die Richtlinien verstößt.",it:"Spiegaci perché questo contenuto viola le linee guida.",nl:"Vertel ons waarom deze inhoud de richtlijnen schendt.",ja:"このコンテンツがガイドライン違反と思う理由を教えてください。",zh:"请说明为什么您认为此内容违反了社区准则。",ru:"Расскажите, почему этот контент нарушает правила сообщества.",ar:"أخبرنا لماذا تعتقد أن هذا المحتوى ينتهك إرشادات المجتمع.",hi:"बताएं कि यह सामग्री समुदाय दिशानिर्देशों का उल्लंघन क्यों करती है।",ko:"이 콘텐츠가 커뮤니티 가이드라인을 위반하는 이유를 알려주세요.",tr:"Bu içeriğin topluluk kurallarını neden ihlal ettiğini açıklayın.",pl:"Powiedz nam, dlaczego ta treść narusza zasady społeczności.",sv:"Berätta varför detta innehåll bryter mot riktlinjerna.",id:"Jelaskan mengapa konten ini melanggar pedoman komunitas.",th:"บอกเราว่าทำไมเนื้อหานี้ละเมิดแนวปฏิบัติของชุมชน"},
"report.detailsPlaceholder":{en:"Provide more details...",pt:"Forneça mais detalhes...",fr:"Fournissez plus de détails...",de:"Weitere Details angeben...",it:"Fornisci più dettagli...",nl:"Geef meer details...",ja:"詳細を記入...",zh:"提供更多详情...",ru:"Предоставьте больше деталей...",ar:"قدم المزيد من التفاصيل...",hi:"अधिक विवरण दें...",ko:"자세한 내용을 입력하세요...",tr:"Daha fazla ayrıntı verin...",pl:"Podaj więcej szczegółów...",sv:"Ange mer detaljer...",id:"Berikan detail lebih lanjut...",th:"ให้รายละเอียดเพิ่มเติม..."},
"report.submit":{en:"Send report",pt:"Enviar reporte",fr:"Envoyer le signalement",de:"Bericht senden",it:"Invia segnalazione",nl:"Rapport verzenden",ja:"報告を送信",zh:"发送举报",ru:"Отправить жалобу",ar:"إرسال البلاغ",hi:"रिपोर्ट भेजें",ko:"신고 보내기",tr:"Rapor gönder",pl:"Wyślij zgłoszenie",sv:"Skicka rapport",id:"Kirim laporan",th:"ส่งรายงาน"},
"report.submitting":{en:"Sending...",pt:"Enviando...",fr:"Envoi...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"发送中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"भेज रहे हैं...",ko:"전송 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"report.success":{en:"Report sent successfully",pt:"Reporte enviado com sucesso",fr:"Signalement envoyé",de:"Bericht erfolgreich gesendet",it:"Segnalazione inviata",nl:"Rapport succesvol verzonden",ja:"報告が送信されました",zh:"举报已发送",ru:"Жалоба отправлена",ar:"تم إرسال البلاغ",hi:"रिपोर्ट भेजी गई",ko:"신고가 전송되었습니다",tr:"Rapor gönderildi",pl:"Zgłoszenie wysłane",sv:"Rapport skickad",id:"Laporan berhasil dikirim",th:"ส่งรายงานสำเร็จ"},
"report.alreadyReported":{en:"You have already reported this content",pt:"Você já reportou este conteúdo",fr:"Vous avez déjà signalé ce contenu",de:"Sie haben diesen Inhalt bereits gemeldet",it:"Hai già segnalato questo contenuto",nl:"Je hebt deze inhoud al gerapporteerd",ja:"このコンテンツは既に報告済みです",zh:"您已举报过此内容",ru:"Вы уже пожаловались на этот контент",ar:"لقد أبلغت عن هذا المحتوى بالفعل",hi:"आपने पहले ही इस सामग्री की रिपोर्ट की है",ko:"이미 이 콘텐츠를 신고했습니다",tr:"Bu içeriği zaten bildirdiniz",pl:"Już zgłosiłeś tę treść",sv:"Du har redan rapporterat detta",id:"Anda sudah melaporkan konten ini",th:"คุณรายงานเนื้อหานี้แล้ว"},
"report.error":{en:"Error sending report",pt:"Erro ao enviar reporte",fr:"Erreur d'envoi",de:"Fehler beim Senden",it:"Errore invio",nl:"Fout bij verzenden",ja:"送信エラー",zh:"发送出错",ru:"Ошибка отправки",ar:"خطأ في الإرسال",hi:"भेजने में त्रुटि",ko:"전송 오류",tr:"Gönderme hatası",pl:"Błąd wysyłania",sv:"Sändningsfel",id:"Error mengirim",th:"เกิดข้อผิดพลาด"},
"report.reasons.spam":{en:"Spam",pt:"Spam",fr:"Spam",de:"Spam",it:"Spam",nl:"Spam",ja:"スパム",zh:"垃圾信息",ru:"Спам",ar:"رسائل مزعجة",hi:"स्पैम",ko:"스팸",tr:"Spam",pl:"Spam",sv:"Spam",id:"Spam",th:"สแปม"},
"report.reasons.harassment":{en:"Harassment or bullying",pt:"Assédio ou bullying",fr:"Harcèlement ou intimidation",de:"Belästigung oder Mobbing",it:"Molestie o bullismo",nl:"Intimidatie of pesten",ja:"嫌がらせまたはいじめ",zh:"骚扰或欺凌",ru:"Преследование или травля",ar:"تحرش أو تنمر",hi:"उत्पीड़न या बदमाशी",ko:"괴롭힘 또는 왕따",tr:"Taciz veya zorbalık",pl:"Nękanie lub zastraszanie",sv:"Trakasserier eller mobbning",id:"Pelecehan atau intimidasi",th:"การคุกคามหรือการกลั่นแกล้ง"},
"report.reasons.inappropriate":{en:"Inappropriate content",pt:"Conteúdo inapropriado",fr:"Contenu inapproprié",de:"Unangemessener Inhalt",it:"Contenuto inappropriato",nl:"Ongepaste inhoud",ja:"不適切なコンテンツ",zh:"不当内容",ru:"Неприемлемый контент",ar:"محتوى غير لائق",hi:"अनुचित सामग्री",ko:"부적절한 콘텐츠",tr:"Uygunsuz içerik",pl:"Nieodpowiednia treść",sv:"Olämpligt innehåll",id:"Konten tidak pantas",th:"เนื้อหาไม่เหมาะสม"},
"report.reasons.offTopic":{en:"Off topic",pt:"Fora de tópico",fr:"Hors sujet",de:"Off-Topic",it:"Fuori tema",nl:"Off-topic",ja:"トピック外",zh:"离题",ru:"Не по теме",ar:"خارج الموضوع",hi:"विषय से हटकर",ko:"주제와 무관",tr:"Konu dışı",pl:"Nie na temat",sv:"Utanför ämnet",id:"Di luar topik",th:"นอกเรื่อง"},
"report.reasons.duplicate":{en:"Duplicate",pt:"Duplicado",fr:"Doublon",de:"Duplikat",it:"Duplicato",nl:"Duplicaat",ja:"重複",zh:"重复",ru:"Дубликат",ar:"مكرر",hi:"डुप्लिकेट",ko:"중복",tr:"Kopya",pl:"Duplikat",sv:"Duplikat",id:"Duplikat",th:"ซ้ำ"},
"report.reasons.falseInfo":{en:"False information",pt:"Informação falsa",fr:"Fausse information",de:"Falschinformation",it:"Informazione falsa",nl:"Valse informatie",ja:"虚偽情報",zh:"虚假信息",ru:"Ложная информация",ar:"معلومات كاذبة",hi:"गलत जानकारी",ko:"거짓 정보",tr:"Yanlış bilgi",pl:"Fałszywe informacje",sv:"Falsk information",id:"Informasi palsu",th:"ข้อมูลเท็จ"},
"report.reasons.illegal":{en:"Illegal content",pt:"Conteúdo ilegal",fr:"Contenu illégal",de:"Illegaler Inhalt",it:"Contenuto illegale",nl:"Illegale inhoud",ja:"違法コンテンツ",zh:"违法内容",ru:"Нелегальный контент",ar:"محتوى غير قانوني",hi:"अवैध सामग्री",ko:"불법 콘텐츠",tr:"Yasadışı içerik",pl:"Nielegalna treść",sv:"Olagligt innehåll",id:"Konten ilegal",th:"เนื้อหาผิดกฎหมาย"},
"report.reasons.other":{en:"Other",pt:"Outro",fr:"Autre",de:"Sonstiges",it:"Altro",nl:"Anders",ja:"その他",zh:"其他",ru:"Другое",ar:"أخرى",hi:"अन्य",ko:"기타",tr:"Diğer",pl:"Inne",sv:"Övrigt",id:"Lainnya",th:"อื่นๆ"},
"report.spam":{en:"Spam",pt:"Spam",fr:"Spam",de:"Spam",it:"Spam",nl:"Spam",ja:"スパム",zh:"垃圾信息",ru:"Спам",ar:"رسائل مزعجة",hi:"स्पैम",ko:"스팸",tr:"Spam",pl:"Spam",sv:"Spam",id:"Spam",th:"สแปม"},
"report.reportPost":{en:"Report post",pt:"Reportar publicação",fr:"Signaler la publication",de:"Beitrag melden",it:"Segnala post",nl:"Bericht rapporteren",ja:"投稿を報告",zh:"举报帖子",ru:"Пожаловаться на пост",ar:"الإبلاغ عن المنشور",hi:"पोस्ट की रिपोर्ट",ko:"게시물 신고",tr:"Gönderiyi bildir",pl:"Zgłoś post",sv:"Rapportera inlägg",id:"Laporkan postingan",th:"รายงานโพสต์"},
"report.reportThread":{en:"Report thread",pt:"Reportar tópico",fr:"Signaler le sujet",de:"Thema melden",it:"Segnala discussione",nl:"Onderwerp rapporteren",ja:"スレッドを報告",zh:"举报主题",ru:"Пожаловаться на тему",ar:"الإبلاغ عن الموضوع",hi:"थ्रेड की रिपोर्ट",ko:"스레드 신고",tr:"Konuyu bildir",pl:"Zgłoś wątek",sv:"Rapportera tråd",id:"Laporkan thread",th:"รายงานกระทู้"},
"report.reportUser":{en:"Report user",pt:"Reportar usuário",fr:"Signaler l'utilisateur",de:"Benutzer melden",it:"Segnala utente",nl:"Gebruiker rapporteren",ja:"ユーザーを報告",zh:"举报用户",ru:"Пожаловаться на пользователя",ar:"الإبلاغ عن المستخدم",hi:"उपयोगकर्ता की रिपोर्ट",ko:"사용자 신고",tr:"Kullanıcıyı bildir",pl:"Zgłoś użytkownika",sv:"Rapportera användare",id:"Laporkan pengguna",th:"รายงานผู้ใช้"},
"report.reportMessage":{en:"Report message",pt:"Reportar mensagem",fr:"Signaler le message",de:"Nachricht melden",it:"Segnala messaggio",nl:"Bericht rapporteren",ja:"メッセージを報告",zh:"举报消息",ru:"Пожаловаться на сообщение",ar:"الإبلاغ عن الرسالة",hi:"संदेश की रिपोर्ट",ko:"메시지 신고",tr:"Mesajı bildir",pl:"Zgłoś wiadomość",sv:"Rapportera meddelande",id:"Laporkan pesan",th:"รายงานข้อความ"},
"report.reasonLabel":{en:"Report reason *",pt:"Motivo do reporte *",fr:"Motif du signalement *",de:"Meldegrund *",it:"Motivo della segnalazione *",nl:"Reden van rapport *",ja:"報告理由 *",zh:"举报原因 *",ru:"Причина жалобы *",ar:"سبب البلاغ *",hi:"रिपोर्ट का कारण *",ko:"신고 사유 *",tr:"Bildirim nedeni *",pl:"Powód zgłoszenia *",sv:"Rapportorsak *",id:"Alasan laporan *",th:"เหตุผลในการรายงาน *"},
"report.additionalDetails":{en:"Additional details (optional)",pt:"Detalhes adicionais (opcional)",fr:"Détails supplémentaires (optionnel)",de:"Zusätzliche Details (optional)",it:"Dettagli aggiuntivi (opzionale)",nl:"Extra details (optioneel)",ja:"追加の詳細（任意）",zh:"补充说明（可选）",ru:"Дополнительные детали (необязательно)",ar:"تفاصيل إضافية (اختيارية)",hi:"अतिरिक्त विवरण (वैकल्पिक)",ko:"추가 세부 사항 (선택)",tr:"Ek ayrıntılar (isteğe bağlı)",pl:"Dodatkowe szczegóły (opcjonalne)",sv:"Ytterligare detaljer (valfritt)",id:"Detail tambahan (opsional)",th:"รายละเอียดเพิ่มเติม (ไม่บังคับ)"},
"report.additionalDetailsPlaceholder":{en:"Provide more details about the issue...",pt:"Forneça mais detalhes sobre o problema...",fr:"Fournissez plus de détails sur le problème...",de:"Weitere Details zum Problem angeben...",it:"Fornisci più dettagli sul problema...",nl:"Geef meer details over het probleem...",ja:"問題の詳細を記入...",zh:"提供更多问题详情...",ru:"Предоставьте больше деталей о проблеме...",ar:"قدم المزيد من التفاصيل حول المشكلة...",hi:"समस्या के बारे में अधिक विवरण दें...",ko:"문제에 대한 자세한 내용을 입력하세요...",tr:"Sorun hakkında daha fazla ayrıntı verin...",pl:"Podaj więcej szczegółów o problemie...",sv:"Ange mer detaljer om problemet...",id:"Berikan detail lebih lanjut tentang masalah...",th:"ให้รายละเอียดเพิ่มเติมเกี่ยวกับปัญหา..."},
"report.fakeAccount":{en:"Fake account or impersonation",pt:"Conta falsa ou falsificação de identidade",fr:"Faux compte ou usurpation d'identité",de:"Falsches Konto oder Identitätsdiebstahl",it:"Account falso o impersonificazione",nl:"Nep account of nabootsing",ja:"偽アカウントまたはなりすまし",zh:"虚假账户或冒充",ru:"Поддельный аккаунт или выдача себя за другого",ar:"حساب مزيف أو انتحال شخصية",hi:"नकली खाता या प्रतिरूपण",ko:"가짜 계정 또는 사칭",tr:"Sahte hesap veya taklit",pl:"Fałszywe konto lub podszywanie się",sv:"Falskt konto eller imitation",id:"Akun palsu atau peniruan",th:"บัญชีปลอมหรือการแอบอ้าง"},
"report.scam":{en:"Scam or fraud",pt:"Golpe ou fraude",fr:"Arnaque ou fraude",de:"Betrug oder Schwindel",it:"Truffa o frode",nl:"Oplichting of fraude",ja:"詐欺または不正",zh:"诈骗或欺诈",ru:"Мошенничество или обман",ar:"احتيال أو نصب",hi:"घोटाला या धोखाधड़ी",ko:"사기 또는 사기행위",tr:"Dolandırıcılık veya sahtecilik",pl:"Oszustwo lub wyłudzenie",sv:"Bedrägeri eller svindel",id:"Penipuan atau kecurangan",th:"การหลอกลวงหรือฉ้อโกง"},
"report.loginRequired":{en:"Sign in to report",pt:"Entre para reportar",fr:"Connectez-vous pour signaler",de:"Anmelden zum Melden",it:"Accedi per segnalare",nl:"Log in om te rapporteren",ja:"報告するにはログイン",zh:"登录以举报",ru:"Войдите для жалобы",ar:"سجل دخولك للإبلاغ",hi:"रिपोर्ट के लिए लॉगिन",ko:"신고하려면 로그인",tr:"Bildirmek için giriş yapın",pl:"Zaloguj się aby zgłosić",sv:"Logga in för att rapportera",id:"Masuk untuk melaporkan",th:"เข้าสู่ระบบเพื่อรายงาน"},
"report.selectReasonFirst":{en:"Select a reason",pt:"Selecione um motivo",fr:"Sélectionnez un motif",de:"Wählen Sie einen Grund",it:"Seleziona un motivo",nl:"Selecteer een reden",ja:"理由を選択",zh:"选择原因",ru:"Выберите причину",ar:"اختر سبباً",hi:"कारण चुनें",ko:"사유 선택",tr:"Bir neden seçin",pl:"Wybierz powód",sv:"Välj en anledning",id:"Pilih alasan",th:"เลือกเหตุผล"},
"report.helpText":{en:"Help us keep the community safe. Select the reason for the report.",pt:"Ajude-nos a manter a comunidade segura. Selecione o motivo do reporte.",fr:"Aidez-nous à maintenir la communauté sûre. Sélectionnez le motif.",de:"Helfen Sie uns, die Community sicher zu halten. Wählen Sie den Grund.",it:"Aiutaci a mantenere la comunità sicura. Seleziona il motivo.",nl:"Help ons de community veilig te houden. Selecteer de reden.",ja:"コミュニティの安全を守るためにご協力ください。報告理由を選択してください。",zh:"帮助我们维护社区安全。选择举报原因。",ru:"Помогите нам сохранить безопасность сообщества. Выберите причину.",ar:"ساعدنا في الحفاظ على أمان المجتمع. اختر سبب البلاغ.",hi:"समुदाय को सुरक्षित रखने में मदद करें। रिपोर्ट का कारण चुनें.",ko:"커뮤니티 안전을 위해 도움을 주세요. 신고 사유를 선택하세요.",tr:"Topluluğu güvende tutmamıza yardımcı olun. Bildirim nedenini seçin.",pl:"Pomóż nam utrzymać bezpieczeństwo społeczności. Wybierz powód.",sv:"Hjälp oss att hålla gemenskapen säker. Välj anledning.",id:"Bantu kami menjaga keamanan komunitas. Pilih alasan laporan.",th:"ช่วยเรารักษาความปลอดภัยของชุมชน เลือกเหตุผลในการรายงาน"},
"report.reportSent":{en:"Report sent",pt:"Reporte enviado",fr:"Signalement envoyé",de:"Bericht gesendet",it:"Segnalazione inviata",nl:"Rapport verzonden",ja:"報告送信済み",zh:"举报已发送",ru:"Жалоба отправлена",ar:"تم إرسال البلاغ",hi:"रिपोर्ट भेजी गई",ko:"신고 전송됨",tr:"Rapor gönderildi",pl:"Zgłoszenie wysłane",sv:"Rapport skickad",id:"Laporan terkirim",th:"ส่งรายงานแล้ว"},
"report.reportSentDesc":{en:"Our team will review your report soon",pt:"Nossa equipe revisará seu reporte em breve",fr:"Notre équipe examinera votre signalement",de:"Unser Team wird Ihren Bericht prüfen",it:"Il nostro team esaminerà la segnalazione",nl:"Ons team beoordeelt je rapport",ja:"チームが報告を確認します",zh:"我们的团队将尽快审核您的举报",ru:"Наша команда рассмотрит вашу жалобу",ar:"سيراجع فريقنا بلاغك قريباً",hi:"हमारी टीम जल्द आपकी रिपोर्ट की समीक्षा करेगी",ko:"팀이 곧 신고를 검토합니다",tr:"Ekibimiz raporunuzu inceleyecek",pl:"Nasz zespół wkrótce sprawdzi zgłoszenie",sv:"Vårt team granskar din rapport",id:"Tim kami akan segera meninjau laporan Anda",th:"ทีมของเราจะตรวจสอบรายงานของคุณเร็วๆ นี้"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Batch 4c done!');
