const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === ADMIN (46) ===
"admin.title":{en:"Administration Panel",pt:"Painel de Administração",fr:"Panneau d'Administration",de:"Administrationspanel",it:"Pannello di Amministrazione",nl:"Beheerpaneel",ja:"管理パネル",zh:"管理面板",ru:"Панель администрирования",ar:"لوحة الإدارة",hi:"प्रशासन पैनल",ko:"관리 패널",tr:"Yönetim Paneli",pl:"Panel Administracyjny",sv:"Administrationspanel",id:"Panel Administrasi",th:"แผงควบคุมการจัดการ"},
"admin.description":{en:"Forum management and moderation",pt:"Gestão e moderação do fórum",fr:"Gestion et modération du forum",de:"Forumverwaltung und Moderation",it:"Gestione e moderazione del forum",nl:"Forumbeheer en moderatie",ja:"フォーラムの管理とモデレーション",zh:"论坛管理和审核",ru:"Управление и модерация форума",ar:"إدارة وإشراف المنتدى",hi:"फ़ोरम प्रबंधन और मॉडरेशन",ko:"포럼 관리 및 중재",tr:"Forum yönetimi ve moderasyon",pl:"Zarządzanie i moderacja forum",sv:"Forumhantering och moderering",id:"Manajemen dan moderasi forum",th:"การจัดการและดูแลฟอรั่ม"},
"admin.totalUsers":{en:"Total Users",pt:"Total de Usuárias",fr:"Total Utilisatrices",de:"Gesamte Benutzer",it:"Totale Utenti",nl:"Totaal Gebruikers",ja:"総ユーザー数",zh:"总用户数",ru:"Всего пользователей",ar:"إجمالي المستخدمين",hi:"कुल उपयोगकर्ता",ko:"총 사용자",tr:"Toplam Kullanıcı",pl:"Łączna Liczba Użytkowników",sv:"Totalt Antal Användare",id:"Total Pengguna",th:"ผู้ใช้ทั้งหมด"},
"admin.pendingReports":{en:"Pending Reports",pt:"Reportes Pendentes",fr:"Signalements en Attente",de:"Ausstehende Meldungen",it:"Segnalazioni in Attesa",nl:"Wachtende Rapporten",ja:"保留中の報告",zh:"待处理举报",ru:"Ожидающие жалобы",ar:"البلاغات المعلقة",hi:"लंबित रिपोर्ट",ko:"대기 중인 신고",tr:"Bekleyen Raporlar",pl:"Oczekujące Zgłoszenia",sv:"Väntande Rapporter",id:"Laporan Tertunda",th:"รายงานที่รอดำเนินการ"},
"admin.pendingVerifications":{en:"Pending Verifications",pt:"Verificações Pendentes",fr:"Vérifications en Attente",de:"Ausstehende Verifizierungen",it:"Verifiche in Attesa",nl:"Wachtende Verificaties",ja:"保留中の検証",zh:"待处理验证",ru:"Ожидающие верификации",ar:"التحققات المعلقة",hi:"लंबित सत्यापन",ko:"대기 중인 인증",tr:"Bekleyen Doğrulamalar",pl:"Oczekujące Weryfikacje",sv:"Väntande Verifieringar",id:"Verifikasi Tertunda",th:"การยืนยันที่รอดำเนินการ"},
"admin.verifications":{en:"Verifications",pt:"Verificações",fr:"Vérifications",de:"Verifizierungen",it:"Verifiche",nl:"Verificaties",ja:"検証",zh:"验证",ru:"Верификации",ar:"التحققات",hi:"सत्यापन",ko:"인증",tr:"Doğrulamalar",pl:"Weryfikacje",sv:"Verifieringar",id:"Verifikasi",th:"การยืนยัน"},
"admin.reports":{en:"Reports",pt:"Reportes",fr:"Signalements",de:"Meldungen",it:"Segnalazioni",nl:"Rapporten",ja:"報告",zh:"举报",ru:"Жалобы",ar:"البلاغات",hi:"रिपोर्ट",ko:"신고",tr:"Raporlar",pl:"Zgłoszenia",sv:"Rapporter",id:"Laporan",th:"รายงาน"},
"admin.stats":{en:"Statistics",pt:"Estatísticas",fr:"Statistiques",de:"Statistiken",it:"Statistiche",nl:"Statistieken",ja:"統計",zh:"统计",ru:"Статистика",ar:"الإحصائيات",hi:"सांख्यिकी",ko:"통계",tr:"İstatistikler",pl:"Statystyki",sv:"Statistik",id:"Statistik",th:"สถิติ"},
"admin.approve":{en:"Approve",pt:"Aprovar",fr:"Approuver",de:"Genehmigen",it:"Approva",nl:"Goedkeuren",ja:"承認",zh:"批准",ru:"Одобрить",ar:"موافقة",hi:"स्वीकृत करें",ko:"승인",tr:"Onayla",pl:"Zatwierdź",sv:"Godkänn",id:"Setujui",th:"อนุมัติ"},
"admin.reject":{en:"Reject",pt:"Rejeitar",fr:"Rejeter",de:"Ablehnen",it:"Rifiuta",nl:"Afwijzen",ja:"却下",zh:"拒绝",ru:"Отклонить",ar:"رفض",hi:"अस्वीकार करें",ko:"거부",tr:"Reddet",pl:"Odrzuć",sv:"Avvisa",id:"Tolak",th:"ปฏิเสธ"},
"admin.resolve":{en:"Resolve",pt:"Resolver",fr:"Résoudre",de:"Erledigen",it:"Risolvere",nl:"Oplossen",ja:"解決",zh:"解决",ru:"Решить",ar:"حل",hi:"हल करें",ko:"해결",tr:"Çöz",pl:"Rozwiąż",sv:"Lös",id:"Selesaikan",th:"แก้ไข"},
"admin.noPendingVerifications":{en:"No pending requests",pt:"Sem solicitações pendentes",fr:"Aucune demande en attente",de:"Keine ausstehenden Anfragen",it:"Nessuna richiesta in attesa",nl:"Geen wachtende verzoeken",ja:"保留中のリクエストなし",zh:"没有待处理的请求",ru:"Нет ожидающих запросов",ar:"لا توجد طلبات معلقة",hi:"कोई लंबित अनुरोध नहीं",ko:"대기 중인 요청 없음",tr:"Bekleyen istek yok",pl:"Brak oczekujących wniosków",sv:"Inga väntande förfrågningar",id:"Tidak ada permintaan tertunda",th:"ไม่มีคำขอที่รอดำเนินการ"},
"admin.noPendingReports":{en:"No pending reports",pt:"Sem reportes pendentes",fr:"Aucun signalement en attente",de:"Keine ausstehenden Meldungen",it:"Nessuna segnalazione in attesa",nl:"Geen wachtende rapporten",ja:"保留中の報告なし",zh:"没有待处理的举报",ru:"Нет ожидающих жалоб",ar:"لا توجد بلاغات معلقة",hi:"कोई लंबित रिपोर्ट नहीं",ko:"대기 중인 신고 없음",tr:"Bekleyen rapor yok",pl:"Brak oczekujących zgłoszeń",sv:"Inga väntande rapporter",id:"Tidak ada laporan tertunda",th:"ไม่มีรายงานที่รอดำเนินการ"},
"admin.approveSuccess":{en:"Verification approved",pt:"Verificação aprovada",fr:"Vérification approuvée",de:"Verifizierung genehmigt",it:"Verifica approvata",nl:"Verificatie goedgekeurd",ja:"検証が承認されました",zh:"验证已批准",ru:"Верификация одобрена",ar:"تم الموافقة على التحقق",hi:"सत्यापन स्वीकृत",ko:"인증 승인됨",tr:"Doğrulama onaylandı",pl:"Weryfikacja zatwierdzona",sv:"Verifiering godkänd",id:"Verifikasi disetujui",th:"อนุมัติการยืนยันแล้ว"},
"admin.resolveSuccess":{en:"Report resolved",pt:"Reporte resolvido",fr:"Signalement résolu",de:"Meldung erledigt",it:"Segnalazione risolta",nl:"Rapport opgelost",ja:"報告が解決しました",zh:"举报已解决",ru:"Жалоба решена",ar:"تم حل البلاغ",hi:"रिपोर्ट हल की गई",ko:"신고 해결됨",tr:"Rapor çözüldü",pl:"Zgłoszenie rozwiązane",sv:"Rapport löst",id:"Laporan diselesaikan",th:"แก้ไขรายงานแล้ว"},
"admin.noPermission":{en:"You don't have permission to access the administration panel",pt:"Você não tem permissão para acessar o painel de administração",fr:"Vous n'avez pas la permission d'accéder au panneau d'administration",de:"Sie haben keine Berechtigung für das Administrationspanel",it:"Non hai il permesso di accedere al pannello di amministrazione",nl:"Je hebt geen toestemming voor het beheerpaneel",ja:"管理パネルへのアクセス権限がありません",zh:"您没有权限访问管理面板",ru:"У вас нет прав доступа к панели администрирования",ar:"ليس لديك صلاحية الوصول إلى لوحة الإدارة",hi:"आपको प्रशासन पैनल तक पहुंचने की अनुमति नहीं है",ko:"관리 패널에 접근할 권한이 없습니다",tr:"Yönetim paneline erişim izniniz yok",pl:"Nie masz uprawnień do panelu administracyjnego",sv:"Du har inte behörighet till administrationspanelen",id:"Anda tidak memiliki izin untuk mengakses panel administrasi",th:"คุณไม่มีสิทธิ์เข้าถึงแผงควบคุมการจัดการ"},
"admin.errorApprovingVerification":{en:"Error approving verification",pt:"Erro ao aprovar verificação",fr:"Erreur d'approbation de la vérification",de:"Fehler bei der Genehmigung der Verifizierung",it:"Errore nell'approvazione della verifica",nl:"Fout bij goedkeuren verificatie",ja:"検証の承認エラー",zh:"批准验证出错",ru:"Ошибка одобрения верификации",ar:"خطأ في الموافقة على التحقق",hi:"सत्यापन स्वीकृति में त्रुटि",ko:"인증 승인 오류",tr:"Doğrulama onaylama hatası",pl:"Błąd zatwierdzania weryfikacji",sv:"Fel vid godkännande av verifiering",id:"Error menyetujui verifikasi",th:"เกิดข้อผิดพลาดในการอนุมัติการยืนยัน"},
"admin.errorUpdatingProfile":{en:"Error updating profile",pt:"Erro ao atualizar perfil",fr:"Erreur de mise à jour du profil",de:"Fehler beim Aktualisieren des Profils",it:"Errore nell'aggiornamento del profilo",nl:"Fout bij bijwerken profiel",ja:"プロフィール更新エラー",zh:"更新个人资料出错",ru:"Ошибка обновления профиля",ar:"خطأ في تحديث الملف الشخصي",hi:"प्रोफ़ाइल अपडेट में त्रुटि",ko:"프로필 업데이트 오류",tr:"Profil güncelleme hatası",pl:"Błąd aktualizacji profilu",sv:"Fel vid uppdatering av profil",id:"Error memperbarui profil",th:"เกิดข้อผิดพลาดในการอัปเดตโปรไฟล์"},
"admin.errorRejectingVerification":{en:"Error rejecting verification",pt:"Erro ao rejeitar verificação",fr:"Erreur de rejet de la vérification",de:"Fehler beim Ablehnen der Verifizierung",it:"Errore nel rifiuto della verifica",nl:"Fout bij afwijzen verificatie",ja:"検証の却下エラー",zh:"拒绝验证出错",ru:"Ошибка отклонения верификации",ar:"خطأ في رفض التحقق",hi:"सत्यापन अस्वीकृति में त्रुटि",ko:"인증 거부 오류",tr:"Doğrulama reddetme hatası",pl:"Błąd odrzucania weryfikacji",sv:"Fel vid avvisande av verifiering",id:"Error menolak verifikasi",th:"เกิดข้อผิดพลาดในการปฏิเสธการยืนยัน"},
"admin.errorResolvingReport":{en:"Error resolving report",pt:"Erro ao resolver reporte",fr:"Erreur de résolution du signalement",de:"Fehler beim Erledigen der Meldung",it:"Errore nella risoluzione della segnalazione",nl:"Fout bij oplossen rapport",ja:"報告の解決エラー",zh:"解决举报出错",ru:"Ошибка решения жалобы",ar:"خطأ في حل البلاغ",hi:"रिपोर्ट समाधान में त्रुटि",ko:"신고 해결 오류",tr:"Rapor çözme hatası",pl:"Błąd rozwiązywania zgłoszenia",sv:"Fel vid lösning av rapport",id:"Error menyelesaikan laporan",th:"เกิดข้อผิดพลาดในการแก้ไขรายงาน"},
"admin.userManagement":{en:"User Management",pt:"Gestão de Usuários",fr:"Gestion des Utilisateurs",de:"Benutzerverwaltung",it:"Gestione Utenti",nl:"Gebruikersbeheer",ja:"ユーザー管理",zh:"用户管理",ru:"Управление пользователями",ar:"إدارة المستخدمين",hi:"उपयोगकर्ता प्रबंधन",ko:"사용자 관리",tr:"Kullanıcı Yönetimi",pl:"Zarządzanie Użytkownikami",sv:"Användarhantering",id:"Manajemen Pengguna",th:"การจัดการผู้ใช้"},
"admin.userManagementDesc":{en:"Manage users, roles, suspensions and IPs",pt:"Administrar usuários, funções, suspensões e IPs",fr:"Gérer les utilisateurs, rôles, suspensions et IPs",de:"Benutzer, Rollen, Sperrungen und IPs verwalten",it:"Gestisci utenti, ruoli, sospensioni e IP",nl:"Beheer gebruikers, rollen, schorsingen en IP's",ja:"ユーザー、ロール、停止、IPを管理",zh:"管理用户、角色、暂停和IP",ru:"Управление пользователями, ролями, блокировками и IP",ar:"إدارة المستخدمين والأدوار والإيقافات وعناوين IP",hi:"उपयोगकर्ता, भूमिकाएं, निलंबन और IP प्रबंधित करें",ko:"사용자, 역할, 정지 및 IP 관리",tr:"Kullanıcıları, rolleri, askıya almaları ve IP'leri yönetin",pl:"Zarządzaj użytkownikami, rolami, zawieszeniami i IP",sv:"Hantera användare, roller, avstängningar och IP",id:"Kelola pengguna, peran, penangguhan, dan IP",th:"จัดการผู้ใช้ บทบาท การระงับ และ IP"},
"admin.geoForumManagement":{en:"Geographic Forum Management",pt:"Gestão de Fóruns Geográficos",fr:"Gestion des Forums Géographiques",de:"Verwaltung geographischer Foren",it:"Gestione Forum Geografici",nl:"Beheer Geografische Forums",ja:"地理フォーラム管理",zh:"地理论坛管理",ru:"Управление географическими форумами",ar:"إدارة المنتديات الجغرافية",hi:"भौगोलिक फ़ोरम प्रबंधन",ko:"지역 포럼 관리",tr:"Coğrafi Forum Yönetimi",pl:"Zarządzanie Forami Geograficznymi",sv:"Hantering av Geografiska Forum",id:"Manajemen Forum Geografis",th:"การจัดการฟอรั่มทางภูมิศาสตร์"},
"admin.geoForumManagementDesc":{en:"Manage countries, cities and subforums",pt:"Administrar países, cidades e subfóruns",fr:"Gérer les pays, villes et sous-forums",de:"Länder, Städte und Unterforen verwalten",it:"Gestisci paesi, città e sottoforum",nl:"Beheer landen, steden en subforums",ja:"国、都市、サブフォーラムを管理",zh:"管理国家、城市和子论坛",ru:"Управление странами, городами и подфорумами",ar:"إدارة البلدان والمدن والمنتديات الفرعية",hi:"देश, शहर और उप-फ़ोरम प्रबंधित करें",ko:"국가, 도시 및 하위 포럼 관리",tr:"Ülkeleri, şehirleri ve alt forumları yönetin",pl:"Zarządzaj krajami, miastami i podforami",sv:"Hantera länder, städer och underforum",id:"Kelola negara, kota, dan subforum",th:"จัดการประเทศ เมือง และฟอรั่มย่อย"},
"admin.moderationHistory":{en:"Moderation History",pt:"Histórico de Moderação",fr:"Historique de Modération",de:"Moderationshistorie",it:"Cronologia Moderazione",nl:"Moderatiegeschiedenis",ja:"モデレーション履歴",zh:"审核历史",ru:"История модерации",ar:"سجل الإشراف",hi:"मॉडरेशन इतिहास",ko:"중재 내역",tr:"Moderasyon Geçmişi",pl:"Historia Moderacji",sv:"Modereringshistorik",id:"Riwayat Moderasi",th:"ประวัติการดูแล"},
"admin.moderationHistoryDesc":{en:"View moderation actions taken",pt:"Ver ações de moderação realizadas",fr:"Voir les actions de modération effectuées",de:"Durchgeführte Moderationsaktionen anzeigen",it:"Visualizza le azioni di moderazione",nl:"Bekijk uitgevoerde moderatieacties",ja:"実行されたモデレーションアクションを表示",zh:"查看已执行的审核操作",ru:"Просмотр выполненных действий модерации",ar:"عرض إجراءات الإشراف المتخذة",hi:"किए गए मॉडरेशन कार्यों को देखें",ko:"수행된 중재 작업 보기",tr:"Yapılan moderasyon eylemlerini görüntüle",pl:"Zobacz podjęte działania moderacyjne",sv:"Visa vidtagna modereringsåtgärder",id:"Lihat tindakan moderasi yang diambil",th:"ดูการดำเนินการดูแลที่ทำ"},
"admin.warningSystem":{en:"Warning System",pt:"Sistema de Advertências",fr:"Système d'Avertissements",de:"Verwarnungssystem",it:"Sistema di Avvertimenti",nl:"Waarschuwingssysteem",ja:"警告システム",zh:"警告系统",ru:"Система предупреждений",ar:"نظام التحذيرات",hi:"चेतावनी प्रणाली",ko:"경고 시스템",tr:"Uyarı Sistemi",pl:"System Ostrzeżeń",sv:"Varningssystem",id:"Sistem Peringatan",th:"ระบบเตือน"},
"admin.warningSystemDesc":{en:"Manage warnings and user points",pt:"Gestionar advertências e pontos de usuários",fr:"Gérer les avertissements et les points des utilisateurs",de:"Verwarnungen und Benutzerpunkte verwalten",it:"Gestisci avvertimenti e punti utente",nl:"Beheer waarschuwingen en gebruikerspunten",ja:"警告とユーザーポイントを管理",zh:"管理警告和用户积分",ru:"Управление предупреждениями и очками пользователей",ar:"إدارة التحذيرات ونقاط المستخدمين",hi:"चेतावनियां और उपयोगकर्ता अंक प्रबंधित करें",ko:"경고 및 사용자 포인트 관리",tr:"Uyarıları ve kullanıcı puanlarını yönetin",pl:"Zarządzaj ostrzeżeniami i punktami użytkowników",sv:"Hantera varningar och användarpunkter",id:"Kelola peringatan dan poin pengguna",th:"จัดการคำเตือนและคะแนนผู้ใช้"},
"admin.contentFilters":{en:"Content Filters",pt:"Filtros de Conteúdo",fr:"Filtres de Contenu",de:"Inhaltsfilter",it:"Filtri di Contenuto",nl:"Inhoudsfilters",ja:"コンテンツフィルター",zh:"内容过滤器",ru:"Фильтры контента",ar:"فلاتر المحتوى",hi:"सामग्री फ़िल्टर",ko:"콘텐츠 필터",tr:"İçerik Filtreleri",pl:"Filtry Treści",sv:"Innehållsfilter",id:"Filter Konten",th:"ตัวกรองเนื้อหา"},
"admin.contentFiltersDesc":{en:"Block prohibited words and URLs",pt:"Bloquear palavras e URLs proibidas",fr:"Bloquer les mots et URLs interdits",de:"Verbotene Wörter und URLs blockieren",it:"Blocca parole e URL proibite",nl:"Verboden woorden en URLs blokkeren",ja:"禁止ワードとURLをブロック",zh:"屏蔽违禁词和URL",ru:"Блокировка запрещённых слов и URL",ar:"حظر الكلمات والروابط المحظورة",hi:"प्रतिबंधित शब्द और URL ब्लॉक करें",ko:"금지된 단어와 URL 차단",tr:"Yasaklı kelimeleri ve URL'leri engelle",pl:"Blokuj zabronione słowa i adresy URL",sv:"Blockera förbjudna ord och URL:er",id:"Blokir kata dan URL yang dilarang",th:"บล็อกคำและ URL ต้องห้าม"},
"admin.reportCenter":{en:"Report Center",pt:"Central de Reportes",fr:"Centre de Signalements",de:"Meldezentrale",it:"Centro Segnalazioni",nl:"Rapportcentrum",ja:"報告センター",zh:"举报中心",ru:"Центр жалоб",ar:"مركز البلاغات",hi:"रिपोर्ट केंद्र",ko:"신고 센터",tr:"Rapor Merkezi",pl:"Centrum Zgłoszeń",sv:"Rapportcenter",id:"Pusat Laporan",th:"ศูนย์รายงาน"},
"admin.reportCenterDesc":{en:"View and manage user reports",pt:"Ver e gerir reportes de usuários",fr:"Voir et gérer les signalements des utilisateurs",de:"Benutzermeldungen anzeigen und verwalten",it:"Visualizza e gestisci le segnalazioni degli utenti",nl:"Bekijk en beheer gebruikersrapporten",ja:"ユーザー報告の表示と管理",zh:"查看和管理用户举报",ru:"Просмотр и управление жалобами пользователей",ar:"عرض وإدارة بلاغات المستخدمين",hi:"उपयोगकर्ता रिपोर्ट देखें और प्रबंधित करें",ko:"사용자 신고 보기 및 관리",tr:"Kullanıcı raporlarını görüntüle ve yönet",pl:"Przeglądaj i zarządzaj zgłoszeniami użytkowników",sv:"Visa och hantera användarrapporter",id:"Lihat dan kelola laporan pengguna",th:"ดูและจัดการรายงานผู้ใช้"},
"admin.suspensions":{en:"Suspensions",pt:"Suspensões",fr:"Suspensions",de:"Sperrungen",it:"Sospensioni",nl:"Schorsingen",ja:"停止措置",zh:"暂停",ru:"Блокировки",ar:"الإيقافات",hi:"निलंबन",ko:"정지",tr:"Askıya Almalar",pl:"Zawieszenia",sv:"Avstängningar",id:"Penangguhan",th:"การระงับ"},
"admin.suspensionsDesc":{en:"Manage suspensions and bans",pt:"Gerir suspensões e banimentos",fr:"Gérer les suspensions et bannissements",de:"Sperrungen und Banns verwalten",it:"Gestisci sospensioni ed espulsioni",nl:"Beheer schorsingen en verbanningen",ja:"停止措置とBANを管理",zh:"管理暂停和封禁",ru:"Управление блокировками и банами",ar:"إدارة الإيقافات والحظر",hi:"निलंबन और प्रतिबंध प्रबंधित करें",ko:"정지 및 차단 관리",tr:"Askıya almaları ve yasaklamaları yönet",pl:"Zarządzaj zawieszeniami i banami",sv:"Hantera avstängningar och bannlysningar",id:"Kelola penangguhan dan pemblokiran",th:"จัดการการระงับและการแบน"},
"admin.badges":{en:"Badges",pt:"Insígnias",fr:"Badges",de:"Badges",it:"Badge",nl:"Badges",ja:"バッジ",zh:"徽章",ru:"Значки",ar:"الشارات",hi:"बैज",ko:"배지",tr:"Rozetler",pl:"Odznaki",sv:"Märken",id:"Lencana",th:"ตรา"},
"admin.badgesDesc":{en:"Manage custom badges and escorts",pt:"Gerir insígnias personalizadas e escorts",fr:"Gérer les badges personnalisés et escorts",de:"Benutzerdefinierte Badges und Escorts verwalten",it:"Gestisci badge personalizzati ed escorts",nl:"Beheer aangepaste badges en escorts",ja:"カスタムバッジとエスコートを管理",zh:"管理自定义徽章和护送",ru:"Управление пользовательскими значками и эскортами",ar:"إدارة الشارات المخصصة والمرافقات",hi:"कस्टम बैज और एस्कॉर्ट प्रबंधित करें",ko:"맞춤 배지 및 에스코트 관리",tr:"Özel rozetleri ve eskortları yönet",pl:"Zarządzaj niestandardowymi odznakami i eskortami",sv:"Hantera anpassade märken och eskorter",id:"Kelola lencana kustom dan eskort",th:"จัดการตราที่กำหนดเองและเอสคอร์ต"},
"admin.verificationRequests":{en:"Verification Requests",pt:"Solicitações de Verificação",fr:"Demandes de Vérification",de:"Verifizierungsanfragen",it:"Richieste di Verifica",nl:"Verificatieverzoeken",ja:"検証リクエスト",zh:"验证请求",ru:"Запросы на верификацию",ar:"طلبات التحقق",hi:"सत्यापन अनुरोध",ko:"인증 요청",tr:"Doğrulama Talepleri",pl:"Wnioski o Weryfikację",sv:"Verifieringsförfrågningar",id:"Permintaan Verifikasi",th:"คำขอยืนยัน"},
"admin.verificationRequestsDesc":{en:"Review and approve verification requests",pt:"Revise e aprove solicitações de verificação",fr:"Examinez et approuvez les demandes de vérification",de:"Verifizierungsanfragen überprüfen und genehmigen",it:"Rivedi e approva le richieste di verifica",nl:"Beoordeel en keur verificatieverzoeken goed",ja:"検証リクエストを確認して承認",zh:"审核并批准验证请求",ru:"Проверяйте и одобряйте запросы на верификацию",ar:"راجع ووافق على طلبات التحقق",hi:"सत्यापन अनुरोधों की समीक्षा और स्वीकृति करें",ko:"인증 요청 검토 및 승인",tr:"Doğrulama taleplerini inceleyin ve onaylayın",pl:"Przeglądaj i zatwierdzaj wnioski o weryfikację",sv:"Granska och godkänn verifieringsförfrågningar",id:"Tinjau dan setujui permintaan verifikasi",th:"ตรวจสอบและอนุมัติคำขอยืนยัน"},
"admin.submitted":{en:"Submitted",pt:"Enviada",fr:"Soumise",de:"Eingereicht",it:"Inviata",nl:"Ingediend",ja:"送信済み",zh:"已提交",ru:"Отправлено",ar:"مرسلة",hi:"सबमिट किया गया",ko:"제출됨",tr:"Gönderildi",pl:"Wysłane",sv:"Inskickad",id:"Dikirim",th:"ส่งแล้ว"},
"admin.viewPhoto":{en:"View photo",pt:"Ver foto",fr:"Voir la photo",de:"Foto ansehen",it:"Vedi foto",nl:"Foto bekijken",ja:"写真を表示",zh:"查看照片",ru:"Просмотреть фото",ar:"عرض الصورة",hi:"फ़ोटो देखें",ko:"사진 보기",tr:"Fotoğrafı gör",pl:"Zobacz zdjęcie",sv:"Visa foto",id:"Lihat foto",th:"ดูรูปภาพ"},
"admin.reviewCommunityReports":{en:"Review community reports",pt:"Revise reportes da comunidade",fr:"Examinez les signalements de la communauté",de:"Community-Meldungen überprüfen",it:"Rivedi le segnalazioni della comunità",nl:"Beoordeel gemeenschapsrapporten",ja:"コミュニティの報告を確認",zh:"审核社区举报",ru:"Проверяйте жалобы сообщества",ar:"راجع بلاغات المجتمع",hi:"समुदाय रिपोर्ट की समीक्षा करें",ko:"커뮤니티 신고 검토",tr:"Topluluk raporlarını incele",pl:"Przeglądaj zgłoszenia społeczności",sv:"Granska communityrapporter",id:"Tinjau laporan komunitas",th:"ตรวจสอบรายงานของชุมชน"},
"admin.reportNum":{en:"Report",pt:"Reporte",fr:"Signalement",de:"Meldung",it:"Segnalazione",nl:"Rapport",ja:"報告",zh:"举报",ru:"Жалоба",ar:"بلاغ",hi:"रिपोर्ट",ko:"신고",tr:"Rapor",pl:"Zgłoszenie",sv:"Rapport",id:"Laporan",th:"รายงาน"},
"admin.reportedBy":{en:"Reported by",pt:"Reportado por",fr:"Signalé par",de:"Gemeldet von",it:"Segnalato da",nl:"Gerapporteerd door",ja:"報告者",zh:"举报者",ru:"Подано",ar:"أبلغ عنه",hi:"द्वारा रिपोर्ट किया गया",ko:"신고자",tr:"Bildiren",pl:"Zgłoszone przez",sv:"Rapporterad av",id:"Dilaporkan oleh",th:"รายงานโดย"},
"admin.reason":{en:"Reason",pt:"Razão",fr:"Raison",de:"Grund",it:"Motivo",nl:"Reden",ja:"理由",zh:"原因",ru:"Причина",ar:"السبب",hi:"कारण",ko:"사유",tr:"Sebep",pl:"Powód",sv:"Anledning",id:"Alasan",th:"เหตุผล"},
"admin.generalStats":{en:"General Statistics",pt:"Estatísticas Gerais",fr:"Statistiques Générales",de:"Allgemeine Statistiken",it:"Statistiche Generali",nl:"Algemene Statistieken",ja:"一般統計",zh:"总体统计",ru:"Общая статистика",ar:"إحصائيات عامة",hi:"सामान्य सांख्यिकी",ko:"일반 통계",tr:"Genel İstatistikler",pl:"Statystyki Ogólne",sv:"Allmän Statistik",id:"Statistik Umum",th:"สถิติทั่วไป"},
"admin.forumMetrics":{en:"Forum Metrics",pt:"Métricas do Fórum",fr:"Métriques du Forum",de:"Forum-Metriken",it:"Metriche del Forum",nl:"Forumstatistieken",ja:"フォーラム指標",zh:"论坛指标",ru:"Метрики форума",ar:"مقاييس المنتدى",hi:"फ़ोरम मेट्रिक्स",ko:"포럼 지표",tr:"Forum Metrikleri",pl:"Metryki Forum",sv:"Forumstatistik",id:"Metrik Forum",th:"ตัวชี้วัดฟอรั่ม"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2g (admin - 46 keys) done!');
