/**
 * Batch 2: Translate all remaining user-facing sections
 */
const fs = require('fs');
const path = require('path');

const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));

function flatten(obj, prefix = '') {
  const result = {};
  for (const k in obj) {
    const p = prefix ? `${prefix}.${k}` : k;
    if (typeof obj[k] === 'object' && obj[k] !== null) Object.assign(result, flatten(obj[k], p));
    else result[p] = obj[k];
  }
  return result;
}
function unflatten(obj) {
  const result = {};
  for (const key in obj) {
    const parts = key.split('.');
    let current = result;
    for (let i = 0; i < parts.length - 1; i++) {
      if (!current[parts[i]]) current[parts[i]] = {};
      current = current[parts[i]];
    }
    current[parts[parts.length - 1]] = obj[key];
  }
  return result;
}
const esFlat = flatten(es);

const T = {
// === FORUM (remaining) ===
"Crear hilo":{en:"Create thread",pt:"Criar tópico",fr:"Créer un sujet",de:"Thema erstellen",it:"Crea discussione",nl:"Onderwerp maken",ja:"スレッド作成",zh:"创建主题",ru:"Создать тему",ar:"إنشاء موضوع",hi:"थ्रेड बनाएं",ko:"스레드 만들기",tr:"Konu oluştur",pl:"Utwórz wątek",sv:"Skapa tråd",id:"Buat thread",th:"สร้างกระทู้"},
"Título del hilo":{en:"Thread title",pt:"Título do tópico",fr:"Titre du sujet",de:"Thementitel",it:"Titolo discussione",nl:"Onderwerptitel",ja:"スレッドタイトル",zh:"主题标题",ru:"Название темы",ar:"عنوان الموضوع",hi:"थ्रेड शीर्षक",ko:"스레드 제목",tr:"Konu başlığı",pl:"Tytuł wątku",sv:"Trådtitel",id:"Judul thread",th:"หัวข้อกระทู้"},
"Publicar":{en:"Post",pt:"Publicar",fr:"Publier",de:"Veröffentlichen",it:"Pubblica",nl:"Plaatsen",ja:"投稿",zh:"发布",ru:"Опубликовать",ar:"نشر",hi:"प्रकाशित करें",ko:"게시",tr:"Yayınla",pl:"Opublikuj",sv:"Publicera",id:"Posting",th:"โพสต์"},
"Destacado":{en:"Featured",pt:"Destaque",fr:"En vedette",de:"Hervorgehoben",it:"In evidenza",nl:"Uitgelicht",ja:"注目",zh:"精选",ru:"Избранное",ar:"مميز",hi:"विशेष",ko:"추천",tr:"Öne çıkan",pl:"Wyróżniony",sv:"Utvalt",id:"Unggulan",th:"แนะนำ"},
"Categorías":{en:"Categories",pt:"Categorias",fr:"Catégories",de:"Kategorien",it:"Categorie",nl:"Categorieën",ja:"カテゴリ",zh:"分类",ru:"Категории",ar:"الفئات",hi:"श्रेणियाँ",ko:"카테고리",tr:"Kategoriler",pl:"Kategorie",sv:"Kategorier",id:"Kategori",th:"หมวดหมู่"},
"No hay subforos en esta categoría":{en:"No subforums in this category",pt:"Nenhum subfórum nesta categoria",fr:"Aucun sous-forum dans cette catégorie",de:"Keine Unterforen in dieser Kategorie",it:"Nessun sottoforum in questa categoria",nl:"Geen subforums in deze categorie",ja:"このカテゴリにサブフォーラムはありません",zh:"此分类没有子论坛",ru:"В этой категории нет подфорумов",ar:"لا توجد منتديات فرعية في هذه الفئة",hi:"इस श्रेणी में कोई उप-फ़ोरम नहीं",ko:"이 카테고리에 하위 포럼이 없습니다",tr:"Bu kategoride alt forum yok",pl:"Brak podforów w tej kategorii",sv:"Inga underforum i denna kategori",id:"Tidak ada subforum di kategori ini",th:"ไม่มีฟอรั่มย่อยในหมวดนี้"},
"Privado":{en:"Private",pt:"Privado",fr:"Privé",de:"Privat",it:"Privato",nl:"Privé",ja:"プライベート",zh:"私密",ru:"Приватный",ar:"خاص",hi:"निजी",ko:"비공개",tr:"Özel",pl:"Prywatny",sv:"Privat",id:"Pribadi",th:"ส่วนตัว"},
"Foros por Región":{en:"Forums by Region",pt:"Fóruns por Região",fr:"Forums par Région",de:"Foren nach Region",it:"Forum per Regione",nl:"Forums per Regio",ja:"地域別フォーラム",zh:"按地区浏览论坛",ru:"Форумы по регионам",ar:"المنتديات حسب المنطقة",hi:"क्षेत्र के अनुसार फ़ोरम",ko:"지역별 포럼",tr:"Bölgeye göre forumlar",pl:"Fora według regionu",sv:"Forum efter region",id:"Forum berdasarkan wilayah",th:"ฟอรั่มตามภูมิภาค"},
"Explora los foros organizados por continente, país y ciudad":{en:"Explore forums organized by continent, country and city",pt:"Explore fóruns organizados por continente, país e cidade",fr:"Explorez les forums organisés par continent, pays et ville",de:"Entdecken Sie Foren nach Kontinent, Land und Stadt",it:"Esplora i forum organizzati per continente, paese e città",nl:"Verken forums georganiseerd per continent, land en stad",ja:"大陸、国、都市別に整理されたフォーラムを探索",zh:"按洲、国家和城市浏览论坛",ru:"Форумы по континентам, странам и городам",ar:"استكشف المنتديات حسب القارة والبلد والمدينة",hi:"महाद्वीप, देश और शहर के अनुसार फ़ोरम देखें",ko:"대륙, 국가, 도시별 포럼 탐색",tr:"Kıta, ülke ve şehre göre forumları keşfet",pl:"Przeglądaj fora według kontynentu, kraju i miasta",sv:"Utforska forum efter kontinent, land och stad",id:"Jelajahi forum berdasarkan benua, negara, dan kota",th:"สำรวจฟอรั่มตามทวีป ประเทศ และเมือง"},
"Alta":{en:"High",pt:"Alta",fr:"Haute",de:"Hoch",it:"Alta",nl:"Hoog",ja:"高",zh:"高",ru:"Высокая",ar:"عالية",hi:"उच्च",ko:"높음",tr:"Yüksek",pl:"Wysoka",sv:"Hög",id:"Tinggi",th:"สูง"},
"Media":{en:"Medium",pt:"Média",fr:"Moyenne",de:"Mittel",it:"Media",nl:"Gemiddeld",ja:"中",zh:"中",ru:"Средняя",ar:"متوسطة",hi:"मध्यम",ko:"중간",tr:"Orta",pl:"Średnia",sv:"Medium",id:"Sedang",th:"กลาง"},
"No hay países disponibles en este continente":{en:"No countries available in this continent",pt:"Nenhum país disponível neste continente",fr:"Aucun pays disponible sur ce continent",de:"Keine Länder auf diesem Kontinent verfügbar",it:"Nessun paese disponibile in questo continente",nl:"Geen landen beschikbaar op dit continent",ja:"この大陸に利用可能な国はありません",zh:"此大陆没有可用的国家",ru:"Нет доступных стран на этом континенте",ar:"لا توجد دول متاحة في هذه القارة",hi:"इस महाद्वीप में कोई देश उपलब्ध नहीं",ko:"이 대륙에 사용 가능한 국가가 없습니다",tr:"Bu kıtada ülke bulunmuyor",pl:"Brak krajów na tym kontynencie",sv:"Inga länder tillgängliga på denna kontinent",id:"Tidak ada negara tersedia di benua ini",th:"ไม่มีประเทศที่ใช้ได้ในทวีปนี้"},
"Foros geográficos":{en:"Geographic forums",pt:"Fóruns geográficos",fr:"Forums géographiques",de:"Geografische Foren",it:"Forum geografici",nl:"Geografische forums",ja:"地理フォーラム",zh:"地理论坛",ru:"Географические форумы",ar:"المنتديات الجغرافية",hi:"भौगोलिक फ़ोरम",ko:"지리 포럼",tr:"Coğrafi forumlar",pl:"Fora geograficzne",sv:"Geografiska forum",id:"Forum geografis",th:"ฟอรั่มภูมิศาสตร์"},
"Los foros por región estarán disponibles próximamente.":{en:"Regional forums will be available soon.",pt:"Os fóruns por região estarão disponíveis em breve.",fr:"Les forums par région seront bientôt disponibles.",de:"Regionale Foren werden bald verfügbar sein.",it:"I forum per regione saranno presto disponibili.",nl:"Regionale forums worden binnenkort beschikbaar.",ja:"地域別フォーラムは近日公開予定です。",zh:"按地区划分的论坛即将推出。",ru:"Региональные форумы скоро будут доступны.",ar:"ستتوفر المنتديات الإقليمية قريباً.",hi:"क्षेत्रीय फ़ोरम जल्द ही उपलब्ध होंगे।",ko:"지역 포럼이 곧 제공됩니다.",tr:"Bölgesel forumlar yakında kullanıma sunulacak.",pl:"Fora regionalne będą wkrótce dostępne.",sv:"Regionala forum kommer snart att finnas tillgängliga.",id:"Forum regional akan segera tersedia.",th:"ฟอรั่มตามภูมิภาคจะพร้อมใช้งานเร็วๆ นี้"},
"Volver a foros":{en:"Back to forums",pt:"Voltar aos fóruns",fr:"Retour aux forums",de:"Zurück zu den Foren",it:"Torna ai forum",nl:"Terug naar forums",ja:"フォーラムに戻る",zh:"返回论坛",ru:"Вернуться к форумам",ar:"العودة إلى المنتديات",hi:"फ़ोरम पर वापस जाएं",ko:"포럼으로 돌아가기",tr:"Forumlara dön",pl:"Powrót do forów",sv:"Tillbaka till forum",id:"Kembali ke forum",th:"กลับไปฟอรั่ม"},
"Foros y comunidades en {country}":{en:"Forums and communities in {country}",pt:"Fóruns e comunidades em {country}",fr:"Forums et communautés en {country}",de:"Foren und Communities in {country}",it:"Forum e comunità in {country}",nl:"Forums en gemeenschappen in {country}",ja:"{country}のフォーラムとコミュニティ",zh:"{country}的论坛和社区",ru:"Форумы и сообщества в {country}",ar:"منتديات ومجتمعات في {country}",hi:"{country} में फ़ोरम और समुदाय",ko:"{country}의 포럼 및 커뮤니티",tr:"{country} forumları ve toplulukları",pl:"Fora i społeczności w {country}",sv:"Forum och gemenskaper i {country}",id:"Forum dan komunitas di {country}",th:"ฟอรั่มและชุมชนใน {country}"},
"Ciudades y Regiones":{en:"Cities and Regions",pt:"Cidades e Regiões",fr:"Villes et Régions",de:"Städte und Regionen",it:"Città e Regioni",nl:"Steden en Regio's",ja:"都市と地域",zh:"城市和地区",ru:"Города и регионы",ar:"المدن والمناطق",hi:"शहर और क्षेत्र",ko:"도시 및 지역",tr:"Şehirler ve Bölgeler",pl:"Miasta i Regiony",sv:"Städer och Regioner",id:"Kota dan Wilayah",th:"เมืองและภูมิภาค"},
"Foro de {name}":{en:"Forum of {name}",pt:"Fórum de {name}",fr:"Forum de {name}",de:"Forum von {name}",it:"Forum di {name}",nl:"Forum van {name}",ja:"{name}のフォーラム",zh:"{name}论坛",ru:"Форум {name}",ar:"منتدى {name}",hi:"{name} फ़ोरम",ko:"{name} 포럼",tr:"{name} forumu",pl:"Forum {name}",sv:"Forum för {name}",id:"Forum {name}",th:"ฟอรั่ม {name}"},
"{count} hilos":{en:"{count} threads",pt:"{count} tópicos",fr:"{count} sujets",de:"{count} Themen",it:"{count} discussioni",nl:"{count} onderwerpen",ja:"{count} スレッド",zh:"{count} 个主题",ru:"{count} тем",ar:"{count} مواضيع",hi:"{count} थ्रेड",ko:"{count} 스레드",tr:"{count} konu",pl:"{count} wątków",sv:"{count} trådar",id:"{count} thread",th:"{count} กระทู้"},
"Sin regiones disponibles":{en:"No regions available",pt:"Sem regiões disponíveis",fr:"Aucune région disponible",de:"Keine Regionen verfügbar",it:"Nessuna regione disponibile",nl:"Geen regio's beschikbaar",ja:"利用可能な地域はありません",zh:"没有可用的地区",ru:"Нет доступных регионов",ar:"لا توجد مناطق متاحة",hi:"कोई क्षेत्र उपलब्ध नहीं",ko:"사용 가능한 지역이 없습니다",tr:"Bölge bulunmuyor",pl:"Brak dostępnych regionów",sv:"Inga regioner tillgängliga",id:"Tidak ada wilayah tersedia",th:"ไม่มีภูมิภาคที่ใช้ได้"},
"Hilos recientes":{en:"Recent threads",pt:"Tópicos recentes",fr:"Sujets récents",de:"Neueste Themen",it:"Discussioni recenti",nl:"Recente onderwerpen",ja:"最近のスレッド",zh:"最新主题",ru:"Последние темы",ar:"مواضيع حديثة",hi:"हाल के थ्रेड",ko:"최근 스레드",tr:"Son konular",pl:"Ostatnie wątki",sv:"Senaste trådar",id:"Thread terbaru",th:"กระทู้ล่าสุด"},
"Ahora mismo":{en:"Just now",pt:"Agora mesmo",fr:"À l'instant",de:"Gerade eben",it:"Proprio ora",nl:"Zojuist",ja:"たった今",zh:"刚刚",ru:"Только что",ar:"الآن",hi:"अभी",ko:"방금",tr:"Az önce",pl:"Właśnie teraz",sv:"Just nu",id:"Baru saja",th:"เมื่อสักครู่"},
"Hoy a las":{en:"Today at",pt:"Hoje às",fr:"Aujourd'hui à",de:"Heute um",it:"Oggi alle",nl:"Vandaag om",ja:"今日",zh:"今天",ru:"Сегодня в",ar:"اليوم في",hi:"आज",ko:"오늘",tr:"Bugün saat",pl:"Dziś o",sv:"Idag kl",id:"Hari ini pukul",th:"วันนี้เวลา"},
"Ayer a las":{en:"Yesterday at",pt:"Ontem às",fr:"Hier à",de:"Gestern um",it:"Ieri alle",nl:"Gisteren om",ja:"昨日",zh:"昨天",ru:"Вчера в",ar:"أمس في",hi:"कल",ko:"어제",tr:"Dün saat",pl:"Wczoraj o",sv:"Igår kl",id:"Kemarin pukul",th:"เมื่อวานเวลา"},
"Usa @usuario para mencionar":{en:"Use @username to mention",pt:"Use @usuário para mencionar",fr:"Utilisez @utilisateur pour mentionner",de:"Verwende @Benutzername zum Erwähnen",it:"Usa @utente per menzionare",nl:"Gebruik @gebruikersnaam om te vermelden",ja:"@ユーザー名でメンション",zh:"使用@用户名来提及",ru:"Используйте @пользователь для упоминания",ar:"استخدم @اسم_المستخدم للإشارة",hi:"@उपयोगकर्तानाम से उल्लेख करें",ko:"@사용자이름으로 멘션",tr:"Bahsetmek için @kullanıcıadı kullanın",pl:"Użyj @użytkownik aby wspomnieć",sv:"Använd @användarnamn för att nämna",id:"Gunakan @namapengguna untuk menyebut",th:"ใช้ @ชื่อผู้ใช้ เพื่อกล่าวถึง"},
"Crear primer hilo":{en:"Create first thread",pt:"Criar primeiro tópico",fr:"Créer le premier sujet",de:"Erstes Thema erstellen",it:"Crea prima discussione",nl:"Eerste onderwerp maken",ja:"最初のスレッドを作成",zh:"创建第一个主题",ru:"Создать первую тему",ar:"إنشاء أول موضوع",hi:"पहला थ्रेड बनाएं",ko:"첫 스레드 만들기",tr:"İlk konuyu oluştur",pl:"Utwórz pierwszy wątek",sv:"Skapa första tråd",id:"Buat thread pertama",th:"สร้างกระทู้แรก"},
"{count} respuestas":{en:"{count} replies",pt:"{count} respostas",fr:"{count} réponses",de:"{count} Antworten",it:"{count} risposte",nl:"{count} antwoorden",ja:"{count} 件の返信",zh:"{count} 条回复",ru:"{count} ответов",ar:"{count} ردود",hi:"{count} उत्तर",ko:"{count} 답글",tr:"{count} yanıt",pl:"{count} odpowiedzi",sv:"{count} svar",id:"{count} balasan",th:"{count} การตอบกลับ"},
"{count} vistas":{en:"{count} views",pt:"{count} visualizações",fr:"{count} vues",de:"{count} Ansichten",it:"{count} visualizzazioni",nl:"{count} weergaven",ja:"{count} 回閲覧",zh:"{count} 次浏览",ru:"{count} просмотров",ar:"{count} مشاهدات",hi:"{count} दृश्य",ko:"{count} 조회",tr:"{count} görüntüleme",pl:"{count} wyświetleń",sv:"{count} visningar",id:"{count} tampilan",th:"{count} การดู"},
"América del Norte":{en:"North America",pt:"América do Norte",fr:"Amérique du Nord",de:"Nordamerika",it:"Nord America",nl:"Noord-Amerika",ja:"北アメリカ",zh:"北美洲",ru:"Северная Америка",ar:"أمريكا الشمالية",hi:"उत्तरी अमेरिका",ko:"북아메리카",tr:"Kuzey Amerika",pl:"Ameryka Północna",sv:"Nordamerika",id:"Amerika Utara",th:"อเมริกาเหนือ"},
"América Latina":{en:"Latin America",pt:"América Latina",fr:"Amérique Latine",de:"Lateinamerika",it:"America Latina",nl:"Latijns-Amerika",ja:"ラテンアメリカ",zh:"拉丁美洲",ru:"Латинская Америка",ar:"أمريكا اللاتينية",hi:"लैटिन अमेरिका",ko:"라틴 아메리카",tr:"Latin Amerika",pl:"Ameryka Łacińska",sv:"Latinamerika",id:"Amerika Latin",th:"ละตินอเมริกา"},
"Europa Occidental":{en:"Western Europe",pt:"Europa Ocidental",fr:"Europe Occidentale",de:"Westeuropa",it:"Europa Occidentale",nl:"West-Europa",ja:"西ヨーロッパ",zh:"西欧",ru:"Западная Европа",ar:"أوروبا الغربية",hi:"पश्चिमी यूरोप",ko:"서유럽",tr:"Batı Avrupa",pl:"Europa Zachodnia",sv:"Västeuropa",id:"Eropa Barat",th:"ยุโรปตะวันตก"},
"Europa":{en:"Europe",pt:"Europa",fr:"Europe",de:"Europa",it:"Europa",nl:"Europa",ja:"ヨーロッパ",zh:"欧洲",ru:"Европа",ar:"أوروبا",hi:"यूरोप",ko:"유럽",tr:"Avrupa",pl:"Europa",sv:"Europa",id:"Eropa",th:"ยุโรป"},
"Asia":{en:"Asia",pt:"Ásia",fr:"Asie",de:"Asien",it:"Asia",nl:"Azië",ja:"アジア",zh:"亚洲",ru:"Азия",ar:"آسيا",hi:"एशिया",ko:"아시아",tr:"Asya",pl:"Azja",sv:"Asien",id:"Asia",th:"เอเชีย"},
"Oceanía":{en:"Oceania",pt:"Oceania",fr:"Océanie",de:"Ozeanien",it:"Oceania",nl:"Oceanië",ja:"オセアニア",zh:"大洋洲",ru:"Океания",ar:"أوقيانوسيا",hi:"ओशिनिया",ko:"오세아니아",tr:"Okyanusya",pl:"Oceania",sv:"Oceanien",id:"Oseania",th:"โอเชียเนีย"},
"África":{en:"Africa",pt:"África",fr:"Afrique",de:"Afrika",it:"Africa",nl:"Afrika",ja:"アフリカ",zh:"非洲",ru:"Африка",ar:"أفريقيا",hi:"अफ्रीका",ko:"아프리카",tr:"Afrika",pl:"Afryka",sv:"Afrika",id:"Afrika",th:"แอฟริกา"},
"Medio Oriente":{en:"Middle East",pt:"Oriente Médio",fr:"Moyen-Orient",de:"Naher Osten",it:"Medio Oriente",nl:"Midden-Oosten",ja:"中東",zh:"中东",ru:"Ближний Восток",ar:"الشرق الأوسط",hi:"मध्य पूर्व",ko:"중동",tr:"Orta Doğu",pl:"Bliski Wschód",sv:"Mellanöstern",id:"Timur Tengah",th:"ตะวันออกกลาง"},
"Review":{en:"Review",pt:"Resenha",fr:"Avis",de:"Bewertung",it:"Recensione",nl:"Beoordeling",ja:"レビュー",zh:"评测",ru:"Обзор",ar:"مراجعة",hi:"समीक्षा",ko:"리뷰",tr:"İnceleme",pl:"Recenzja",sv:"Recension",id:"Ulasan",th:"รีวิว"},
"Pregunta":{en:"Question",pt:"Pergunta",fr:"Question",de:"Frage",it:"Domanda",nl:"Vraag",ja:"質問",zh:"提问",ru:"Вопрос",ar:"سؤال",hi:"प्रश्न",ko:"질문",tr:"Soru",pl:"Pytanie",sv:"Fråga",id:"Pertanyaan",th:"คำถาม"},
"General":{en:"General",pt:"Geral",fr:"Général",de:"Allgemein",it:"Generale",nl:"Algemeen",ja:"一般",zh:"综合",ru:"Общий",ar:"عام",hi:"सामान्य",ko:"일반",tr:"Genel",pl:"Ogólny",sv:"Allmänt",id:"Umum",th:"ทั่วไป"},
"Selecciona una etiqueta":{en:"Select a tag",pt:"Selecione uma tag",fr:"Sélectionnez un tag",de:"Wählen Sie ein Tag",it:"Seleziona un tag",nl:"Selecteer een tag",ja:"タグを選択",zh:"选择标签",ru:"Выберите тег",ar:"اختر وسماً",hi:"टैग चुनें",ko:"태그 선택",tr:"Bir etiket seçin",pl:"Wybierz tag",sv:"Välj en tagg",id:"Pilih tag",th:"เลือกแท็ก"},
"Debes seleccionar una etiqueta":{en:"You must select a tag",pt:"Você deve selecionar uma tag",fr:"Vous devez sélectionner un tag",de:"Sie müssen ein Tag auswählen",it:"Devi selezionare un tag",nl:"Je moet een tag selecteren",ja:"タグを選択してください",zh:"请选择标签",ru:"Необходимо выбрать тег",ar:"يجب اختيار وسم",hi:"आपको एक टैग चुनना होगा",ko:"태그를 선택해야 합니다",tr:"Bir etiket seçmelisiniz",pl:"Musisz wybrać tag",sv:"Du måste välja en tagg",id:"Anda harus memilih tag",th:"คุณต้องเลือกแท็ก"},
"Suscribirse al hilo":{en:"Subscribe to thread",pt:"Inscrever-se no tópico",fr:"S'abonner au sujet",de:"Thema abonnieren",it:"Iscriviti alla discussione",nl:"Abonneren op onderwerp",ja:"スレッドを購読",zh:"订阅主题",ru:"Подписаться на тему",ar:"الاشتراك في الموضوع",hi:"थ्रेड की सदस्यता लें",ko:"스레드 구독",tr:"Konuya abone ol",pl:"Subskrybuj wątek",sv:"Prenumerera på tråd",id:"Berlangganan thread",th:"ติดตามกระทู้"},
"Cancelar suscripción":{en:"Unsubscribe",pt:"Cancelar inscrição",fr:"Se désabonner",de:"Abbestellen",it:"Annulla iscrizione",nl:"Uitschrijven",ja:"購読解除",zh:"取消订阅",ru:"Отписаться",ar:"إلغاء الاشتراك",hi:"सदस्यता रद्द करें",ko:"구독 취소",tr:"Aboneliği iptal et",pl:"Anuluj subskrypcję",sv:"Avprenumerera",id:"Berhenti berlangganan",th:"ยกเลิกการติดตาม"},
"Guardado":{en:"Saved",pt:"Salvo",fr:"Enregistré",de:"Gespeichert",it:"Salvato",nl:"Opgeslagen",ja:"保存済み",zh:"已保存",ru:"Сохранено",ar:"محفوظ",hi:"सहेजा गया",ko:"저장됨",tr:"Kaydedildi",pl:"Zapisano",sv:"Sparat",id:"Tersimpan",th:"บันทึกแล้ว"},
"Publicando...":{en:"Publishing...",pt:"Publicando...",fr:"Publication...",de:"Veröffentlichen...",it:"Pubblicazione...",nl:"Plaatsen...",ja:"投稿中...",zh:"发布中...",ru:"Публикация...",ar:"جاري النشر...",hi:"प्रकाशित हो रहा है...",ko:"게시 중...",tr:"Yayınlanıyor...",pl:"Publikowanie...",sv:"Publicerar...",id:"Memposting...",th:"กำลังโพสต์..."},
"Publicar respuesta":{en:"Post reply",pt:"Publicar resposta",fr:"Publier la réponse",de:"Antwort veröffentlichen",it:"Pubblica risposta",nl:"Antwoord plaatsen",ja:"返信を投稿",zh:"发布回复",ru:"Опубликовать ответ",ar:"نشر الرد",hi:"उत्तर प्रकाशित करें",ko:"답글 게시",tr:"Yanıt yayınla",pl:"Opublikuj odpowiedź",sv:"Publicera svar",id:"Posting balasan",th:"โพสต์คำตอบ"},
"Responder al hilo":{en:"Reply to thread",pt:"Responder ao tópico",fr:"Répondre au sujet",de:"Auf Thema antworten",it:"Rispondi alla discussione",nl:"Antwoorden op onderwerp",ja:"スレッドに返信",zh:"回复主题",ru:"Ответить в тему",ar:"الرد على الموضوع",hi:"थ्रेड का जवाब दें",ko:"스레드에 답글",tr:"Konuya yanıt ver",pl:"Odpowiedz na wątek",sv:"Svara på tråd",id:"Balas thread",th:"ตอบกระทู้"},
"Escribe tu respuesta... Usa @usuario para mencionar":{en:"Write your reply... Use @username to mention",pt:"Escreva sua resposta... Use @usuário para mencionar",fr:"Écrivez votre réponse... Utilisez @utilisateur pour mentionner",de:"Schreiben Sie Ihre Antwort... Verwenden Sie @Benutzername zum Erwähnen",it:"Scrivi la tua risposta... Usa @utente per menzionare",nl:"Schrijf je antwoord... Gebruik @gebruikersnaam om te vermelden",ja:"返信を書いてください... @ユーザー名でメンション",zh:"写下你的回复... 使用@用户名来提及",ru:"Напишите ответ... Используйте @пользователь для упоминания",ar:"اكتب ردك... استخدم @اسم_المستخدم للإشارة",hi:"अपना जवाब लिखें... @उपयोगकर्तानाम से उल्लेख करें",ko:"답글을 작성하세요... @사용자이름으로 멘션",tr:"Yanıtınızı yazın... Bahsetmek için @kullanıcıadı kullanın",pl:"Napisz odpowiedź... Użyj @użytkownik aby wspomnieć",sv:"Skriv ditt svar... Använd @användarnamn för att nämna",id:"Tulis balasan Anda... Gunakan @namapengguna untuk menyebut",th:"เขียนคำตอบของคุณ... ใช้ @ชื่อผู้ใช้ เพื่อกล่าวถึง"},
"Respondiendo como":{en:"Replying as",pt:"Respondendo como",fr:"Répondre en tant que",de:"Antworten als",it:"Rispondendo come",nl:"Antwoorden als",ja:"として返信",zh:"以...身份回复",ru:"Ответ от",ar:"الرد باسم",hi:"के रूप में जवाब दे रहे हैं",ko:"로 답글 작성",tr:"Olarak yanıtlanıyor",pl:"Odpowiadasz jako",sv:"Svarar som",id:"Membalas sebagai",th:"ตอบกลับในฐานะ"},
"Debes iniciar sesión para responder a este hilo":{en:"You must sign in to reply to this thread",pt:"Você precisa entrar para responder a este tópico",fr:"Vous devez vous connecter pour répondre à ce sujet",de:"Sie müssen sich anmelden, um auf dieses Thema zu antworten",it:"Devi accedere per rispondere a questa discussione",nl:"Je moet inloggen om op dit onderwerp te antwoorden",ja:"このスレッドに返信するにはログインが必要です",zh:"您必须登录才能回复此主题",ru:"Войдите, чтобы ответить в эту тему",ar:"يجب تسجيل الدخول للرد على هذا الموضوع",hi:"इस थ्रेड का जवाब देने के लिए लॉगिन करें",ko:"이 스레드에 답글을 달려면 로그인해야 합니다",tr:"Bu konuya yanıt vermek için giriş yapmalısınız",pl:"Musisz się zalogować, aby odpowiedzieć na ten wątek",sv:"Du måste logga in för att svara på denna tråd",id:"Anda harus masuk untuk membalas thread ini",th:"คุณต้องเข้าสู่ระบบเพื่อตอบกระทู้นี้"},
"Debes iniciar sesión para responder":{en:"You must sign in to reply",pt:"Você precisa entrar para responder",fr:"Vous devez vous connecter pour répondre",de:"Anmelden zum Antworten",it:"Accedi per rispondere",nl:"Log in om te antwoorden",ja:"返信するにはログインしてください",zh:"请登录后回复",ru:"Войдите, чтобы ответить",ar:"يجب تسجيل الدخول للرد",hi:"जवाब देने के लिए लॉगिन करें",ko:"답글을 달려면 로그인하세요",tr:"Yanıt vermek için giriş yapın",pl:"Zaloguj się, aby odpowiedzieć",sv:"Logga in för att svara",id:"Masuk untuk membalas",th:"เข้าสู่ระบบเพื่อตอบกลับ"},
"La respuesta debe tener al menos 3 caracteres":{en:"Reply must be at least 3 characters",pt:"A resposta deve ter pelo menos 3 caracteres",fr:"La réponse doit contenir au moins 3 caractères",de:"Antwort muss mindestens 3 Zeichen lang sein",it:"La risposta deve avere almeno 3 caratteri",nl:"Antwoord moet minstens 3 tekens bevatten",ja:"返信は3文字以上必要です",zh:"回复至少需要3个字符",ru:"Ответ должен содержать не менее 3 символов",ar:"يجب أن يكون الرد 3 أحرف على الأقل",hi:"उत्तर कम से कम 3 अक्षर का होना चाहिए",ko:"답글은 최소 3자 이상이어야 합니다",tr:"Yanıt en az 3 karakter olmalıdır",pl:"Odpowiedź musi mieć co najmniej 3 znaki",sv:"Svaret måste vara minst 3 tecken",id:"Balasan harus minimal 3 karakter",th:"คำตอบต้องมีอย่างน้อย 3 ตัวอักษร"},
"Respuesta publicada":{en:"Reply posted",pt:"Resposta publicada",fr:"Réponse publiée",de:"Antwort veröffentlicht",it:"Risposta pubblicata",nl:"Antwoord geplaatst",ja:"返信が投稿されました",zh:"回复已发布",ru:"Ответ опубликован",ar:"تم نشر الرد",hi:"उत्तर प्रकाशित हुआ",ko:"답글이 게시되었습니다",tr:"Yanıt yayınlandı",pl:"Odpowiedź opublikowana",sv:"Svar publicerat",id:"Balasan diposting",th:"โพสต์คำตอบแล้ว"},
"Error al publicar respuesta":{en:"Error posting reply",pt:"Erro ao publicar resposta",fr:"Erreur lors de la publication",de:"Fehler beim Veröffentlichen",it:"Errore nella pubblicazione",nl:"Fout bij plaatsen antwoord",ja:"返信の投稿エラー",zh:"发布回复出错",ru:"Ошибка при публикации ответа",ar:"خطأ في نشر الرد",hi:"उत्तर प्रकाशित करने में त्रुटि",ko:"답글 게시 오류",tr:"Yanıt yayınlanırken hata",pl:"Błąd publikacji odpowiedzi",sv:"Fel vid publicering av svar",id:"Error saat posting balasan",th:"เกิดข้อผิดพลาดในการโพสต์คำตอบ"},
"Añadido a favoritos":{en:"Added to favorites",pt:"Adicionado aos favoritos",fr:"Ajouté aux favoris",de:"Zu Favoriten hinzugefügt",it:"Aggiunto ai preferiti",nl:"Toegevoegd aan favorieten",ja:"お気に入りに追加",zh:"已添加到收藏",ru:"Добавлено в избранное",ar:"تمت الإضافة إلى المفضلة",hi:"पसंदीदा में जोड़ा गया",ko:"즐겨찾기에 추가됨",tr:"Favorilere eklendi",pl:"Dodano do ulubionych",sv:"Tillagt i favoriter",id:"Ditambahkan ke favorit",th:"เพิ่มในรายการโปรด"},
"Eliminado de favoritos":{en:"Removed from favorites",pt:"Removido dos favoritos",fr:"Retiré des favoris",de:"Aus Favoriten entfernt",it:"Rimosso dai preferiti",nl:"Verwijderd uit favorieten",ja:"お気に入りから削除",zh:"已从收藏中移除",ru:"Удалено из избранного",ar:"تمت الإزالة من المفضلة",hi:"पसंदीदा से हटाया गया",ko:"즐겨찾기에서 제거됨",tr:"Favorilerden kaldırıldı",pl:"Usunięto z ulubionych",sv:"Borttaget från favoriter",id:"Dihapus dari favorit",th:"ลบออกจากรายการโปรด"},
"Debes iniciar sesión para guardar favoritos":{en:"You must sign in to save favorites",pt:"Você precisa entrar para salvar favoritos",fr:"Connectez-vous pour sauvegarder des favoris",de:"Melden Sie sich an, um Favoriten zu speichern",it:"Accedi per salvare i preferiti",nl:"Log in om favorieten op te slaan",ja:"お気に入りを保存するにはログインしてください",zh:"请登录以保存收藏",ru:"Войдите, чтобы сохранить в избранное",ar:"سجل دخولك لحفظ المفضلة",hi:"पसंदीदा सहेजने के लिए लॉगिन करें",ko:"즐겨찾기를 저장하려면 로그인하세요",tr:"Favori kaydetmek için giriş yapın",pl:"Zaloguj się, aby zapisać ulubione",sv:"Logga in för att spara favoriter",id:"Masuk untuk menyimpan favorit",th:"เข้าสู่ระบบเพื่อบันทึกรายการโปรด"},
"Error al guardar favorito":{en:"Error saving favorite",pt:"Erro ao salvar favorito",fr:"Erreur lors de l'enregistrement",de:"Fehler beim Speichern",it:"Errore nel salvare",nl:"Fout bij opslaan",ja:"お気に入り保存エラー",zh:"保存收藏出错",ru:"Ошибка сохранения в избранное",ar:"خطأ في حفظ المفضلة",hi:"पसंदीदा सहेजने में त्रुटि",ko:"즐겨찾기 저장 오류",tr:"Favori kaydedilirken hata",pl:"Błąd zapisywania ulubionego",sv:"Fel vid sparande av favorit",id:"Error menyimpan favorit",th:"เกิดข้อผิดพลาดในการบันทึกรายการโปรด"},
"Quitar de favoritos":{en:"Remove from favorites",pt:"Remover dos favoritos",fr:"Retirer des favoris",de:"Aus Favoriten entfernen",it:"Rimuovi dai preferiti",nl:"Uit favorieten verwijderen",ja:"お気に入りから削除",zh:"从收藏中移除",ru:"Удалить из избранного",ar:"إزالة من المفضلة",hi:"पसंदीदा से हटाएं",ko:"즐겨찾기에서 제거",tr:"Favorilerden kaldır",pl:"Usuń z ulubionych",sv:"Ta bort från favoriter",id:"Hapus dari favorit",th:"ลบจากรายการโปรด"},
"Añadir a favoritos":{en:"Add to favorites",pt:"Adicionar aos favoritos",fr:"Ajouter aux favoris",de:"Zu Favoriten hinzufügen",it:"Aggiungi ai preferiti",nl:"Toevoegen aan favorieten",ja:"お気に入りに追加",zh:"添加到收藏",ru:"Добавить в избранное",ar:"إضافة إلى المفضلة",hi:"पसंदीदा में जोड़ें",ko:"즐겨찾기에 추가",tr:"Favorilere ekle",pl:"Dodaj do ulubionych",sv:"Lägg till i favoriter",id:"Tambah ke favorit",th:"เพิ่มในรายการโปรด"},
"Me gusta":{en:"Like",pt:"Curtir",fr:"J'aime",de:"Gefällt mir",it:"Mi piace",nl:"Vind ik leuk",ja:"いいね",zh:"喜欢",ru:"Нравится",ar:"إعجاب",hi:"पसंद",ko:"좋아요",tr:"Beğen",pl:"Lubię",sv:"Gilla",id:"Suka",th:"ถูกใจ"},
"Me encanta":{en:"Love",pt:"Amei",fr:"J'adore",de:"Liebe",it:"Adoro",nl:"Geweldig",ja:"大好き",zh:"大爱",ru:"Люблю",ar:"أحب",hi:"बहुत पसंद",ko:"좋아",tr:"Harika",pl:"Kocham",sv:"Älskar",id:"Cinta",th:"รัก"},
"Jaja":{en:"Haha",pt:"Haha",fr:"Haha",de:"Haha",it:"Haha",nl:"Haha",ja:"笑",zh:"哈哈",ru:"Хаха",ar:"هاها",hi:"हाहा",ko:"하하",tr:"Haha",pl:"Haha",sv:"Haha",id:"Haha",th:"ฮ่าฮ่า"},
"Wow":{en:"Wow",pt:"Uau",fr:"Wow",de:"Wow",it:"Wow",nl:"Wow",ja:"ワオ",zh:"哇",ru:"Ого",ar:"واو",hi:"वाह",ko:"와우",tr:"Vay",pl:"Wow",sv:"Wow",id:"Wow",th:"ว้าว"},
"Triste":{en:"Sad",pt:"Triste",fr:"Triste",de:"Traurig",it:"Triste",nl:"Verdrietig",ja:"悲しい",zh:"悲伤",ru:"Грустно",ar:"حزين",hi:"दुखी",ko:"슬퍼요",tr:"Üzgün",pl:"Smutne",sv:"Ledsen",id:"Sedih",th:"เศร้า"},
"Fuego":{en:"Fire",pt:"Fogo",fr:"Feu",de:"Feuer",it:"Fuoco",nl:"Vuur",ja:"炎",zh:"火",ru:"Огонь",ar:"نار",hi:"आग",ko:"불",tr:"Ateş",pl:"Ogień",sv:"Eld",id:"Api",th:"ไฟ"},
"Perfecto":{en:"Perfect",pt:"Perfeito",fr:"Parfait",de:"Perfekt",it:"Perfetto",nl:"Perfect",ja:"完璧",zh:"完美",ru:"Идеально",ar:"مثالي",hi:"बिल्कुल सही",ko:"완벽",tr:"Mükemmel",pl:"Idealnie",sv:"Perfekt",id:"Sempurna",th:"สมบูรณ์แบบ"},
"No hay posts en este hilo.":{en:"No posts in this thread.",pt:"Nenhum post neste tópico.",fr:"Aucun message dans ce sujet.",de:"Keine Beiträge in diesem Thema.",it:"Nessun post in questa discussione.",nl:"Geen berichten in dit onderwerp.",ja:"このスレッドに投稿はありません。",zh:"此主题没有帖子。",ru:"В этой теме нет сообщений.",ar:"لا توجد مشاركات في هذا الموضوع.",hi:"इस थ्रेड में कोई पोस्ट नहीं।",ko:"이 스레드에 게시물이 없습니다.",tr:"Bu konuda gönderi yok.",pl:"Brak postów w tym wątku.",sv:"Inga inlägg i denna tråd.",id:"Tidak ada postingan di thread ini.",th:"ไม่มีโพสต์ในกระทู้นี้"},
"Este hilo está cerrado y no se pueden agregar más respuestas.":{en:"This thread is closed and no more replies can be added.",pt:"Este tópico está fechado e não é possível adicionar mais respostas.",fr:"Ce sujet est fermé et aucune réponse ne peut être ajoutée.",de:"Dieses Thema ist geschlossen und es können keine Antworten mehr hinzugefügt werden.",it:"Questa discussione è chiusa e non è possibile aggiungere altre risposte.",nl:"Dit onderwerp is gesloten en er kunnen geen antwoorden meer worden toegevoegd.",ja:"このスレッドはクローズされており、返信を追加できません。",zh:"此主题已关闭，无法添加更多回复。",ru:"Эта тема закрыта, новые ответы невозможны.",ar:"هذا الموضوع مغلق ولا يمكن إضافة المزيد من الردود.",hi:"यह थ्रेड बंद है और अधिक उत्तर नहीं जोड़े जा सकते।",ko:"이 스레드는 닫혔으며 더 이상 답글을 추가할 수 없습니다.",tr:"Bu konu kapatılmıştır ve daha fazla yanıt eklenemez.",pl:"Ten wątek jest zamknięty i nie można dodawać więcej odpowiedzi.",sv:"Denna tråd är stängd och inga fler svar kan läggas till.",id:"Thread ini ditutup dan tidak bisa menambahkan balasan lagi.",th:"กระทู้นี้ปิดแล้วและไม่สามารถเพิ่มคำตอบได้อีก"},
"Subforo":{en:"Subforum",pt:"Subfórum",fr:"Sous-forum",de:"Unterforum",it:"Sottoforum",nl:"Subforum",ja:"サブフォーラム",zh:"子论坛",ru:"Подфорум",ar:"منتدى فرعي",hi:"उप-फ़ोरम",ko:"하위 포럼",tr:"Alt forum",pl:"Podforum",sv:"Underforum",id:"Subforum",th:"ฟอรั่มย่อย"},
"Hot":{en:"Hot",pt:"Popular",fr:"Populaire",de:"Beliebt",it:"Popolare",nl:"Populair",ja:"人気",zh:"热门",ru:"Горячее",ar:"ساخن",hi:"लोकप्रिय",ko:"인기",tr:"Popüler",pl:"Gorący",sv:"Hett",id:"Populer",th:"ยอดนิยม"},
"visitas":{en:"views",pt:"visualizações",fr:"vues",de:"Ansichten",it:"visualizzazioni",nl:"weergaven",ja:"閲覧",zh:"浏览",ru:"просмотров",ar:"مشاهدات",hi:"दृश्य",ko:"조회",tr:"görüntüleme",pl:"wyświetleń",sv:"visningar",id:"tampilan",th:"การดู"},
"respuestas":{en:"replies",pt:"respostas",fr:"réponses",de:"Antworten",it:"risposte",nl:"antwoorden",ja:"返信",zh:"回复",ru:"ответов",ar:"ردود",hi:"उत्तर",ko:"답글",tr:"yanıt",pl:"odpowiedzi",sv:"svar",id:"balasan",th:"การตอบกลับ"},
"Usuario":{en:"User",pt:"Usuário",fr:"Utilisateur",de:"Benutzer",it:"Utente",nl:"Gebruiker",ja:"ユーザー",zh:"用户",ru:"Пользователь",ar:"مستخدم",hi:"उपयोगकर्ता",ko:"사용자",tr:"Kullanıcı",pl:"Użytkownik",sv:"Användare",id:"Pengguna",th:"ผู้ใช้"},
"Seleccionar la etiqueta":{en:"Select the tag",pt:"Selecionar a tag",fr:"Sélectionner le tag",de:"Tag auswählen",it:"Seleziona il tag",nl:"Selecteer de tag",ja:"タグを選択",zh:"选择标签",ru:"Выберите тег",ar:"اختر الوسم",hi:"टैग चुनें",ko:"태그 선택",tr:"Etiketi seçin",pl:"Wybierz tag",sv:"Välj tagg",id:"Pilih tag",th:"เลือกแท็ก"},

// === AUTH remaining ===
"Confirmar contraseña":{en:"Confirm password",pt:"Confirmar senha",fr:"Confirmer le mot de passe",de:"Passwort bestätigen",it:"Conferma password",nl:"Wachtwoord bevestigen",ja:"パスワード確認",zh:"确认密码",ru:"Подтвердите пароль",ar:"تأكيد كلمة المرور",hi:"पासवर्ड पुष्टि करें",ko:"비밀번호 확인",tr:"Şifreyi onayla",pl:"Potwierdź hasło",sv:"Bekräfta lösenord",id:"Konfirmasi kata sandi",th:"ยืนยันรหัสผ่าน"},
"Tu nombre de usuario":{en:"Your username",pt:"Seu nome de usuário",fr:"Votre nom d'utilisateur",de:"Dein Benutzername",it:"Il tuo nome utente",nl:"Je gebruikersnaam",ja:"ユーザー名",zh:"你的用户名",ru:"Ваше имя пользователя",ar:"اسم المستخدم الخاص بك",hi:"आपका उपयोगकर्ता नाम",ko:"사용자 이름",tr:"Kullanıcı adınız",pl:"Twoja nazwa użytkownika",sv:"Ditt användarnamn",id:"Nama pengguna Anda",th:"ชื่อผู้ใช้ของคุณ"},
"Ingresa a tu cuenta para participar en el foro":{en:"Sign in to your account to participate in the forum",pt:"Entre na sua conta para participar do fórum",fr:"Connectez-vous pour participer au forum",de:"Melden Sie sich an, um am Forum teilzunehmen",it:"Accedi al tuo account per partecipare al forum",nl:"Log in om deel te nemen aan het forum",ja:"フォーラムに参加するにはアカウントにログインしてください",zh:"登录您的帐户以参与论坛",ru:"Войдите в аккаунт для участия в форуме",ar:"سجل دخولك للمشاركة في المنتدى",hi:"फ़ोरम में भाग लेने के लिए लॉगिन करें",ko:"포럼에 참여하려면 로그인하세요",tr:"Foruma katılmak için giriş yapın",pl:"Zaloguj się, aby uczestniczyć w forum",sv:"Logga in för att delta i forumet",id:"Masuk untuk berpartisipasi di forum",th:"เข้าสู่ระบบเพื่อเข้าร่วมฟอรั่ม"},
"Crear cuenta":{en:"Create account",pt:"Criar conta",fr:"Créer un compte",de:"Konto erstellen",it:"Crea account",nl:"Account aanmaken",ja:"アカウント作成",zh:"创建账户",ru:"Создать аккаунт",ar:"إنشاء حساب",hi:"खाता बनाएं",ko:"계정 만들기",tr:"Hesap oluştur",pl:"Utwórz konto",sv:"Skapa konto",id:"Buat akun",th:"สร้างบัญชี"},
"Únete a la comunidad de TS Rating":{en:"Join the TS Rating community",pt:"Junte-se à comunidade TS Rating",fr:"Rejoignez la communauté TS Rating",de:"Tritt der TS Rating Community bei",it:"Unisciti alla comunità TS Rating",nl:"Word lid van de TS Rating community",ja:"TS Ratingコミュニティに参加",zh:"加入TS Rating社区",ru:"Присоединяйтесь к сообществу TS Rating",ar:"انضم إلى مجتمع TS Rating",hi:"TS Rating समुदाय से जुड़ें",ko:"TS Rating 커뮤니티에 가입하세요",tr:"TS Rating topluluğuna katılın",pl:"Dołącz do społeczności TS Rating",sv:"Gå med i TS Rating-gemenskapen",id:"Bergabung dengan komunitas TS Rating",th:"เข้าร่วมชุมชน TS Rating"},
"Iniciando sesión...":{en:"Signing in...",pt:"Entrando...",fr:"Connexion...",de:"Anmelden...",it:"Accesso...",nl:"Inloggen...",ja:"ログイン中...",zh:"登录中...",ru:"Вход...",ar:"جاري تسجيل الدخول...",hi:"लॉगिन हो रहा है...",ko:"로그인 중...",tr:"Giriş yapılıyor...",pl:"Logowanie...",sv:"Loggar in...",id:"Masuk...",th:"กำลังเข้าสู่ระบบ..."},
"Creando cuenta...":{en:"Creating account...",pt:"Criando conta...",fr:"Création du compte...",de:"Konto wird erstellt...",it:"Creazione account...",nl:"Account aanmaken...",ja:"アカウント作成中...",zh:"创建账户中...",ru:"Создание аккаунта...",ar:"جاري إنشاء الحساب...",hi:"खाता बना रहे हैं...",ko:"계정 생성 중...",tr:"Hesap oluşturuluyor...",pl:"Tworzenie konta...",sv:"Skapar konto...",id:"Membuat akun...",th:"กำลังสร้างบัญชี..."},
"Bienvenida de vuelta":{en:"Welcome back",pt:"Bem-vinda de volta",fr:"Bienvenue",de:"Willkommen zurück",it:"Bentornata",nl:"Welkom terug",ja:"おかえりなさい",zh:"欢迎回来",ru:"С возвращением",ar:"مرحباً بعودتك",hi:"वापसी पर स्वागत है",ko:"다시 오신 것을 환영합니다",tr:"Tekrar hoş geldiniz",pl:"Witaj ponownie",sv:"Välkommen tillbaka",id:"Selamat datang kembali",th:"ยินดีต้อนรับกลับ"},
"Cuenta creada exitosamente":{en:"Account created successfully",pt:"Conta criada com sucesso",fr:"Compte créé avec succès",de:"Konto erfolgreich erstellt",it:"Account creato con successo",nl:"Account succesvol aangemaakt",ja:"アカウントが作成されました",zh:"账户创建成功",ru:"Аккаунт успешно создан",ar:"تم إنشاء الحساب بنجاح",hi:"खाता सफलतापूर्वक बनाया गया",ko:"계정이 성공적으로 생성되었습니다",tr:"Hesap başarıyla oluşturuldu",pl:"Konto zostało utworzone",sv:"Konto skapat",id:"Akun berhasil dibuat",th:"สร้างบัญชีสำเร็จ"},
"Bienvenida a TS Rating":{en:"Welcome to TS Rating",pt:"Bem-vinda ao TS Rating",fr:"Bienvenue sur TS Rating",de:"Willkommen bei TS Rating",it:"Benvenuta su TS Rating",nl:"Welkom bij TS Rating",ja:"TS Ratingへようこそ",zh:"欢迎来到TS Rating",ru:"Добро пожаловать в TS Rating",ar:"مرحباً بك في TS Rating",hi:"TS Rating में आपका स्वागत है",ko:"TS Rating에 오신 것을 환영합니다",tr:"TS Rating'e hoş geldiniz",pl:"Witaj w TS Rating",sv:"Välkommen till TS Rating",id:"Selamat datang di TS Rating",th:"ยินดีต้อนรับสู่ TS Rating"},
"Error al iniciar sesión":{en:"Error signing in",pt:"Erro ao entrar",fr:"Erreur de connexion",de:"Fehler bei der Anmeldung",it:"Errore di accesso",nl:"Fout bij inloggen",ja:"ログインエラー",zh:"登录出错",ru:"Ошибка входа",ar:"خطأ في تسجيل الدخول",hi:"लॉगिन में त्रुटि",ko:"로그인 오류",tr:"Giriş hatası",pl:"Błąd logowania",sv:"Inloggningsfel",id:"Error saat masuk",th:"เกิดข้อผิดพลาดในการเข้าสู่ระบบ"},
"Error al registrarse":{en:"Error registering",pt:"Erro ao registrar",fr:"Erreur d'inscription",de:"Fehler bei der Registrierung",it:"Errore di registrazione",nl:"Fout bij registratie",ja:"登録エラー",zh:"注册出错",ru:"Ошибка регистрации",ar:"خطأ في التسجيل",hi:"पंजीकरण में त्रुटि",ko:"회원가입 오류",tr:"Kayıt hatası",pl:"Błąd rejestracji",sv:"Registreringsfel",id:"Error saat mendaftar",th:"เกิดข้อผิดพลาดในการสมัคร"},
"Error inesperado":{en:"Unexpected error",pt:"Erro inesperado",fr:"Erreur inattendue",de:"Unerwarteter Fehler",it:"Errore imprevisto",nl:"Onverwachte fout",ja:"予期しないエラー",zh:"意外错误",ru:"Неожиданная ошибка",ar:"خطأ غير متوقع",hi:"अप्रत्याशित त्रुटि",ko:"예기치 않은 오류",tr:"Beklenmeyen hata",pl:"Nieoczekiwany błąd",sv:"Oväntat fel",id:"Error tidak terduga",th:"ข้อผิดพลาดที่ไม่คาดคิด"},
"Las contraseñas no coinciden":{en:"Passwords do not match",pt:"As senhas não coincidem",fr:"Les mots de passe ne correspondent pas",de:"Passwörter stimmen nicht überein",it:"Le password non corrispondono",nl:"Wachtwoorden komen niet overeen",ja:"パスワードが一致しません",zh:"密码不匹配",ru:"Пароли не совпадают",ar:"كلمات المرور غير متطابقة",hi:"पासवर्ड मेल नहीं खाते",ko:"비밀번호가 일치하지 않습니다",tr:"Şifreler eşleşmiyor",pl:"Hasła się nie zgadzają",sv:"Lösenorden matchar inte",id:"Kata sandi tidak cocok",th:"รหัสผ่านไม่ตรงกัน"},
"La contraseña debe tener al menos 6 caracteres":{en:"Password must be at least 6 characters",pt:"A senha deve ter pelo menos 6 caracteres",fr:"Le mot de passe doit contenir au moins 6 caractères",de:"Passwort muss mindestens 6 Zeichen lang sein",it:"La password deve avere almeno 6 caratteri",nl:"Wachtwoord moet minstens 6 tekens bevatten",ja:"パスワードは6文字以上必要です",zh:"密码至少需要6个字符",ru:"Пароль должен содержать не менее 6 символов",ar:"يجب أن تكون كلمة المرور 6 أحرف على الأقل",hi:"पासवर्ड कम से कम 6 अक्षर का होना चाहिए",ko:"비밀번호는 최소 6자 이상이어야 합니다",tr:"Şifre en az 6 karakter olmalıdır",pl:"Hasło musi mieć co najmniej 6 znaków",sv:"Lösenordet måste vara minst 6 tecken",id:"Kata sandi harus minimal 6 karakter",th:"รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร"},
"Debes aceptar las reglas del foro":{en:"You must accept the forum rules",pt:"Você deve aceitar as regras do fórum",fr:"Vous devez accepter les règles du forum",de:"Sie müssen die Forenregeln akzeptieren",it:"Devi accettare le regole del forum",nl:"Je moet de forumregels accepteren",ja:"フォーラムルールに同意してください",zh:"您必须接受论坛规则",ru:"Необходимо принять правила форума",ar:"يجب قبول قواعد المنتدى",hi:"आपको फ़ोरम नियम स्वीकार करने होंगे",ko:"포럼 규칙에 동의해야 합니다",tr:"Forum kurallarını kabul etmelisiniz",pl:"Musisz zaakceptować regulamin forum",sv:"Du måste acceptera forumreglerna",id:"Anda harus menerima aturan forum",th:"คุณต้องยอมรับกฎของฟอรั่ม"},
"Por favor, completa la verificación de seguridad":{en:"Please complete the security verification",pt:"Por favor, complete a verificação de segurança",fr:"Veuillez compléter la vérification de sécurité",de:"Bitte vervollständigen Sie die Sicherheitsüberprüfung",it:"Per favore completa la verifica di sicurezza",nl:"Voltooi de beveiligingsverificatie",ja:"セキュリティ認証を完了してください",zh:"请完成安全验证",ru:"Пожалуйста, пройдите проверку безопасности",ar:"يرجى إكمال التحقق الأمني",hi:"कृपया सुरक्षा सत्यापन पूरा करें",ko:"보안 인증을 완료해주세요",tr:"Lütfen güvenlik doğrulamasını tamamlayın",pl:"Proszę dokończyć weryfikację bezpieczeństwa",sv:"Vänligen slutför säkerhetsverifieringen",id:"Mohon selesaikan verifikasi keamanan",th:"กรุณาทำการยืนยันความปลอดภัยให้เสร็จ"},
"Soy mayor de 18 años y acepto las":{en:"I am over 18 and I accept the",pt:"Tenho mais de 18 anos e aceito as",fr:"J'ai plus de 18 ans et j'accepte les",de:"Ich bin über 18 und akzeptiere die",it:"Ho più di 18 anni e accetto le",nl:"Ik ben ouder dan 18 en accepteer de",ja:"18歳以上であり、以下に同意します",zh:"我已满18岁并接受",ru:"Мне исполнилось 18 лет и я принимаю",ar:"أنا فوق 18 عاماً وأوافق على",hi:"मैं 18 से अधिक उम्र का हूं और स्वीकार करता हूं",ko:"18세 이상이며 다음에 동의합니다",tr:"18 yaşından büyüğüm ve kabul ediyorum",pl:"Mam ponad 18 lat i akceptuję",sv:"Jag är över 18 och accepterar",id:"Saya berusia di atas 18 tahun dan menerima",th:"ฉันอายุมากกว่า 18 ปีและยอมรับ"},
"reglas del foro":{en:"forum rules",pt:"regras do fórum",fr:"règles du forum",de:"Forenregeln",it:"regole del forum",nl:"forumregels",ja:"フォーラムルール",zh:"论坛规则",ru:"правила форума",ar:"قواعد المنتدى",hi:"फ़ोरम नियम",ko:"포럼 규칙",tr:"forum kuralları",pl:"regulamin forum",sv:"forumregler",id:"aturan forum",th:"กฎฟอรั่ม"},

// === PROFILE remaining ===
"Biografía":{en:"Biography",pt:"Biografia",fr:"Biographie",de:"Biografie",it:"Biografia",nl:"Biografie",ja:"自己紹介",zh:"个人简介",ru:"Биография",ar:"السيرة الذاتية",hi:"जीवनी",ko:"자기소개",tr:"Biyografi",pl:"Biografia",sv:"Biografi",id:"Biografi",th:"ประวัติ"},
"Ubicación":{en:"Location",pt:"Localização",fr:"Emplacement",de:"Standort",it:"Posizione",nl:"Locatie",ja:"場所",zh:"位置",ru:"Местоположение",ar:"الموقع",hi:"स्थान",ko:"위치",tr:"Konum",pl:"Lokalizacja",sv:"Plats",id:"Lokasi",th:"ตำแหน่ง"},
"Sitio web":{en:"Website",pt:"Website",fr:"Site web",de:"Website",it:"Sito web",nl:"Website",ja:"ウェブサイト",zh:"网站",ru:"Сайт",ar:"موقع الويب",hi:"वेबसाइट",ko:"웹사이트",tr:"Web sitesi",pl:"Strona www",sv:"Webbplats",id:"Situs web",th:"เว็บไซต์"},
"Redes sociales":{en:"Social media",pt:"Redes sociais",fr:"Réseaux sociaux",de:"Soziale Medien",it:"Social media",nl:"Sociale media",ja:"ソーシャルメディア",zh:"社交媒体",ru:"Соцсети",ar:"وسائل التواصل الاجتماعي",hi:"सोशल मीडिया",ko:"소셜 미디어",tr:"Sosyal medya",pl:"Media społecznościowe",sv:"Sociala medier",id:"Media sosial",th:"โซเชียลมีเดีย"},
"Hilos":{en:"Threads",pt:"Tópicos",fr:"Sujets",de:"Themen",it:"Discussioni",nl:"Onderwerpen",ja:"スレッド",zh:"主题",ru:"Темы",ar:"المواضيع",hi:"थ्रेड",ko:"스레드",tr:"Konular",pl:"Wątki",sv:"Trådar",id:"Thread",th:"กระทู้"},
"Ver perfil":{en:"View profile",pt:"Ver perfil",fr:"Voir le profil",de:"Profil anzeigen",it:"Vedi profilo",nl:"Profiel bekijken",ja:"プロフィールを見る",zh:"查看个人资料",ru:"Просмотр профиля",ar:"عرض الملف الشخصي",hi:"प्रोफ़ाइल देखें",ko:"프로필 보기",tr:"Profili gör",pl:"Zobacz profil",sv:"Visa profil",id:"Lihat profil",th:"ดูโปรไฟล์"},
"Última conexión":{en:"Last seen",pt:"Última conexão",fr:"Dernière connexion",de:"Zuletzt gesehen",it:"Ultimo accesso",nl:"Laatst gezien",ja:"最終接続",zh:"最后在线",ru:"Последний визит",ar:"آخر اتصال",hi:"अंतिम कनेक्शन",ko:"마지막 접속",tr:"Son bağlantı",pl:"Ostatnio online",sv:"Senast sedd",id:"Terakhir online",th:"เชื่อมต่อล่าสุด"},
"Acerca de":{en:"About",pt:"Sobre",fr:"À propos",de:"Über",it:"Informazioni",nl:"Over",ja:"概要",zh:"关于",ru:"О пользователе",ar:"حول",hi:"के बारे में",ko:"소개",tr:"Hakkında",pl:"O mnie",sv:"Om",id:"Tentang",th:"เกี่ยวกับ"},
"Sin actividad reciente":{en:"No recent activity",pt:"Sem atividade recente",fr:"Aucune activité récente",de:"Keine aktuelle Aktivität",it:"Nessuna attività recente",nl:"Geen recente activiteit",ja:"最近のアクティビティはありません",zh:"没有最近活动",ru:"Нет недавней активности",ar:"لا يوجد نشاط حديث",hi:"कोई हालिया गतिविधि नहीं",ko:"최근 활동 없음",tr:"Son aktivite yok",pl:"Brak ostatniej aktywności",sv:"Ingen senaste aktivitet",id:"Tidak ada aktivitas terbaru",th:"ไม่มีกิจกรรมล่าสุด"},
"Hilos creados":{en:"Threads created",pt:"Tópicos criados",fr:"Sujets créés",de:"Erstellte Themen",it:"Discussioni create",nl:"Aangemaakte onderwerpen",ja:"作成したスレッド",zh:"创建的主题",ru:"Созданные темы",ar:"المواضيع المنشأة",hi:"बनाए गए थ्रेड",ko:"작성한 스레드",tr:"Oluşturulan konular",pl:"Utworzone wątki",sv:"Skapade trådar",id:"Thread yang dibuat",th:"กระทู้ที่สร้าง"},
"Aún no ha creado hilos":{en:"No threads created yet",pt:"Ainda não criou tópicos",fr:"Aucun sujet créé",de:"Noch keine Themen erstellt",it:"Nessuna discussione creata",nl:"Nog geen onderwerpen aangemaakt",ja:"まだスレッドを作成していません",zh:"尚未创建主题",ru:"Пока не создано тем",ar:"لم ينشئ مواضيع بعد",hi:"अभी तक कोई थ्रेड नहीं बनाया",ko:"아직 스레드를 만들지 않았습니다",tr:"Henüz konu oluşturmadı",pl:"Nie utworzono jeszcze wątków",sv:"Har inte skapat några trådar ännu",id:"Belum membuat thread",th:"ยังไม่ได้สร้างกระทู้"},
"Sin publicaciones":{en:"No posts",pt:"Sem publicações",fr:"Aucun message",de:"Keine Beiträge",it:"Nessun post",nl:"Geen berichten",ja:"投稿なし",zh:"没有帖子",ru:"Нет публикаций",ar:"لا توجد منشورات",hi:"कोई पोस्ट नहीं",ko:"게시물 없음",tr:"Gönderi yok",pl:"Brak postów",sv:"Inga inlägg",id:"Tidak ada postingan",th:"ไม่มีโพสต์"},
"Desconocido":{en:"Unknown",pt:"Desconhecido",fr:"Inconnu",de:"Unbekannt",it:"Sconosciuto",nl:"Onbekend",ja:"不明",zh:"未知",ru:"Неизвестно",ar:"مجهول",hi:"अज्ञात",ko:"알 수 없음",tr:"Bilinmiyor",pl:"Nieznany",sv:"Okänd",id:"Tidak diketahui",th:"ไม่ทราบ"},
"Total de publicaciones":{en:"Total posts",pt:"Total de publicações",fr:"Total de messages",de:"Gesamtbeiträge",it:"Totale post",nl:"Totaal berichten",ja:"総投稿数",zh:"总帖数",ru:"Всего публикаций",ar:"إجمالي المنشورات",hi:"कुल पोस्ट",ko:"총 게시물",tr:"Toplam gönderi",pl:"Łączna liczba postów",sv:"Totalt antal inlägg",id:"Total postingan",th:"โพสต์ทั้งหมด"},
"Puntos":{en:"Points",pt:"Pontos",fr:"Points",de:"Punkte",it:"Punti",nl:"Punten",ja:"ポイント",zh:"积分",ru:"Баллы",ar:"نقاط",hi:"अंक",ko:"포인트",tr:"Puanlar",pl:"Punkty",sv:"Poäng",id:"Poin",th:"คะแนน"},
"Firma":{en:"Signature",pt:"Assinatura",fr:"Signature",de:"Signatur",it:"Firma",nl:"Handtekening",ja:"署名",zh:"签名",ru:"Подпись",ar:"التوقيع",hi:"हस्ताक्षर",ko:"서명",tr:"İmza",pl:"Podpis",sv:"Signatur",id:"Tanda tangan",th:"ลายเซ็น"},
"En":{en:"In",pt:"Em",fr:"Dans",de:"In",it:"In",nl:"In",ja:"内",zh:"在",ru:"В",ar:"في",hi:"में",ko:"에",tr:"İçinde",pl:"W",sv:"I",id:"Di",th:"ใน"},

// === NOTIFICATIONS remaining ===
"{count} sin leer":{en:"{count} unread",pt:"{count} não lidas",fr:"{count} non lues",de:"{count} ungelesen",it:"{count} non lette",nl:"{count} ongelezen",ja:"{count} 件未読",zh:"{count} 条未读",ru:"{count} непрочитанных",ar:"{count} غير مقروءة",hi:"{count} अपठित",ko:"{count} 읽지 않음",tr:"{count} okunmamış",pl:"{count} nieprzeczytanych",sv:"{count} olästa",id:"{count} belum dibaca",th:"{count} ยังไม่อ่าน"},
"Te mencionó":{en:"Mentioned you",pt:"Mencionou você",fr:"Vous a mentionné",de:"Hat dich erwähnt",it:"Ti ha menzionato",nl:"Heeft je vermeld",ja:"あなたをメンションしました",zh:"提到了你",ru:"Упомянул вас",ar:"أشار إليك",hi:"आपका उल्लेख किया",ko:"회원님을 언급했습니다",tr:"Sizi bahsetti",pl:"Wspomniał o Tobie",sv:"Nämnde dig",id:"Menyebut Anda",th:"กล่าวถึงคุณ"},
"Respondió":{en:"Replied",pt:"Respondeu",fr:"A répondu",de:"Hat geantwortet",it:"Ha risposto",nl:"Heeft geantwoord",ja:"返信しました",zh:"回复了",ru:"Ответил",ar:"رد",hi:"जवाब दिया",ko:"답글 남김",tr:"Yanıtladı",pl:"Odpowiedział",sv:"Svarade",id:"Membalas",th:"ตอบกลับ"},
"Te citó":{en:"Quoted you",pt:"Citou você",fr:"Vous a cité",de:"Hat dich zitiert",it:"Ti ha citato",nl:"Heeft je geciteerd",ja:"あなたを引用しました",zh:"引用了你",ru:"Процитировал вас",ar:"اقتبس منك",hi:"आपको उद्धृत किया",ko:"회원님을 인용했습니다",tr:"Sizi alıntıladı",pl:"Zacytował Cię",sv:"Citerade dig",id:"Mengutip Anda",th:"อ้างถึงคุณ"},
"Agradeció tu post":{en:"Thanked your post",pt:"Agradeceu seu post",fr:"A remercié votre message",de:"Hat deinen Beitrag bedankt",it:"Ha ringraziato il tuo post",nl:"Heeft je bericht bedankt",ja:"あなたの投稿に感謝しました",zh:"感谢了你的帖子",ru:"Поблагодарил ваш пост",ar:"شكر منشورك",hi:"आपकी पोस्ट पर धन्यवाद दिया",ko:"회원님의 게시물에 감사",tr:"Gönderinize teşekkür etti",pl:"Podziękował za Twój post",sv:"Tackade för ditt inlägg",id:"Berterima kasih atas postingan Anda",th:"ขอบคุณโพสต์ของคุณ"},
"Reaccionó a tu post":{en:"Reacted to your post",pt:"Reagiu ao seu post",fr:"A réagi à votre message",de:"Hat auf deinen Beitrag reagiert",it:"Ha reagito al tuo post",nl:"Heeft gereageerd op je bericht",ja:"あなたの投稿にリアクションしました",zh:"对你的帖子做出了反应",ru:"Отреагировал на ваш пост",ar:"تفاعل مع منشورك",hi:"आपकी पोस्ट पर प्रतिक्रिया दी",ko:"회원님의 게시물에 반응",tr:"Gönderinize tepki verdi",pl:"Zareagował na Twój post",sv:"Reagerade på ditt inlägg",id:"Bereaksi terhadap postingan Anda",th:"แสดงปฏิกิริยาต่อโพสต์ของคุณ"},
"Nueva insignia":{en:"New badge",pt:"Nova insígnia",fr:"Nouveau badge",de:"Neues Abzeichen",it:"Nuovo badge",nl:"Nieuwe badge",ja:"新しいバッジ",zh:"新徽章",ru:"Новый значок",ar:"شارة جديدة",hi:"नया बैज",ko:"새로운 배지",tr:"Yeni rozet",pl:"Nowa odznaka",sv:"Nytt märke",id:"Lencana baru",th:"ตราใหม่"},
"Cambio de reputación":{en:"Reputation change",pt:"Mudança de reputação",fr:"Changement de réputation",de:"Reputationsänderung",it:"Cambio reputazione",nl:"Reputatiewijziging",ja:"評判の変更",zh:"声誉变化",ru:"Изменение репутации",ar:"تغيير السمعة",hi:"प्रतिष्ठा परिवर्तन",ko:"평판 변동",tr:"İtibar değişikliği",pl:"Zmiana reputacji",sv:"Rykteändring",id:"Perubahan reputasi",th:"การเปลี่ยนแปลงชื่อเสียง"},
"Nuevo mensaje":{en:"New message",pt:"Nova mensagem",fr:"Nouveau message",de:"Neue Nachricht",it:"Nuovo messaggio",nl:"Nieuw bericht",ja:"新着メッセージ",zh:"新消息",ru:"Новое сообщение",ar:"رسالة جديدة",hi:"नया संदेश",ko:"새 메시지",tr:"Yeni mesaj",pl:"Nowa wiadomość",sv:"Nytt meddelande",id:"Pesan baru",th:"ข้อความใหม่"},
"Nueva respuesta en hilo":{en:"New reply in thread",pt:"Nova resposta no tópico",fr:"Nouvelle réponse dans le sujet",de:"Neue Antwort im Thema",it:"Nuova risposta nella discussione",nl:"Nieuw antwoord in onderwerp",ja:"スレッドに新しい返信",zh:"主题有新回复",ru:"Новый ответ в теме",ar:"رد جديد في الموضوع",hi:"थ्रेड में नया उत्तर",ko:"스레드에 새 답글",tr:"Konuda yeni yanıt",pl:"Nowa odpowiedź w wątku",sv:"Nytt svar i tråd",id:"Balasan baru di thread",th:"คำตอบใหม่ในกระทู้"},
"Te sigue":{en:"Follows you",pt:"Segue você",fr:"Vous suit",de:"Folgt dir",it:"Ti segue",nl:"Volgt je",ja:"あなたをフォローしています",zh:"关注了你",ru:"Подписался на вас",ar:"يتابعك",hi:"आपको फ़ॉलो करता है",ko:"회원님을 팔로우합니다",tr:"Sizi takip ediyor",pl:"Obserwuje Cię",sv:"Följer dig",id:"Mengikuti Anda",th:"ติดตามคุณ"},
"Inicia sesión":{en:"Sign in",pt:"Entrar",fr:"Se connecter",de:"Anmelden",it:"Accedi",nl:"Inloggen",ja:"ログイン",zh:"登录",ru:"Войти",ar:"تسجيل الدخول",hi:"लॉगिन करें",ko:"로그인",tr:"Giriş yap",pl:"Zaloguj się",sv:"Logga in",id:"Masuk",th:"เข้าสู่ระบบ"},
"Debes iniciar sesión para ver tus notificaciones":{en:"You must sign in to view your notifications",pt:"Você precisa entrar para ver suas notificações",fr:"Connectez-vous pour voir vos notifications",de:"Melden Sie sich an, um Ihre Benachrichtigungen zu sehen",it:"Accedi per visualizzare le notifiche",nl:"Log in om je meldingen te bekijken",ja:"通知を確認するにはログインしてください",zh:"请登录查看通知",ru:"Войдите, чтобы просмотреть уведомления",ar:"سجل دخولك لرؤية إشعاراتك",hi:"अपनी सूचनाएँ देखने के लिए लॉगिन करें",ko:"알림을 보려면 로그인하세요",tr:"Bildirimlerinizi görmek için giriş yapın",pl:"Zaloguj się, aby zobaczyć powiadomienia",sv:"Logga in för att se dina aviseringar",id:"Masuk untuk melihat notifikasi Anda",th:"เข้าสู่ระบบเพื่อดูการแจ้งเตือนของคุณ"},
"Iniciar Sesión":{en:"Sign In",pt:"Entrar",fr:"Se Connecter",de:"Anmelden",it:"Accedi",nl:"Inloggen",ja:"ログイン",zh:"登录",ru:"Войти",ar:"تسجيل الدخول",hi:"लॉगिन करें",ko:"로그인",tr:"Giriş Yap",pl:"Zaloguj się",sv:"Logga in",id:"Masuk",th:"เข้าสู่ระบบ"},
"Todas":{en:"All",pt:"Todas",fr:"Toutes",de:"Alle",it:"Tutte",nl:"Alle",ja:"すべて",zh:"全部",ru:"Все",ar:"الكل",hi:"सभी",ko:"전체",tr:"Tümü",pl:"Wszystkie",sv:"Alla",id:"Semua",th:"ทั้งหมด"},
"Sin leer":{en:"Unread",pt:"Não lidas",fr:"Non lues",de:"Ungelesen",it:"Non lette",nl:"Ongelezen",ja:"未読",zh:"未读",ru:"Непрочитанные",ar:"غير مقروءة",hi:"अपठित",ko:"읽지 않음",tr:"Okunmamış",pl:"Nieprzeczytane",sv:"Olästa",id:"Belum dibaca",th:"ยังไม่อ่าน"},
"Todas marcadas como leídas":{en:"All marked as read",pt:"Todas marcadas como lidas",fr:"Toutes marquées comme lues",de:"Alle als gelesen markiert",it:"Tutte segnate come lette",nl:"Alle als gelezen gemarkeerd",ja:"すべて既読にしました",zh:"全部标记为已读",ru:"Все отмечены как прочитанные",ar:"تم تحديد الكل كمقروء",hi:"सभी पढ़ा हुआ चिह्नित",ko:"모두 읽음으로 표시됨",tr:"Tümü okundu olarak işaretlendi",pl:"Wszystkie oznaczone jako przeczytane",sv:"Alla markerade som lästa",id:"Semua ditandai dibaca",th:"ทำเครื่องหมายทั้งหมดว่าอ่านแล้ว"},
"Notificación eliminada":{en:"Notification deleted",pt:"Notificação excluída",fr:"Notification supprimée",de:"Benachrichtigung gelöscht",it:"Notifica eliminata",nl:"Melding verwijderd",ja:"通知を削除しました",zh:"通知已删除",ru:"Уведомление удалено",ar:"تم حذف الإشعار",hi:"सूचना हटाई गई",ko:"알림 삭제됨",tr:"Bildirim silindi",pl:"Powiadomienie usunięte",sv:"Avisering borttagen",id:"Notifikasi dihapus",th:"ลบการแจ้งเตือนแล้ว"},
"Marcar como leída":{en:"Mark as read",pt:"Marcar como lida",fr:"Marquer comme lu",de:"Als gelesen markieren",it:"Segna come letto",nl:"Als gelezen markeren",ja:"既読にする",zh:"标记为已读",ru:"Отметить как прочитанное",ar:"تحديد كمقروء",hi:"पढ़ा हुआ चिह्नित करें",ko:"읽음으로 표시",tr:"Okundu işaretle",pl:"Oznacz jako przeczytane",sv:"Markera som läst",id:"Tandai dibaca",th:"ทำเครื่องหมายว่าอ่านแล้ว"},

// === MESSAGES ===
"Mensajes privados":{en:"Private messages",pt:"Mensagens privadas",fr:"Messages privés",de:"Private Nachrichten",it:"Messaggi privati",nl:"Privéberichten",ja:"プライベートメッセージ",zh:"私信",ru:"Личные сообщения",ar:"الرسائل الخاصة",hi:"निजी संदेश",ko:"비공개 메시지",tr:"Özel mesajlar",pl:"Wiadomości prywatne",sv:"Privata meddelanden",id:"Pesan pribadi",th:"ข้อความส่วนตัว"},
"No tienes mensajes todavía":{en:"You have no messages yet",pt:"Você ainda não tem mensagens",fr:"Vous n'avez pas encore de messages",de:"Sie haben noch keine Nachrichten",it:"Non hai ancora messaggi",nl:"Je hebt nog geen berichten",ja:"メッセージはまだありません",zh:"您还没有消息",ru:"У вас пока нет сообщений",ar:"لا توجد رسائل بعد",hi:"अभी तक कोई संदेश नहीं",ko:"아직 메시지가 없습니다",tr:"Henüz mesajınız yok",pl:"Nie masz jeszcze wiadomości",sv:"Du har inga meddelanden ännu",id:"Anda belum memiliki pesan",th:"ยังไม่มีข้อความ"},
"Escribe un mensaje...":{en:"Write a message...",pt:"Escreva uma mensagem...",fr:"Écrivez un message...",de:"Nachricht schreiben...",it:"Scrivi un messaggio...",nl:"Schrijf een bericht...",ja:"メッセージを書く...",zh:"写消息...",ru:"Напишите сообщение...",ar:"اكتب رسالة...",hi:"संदेश लिखें...",ko:"메시지를 입력하세요...",tr:"Bir mesaj yazın...",pl:"Napisz wiadomość...",sv:"Skriv ett meddelande...",id:"Tulis pesan...",th:"เขียนข้อความ..."},

// === COMMON remaining ===
"Tienda":{en:"Store",pt:"Loja",fr:"Boutique",de:"Shop",it:"Negozio",nl:"Winkel",ja:"ストア",zh:"商店",ru:"Магазин",ar:"المتجر",hi:"दुकान",ko:"스토어",tr:"Mağaza",pl:"Sklep",sv:"Butik",id:"Toko",th:"ร้านค้า"},

// === POST remaining ===
"Posts":{en:"Posts",pt:"Posts",fr:"Messages",de:"Beiträge",it:"Post",nl:"Berichten",ja:"投稿",zh:"帖子",ru:"Сообщения",ar:"المشاركات",hi:"पोस्ट",ko:"게시물",tr:"Gönderiler",pl:"Posty",sv:"Inlägg",id:"Postingan",th:"โพสต์"},
"Registro":{en:"Joined",pt:"Registro",fr:"Inscription",de:"Registriert",it:"Registrato",nl:"Registratie",ja:"登録",zh:"注册",ru:"Регистрация",ar:"التسجيل",hi:"पंजीकरण",ko:"가입",tr:"Kayıt",pl:"Rejestracja",sv:"Registrerad",id:"Registrasi",th:"สมัคร"},
"Editado":{en:"Edited",pt:"Editado",fr:"Modifié",de:"Bearbeitet",it:"Modificato",nl:"Bewerkt",ja:"編集済み",zh:"已编辑",ru:"Отредактировано",ar:"تم التعديل",hi:"संपादित",ko:"편집됨",tr:"Düzenlendi",pl:"Edytowano",sv:"Redigerad",id:"Diedit",th:"แก้ไขแล้ว"},

// === RATINGS ===
"No me gusta":{en:"Dislike",pt:"Não gostei",fr:"Je n'aime pas",de:"Gefällt mir nicht",it:"Non mi piace",nl:"Vind ik niet leuk",ja:"よくない",zh:"不喜欢",ru:"Не нравится",ar:"لم يعجبني",hi:"नापसंद",ko:"싫어요",tr:"Beğenme",pl:"Nie lubię",sv:"Ogillar",id:"Tidak suka",th:"ไม่ชอบ"},
"Calificar":{en:"Rate",pt:"Avaliar",fr:"Évaluer",de:"Bewerten",it:"Valuta",nl:"Beoordelen",ja:"評価",zh:"评分",ru:"Оценить",ar:"تقييم",hi:"रेट करें",ko:"평가",tr:"Puanla",pl:"Oceń",sv:"Betygsätt",id:"Beri nilai",th:"ให้คะแนน"},

// === FOLLOW remaining ===
"Ahora sigues a":{en:"You now follow",pt:"Agora segue",fr:"Vous suivez maintenant",de:"Du folgst jetzt",it:"Ora segui",nl:"Je volgt nu",ja:"フォローしました",zh:"你现在关注了",ru:"Вы подписались на",ar:"أنت الآن تتابع",hi:"अब आप फ़ॉलो कर रहे हैं",ko:"팔로우 중",tr:"Artık takip ediyorsunuz",pl:"Teraz obserwujesz",sv:"Du följer nu",id:"Anda sekarang mengikuti",th:"คุณกำลังติดตาม"},
"Dejaste de seguir a":{en:"You unfollowed",pt:"Deixou de seguir",fr:"Vous ne suivez plus",de:"Du folgst nicht mehr",it:"Hai smesso di seguire",nl:"Je volgt niet meer",ja:"フォロー解除しました",zh:"你取消了关注",ru:"Вы отписались от",ar:"ألغيت متابعة",hi:"अनफ़ॉलो कर दिया",ko:"팔로우 취소",tr:"Takibi bıraktınız",pl:"Przestałeś obserwować",sv:"Du slutade följa",id:"Anda berhenti mengikuti",th:"คุณเลิกติดตาม"},
"Inicia sesión para seguir usuarios":{en:"Sign in to follow users",pt:"Entre para seguir usuários",fr:"Connectez-vous pour suivre des utilisateurs",de:"Melden Sie sich an, um Benutzern zu folgen",it:"Accedi per seguire gli utenti",nl:"Log in om gebruikers te volgen",ja:"ユーザーをフォローするにはログインしてください",zh:"登录以关注用户",ru:"Войдите, чтобы подписаться",ar:"سجل دخولك لمتابعة المستخدمين",hi:"उपयोगकर्ताओं को फ़ॉलो करने के लिए लॉगिन करें",ko:"사용자를 팔로우하려면 로그인하세요",tr:"Kullanıcıları takip etmek için giriş yapın",pl:"Zaloguj się, aby obserwować użytkowników",sv:"Logga in för att följa användare",id:"Masuk untuk mengikuti pengguna",th:"เข้าสู่ระบบเพื่อติดตามผู้ใช้"},
"No puedes seguirte a ti mismo":{en:"You cannot follow yourself",pt:"Você não pode seguir a si mesmo",fr:"Vous ne pouvez pas vous suivre",de:"Sie können sich nicht selbst folgen",it:"Non puoi seguire te stesso",nl:"Je kunt jezelf niet volgen",ja:"自分自身をフォローすることはできません",zh:"你不能关注自己",ru:"Нельзя подписаться на себя",ar:"لا يمكنك متابعة نفسك",hi:"आप स्वयं को फ़ॉलो नहीं कर सकते",ko:"자신을 팔로우할 수 없습니다",tr:"Kendinizi takip edemezsiniz",pl:"Nie możesz obserwować siebie",sv:"Du kan inte följa dig själv",id:"Anda tidak bisa mengikuti diri sendiri",th:"คุณไม่สามารถติดตามตัวเองได้"},

// === PROFILESTATS remaining ===
// "Posts" and "Hilos" already defined above
};

const targetLangs = ['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];

for (const lang of targetLangs) {
  const filePath = path.join(messagesDir, `${lang}.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const dataFlat = flatten(data);
  let changed = 0;

  for (const key in esFlat) {
    const esValue = esFlat[key];
    const currentValue = dataFlat[key];
    if (currentValue === undefined || currentValue === esValue) {
      const t = T[esValue];
      if (t && t[lang]) {
        dataFlat[key] = t[lang];
        changed++;
      }
    }
  }

  if (changed > 0) {
    const result = unflatten(dataFlat);
    fs.writeFileSync(filePath, JSON.stringify(result, null, 2) + '\n', 'utf8');
    console.log(`${lang.toUpperCase()}: Applied ${changed} translations`);
  } else {
    console.log(`${lang.toUpperCase()}: No changes needed`);
  }
}

console.log('\nBatch 2 done!');
