const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
"publicidad.title":{en:"Buy Advertising",pt:"Comprar Publicidade",fr:"Acheter de la Publicité",de:"Werbung Kaufen",it:"Acquista Pubblicità",nl:"Advertentie Kopen",ja:"広告を購入",zh:"购买广告",ru:"Купить рекламу",ar:"شراء إعلان",hi:"विज्ञापन खरीदें",ko:"광고 구매",tr:"Reklam Satın Al",pl:"Kup Reklamę",sv:"Köp Annonsering",id:"Beli Iklan",th:"ซื้อโฆษณา"},
"publicidad.subtitle":{en:"Choose where you want your banner to appear on TS Rating.",pt:"Escolha onde deseja que seu banner apareça no TS Rating.",fr:"Choisissez où vous souhaitez que votre bannière apparaisse sur TS Rating.",de:"Wählen Sie, wo Ihr Banner auf TS Rating erscheinen soll.",it:"Scegli dove vuoi che appaia il tuo banner su TS Rating.",nl:"Kies waar je banner moet verschijnen op TS Rating.",ja:"TS Ratingでバナーを表示する場所を選択してください。",zh:"选择您希望横幅在TS Rating上显示的位置。",ru:"Выберите, где вы хотите разместить баннер на TS Rating.",ar:"اختر أين تريد أن يظهر إعلانك على TS Rating.",hi:"चुनें कि आप TS Rating पर अपना बैनर कहाँ दिखाना चाहते हैं।",ko:"TS Rating에서 배너가 표시될 위치를 선택하세요.",tr:"Banner'ınızın TS Rating'de nerede görüneceğini seçin.",pl:"Wybierz, gdzie chcesz wyświetlać baner na TS Rating.",sv:"Välj var du vill att din banner ska visas på TS Rating.",id:"Pilih di mana Anda ingin banner Anda muncul di TS Rating.",th:"เลือกตำแหน่งที่คุณต้องการให้แบนเนอร์ปรากฏบน TS Rating"},
"publicidad.step1Title":{en:"Select the Zone",pt:"Selecione a Zona",fr:"Sélectionnez la Zone",de:"Zone auswählen",it:"Seleziona la Zona",nl:"Selecteer de Zone",ja:"ゾーンを選択",zh:"选择区域",ru:"Выберите зону",ar:"اختر المنطقة",hi:"ज़ोन चुनें",ko:"지역 선택",tr:"Bölge Seçin",pl:"Wybierz Strefę",sv:"Välj Zon",id:"Pilih Zona",th:"เลือกโซน"},
"publicidad.step1Desc":{en:"Choose in which country or city you want your banner to appear.",pt:"Escolha em qual país ou cidade deseja que seu banner apareça.",fr:"Choisissez dans quel pays ou ville vous souhaitez que votre bannière apparaisse.",de:"Wählen Sie, in welchem Land oder welcher Stadt Ihr Banner erscheinen soll.",it:"Scegli in quale paese o città vuoi che appaia il tuo banner.",nl:"Kies in welk land of welke stad je banner moet verschijnen.",ja:"バナーを表示する国または都市を選択してください。",zh:"选择您希望横幅显示的国家或城市。",ru:"Выберите, в какой стране или городе должен отображаться ваш баннер.",ar:"اختر في أي بلد أو مدينة تريد أن يظهر إعلانك.",hi:"चुनें कि आप किस देश या शहर में अपना बैनर दिखाना चाहते हैं।",ko:"배너가 표시될 국가 또는 도시를 선택하세요.",tr:"Banner'ınızın hangi ülke veya şehirde görüneceğini seçin.",pl:"Wybierz, w jakim kraju lub mieście ma się wyświetlać baner.",sv:"Välj i vilket land eller stad du vill att din banner ska visas.",id:"Pilih di negara atau kota mana Anda ingin banner Anda muncul.",th:"เลือกประเทศหรือเมืองที่คุณต้องการให้แบนเนอร์ปรากฏ"},
"publicidad.selectCountry":{en:"Select a country",pt:"Selecione um país",fr:"Sélectionnez un pays",de:"Land auswählen",it:"Seleziona un paese",nl:"Selecteer een land",ja:"国を選択",zh:"选择国家",ru:"Выберите страну",ar:"اختر بلداً",hi:"देश चुनें",ko:"국가 선택",tr:"Ülke seçin",pl:"Wybierz kraj",sv:"Välj land",id:"Pilih negara",th:"เลือกประเทศ"},
"publicidad.zoneType":{en:"Zone type",pt:"Tipo de zona",fr:"Type de zone",de:"Zonentyp",it:"Tipo di zona",nl:"Zonetype",ja:"ゾーンタイプ",zh:"区域类型",ru:"Тип зоны",ar:"نوع المنطقة",hi:"ज़ोन प्रकार",ko:"지역 유형",tr:"Bölge türü",pl:"Typ strefy",sv:"Zontyp",id:"Jenis zona",th:"ประเภทโซน"},
"publicidad.homeCountry":{en:"Home + Country",pt:"Home + País",fr:"Accueil + Pays",de:"Startseite + Land",it:"Home + Paese",nl:"Home + Land",ja:"ホーム + 国",zh:"首页 + 国家",ru:"Главная + Страна",ar:"الرئيسية + البلد",hi:"होम + देश",ko:"홈 + 국가",tr:"Ana Sayfa + Ülke",pl:"Strona główna + Kraj",sv:"Hem + Land",id:"Beranda + Negara",th:"หน้าแรก + ประเทศ"},
"publicidad.homeCountryDesc":{en:"Appears on the homepage and the selected country page.",pt:"Aparece na página principal e na página do país selecionado.",fr:"Apparaît sur la page d'accueil et la page du pays sélectionné.",de:"Erscheint auf der Startseite und der ausgewählten Länderseite.",it:"Appare nella pagina principale e nella pagina del paese selezionato.",nl:"Verschijnt op de startpagina en de geselecteerde landpagina.",ja:"ホームページと選択した国のページに表示されます。",zh:"显示在首页和所选国家页面上。",ru:"Отображается на главной странице и странице выбранной страны.",ar:"يظهر في الصفحة الرئيسية وصفحة البلد المحدد.",hi:"मुख्य पृष्ठ और चयनित देश पृष्ठ पर दिखाई देता है।",ko:"홈페이지와 선택한 국가 페이지에 표시됩니다.",tr:"Ana sayfada ve seçili ülke sayfasında görünür.",pl:"Wyświetla się na stronie głównej i stronie wybranego kraju.",sv:"Visas på startsidan och den valda landssidan.",id:"Muncul di halaman utama dan halaman negara yang dipilih.",th:"แสดงบนหน้าแรกและหน้าประเทศที่เลือก"},
"publicidad.highVisibility":{en:"Higher visibility",pt:"Maior visibilidade",fr:"Plus de visibilité",de:"Höhere Sichtbarkeit",it:"Maggiore visibilità",nl:"Hogere zichtbaarheid",ja:"高い可視性",zh:"更高可见度",ru:"Высокая видимость",ar:"رؤية أعلى",hi:"अधिक दृश्यता",ko:"높은 가시성",tr:"Daha yüksek görünürlük",pl:"Wyższa widoczność",sv:"Högre synlighet",id:"Visibilitas lebih tinggi",th:"การมองเห็นสูงขึ้น"},
"publicidad.cityRegion":{en:"City / Region",pt:"Cidade / Região",fr:"Ville / Région",de:"Stadt / Region",it:"Città / Regione",nl:"Stad / Regio",ja:"都市 / 地域",zh:"城市 / 地区",ru:"Город / Регион",ar:"المدينة / المنطقة",hi:"शहर / क्षेत्र",ko:"도시 / 지역",tr:"Şehir / Bölge",pl:"Miasto / Region",sv:"Stad / Region",id:"Kota / Wilayah",th:"เมือง / ภูมิภาค"},
"publicidad.cityRegionDesc":{en:"Appears only in the selected city/region forum.",pt:"Aparece apenas no fórum da cidade/região selecionada.",fr:"Apparaît uniquement dans le forum de la ville/région sélectionnée.",de:"Erscheint nur im Forum der ausgewählten Stadt/Region.",it:"Appare solo nel forum della città/regione selezionata.",nl:"Verschijnt alleen in het geselecteerde stad/regio forum.",ja:"選択した都市/地域のフォーラムにのみ表示されます。",zh:"仅显示在所选城市/地区论坛中。",ru:"Отображается только на форуме выбранного города/региона.",ar:"يظهر فقط في منتدى المدينة/المنطقة المحددة.",hi:"केवल चयनित शहर/क्षेत्र फ़ोरम में दिखाई देता है।",ko:"선택한 도시/지역 포럼에만 표시됩니다.",tr:"Yalnızca seçili şehir/bölge forumunda görünür.",pl:"Wyświetla się tylko na forum wybranego miasta/regionu.",sv:"Visas endast i det valda stad/regionforumet.",id:"Muncul hanya di forum kota/wilayah yang dipilih.",th:"แสดงเฉพาะในฟอรั่มเมือง/ภูมิภาคที่เลือก"},
"publicidad.moreAffordable":{en:"More affordable",pt:"Mais econômico",fr:"Plus abordable",de:"Günstiger",it:"Più economico",nl:"Voordeliger",ja:"お手頃価格",zh:"更实惠",ru:"Более доступно",ar:"أقل تكلفة",hi:"अधिक किफायती",ko:"더 저렴",tr:"Daha uygun fiyat",pl:"Bardziej przystępne",sv:"Mer prisvärt",id:"Lebih terjangkau",th:"ราคาย่อมเยาว์กว่า"},
"publicidad.selectCity":{en:"Select a city",pt:"Selecione uma cidade",fr:"Sélectionnez une ville",de:"Stadt auswählen",it:"Seleziona una città",nl:"Selecteer een stad",ja:"都市を選択",zh:"选择城市",ru:"Выберите город",ar:"اختر مدينة",hi:"शहर चुनें",ko:"도시 선택",tr:"Şehir seçin",pl:"Wybierz miasto",sv:"Välj stad",id:"Pilih kota",th:"เลือกเมือง"},
"publicidad.noRegions":{en:"This country does not have cities/regions available yet.",pt:"Este país ainda não tem cidades/regiões disponíveis.",fr:"Ce pays n'a pas encore de villes/régions disponibles.",de:"Dieses Land hat noch keine verfügbaren Städte/Regionen.",it:"Questo paese non ha ancora città/regioni disponibili.",nl:"Dit land heeft nog geen beschikbare steden/regio's.",ja:"この国にはまだ利用可能な都市/地域がありません。",zh:"该国家尚无可用城市/地区。",ru:"В этой стране пока нет доступных городов/регионов.",ar:"هذا البلد لا يحتوي على مدن/مناطق متاحة بعد.",hi:"इस देश में अभी शहर/क्षेत्र उपलब्ध नहीं हैं।",ko:"이 국가에는 아직 사용 가능한 도시/지역이 없습니다.",tr:"Bu ülkede henüz mevcut şehir/bölge yok.",pl:"Ten kraj nie ma jeszcze dostępnych miast/regionów.",sv:"Detta land har ännu inga tillgängliga städer/regioner.",id:"Negara ini belum memiliki kota/wilayah yang tersedia.",th:"ประเทศนี้ยังไม่มีเมือง/ภูมิภาคที่พร้อมใช้งาน"},
"publicidad.step2Title":{en:"Format and Position",pt:"Formato e Posição",fr:"Format et Position",de:"Format und Position",it:"Formato e Posizione",nl:"Formaat en Positie",ja:"フォーマットと位置",zh:"格式和位置",ru:"Формат и Позиция",ar:"الشكل والموقع",hi:"प्रारूप और स्थिति",ko:"형식 및 위치",tr:"Format ve Konum",pl:"Format i Pozycja",sv:"Format och Position",id:"Format dan Posisi",th:"รูปแบบและตำแหน่ง"},
"publicidad.step2Desc":{en:"Choose the banner size and where you want it displayed.",pt:"Escolha o tamanho do banner e onde deseja exibi-lo.",fr:"Choisissez la taille de la bannière et où vous souhaitez l'afficher.",de:"Wählen Sie die Bannergröße und wo es angezeigt werden soll.",it:"Scegli la dimensione del banner e dove vuoi visualizzarlo.",nl:"Kies de bannergrootte en waar je het wilt weergeven.",ja:"バナーのサイズと表示位置を選択してください。",zh:"选择横幅尺寸和显示位置。",ru:"Выберите размер баннера и место отображения.",ar:"اختر حجم الإعلان وأين تريد عرضه.",hi:"बैनर का आकार और प्रदर्शन स्थान चुनें।",ko:"배너 크기와 표시 위치를 선택하세요.",tr:"Banner boyutunu ve nerede gösterileceğini seçin.",pl:"Wybierz rozmiar banera i miejsce wyświetlania.",sv:"Välj bannerstorlek och var du vill att den ska visas.",id:"Pilih ukuran banner dan di mana Anda ingin menampilkannya.",th:"เลือกขนาดแบนเนอร์และตำแหน่งที่ต้องการแสดง"},
"publicidad.bannerFormat":{en:"Banner format",pt:"Formato do banner",fr:"Format de la bannière",de:"Bannerformat",it:"Formato del banner",nl:"Bannerformaat",ja:"バナーフォーマット",zh:"横幅格式",ru:"Формат баннера",ar:"شكل الإعلان",hi:"बैनर प्रारूप",ko:"배너 형식",tr:"Banner formatı",pl:"Format banera",sv:"Bannerformat",id:"Format banner",th:"รูปแบบแบนเนอร์"},
"publicidad.pagePosition":{en:"Page position",pt:"Posição na página",fr:"Position sur la page",de:"Seitenposition",it:"Posizione nella pagina",nl:"Paginapositie",ja:"ページ位置",zh:"页面位置",ru:"Позиция на странице",ar:"موقع الصفحة",hi:"पृष्ठ स्थिति",ko:"페이지 위치",tr:"Sayfa konumu",pl:"Pozycja na stronie",sv:"Sidposition",id:"Posisi halaman",th:"ตำแหน่งในหน้า"},
"publicidad.siteLocation":{en:"Site location:",pt:"Localização no site:",fr:"Emplacement sur le site :",de:"Standort auf der Seite:",it:"Posizione sul sito:",nl:"Locatie op de site:",ja:"サイト上の位置：",zh:"站点位置：",ru:"Расположение на сайте:",ar:"الموقع على الصفحة:",hi:"साइट स्थान:",ko:"사이트 위치:",tr:"Site konumu:",pl:"Lokalizacja na stronie:",sv:"Plats på sidan:",id:"Lokasi situs:",th:"ตำแหน่งบนเว็บไซต์:"},
"publicidad.yourBanner":{en:"YOUR BANNER",pt:"SEU BANNER",fr:"VOTRE BANNIÈRE",de:"IHR BANNER",it:"IL TUO BANNER",nl:"JOUW BANNER",ja:"あなたのバナー",zh:"您的横幅",ru:"ВАШ БАННЕР",ar:"إعلانك",hi:"आपका बैनर",ko:"내 배너",tr:"BANNER'INIZ",pl:"TWÓJ BANER",sv:"DIN BANNER",id:"BANNER ANDA",th:"แบนเนอร์ของคุณ"},
"publicidad.contentArea":{en:"CONTENT",pt:"CONTEÚDO",fr:"CONTENU",de:"INHALT",it:"CONTENUTO",nl:"INHOUD",ja:"コンテンツ",zh:"内容",ru:"КОНТЕНТ",ar:"المحتوى",hi:"सामग्री",ko:"콘텐츠",tr:"İÇERİK",pl:"TREŚĆ",sv:"INNEHÅLL",id:"KONTEN",th:"เนื้อหา"},
"publicidad.step3Title":{en:"Dates and Duration",pt:"Datas e Duração",fr:"Dates et Durée",de:"Datum und Dauer",it:"Date e Durata",nl:"Datums en Duur",ja:"日付と期間",zh:"日期和时长",ru:"Даты и Длительность",ar:"التواريخ والمدة",hi:"तिथि और अवधि",ko:"날짜 및 기간",tr:"Tarih ve Süre",pl:"Daty i Czas Trwania",sv:"Datum och Varaktighet",id:"Tanggal dan Durasi",th:"วันที่และระยะเวลา"},
"publicidad.step3Desc":{en:"Select when you want to start and the ad duration.",pt:"Selecione quando deseja iniciar e a duração do anúncio.",fr:"Sélectionnez quand vous souhaitez commencer et la durée de l'annonce.",de:"Wählen Sie den Starttermin und die Anzeigendauer.",it:"Seleziona quando vuoi iniziare e la durata dell'annuncio.",nl:"Selecteer wanneer je wilt starten en de advertentieduur.",ja:"開始時期と広告の期間を選択してください。",zh:"选择开始时间和广告时长。",ru:"Выберите дату начала и продолжительность рекламы.",ar:"حدد موعد البدء ومدة الإعلان.",hi:"प्रारंभ तिथि और विज्ञापन अवधि चुनें।",ko:"시작 날짜와 광고 기간을 선택하세요.",tr:"Ne zaman başlamak istediğinizi ve reklam süresini seçin.",pl:"Wybierz datę rozpoczęcia i czas trwania reklamy.",sv:"Välj startdatum och annonsens varaktighet.",id:"Pilih kapan Anda ingin memulai dan durasi iklan.",th:"เลือกวันเริ่มต้นและระยะเวลาโฆษณา"},
"publicidad.loadingAvailability":{en:"Loading availability...",pt:"Carregando disponibilidade...",fr:"Chargement de la disponibilité...",de:"Verfügbarkeit wird geladen...",it:"Caricamento disponibilità...",nl:"Beschikbaarheid laden...",ja:"空き状況を読み込み中...",zh:"正在加载可用性...",ru:"Загрузка доступности...",ar:"جاري تحميل التوفر...",hi:"उपलब्धता लोड हो रही है...",ko:"가용성 로딩 중...",tr:"Müsaitlik yükleniyor...",pl:"Ładowanie dostępności...",sv:"Laddar tillgänglighet...",id:"Memuat ketersediaan...",th:"กำลังโหลดความพร้อม..."},
"publicidad.datesReserved":{en:"Dates already reserved:",pt:"Datas já reservadas:",fr:"Dates déjà réservées :",de:"Bereits reservierte Termine:",it:"Date già prenotate:",nl:"Al gereserveerde datums:",ja:"予約済みの日付：",zh:"已预订的日期：",ru:"Уже забронированные даты:",ar:"تواريخ محجوزة بالفعل:",hi:"पहले से आरक्षित तिथियाँ:",ko:"이미 예약된 날짜:",tr:"Zaten rezerve edilen tarihler:",pl:"Już zarezerwowane daty:",sv:"Redan reserverade datum:",id:"Tanggal yang sudah dipesan:",th:"วันที่จองแล้ว:"},
"publicidad.toDate":{en:"to",pt:"até",fr:"au",de:"bis",it:"al",nl:"tot",ja:"まで",zh:"至",ru:"до",ar:"إلى",hi:"तक",ko:"까지",tr:"tarihine",pl:"do",sv:"till",id:"hingga",th:"ถึง"},
"publicidad.nextAvailability":{en:"Next availability:",pt:"Próxima disponibilidade:",fr:"Prochaine disponibilité :",de:"Nächste Verfügbarkeit:",it:"Prossima disponibilità:",nl:"Volgende beschikbaarheid:",ja:"次の空き：",zh:"下一个可用日期：",ru:"Следующая доступность:",ar:"التوفر التالي:",hi:"अगली उपलब्धता:",ko:"다음 가용 날짜:",tr:"Sonraki müsaitlik:",pl:"Następna dostępność:",sv:"Nästa tillgänglighet:",id:"Ketersediaan berikutnya:",th:"ช่วงว่างถัดไป:"},
"publicidad.nextAvailabilityDesc":{en:"You can book starting from this date. Your banner will be activated automatically at the start.",pt:"Você pode reservar a partir desta data. Seu banner será ativado automaticamente no início.",fr:"Vous pouvez réserver à partir de cette date. Votre bannière sera activée automatiquement au début.",de:"Sie können ab diesem Datum buchen. Ihr Banner wird automatisch aktiviert.",it:"Puoi prenotare a partire da questa data. Il tuo banner sarà attivato automaticamente all'inizio.",nl:"Je kunt boeken vanaf deze datum. Je banner wordt automatisch geactiveerd.",ja:"この日付から予約できます。バナーは開始時に自動的に有効化されます。",zh:"您可以从此日期开始预订。您的横幅将在开始时自动激活。",ru:"Вы можете бронировать с этой даты. Ваш баннер будет активирован автоматически.",ar:"يمكنك الحجز ابتداءً من هذا التاريخ. سيتم تفعيل إعلانك تلقائياً.",hi:"आप इस तिथि से बुकिंग कर सकते हैं। आपका बैनर शुरू में स्वचालित रूप से सक्रिय हो जाएगा।",ko:"이 날짜부터 예약할 수 있습니다. 배너는 시작 시 자동으로 활성화됩니다.",tr:"Bu tarihten itibaren rezervasyon yapabilirsiniz. Banner'ınız başlangıçta otomatik olarak etkinleştirilecek.",pl:"Możesz rezerwować od tej daty. Twój baner zostanie automatycznie aktywowany.",sv:"Du kan boka från detta datum. Din banner aktiveras automatiskt vid start.",id:"Anda dapat memesan mulai dari tanggal ini. Banner Anda akan diaktifkan secara otomatis.",th:"คุณสามารถจองได้ตั้งแต่วันนี้ แบนเนอร์ของคุณจะเปิดใช้งานโดยอัตโนมัติ"},
"publicidad.useThisDate":{en:"Use this date as start",pt:"Usar esta data como início",fr:"Utiliser cette date comme début",de:"Dieses Datum als Start verwenden",it:"Usa questa data come inizio",nl:"Gebruik deze datum als start",ja:"この日付を開始日として使用",zh:"使用此日期作为开始",ru:"Использовать эту дату как начало",ar:"استخدم هذا التاريخ كبداية",hi:"इस तिथि को प्रारंभ के रूप में उपयोग करें",ko:"이 날짜를 시작일로 사용",tr:"Bu tarihi başlangıç olarak kullan",pl:"Użyj tej daty jako początek",sv:"Använd detta datum som start",id:"Gunakan tanggal ini sebagai awal",th:"ใช้วันที่นี้เป็นวันเริ่มต้น"},
"publicidad.available":{en:"Available",pt:"Disponível",fr:"Disponible",de:"Verfügbar",it:"Disponibile",nl:"Beschikbaar",ja:"利用可能",zh:"可用",ru:"Доступно",ar:"متاح",hi:"उपलब्ध",ko:"사용 가능",tr:"Mevcut",pl:"Dostępne",sv:"Tillgänglig",id:"Tersedia",th:"พร้อมใช้งาน"},
"publicidad.availableDesc":{en:"This position is free, you can choose any date!",pt:"Esta posição está livre, você pode escolher qualquer data!",fr:"Cette position est libre, vous pouvez choisir n'importe quelle date !",de:"Diese Position ist frei, Sie können jedes Datum wählen!",it:"Questa posizione è libera, puoi scegliere qualsiasi data!",nl:"Deze positie is vrij, je kunt elke datum kiezen!",ja:"この位置は空いています、任意の日付を選択できます！",zh:"此位置空闲，您可以选择任何日期！",ru:"Эта позиция свободна, вы можете выбрать любую дату!",ar:"هذا الموقع متاح، يمكنك اختيار أي تاريخ!",hi:"यह स्थिति खाली है, आप कोई भी तिथि चुन सकते हैं!",ko:"이 위치는 비어 있습니다. 아무 날짜나 선택하세요!",tr:"Bu konum boş, herhangi bir tarih seçebilirsiniz!",pl:"Ta pozycja jest wolna, możesz wybrać dowolną datę!",sv:"Denna position är ledig, du kan välja vilket datum som helst!",id:"Posisi ini kosong, Anda dapat memilih tanggal apa pun!",th:"ตำแหน่งนี้ว่าง คุณเลือกวันที่ใดก็ได้!"},
"publicidad.startDate":{en:"Start date (available from {date})",pt:"Data de início (disponível a partir de {date})",fr:"Date de début (disponible à partir du {date})",de:"Startdatum (verfügbar ab {date})",it:"Data di inizio (disponibile dal {date})",nl:"Startdatum (beschikbaar vanaf {date})",ja:"開始日（{date}から利用可能）",zh:"开始日期（从{date}起可用）",ru:"Дата начала (доступно с {date})",ar:"تاريخ البدء (متاح من {date})",hi:"प्रारंभ तिथि ({date} से उपलब्ध)",ko:"시작 날짜 ({date}부터 가능)",tr:"Başlangıç tarihi ({date} tarihinden itibaren)",pl:"Data rozpoczęcia (dostępne od {date})",sv:"Startdatum (tillgängligt från {date})",id:"Tanggal mulai (tersedia dari {date})",th:"วันเริ่มต้น (พร้อมตั้งแต่ {date})"},
"publicidad.dateOccupied":{en:"This date is already reserved.",pt:"Esta data já está reservada.",fr:"Cette date est déjà réservée.",de:"Dieses Datum ist bereits reserviert.",it:"Questa data è già prenotata.",nl:"Deze datum is al gereserveerd.",ja:"この日付はすでに予約されています。",zh:"该日期已被预订。",ru:"Эта дата уже забронирована.",ar:"هذا التاريخ محجوز بالفعل.",hi:"यह तिथि पहले से आरक्षित है।",ko:"이 날짜는 이미 예약되었습니다.",tr:"Bu tarih zaten rezerve edilmiş.",pl:"Ta data jest już zarezerwowana.",sv:"Detta datum är redan reserverat.",id:"Tanggal ini sudah dipesan.",th:"วันที่นี้จองแล้ว"},
"publicidad.durationPrice":{en:"Duration and Price",pt:"Duração e Preço",fr:"Durée et Prix",de:"Dauer und Preis",it:"Durata e Prezzo",nl:"Duur en Prijs",ja:"期間と価格",zh:"时长和价格",ru:"Длительность и Цена",ar:"المدة والسعر",hi:"अवधि और मूल्य",ko:"기간 및 가격",tr:"Süre ve Fiyat",pl:"Czas Trwania i Cena",sv:"Varaktighet och Pris",id:"Durasi dan Harga",th:"ระยะเวลาและราคา"},
"publicidad.days":{en:"days",pt:"dias",fr:"jours",de:"Tage",it:"giorni",nl:"dagen",ja:"日",zh:"天",ru:"дней",ar:"أيام",hi:"दिन",ko:"일",tr:"gün",pl:"dni",sv:"dagar",id:"hari",th:"วัน"},
"publicidad.summary":{en:"Summary:",pt:"Resumo:",fr:"Résumé :",de:"Zusammenfassung:",it:"Riepilogo:",nl:"Samenvatting:",ja:"概要：",zh:"摘要：",ru:"Итого:",ar:"ملخص:",hi:"सारांश:",ko:"요약:",tr:"Özet:",pl:"Podsumowanie:",sv:"Sammanfattning:",id:"Ringkasan:",th:"สรุป:"},
"publicidad.step4Title":{en:"Upload your Banner",pt:"Envie seu Banner",fr:"Téléchargez votre Bannière",de:"Banner hochladen",it:"Carica il tuo Banner",nl:"Upload je Banner",ja:"バナーをアップロード",zh:"上传您的横幅",ru:"Загрузите ваш баннер",ar:"ارفع إعلانك",hi:"अपना बैनर अपलोड करें",ko:"배너 업로드",tr:"Banner'ınızı Yükleyin",pl:"Prześlij swój Baner",sv:"Ladda upp din Banner",id:"Unggah Banner Anda",th:"อัปโหลดแบนเนอร์ของคุณ"},
"publicidad.step4Desc":{en:"The image must be exactly {format} pixels. Formats: JPG, PNG, GIF, WebP (max. 2MB).",pt:"A imagem deve ter exatamente {format} pixels. Formatos: JPG, PNG, GIF, WebP (máx. 2MB).",fr:"L'image doit faire exactement {format} pixels. Formats : JPG, PNG, GIF, WebP (max. 2 Mo).",de:"Das Bild muss genau {format} Pixel groß sein. Formate: JPG, PNG, GIF, WebP (max. 2MB).",it:"L'immagine deve essere esattamente {format} pixel. Formati: JPG, PNG, GIF, WebP (max. 2MB).",nl:"De afbeelding moet exact {format} pixels zijn. Formaten: JPG, PNG, GIF, WebP (max. 2MB).",ja:"画像は正確に{format}ピクセルである必要があります。形式：JPG、PNG、GIF、WebP（最大2MB）。",zh:"图片必须正好为{format}像素。格式：JPG、PNG、GIF、WebP（最大2MB）。",ru:"Изображение должно быть точно {format} пикселей. Форматы: JPG, PNG, GIF, WebP (макс. 2МБ).",ar:"يجب أن تكون الصورة بحجم {format} بكسل تماماً. الصيغ: JPG، PNG، GIF، WebP (حد أقصى 2MB).",hi:"छवि बिल्कुल {format} पिक्सेल होनी चाहिए। प्रारूप: JPG, PNG, GIF, WebP (अधिकतम 2MB)।",ko:"이미지는 정확히 {format} 픽셀이어야 합니다. 형식: JPG, PNG, GIF, WebP (최대 2MB).",tr:"Görsel tam olarak {format} piksel olmalıdır. Formatlar: JPG, PNG, GIF, WebP (maks. 2MB).",pl:"Obraz musi mieć dokładnie {format} pikseli. Formaty: JPG, PNG, GIF, WebP (maks. 2MB).",sv:"Bilden måste vara exakt {format} pixlar. Format: JPG, PNG, GIF, WebP (max. 2MB).",id:"Gambar harus berukuran tepat {format} piksel. Format: JPG, PNG, GIF, WebP (maks. 2MB).",th:"รูปภาพต้องมีขนาดพอดี {format} พิกเซล รูปแบบ: JPG, PNG, GIF, WebP (สูงสุด 2MB)"},
"publicidad.clickToUpload":{en:"Click to upload your banner",pt:"Clique para enviar seu banner",fr:"Cliquez pour télécharger votre bannière",de:"Klicken Sie, um Ihr Banner hochzuladen",it:"Clicca per caricare il tuo banner",nl:"Klik om je banner te uploaden",ja:"クリックしてバナーをアップロード",zh:"点击上传您的横幅",ru:"Нажмите, чтобы загрузить баннер",ar:"انقر لرفع إعلانك",hi:"अपना बैनर अपलोड करने के लिए क्लिक करें",ko:"배너를 업로드하려면 클릭하세요",tr:"Banner'ınızı yüklemek için tıklayın",pl:"Kliknij, aby przesłać baner",sv:"Klicka för att ladda upp din banner",id:"Klik untuk mengunggah banner Anda",th:"คลิกเพื่ออัปโหลดแบนเนอร์ของคุณ"},
"publicidad.requiredDimensions":{en:"Required dimensions: {format}",pt:"Dimensões necessárias: {format}",fr:"Dimensions requises : {format}",de:"Erforderliche Abmessungen: {format}",it:"Dimensioni richieste: {format}",nl:"Vereiste afmetingen: {format}",ja:"必要な寸法：{format}",zh:"所需尺寸：{format}",ru:"Требуемые размеры: {format}",ar:"الأبعاد المطلوبة: {format}",hi:"आवश्यक आयाम: {format}",ko:"필요한 크기: {format}",tr:"Gerekli boyutlar: {format}",pl:"Wymagane wymiary: {format}",sv:"Krävda dimensioner: {format}",id:"Dimensi yang diperlukan: {format}",th:"ขนาดที่ต้องการ: {format}"},
"publicidad.clickUrl":{en:"Destination URL (optional)",pt:"URL de destino (opcional)",fr:"URL de destination (optionnel)",de:"Ziel-URL (optional)",it:"URL di destinazione (opzionale)",nl:"Bestemmings-URL (optioneel)",ja:"リンク先URL（任意）",zh:"目标URL（可选）",ru:"URL назначения (необязательно)",ar:"رابط الوجهة (اختياري)",hi:"गंतव्य URL (वैकल्पिक)",ko:"목적지 URL (선택사항)",tr:"Hedef URL (isteğe bağlı)",pl:"Docelowy URL (opcjonalnie)",sv:"Mål-URL (valfritt)",id:"URL tujuan (opsional)",th:"URL ปลายทาง (ไม่จำเป็น)"},
"publicidad.clickUrlPlaceholder":{en:"https://example.com",pt:"https://exemplo.com",fr:"https://exemple.com",de:"https://beispiel.com",it:"https://esempio.com",nl:"https://voorbeeld.com",ja:"https://example.com",zh:"https://example.com",ru:"https://example.com",ar:"https://example.com",hi:"https://example.com",ko:"https://example.com",tr:"https://ornek.com",pl:"https://przyklad.com",sv:"https://exempel.com",id:"https://contoh.com",th:"https://example.com"},
"publicidad.clickUrlDesc":{en:"Where users will go when they click on your banner.",pt:"Para onde os usuários irão ao clicar no seu banner.",fr:"Où les utilisateurs iront en cliquant sur votre bannière.",de:"Wohin Benutzer gelangen, wenn sie auf Ihr Banner klicken.",it:"Dove andranno gli utenti quando cliccano sul tuo banner.",nl:"Waar gebruikers naartoe gaan als ze op je banner klikken.",ja:"ユーザーがバナーをクリックした際のリンク先。",zh:"用户点击横幅时将前往的地方。",ru:"Куда перейдут пользователи при клике на ваш баннер.",ar:"أين سيذهب المستخدمون عند النقر على إعلانك.",hi:"जब उपयोगकर्ता आपके बैनर पर क्लिक करें तो कहाँ जाएंगे।",ko:"사용자가 배너를 클릭하면 이동할 위치.",tr:"Kullanıcılar banner'ınıza tıkladığında nereye gidecek.",pl:"Gdzie zostaną przekierowani użytkownicy po kliknięciu banera.",sv:"Vart användare går när de klickar på din banner.",id:"Ke mana pengguna akan pergi saat mengklik banner Anda.",th:"ผู้ใช้จะไปที่ไหนเมื่อคลิกแบนเนอร์ของคุณ"},
"publicidad.step5Title":{en:"Confirm Request",pt:"Confirmar Solicitação",fr:"Confirmer la Demande",de:"Anfrage bestätigen",it:"Conferma Richiesta",nl:"Verzoek Bevestigen",ja:"リクエストを確認",zh:"确认请求",ru:"Подтвердить запрос",ar:"تأكيد الطلب",hi:"अनुरोध की पुष्टि करें",ko:"요청 확인",tr:"Talebi Onayla",pl:"Potwierdź Żądanie",sv:"Bekräfta Förfrågan",id:"Konfirmasi Permintaan",th:"ยืนยันคำขอ"},
"publicidad.step5Desc":{en:"Review the details before submitting.",pt:"Revise os detalhes antes de enviar.",fr:"Vérifiez les détails avant d'envoyer.",de:"Überprüfen Sie die Details vor dem Absenden.",it:"Rivedi i dettagli prima di inviare.",nl:"Controleer de details voor het indienen.",ja:"送信前に詳細を確認してください。",zh:"提交前请检查详细信息。",ru:"Проверьте детали перед отправкой.",ar:"راجع التفاصيل قبل الإرسال.",hi:"सबमिट करने से पहले विवरण की समीक्षा करें।",ko:"제출하기 전에 세부사항을 확인하세요.",tr:"Göndermeden önce ayrıntıları gözden geçirin.",pl:"Sprawdź szczegóły przed wysłaniem.",sv:"Granska detaljerna innan du skickar.",id:"Tinjau detail sebelum mengirim.",th:"ตรวจสอบรายละเอียดก่อนส่ง"},
"publicidad.type":{en:"Type",pt:"Tipo",fr:"Type",de:"Typ",it:"Tipo",nl:"Type",ja:"タイプ",zh:"类型",ru:"Тип",ar:"النوع",hi:"प्रकार",ko:"유형",tr:"Tür",pl:"Typ",sv:"Typ",id:"Tipe",th:"ประเภท"},
"publicidad.format":{en:"Format",pt:"Formato",fr:"Format",de:"Format",it:"Formato",nl:"Formaat",ja:"フォーマット",zh:"格式",ru:"Формат",ar:"الشكل",hi:"प्रारूप",ko:"형식",tr:"Format",pl:"Format",sv:"Format",id:"Format",th:"รูปแบบ"},
"publicidad.position":{en:"Position",pt:"Posição",fr:"Position",de:"Position",it:"Posizione",nl:"Positie",ja:"位置",zh:"位置",ru:"Позиция",ar:"الموقع",hi:"स्थिति",ko:"위치",tr:"Konum",pl:"Pozycja",sv:"Position",id:"Posisi",th:"ตำแหน่ง"},
"publicidad.dates":{en:"Dates",pt:"Datas",fr:"Dates",de:"Termine",it:"Date",nl:"Datums",ja:"日付",zh:"日期",ru:"Даты",ar:"التواريخ",hi:"तिथियाँ",ko:"날짜",tr:"Tarihler",pl:"Daty",sv:"Datum",id:"Tanggal",th:"วันที่"},
"publicidad.duration":{en:"Duration",pt:"Duração",fr:"Durée",de:"Dauer",it:"Durata",nl:"Duur",ja:"期間",zh:"时长",ru:"Длительность",ar:"المدة",hi:"अवधि",ko:"기간",tr:"Süre",pl:"Czas trwania",sv:"Varaktighet",id:"Durasi",th:"ระยะเวลา"},
"publicidad.destinationUrl":{en:"Destination URL",pt:"URL de destino",fr:"URL de destination",de:"Ziel-URL",it:"URL di destinazione",nl:"Bestemmings-URL",ja:"リンク先URL",zh:"目标URL",ru:"URL назначения",ar:"رابط الوجهة",hi:"गंतव्य URL",ko:"목적지 URL",tr:"Hedef URL",pl:"Docelowy URL",sv:"Mål-URL",id:"URL tujuan",th:"URL ปลายทาง"},
"publicidad.none":{en:"(none)",pt:"(nenhuma)",fr:"(aucune)",de:"(keine)",it:"(nessuno)",nl:"(geen)",ja:"（なし）",zh:"（无）",ru:"(нет)",ar:"(لا شيء)",hi:"(कोई नहीं)",ko:"(없음)",tr:"(yok)",pl:"(brak)",sv:"(ingen)",id:"(tidak ada)",th:"(ไม่มี)"},
"publicidad.price":{en:"Price",pt:"Preço",fr:"Prix",de:"Preis",it:"Prezzo",nl:"Prijs",ja:"価格",zh:"价格",ru:"Цена",ar:"السعر",hi:"मूल्य",ko:"가격",tr:"Fiyat",pl:"Cena",sv:"Pris",id:"Harga",th:"ราคา"},
"publicidad.bannerPreview":{en:"Banner preview:",pt:"Pré-visualização do banner:",fr:"Aperçu de la bannière :",de:"Banner-Vorschau:",it:"Anteprima del banner:",nl:"Bannervoorbeeld:",ja:"バナープレビュー：",zh:"横幅预览：",ru:"Предпросмотр баннера:",ar:"معاينة الإعلان:",hi:"बैनर पूर्वावलोकन:",ko:"배너 미리보기:",tr:"Banner önizleme:",pl:"Podgląd banera:",sv:"Bannerförhandsvisning:",id:"Pratinjau banner:",th:"ตัวอย่างแบนเนอร์:"},
"publicidad.reviewNote":{en:"Your request will be reviewed by a moderator. You will receive a notification when it is approved.",pt:"Sua solicitação será revisada por um moderador. Você receberá uma notificação quando for aprovada.",fr:"Votre demande sera examinée par un modérateur. Vous recevrez une notification lorsqu'elle sera approuvée.",de:"Ihre Anfrage wird von einem Moderator überprüft. Sie erhalten eine Benachrichtigung bei Genehmigung.",it:"La tua richiesta sarà esaminata da un moderatore. Riceverai una notifica quando sarà approvata.",nl:"Je verzoek wordt beoordeeld door een moderator. Je ontvangt een melding wanneer het is goedgekeurd.",ja:"リクエストはモデレーターによって審査されます。承認されると通知が届きます。",zh:"您的请求将由版主审核。审批通过后您将收到通知。",ru:"Ваш запрос будет рассмотрен модератором. Вы получите уведомление после одобрения.",ar:"سيتم مراجعة طلبك من قبل مشرف. ستتلقى إشعاراً عند الموافقة.",hi:"आपका अनुरोध मॉडरेटर द्वारा समीक्षा किया जाएगा। स्वीकृति पर आपको सूचना मिलेगी।",ko:"요청은 관리자가 검토합니다. 승인되면 알림을 받게 됩니다.",tr:"Talebiniz bir moderatör tarafından incelenecektir. Onaylandığında bildirim alacaksınız.",pl:"Twoje żądanie zostanie sprawdzone przez moderatora. Otrzymasz powiadomienie po zatwierdzeniu.",sv:"Din förfrågan granskas av en moderator. Du får ett meddelande när den godkänns.",id:"Permintaan Anda akan ditinjau oleh moderator. Anda akan menerima notifikasi saat disetujui.",th:"คำขอของคุณจะถูกตรวจสอบโดยผู้ดูแล คุณจะได้รับการแจ้งเตือนเมื่อได้รับการอนุมัติ"},
"publicidad.submitting":{en:"Submitting...",pt:"Enviando...",fr:"Envoi en cours...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"提交中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"सबमिट हो रहा है...",ko:"제출 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"publicidad.submitRequest":{en:"Submit Request",pt:"Enviar Solicitação",fr:"Envoyer la Demande",de:"Anfrage senden",it:"Invia Richiesta",nl:"Verzoek Indienen",ja:"リクエストを送信",zh:"提交请求",ru:"Отправить запрос",ar:"إرسال الطلب",hi:"अनुरोध सबमिट करें",ko:"요청 제출",tr:"Talebi Gönder",pl:"Wyślij Żądanie",sv:"Skicka Förfrågan",id:"Kirim Permintaan",th:"ส่งคำขอ"},
"publicidad.completeAllFields":{en:"Complete all fields.",pt:"Preencha todos os campos.",fr:"Remplissez tous les champs.",de:"Füllen Sie alle Felder aus.",it:"Completa tutti i campi.",nl:"Vul alle velden in.",ja:"すべてのフィールドを入力してください。",zh:"请填写所有字段。",ru:"Заполните все поля.",ar:"أكمل جميع الحقول.",hi:"सभी फ़ील्ड भरें।",ko:"모든 필드를 작성하세요.",tr:"Tüm alanları doldurun.",pl:"Wypełnij wszystkie pola.",sv:"Fyll i alla fält.",id:"Lengkapi semua kolom.",th:"กรอกข้อมูลทุกช่อง"},
"publicidad.requestSent":{en:"Request sent! A moderator will review your banner soon.",pt:"Solicitação enviada! Um moderador revisará seu banner em breve.",fr:"Demande envoyée ! Un modérateur examinera votre bannière bientôt.",de:"Anfrage gesendet! Ein Moderator wird Ihr Banner bald überprüfen.",it:"Richiesta inviata! Un moderatore esaminerà il tuo banner presto.",nl:"Verzoek verzonden! Een moderator bekijkt je banner binnenkort.",ja:"リクエスト送信！モデレーターがバナーを確認します。",zh:"请求已发送！版主将尽快审核您的横幅。",ru:"Запрос отправлен! Модератор скоро проверит ваш баннер.",ar:"تم إرسال الطلب! سيراجع مشرف إعلانك قريباً.",hi:"अनुरोध भेजा गया! एक मॉडरेटर जल्द ही आपके बैनर की समीक्षा करेगा।",ko:"요청이 전송되었습니다! 관리자가 곧 배너를 검토합니다.",tr:"Talep gönderildi! Bir moderatör banner'ınızı yakında inceleyecek.",pl:"Żądanie wysłane! Moderator wkrótce sprawdzi Twój baner.",sv:"Förfrågan skickad! En moderator granskar din banner snart.",id:"Permintaan terkirim! Moderator akan meninjau banner Anda segera.",th:"ส่งคำขอแล้ว! ผู้ดูแลจะตรวจสอบแบนเนอร์ของคุณเร็วๆ นี้"},
"publicidad.uploadError":{en:"Error uploading the image.",pt:"Erro ao enviar a imagem.",fr:"Erreur lors du téléchargement de l'image.",de:"Fehler beim Hochladen des Bildes.",it:"Errore nel caricamento dell'immagine.",nl:"Fout bij uploaden van afbeelding.",ja:"画像のアップロードエラー。",zh:"上传图片出错。",ru:"Ошибка загрузки изображения.",ar:"خطأ في رفع الصورة.",hi:"छवि अपलोड करने में त्रुटि।",ko:"이미지 업로드 오류.",tr:"Görsel yükleme hatası.",pl:"Błąd przesyłania obrazu.",sv:"Fel vid uppladdning av bild.",id:"Error mengunggah gambar.",th:"เกิดข้อผิดพลาดในการอัปโหลดรูปภาพ"},
"publicidad.unexpectedError":{en:"Unexpected error uploading the image.",pt:"Erro inesperado ao enviar a imagem.",fr:"Erreur inattendue lors du téléchargement de l'image.",de:"Unerwarteter Fehler beim Hochladen des Bildes.",it:"Errore imprevisto nel caricamento dell'immagine.",nl:"Onverwachte fout bij uploaden van afbeelding.",ja:"画像アップロード中に予期しないエラー。",zh:"上传图片时发生意外错误。",ru:"Неожиданная ошибка при загрузке изображения.",ar:"خطأ غير متوقع في رفع الصورة.",hi:"छवि अपलोड करते समय अप्रत्याशित त्रुटि।",ko:"이미지 업로드 중 예상치 못한 오류.",tr:"Görsel yüklenirken beklenmeyen hata.",pl:"Nieoczekiwany błąd przesyłania obrazu.",sv:"Oväntat fel vid uppladdning av bild.",id:"Error tak terduga saat mengunggah gambar.",th:"เกิดข้อผิดพลาดที่ไม่คาดคิดในการอัปโหลดรูปภาพ"},
"publicidad.cityLabel":{en:"City: {name}",pt:"Cidade: {name}",fr:"Ville : {name}",de:"Stadt: {name}",it:"Città: {name}",nl:"Stad: {name}",ja:"都市: {name}",zh:"城市：{name}",ru:"Город: {name}",ar:"المدينة: {name}",hi:"शहर: {name}",ko:"도시: {name}",tr:"Şehir: {name}",pl:"Miasto: {name}",sv:"Stad: {name}",id:"Kota: {name}",th:"เมือง: {name}"},
"publicidad.note":{en:"Note:",pt:"Nota:",fr:"Note :",de:"Hinweis:",it:"Nota:",nl:"Opmerking:",ja:"注意：",zh:"注意：",ru:"Примечание:",ar:"ملاحظة:",hi:"नोट:",ko:"참고:",tr:"Not:",pl:"Uwaga:",sv:"Obs:",id:"Catatan:",th:"หมายเหตุ:"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2e (publicidad - 63 keys) done!');
