const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === PAYMENTS (55) ===
"payments.title":{en:"Payment",pt:"Pagamento",fr:"Paiement",de:"Zahlung",it:"Pagamento",nl:"Betaling",ja:"支払い",zh:"支付",ru:"Оплата",ar:"الدفع",hi:"भुगतान",ko:"결제",tr:"Ödeme",pl:"Płatność",sv:"Betalning",id:"Pembayaran",th:"การชำระเงิน"},
"payments.subtitle":{en:"Complete the payment to activate your banner.",pt:"Complete o pagamento para ativar seu banner.",fr:"Complétez le paiement pour activer votre bannière.",de:"Schließen Sie die Zahlung ab, um Ihr Banner zu aktivieren.",it:"Completa il pagamento per attivare il tuo banner.",nl:"Voltooi de betaling om je banner te activeren.",ja:"バナーを有効にするには支払いを完了してください。",zh:"完成支付以激活您的横幅。",ru:"Завершите оплату для активации баннера.",ar:"أكمل الدفع لتفعيل إعلانك.",hi:"अपना बैनर सक्रिय करने के लिए भुगतान पूरा करें।",ko:"배너를 활성화하려면 결제를 완료하세요.",tr:"Banner'ınızı etkinleştirmek için ödemeyi tamamlayın.",pl:"Dokonaj płatności, aby aktywować baner.",sv:"Slutför betalningen för att aktivera din banner.",id:"Selesaikan pembayaran untuk mengaktifkan banner Anda.",th:"ชำระเงินเพื่อเปิดใช้งานแบนเนอร์ของคุณ"},
"payments.backToAds":{en:"Back to advertising",pt:"Voltar à publicidade",fr:"Retour à la publicité",de:"Zurück zur Werbung",it:"Torna alla pubblicità",nl:"Terug naar advertenties",ja:"広告に戻る",zh:"返回广告",ru:"Вернуться к рекламе",ar:"العودة إلى الإعلانات",hi:"विज्ञापन पर वापस जाएं",ko:"광고로 돌아가기",tr:"Reklamlara dön",pl:"Wróć do reklam",sv:"Tillbaka till annonsering",id:"Kembali ke iklan",th:"กลับไปที่โฆษณา"},
"payments.orderSummary":{en:"Order summary",pt:"Resumo do pedido",fr:"Résumé de la commande",de:"Bestellübersicht",it:"Riepilogo ordine",nl:"Besteloverzicht",ja:"注文概要",zh:"订单摘要",ru:"Итого заказа",ar:"ملخص الطلب",hi:"ऑर्डर सारांश",ko:"주문 요약",tr:"Sipariş özeti",pl:"Podsumowanie zamówienia",sv:"Ordersammanfattning",id:"Ringkasan pesanan",th:"สรุปคำสั่งซื้อ"},
"payments.zone":{en:"Zone",pt:"Zona",fr:"Zone",de:"Zone",it:"Zona",nl:"Zone",ja:"ゾーン",zh:"区域",ru:"Зона",ar:"المنطقة",hi:"ज़ोन",ko:"지역",tr:"Bölge",pl:"Strefa",sv:"Zon",id:"Zona",th:"โซน"},
"payments.position":{en:"Position",pt:"Posição",fr:"Position",de:"Position",it:"Posizione",nl:"Positie",ja:"位置",zh:"位置",ru:"Позиция",ar:"الموقع",hi:"स्थिति",ko:"위치",tr:"Konum",pl:"Pozycja",sv:"Position",id:"Posisi",th:"ตำแหน่ง"},
"payments.dates":{en:"Dates",pt:"Datas",fr:"Dates",de:"Termine",it:"Date",nl:"Datums",ja:"日付",zh:"日期",ru:"Даты",ar:"التواريخ",hi:"तिथियाँ",ko:"날짜",tr:"Tarihler",pl:"Daty",sv:"Datum",id:"Tanggal",th:"วันที่"},
"payments.duration":{en:"Duration",pt:"Duração",fr:"Durée",de:"Dauer",it:"Durata",nl:"Duur",ja:"期間",zh:"时长",ru:"Длительность",ar:"المدة",hi:"अवधि",ko:"기간",tr:"Süre",pl:"Czas trwania",sv:"Varaktighet",id:"Durasi",th:"ระยะเวลา"},
"payments.days":{en:"days",pt:"dias",fr:"jours",de:"Tage",it:"giorni",nl:"dagen",ja:"日",zh:"天",ru:"дней",ar:"أيام",hi:"दिन",ko:"일",tr:"gün",pl:"dni",sv:"dagar",id:"hari",th:"วัน"},
"payments.total":{en:"Total",pt:"Total",fr:"Total",de:"Gesamt",it:"Totale",nl:"Totaal",ja:"合計",zh:"总计",ru:"Итого",ar:"المجموع",hi:"कुल",ko:"합계",tr:"Toplam",pl:"Razem",sv:"Totalt",id:"Total",th:"ทั้งหมด"},
"payments.paymentStatus":{en:"Payment status",pt:"Status do pagamento",fr:"Statut du paiement",de:"Zahlungsstatus",it:"Stato del pagamento",nl:"Betalingsstatus",ja:"支払い状況",zh:"支付状态",ru:"Статус оплаты",ar:"حالة الدفع",hi:"भुगतान स्थिति",ko:"결제 상태",tr:"Ödeme durumu",pl:"Status płatności",sv:"Betalningsstatus",id:"Status pembayaran",th:"สถานะการชำระเงิน"},
"payments.reference":{en:"Reference",pt:"Referência",fr:"Référence",de:"Referenz",it:"Riferimento",nl:"Referentie",ja:"参照番号",zh:"参考编号",ru:"Номер ссылки",ar:"المرجع",hi:"संदर्भ",ko:"참조번호",tr:"Referans",pl:"Numer referencyjny",sv:"Referens",id:"Referensi",th:"อ้างอิง"},
"payments.referenceCopied":{en:"Reference copied",pt:"Referência copiada",fr:"Référence copiée",de:"Referenz kopiert",it:"Riferimento copiato",nl:"Referentie gekopieerd",ja:"参照番号をコピーしました",zh:"参考编号已复制",ru:"Номер скопирован",ar:"تم نسخ المرجع",hi:"संदर्भ कॉपी किया गया",ko:"참조번호 복사됨",tr:"Referans kopyalandı",pl:"Numer skopiowany",sv:"Referens kopierad",id:"Referensi disalin",th:"คัดลอกอ้างอิงแล้ว"},
"payments.status_pending":{en:"Pending payment",pt:"Pagamento pendente",fr:"Paiement en attente",de:"Zahlung ausstehend",it:"Pagamento in attesa",nl:"Betaling in afwachting",ja:"支払い待ち",zh:"待付款",ru:"Ожидает оплаты",ar:"في انتظار الدفع",hi:"भुगतान लंबित",ko:"결제 대기",tr:"Ödeme bekliyor",pl:"Oczekuje płatności",sv:"Väntar på betalning",id:"Menunggu pembayaran",th:"รอการชำระเงิน"},
"payments.status_submitted":{en:"Proof submitted",pt:"Comprovante enviado",fr:"Justificatif envoyé",de:"Beleg eingereicht",it:"Ricevuta inviata",nl:"Bewijs ingediend",ja:"証明書提出済み",zh:"凭证已提交",ru:"Подтверждение отправлено",ar:"تم إرسال الإثبات",hi:"प्रमाण सबमिट किया गया",ko:"증빙 제출됨",tr:"Kanıt gönderildi",pl:"Dowód wysłany",sv:"Kvitto inskickat",id:"Bukti dikirim",th:"ส่งหลักฐานแล้ว"},
"payments.status_confirmed":{en:"Payment confirmed",pt:"Pagamento confirmado",fr:"Paiement confirmé",de:"Zahlung bestätigt",it:"Pagamento confermato",nl:"Betaling bevestigd",ja:"支払い確認済み",zh:"支付已确认",ru:"Оплата подтверждена",ar:"تم تأكيد الدفع",hi:"भुगतान पुष्टि",ko:"결제 확인됨",tr:"Ödeme onaylandı",pl:"Płatność potwierdzona",sv:"Betalning bekräftad",id:"Pembayaran dikonfirmasi",th:"ยืนยันการชำระเงินแล้ว"},
"payments.status_rejected":{en:"Payment rejected",pt:"Pagamento rejeitado",fr:"Paiement rejeté",de:"Zahlung abgelehnt",it:"Pagamento rifiutato",nl:"Betaling afgewezen",ja:"支払い拒否",zh:"支付被拒绝",ru:"Оплата отклонена",ar:"تم رفض الدفع",hi:"भुगतान अस्वीकृत",ko:"결제 거부됨",tr:"Ödeme reddedildi",pl:"Płatność odrzucona",sv:"Betalning avvisad",id:"Pembayaran ditolak",th:"การชำระเงินถูกปฏิเสธ"},
"payments.status_refunded":{en:"Refunded",pt:"Reembolsado",fr:"Remboursé",de:"Erstattet",it:"Rimborsato",nl:"Terugbetaald",ja:"返金済み",zh:"已退款",ru:"Возвращено",ar:"تم الاسترداد",hi:"रिफ़ंड किया गया",ko:"환불됨",tr:"İade edildi",pl:"Zwrócono",sv:"Återbetald",id:"Dikembalikan",th:"คืนเงินแล้ว"},
"payments.status_cancelled":{en:"Cancelled",pt:"Cancelado",fr:"Annulé",de:"Storniert",it:"Cancellato",nl:"Geannuleerd",ja:"キャンセル済み",zh:"已取消",ru:"Отменено",ar:"ملغى",hi:"रद्द",ko:"취소됨",tr:"İptal edildi",pl:"Anulowano",sv:"Avbruten",id:"Dibatalkan",th:"ยกเลิกแล้ว"},
"payments.paymentConfirmed":{en:"Payment confirmed",pt:"Pagamento confirmado",fr:"Paiement confirmé",de:"Zahlung bestätigt",it:"Pagamento confermato",nl:"Betaling bevestigd",ja:"支払い確認済み",zh:"支付已确认",ru:"Оплата подтверждена",ar:"تم تأكيد الدفع",hi:"भुगतान पुष्टि",ko:"결제 확인됨",tr:"Ödeme onaylandı",pl:"Płatność potwierdzona",sv:"Betalning bekräftad",id:"Pembayaran dikonfirmasi",th:"ยืนยันการชำระเงินแล้ว"},
"payments.paymentConfirmedDesc":{en:"Your banner will be activated automatically on the start date.",pt:"Seu banner será ativado automaticamente na data de início.",fr:"Votre bannière sera activée automatiquement à la date de début.",de:"Ihr Banner wird automatisch am Startdatum aktiviert.",it:"Il tuo banner sarà attivato automaticamente alla data di inizio.",nl:"Je banner wordt automatisch geactiveerd op de startdatum.",ja:"バナーは開始日に自動的に有効化されます。",zh:"您的横幅将在开始日期自动激活。",ru:"Ваш баннер будет автоматически активирован в дату начала.",ar:"سيتم تفعيل إعلانك تلقائياً في تاريخ البدء.",hi:"आपका बैनर प्रारंभ तिथि पर स्वचालित रूप से सक्रिय हो जाएगा।",ko:"배너가 시작 날짜에 자동으로 활성화됩니다.",tr:"Banner'ınız başlangıç tarihinde otomatik olarak etkinleştirilecek.",pl:"Twój baner zostanie automatycznie aktywowany w dacie rozpoczęcia.",sv:"Din banner aktiveras automatiskt på startdatumet.",id:"Banner Anda akan diaktifkan secara otomatis pada tanggal mulai.",th:"แบนเนอร์ของคุณจะเปิดใช้งานโดยอัตโนมัติในวันเริ่มต้น"},
"payments.proofUnderReview":{en:"Proof under review",pt:"Comprovante em revisão",fr:"Justificatif en cours d'examen",de:"Beleg wird überprüft",it:"Ricevuta in revisione",nl:"Bewijs wordt beoordeeld",ja:"証明書確認中",zh:"凭证审核中",ru:"Подтверждение на проверке",ar:"الإثبات قيد المراجعة",hi:"प्रमाण समीक्षाधीन",ko:"증빙 검토 중",tr:"Kanıt inceleniyor",pl:"Dowód w trakcie weryfikacji",sv:"Kvitto granskas",id:"Bukti sedang ditinjau",th:"หลักฐานอยู่ระหว่างการตรวจสอบ"},
"payments.proofUnderReviewDesc":{en:"An administrator will review your proof soon. We will notify you when it is processed.",pt:"Um administrador revisará seu comprovante em breve. Notificaremos quando for processado.",fr:"Un administrateur examinera votre justificatif bientôt. Nous vous notifierons du résultat.",de:"Ein Administrator wird Ihren Beleg bald überprüfen. Sie werden benachrichtigt.",it:"Un amministratore esaminerà la tua ricevuta presto. Ti avviseremo quando sarà elaborata.",nl:"Een beheerder bekijkt je bewijs binnenkort. We laten je weten wanneer het is verwerkt.",ja:"管理者がまもなく証明書を確認します。処理後に通知します。",zh:"管理员将很快审核您的凭证。处理后会通知您。",ru:"Администратор скоро проверит ваше подтверждение. Мы уведомим вас о результате.",ar:"سيراجع مسؤول إثباتك قريباً. سنخبرك عند معالجته.",hi:"एक व्यवस्थापक जल्द ही आपके प्रमाण की समीक्षा करेगा। प्रसंस्करण के बाद सूचित किया जाएगा।",ko:"관리자가 곧 증빙을 검토합니다. 처리되면 알려드리겠습니다.",tr:"Bir yönetici kanıtınızı yakında inceleyecek. İşlendiğinde sizi bilgilendireceğiz.",pl:"Administrator wkrótce sprawdzi Twój dowód. Powiadomimy Cię po przetworzeniu.",sv:"En administratör granskar ditt kvitto snart. Vi meddelar dig när det har behandlats.",id:"Administrator akan meninjau bukti Anda segera. Kami akan memberi tahu saat diproses.",th:"ผู้ดูแลระบบจะตรวจสอบหลักฐานของคุณเร็วๆ นี้ เราจะแจ้งให้คุณทราบเมื่อดำเนินการเสร็จ"},
"payments.paymentRejected":{en:"Payment rejected",pt:"Pagamento rejeitado",fr:"Paiement rejeté",de:"Zahlung abgelehnt",it:"Pagamento rifiutato",nl:"Betaling afgewezen",ja:"支払い拒否",zh:"支付被拒绝",ru:"Оплата отклонена",ar:"تم رفض الدفع",hi:"भुगतान अस्वीकृत",ko:"결제 거부됨",tr:"Ödeme reddedildi",pl:"Płatność odrzucona",sv:"Betalning avvisad",id:"Pembayaran ditolak",th:"การชำระเงินถูกปฏิเสธ"},
"payments.reason":{en:"Reason",pt:"Motivo",fr:"Motif",de:"Grund",it:"Motivo",nl:"Reden",ja:"理由",zh:"原因",ru:"Причина",ar:"السبب",hi:"कारण",ko:"사유",tr:"Sebep",pl:"Powód",sv:"Anledning",id:"Alasan",th:"เหตุผล"},
"payments.adminNotes":{en:"Admin notes",pt:"Notas do admin",fr:"Notes de l'admin",de:"Admin-Notizen",it:"Note dell'admin",nl:"Admin notities",ja:"管理者メモ",zh:"管理员备注",ru:"Заметки админа",ar:"ملاحظات المسؤول",hi:"एडमिन नोट्स",ko:"관리자 메모",tr:"Admin notları",pl:"Notatki admina",sv:"Adminanteckningar",id:"Catatan admin",th:"หมายเหตุแอดมิน"},
"payments.selectPaymentMethod":{en:"Select payment method",pt:"Selecione método de pagamento",fr:"Sélectionnez le mode de paiement",de:"Zahlungsmethode auswählen",it:"Seleziona metodo di pagamento",nl:"Selecteer betaalmethode",ja:"支払い方法を選択",zh:"选择支付方式",ru:"Выберите способ оплаты",ar:"اختر طريقة الدفع",hi:"भुगतान विधि चुनें",ko:"결제 방법 선택",tr:"Ödeme yöntemini seçin",pl:"Wybierz metodę płatności",sv:"Välj betalningsmetod",id:"Pilih metode pembayaran",th:"เลือกวิธีชำระเงิน"},
"payments.selectPaymentMethodDesc":{en:"Choose how you want to make the payment.",pt:"Escolha como deseja realizar o pagamento.",fr:"Choisissez comment vous souhaitez effectuer le paiement.",de:"Wählen Sie, wie Sie bezahlen möchten.",it:"Scegli come vuoi effettuare il pagamento.",nl:"Kies hoe je wilt betalen.",ja:"支払い方法を選択してください。",zh:"选择您想要的付款方式。",ru:"Выберите, как вы хотите произвести оплату.",ar:"اختر كيف تريد الدفع.",hi:"चुनें कि आप कैसे भुगतान करना चाहते हैं।",ko:"결제 방법을 선택하세요.",tr:"Nasıl ödeme yapmak istediğinizi seçin.",pl:"Wybierz, jak chcesz dokonać płatności.",sv:"Välj hur du vill betala.",id:"Pilih bagaimana Anda ingin membayar.",th:"เลือกวิธีที่คุณต้องการชำระเงิน"},
"payments.selectMethod":{en:"Select a payment method.",pt:"Selecione um método de pagamento.",fr:"Sélectionnez un mode de paiement.",de:"Wählen Sie eine Zahlungsmethode.",it:"Seleziona un metodo di pagamento.",nl:"Selecteer een betaalmethode.",ja:"支払い方法を選択してください。",zh:"请选择支付方式。",ru:"Выберите способ оплаты.",ar:"اختر طريقة دفع.",hi:"भुगतान विधि चुनें।",ko:"결제 방법을 선택하세요.",tr:"Bir ödeme yöntemi seçin.",pl:"Wybierz metodę płatności.",sv:"Välj en betalningsmetod.",id:"Pilih metode pembayaran.",th:"เลือกวิธีชำระเงิน"},
"payments.continueToPayment":{en:"Continue to payment",pt:"Continuar para pagamento",fr:"Continuer vers le paiement",de:"Weiter zur Zahlung",it:"Continua al pagamento",nl:"Doorgaan naar betaling",ja:"支払いに進む",zh:"继续付款",ru:"Перейти к оплате",ar:"المتابعة إلى الدفع",hi:"भुगतान जारी रखें",ko:"결제 계속",tr:"Ödemeye devam et",pl:"Przejdź do płatności",sv:"Fortsätt till betalning",id:"Lanjut ke pembayaran",th:"ดำเนินการชำระเงินต่อ"},
"payments.processing":{en:"Processing...",pt:"Processando...",fr:"Traitement...",de:"Wird verarbeitet...",it:"Elaborazione...",nl:"Verwerken...",ja:"処理中...",zh:"处理中...",ru:"Обработка...",ar:"جاري المعالجة...",hi:"प्रोसेसिंग...",ko:"처리 중...",tr:"İşleniyor...",pl:"Przetwarzanie...",sv:"Bearbetar...",id:"Memproses...",th:"กำลังดำเนินการ..."},
"payments.paymentCreated":{en:"Payment created. Follow the instructions to complete it.",pt:"Pagamento criado. Siga as instruções para completá-lo.",fr:"Paiement créé. Suivez les instructions pour le compléter.",de:"Zahlung erstellt. Befolgen Sie die Anweisungen.",it:"Pagamento creato. Segui le istruzioni per completarlo.",nl:"Betaling aangemaakt. Volg de instructies om te voltooien.",ja:"支払いが作成されました。手順に従って完了してください。",zh:"支付已创建。请按照说明完成支付。",ru:"Платёж создан. Следуйте инструкциям для завершения.",ar:"تم إنشاء الدفع. اتبع التعليمات لإكماله.",hi:"भुगतान बनाया गया। इसे पूरा करने के लिए निर्देशों का पालन करें।",ko:"결제가 생성되었습니다. 안내에 따라 완료하세요.",tr:"Ödeme oluşturuldu. Tamamlamak için talimatları izleyin.",pl:"Płatność utworzona. Postępuj zgodnie z instrukcjami.",sv:"Betalning skapad. Följ instruktionerna för att slutföra.",id:"Pembayaran dibuat. Ikuti instruksi untuk menyelesaikannya.",th:"สร้างการชำระเงินแล้ว ทำตามคำแนะนำเพื่อดำเนินการให้เสร็จ"},
"payments.paymentInstructions":{en:"Payment instructions",pt:"Instruções de pagamento",fr:"Instructions de paiement",de:"Zahlungsanweisungen",it:"Istruzioni di pagamento",nl:"Betalingsinstructies",ja:"支払い手順",zh:"支付说明",ru:"Инструкции по оплате",ar:"تعليمات الدفع",hi:"भुगतान निर्देश",ko:"결제 안내",tr:"Ödeme talimatları",pl:"Instrukcje płatności",sv:"Betalningsinstruktioner",id:"Instruksi pembayaran",th:"คำแนะนำการชำระเงิน"},
"payments.contactAdmin":{en:"Contact the administrator to coordinate the payment.",pt:"Entre em contato com o administrador para coordenar o pagamento.",fr:"Contactez l'administrateur pour coordonner le paiement.",de:"Kontaktieren Sie den Administrator zur Zahlungskoordination.",it:"Contatta l'amministratore per coordinare il pagamento.",nl:"Neem contact op met de beheerder om de betaling te coördineren.",ja:"支払いの調整について管理者に連絡してください。",zh:"联系管理员协调付款。",ru:"Свяжитесь с администратором для координации оплаты.",ar:"تواصل مع المسؤول لتنسيق الدفع.",hi:"भुगतान समन्वय के लिए व्यवस्थापक से संपर्क करें।",ko:"결제 조율을 위해 관리자에게 연락하세요.",tr:"Ödemeyi koordine etmek için yöneticiyle iletişime geçin.",pl:"Skontaktuj się z administratorem w celu koordynacji płatności.",sv:"Kontakta administratören för att samordna betalningen.",id:"Hubungi administrator untuk mengoordinasikan pembayaran.",th:"ติดต่อผู้ดูแลระบบเพื่อประสานการชำระเงิน"},
"payments.importantNote":{en:"Important",pt:"Importante",fr:"Important",de:"Wichtig",it:"Importante",nl:"Belangrijk",ja:"重要",zh:"重要",ru:"Важно",ar:"مهم",hi:"महत्वपूर्ण",ko:"중요",tr:"Önemli",pl:"Ważne",sv:"Viktigt",id:"Penting",th:"สำคัญ"},
"payments.includeReference":{en:"Include the reference {ref} in your payment or proof.",pt:"Inclua a referência {ref} no seu pagamento ou comprovante.",fr:"Incluez la référence {ref} dans votre paiement ou justificatif.",de:"Geben Sie die Referenz {ref} in Ihrer Zahlung oder Ihrem Beleg an.",it:"Includi il riferimento {ref} nel tuo pagamento o ricevuta.",nl:"Vermeld de referentie {ref} in je betaling of bewijs.",ja:"支払いまたは証明書に参照番号{ref}を含めてください。",zh:"请在付款或凭证中包含参考编号{ref}。",ru:"Укажите номер {ref} в платеже или подтверждении.",ar:"أدرج المرجع {ref} في دفعتك أو إثباتك.",hi:"अपने भुगतान या प्रमाण में संदर्भ {ref} शामिल करें।",ko:"결제 또는 증빙에 참조번호 {ref}를 포함하세요.",tr:"Ödemenize veya kanıtınıza {ref} referansını ekleyin.",pl:"Dołącz numer referencyjny {ref} do płatności lub dowodu.",sv:"Inkludera referens {ref} i din betalning eller kvitto.",id:"Sertakan referensi {ref} dalam pembayaran atau bukti Anda.",th:"ระบุหมายเลขอ้างอิง {ref} ในการชำระเงินหรือหลักฐานของคุณ"},
"payments.submitProof":{en:"Submit proof",pt:"Enviar comprovante",fr:"Envoyer le justificatif",de:"Beleg einreichen",it:"Invia ricevuta",nl:"Bewijs indienen",ja:"証明書を提出",zh:"提交凭证",ru:"Отправить подтверждение",ar:"إرسال الإثبات",hi:"प्रमाण सबमिट करें",ko:"증빙 제출",tr:"Kanıt gönder",pl:"Wyślij dowód",sv:"Skicka kvitto",id:"Kirim bukti",th:"ส่งหลักฐาน"},
"payments.submitProofDesc":{en:"Upload your payment proof or include the transaction reference.",pt:"Envie seu comprovante de pagamento ou inclua a referência da transação.",fr:"Téléchargez votre justificatif de paiement ou incluez la référence de transaction.",de:"Laden Sie Ihren Zahlungsbeleg hoch oder geben Sie die Transaktionsreferenz an.",it:"Carica la tua ricevuta di pagamento o includi il riferimento della transazione.",nl:"Upload je betalingsbewijs of vermeld de transactiereferentie.",ja:"支払い証明書をアップロードするか取引参照番号を含めてください。",zh:"上传您的付款凭证或包含交易参考编号。",ru:"Загрузите подтверждение оплаты или укажите номер транзакции.",ar:"ارفع إثبات الدفع أو أدرج مرجع المعاملة.",hi:"भुगतान प्रमाण अपलोड करें या लेनदेन संदर्भ शामिल करें।",ko:"결제 증빙을 업로드하거나 거래 참조번호를 포함하세요.",tr:"Ödeme kanıtınızı yükleyin veya işlem referansını ekleyin.",pl:"Prześlij dowód płatności lub podaj numer transakcji.",sv:"Ladda upp ditt betalningskvitto eller inkludera transaktionsreferensen.",id:"Unggah bukti pembayaran atau sertakan referensi transaksi.",th:"อัปโหลดหลักฐานการชำระเงินหรือระบุหมายเลขอ้างอิงธุรกรรม"},
"payments.proofNotes":{en:"Notes / Transaction reference",pt:"Notas / Referência da transação",fr:"Notes / Référence de transaction",de:"Notizen / Transaktionsreferenz",it:"Note / Riferimento transazione",nl:"Notities / Transactiereferentie",ja:"メモ / 取引参照番号",zh:"备注 / 交易参考编号",ru:"Заметки / Номер транзакции",ar:"ملاحظات / مرجع المعاملة",hi:"नोट्स / लेनदेन संदर्भ",ko:"메모 / 거래 참조번호",tr:"Notlar / İşlem referansı",pl:"Notatki / Numer transakcji",sv:"Anteckningar / Transaktionsreferens",id:"Catatan / Referensi transaksi",th:"หมายเหตุ / อ้างอิงธุรกรรม"},
"payments.proofNotesPlaceholder":{en:"E.g.: Transaction hash, bank reference number...",pt:"Ex: Hash de transação, número de referência bancária...",fr:"Ex : Hash de transaction, numéro de référence bancaire...",de:"Z.B.: Transaktions-Hash, Bankreferenznummer...",it:"Es: Hash transazione, numero di riferimento bancario...",nl:"Bijv.: Transactie-hash, bankreferentienummer...",ja:"例：トランザクションハッシュ、銀行参照番号...",zh:"例：交易哈希、银行参考号...",ru:"Пример: Хеш транзакции, банковский номер...",ar:"مثال: هاش المعاملة، رقم مرجع البنك...",hi:"उदा.: लेनदेन हैश, बैंक संदर्भ संख्या...",ko:"예: 거래 해시, 은행 참조번호...",tr:"Örn: İşlem hash'i, banka referans numarası...",pl:"Np.: Hash transakcji, numer referencyjny banku...",sv:"T.ex.: Transaktionshash, bankreferensnummer...",id:"Contoh: Hash transaksi, nomor referensi bank...",th:"เช่น: แฮชธุรกรรม, เลขอ้างอิงธนาคาร..."},
"payments.proofFile":{en:"Proof (image or PDF)",pt:"Comprovante (imagem ou PDF)",fr:"Justificatif (image ou PDF)",de:"Beleg (Bild oder PDF)",it:"Ricevuta (immagine o PDF)",nl:"Bewijs (afbeelding of PDF)",ja:"証明書（画像またはPDF）",zh:"凭证（图片或PDF）",ru:"Подтверждение (изображение или PDF)",ar:"الإثبات (صورة أو PDF)",hi:"प्रमाण (छवि या PDF)",ko:"증빙 (이미지 또는 PDF)",tr:"Kanıt (resim veya PDF)",pl:"Dowód (obraz lub PDF)",sv:"Kvitto (bild eller PDF)",id:"Bukti (gambar atau PDF)",th:"หลักฐาน (รูปภาพหรือ PDF)"},
"payments.submitting":{en:"Submitting...",pt:"Enviando...",fr:"Envoi en cours...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"提交中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"सबमिट हो रहा है...",ko:"제출 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"payments.submitProofBtn":{en:"Submit payment proof",pt:"Enviar comprovante de pagamento",fr:"Envoyer le justificatif de paiement",de:"Zahlungsbeleg einreichen",it:"Invia ricevuta di pagamento",nl:"Betalingsbewijs indienen",ja:"支払い証明書を提出",zh:"提交付款凭证",ru:"Отправить подтверждение оплаты",ar:"إرسال إثبات الدفع",hi:"भुगतान प्रमाण सबमिट करें",ko:"결제 증빙 제출",tr:"Ödeme kanıtı gönder",pl:"Wyślij dowód płatności",sv:"Skicka betalningskvitto",id:"Kirim bukti pembayaran",th:"ส่งหลักฐานการชำระเงิน"},
"payments.addProofOrNotes":{en:"Add a proof or reference notes.",pt:"Adicione um comprovante ou notas de referência.",fr:"Ajoutez un justificatif ou des notes de référence.",de:"Fügen Sie einen Beleg oder Referenznotizen hinzu.",it:"Aggiungi una ricevuta o note di riferimento.",nl:"Voeg een bewijs of referentienotities toe.",ja:"証明書または参照メモを追加してください。",zh:"添加凭证或参考备注。",ru:"Добавьте подтверждение или заметки.",ar:"أضف إثباتاً أو ملاحظات مرجعية.",hi:"प्रमाण या संदर्भ नोट्स जोड़ें।",ko:"증빙 또는 참고 메모를 추가하세요.",tr:"Kanıt veya referans notları ekleyin.",pl:"Dodaj dowód lub notatki referencyjne.",sv:"Lägg till kvitto eller referensanteckningar.",id:"Tambahkan bukti atau catatan referensi.",th:"เพิ่มหลักฐานหรือหมายเหตุอ้างอิง"},
"payments.uploadError":{en:"Error uploading proof.",pt:"Erro ao enviar comprovante.",fr:"Erreur de téléchargement du justificatif.",de:"Fehler beim Hochladen des Belegs.",it:"Errore nel caricamento della ricevuta.",nl:"Fout bij uploaden bewijs.",ja:"証明書のアップロードエラー。",zh:"上传凭证出错。",ru:"Ошибка загрузки подтверждения.",ar:"خطأ في رفع الإثبات.",hi:"प्रमाण अपलोड करने में त्रुटि।",ko:"증빙 업로드 오류.",tr:"Kanıt yükleme hatası.",pl:"Błąd przesyłania dowodu.",sv:"Fel vid uppladdning av kvitto.",id:"Error mengunggah bukti.",th:"เกิดข้อผิดพลาดในการอัปโหลดหลักฐาน"},
"payments.proofSubmitted":{en:"Proof submitted. We will notify you when it is reviewed.",pt:"Comprovante enviado. Notificaremos quando for revisado.",fr:"Justificatif envoyé. Nous vous notifierons du résultat.",de:"Beleg eingereicht. Sie werden über das Ergebnis benachrichtigt.",it:"Ricevuta inviata. Ti avviseremo quando sarà esaminata.",nl:"Bewijs ingediend. We laten je weten wanneer het is beoordeeld.",ja:"証明書が提出されました。確認後に通知します。",zh:"凭证已提交。审核后会通知您。",ru:"Подтверждение отправлено. Мы уведомим вас о результате.",ar:"تم إرسال الإثبات. سنخبرك عند مراجعته.",hi:"प्रमाण सबमिट किया गया। समीक्षा के बाद सूचित किया जाएगा।",ko:"증빙이 제출되었습니다. 검토 후 알려드리겠습니다.",tr:"Kanıt gönderildi. İncelendiğinde sizi bilgilendireceğiz.",pl:"Dowód wysłany. Powiadomimy Cię po weryfikacji.",sv:"Kvitto inskickat. Vi meddelar dig när det har granskats.",id:"Bukti terkirim. Kami akan memberi tahu saat ditinjau.",th:"ส่งหลักฐานแล้ว เราจะแจ้งให้คุณทราบเมื่อตรวจสอบเสร็จ"},
"payments.unexpectedError":{en:"Unexpected error.",pt:"Erro inesperado.",fr:"Erreur inattendue.",de:"Unerwarteter Fehler.",it:"Errore imprevisto.",nl:"Onverwachte fout.",ja:"予期しないエラー。",zh:"意外错误。",ru:"Неожиданная ошибка.",ar:"خطأ غير متوقع.",hi:"अप्रत्याशित त्रुटि।",ko:"예상치 못한 오류.",tr:"Beklenmeyen hata.",pl:"Nieoczekiwany błąd.",sv:"Oväntat fel.",id:"Error tak terduga.",th:"เกิดข้อผิดพลาดที่ไม่คาดคิด"},
"payments.fileTooLarge":{en:"File must not exceed 5MB.",pt:"O arquivo não deve ultrapassar 5MB.",fr:"Le fichier ne doit pas dépasser 5 Mo.",de:"Die Datei darf 5MB nicht überschreiten.",it:"Il file non deve superare 5MB.",nl:"Het bestand mag niet groter zijn dan 5MB.",ja:"ファイルは5MBを超えてはいけません。",zh:"文件不得超过5MB。",ru:"Файл не должен превышать 5МБ.",ar:"يجب ألا يتجاوز الملف 5MB.",hi:"फ़ाइल 5MB से अधिक नहीं होनी चाहिए।",ko:"파일은 5MB를 초과할 수 없습니다.",tr:"Dosya 5MB'ı aşmamalıdır.",pl:"Plik nie może przekraczać 5MB.",sv:"Filen får inte överstiga 5MB.",id:"File tidak boleh melebihi 5MB.",th:"ไฟล์ต้องไม่เกิน 5MB"},
"payments.myPayments":{en:"My payments",pt:"Meus pagamentos",fr:"Mes paiements",de:"Meine Zahlungen",it:"I miei pagamenti",nl:"Mijn betalingen",ja:"マイ支払い",zh:"我的支付",ru:"Мои платежи",ar:"مدفوعاتي",hi:"मेरे भुगतान",ko:"내 결제",tr:"Ödemelerim",pl:"Moje płatności",sv:"Mina betalningar",id:"Pembayaran saya",th:"การชำระเงินของฉัน"},
"payments.myPaymentsDesc":{en:"Payment history and advertising invoices.",pt:"Histórico de pagamentos e faturas de publicidade.",fr:"Historique des paiements et factures de publicité.",de:"Zahlungshistorie und Werberechnungen.",it:"Cronologia pagamenti e fatture pubblicitarie.",nl:"Betalingsgeschiedenis en advertentiefacturen.",ja:"支払い履歴と広告請求書。",zh:"支付历史和广告发票。",ru:"История платежей и рекламные счета.",ar:"سجل المدفوعات وفواتير الإعلانات.",hi:"भुगतान इतिहास और विज्ञापन चालान।",ko:"결제 내역 및 광고 청구서.",tr:"Ödeme geçmişi ve reklam faturaları.",pl:"Historia płatności i faktury reklamowe.",sv:"Betalningshistorik och annonsfakturor.",id:"Riwayat pembayaran dan faktur iklan.",th:"ประวัติการชำระเงินและใบแจ้งหนี้โฆษณา"},
"payments.back":{en:"Back",pt:"Voltar",fr:"Retour",de:"Zurück",it:"Indietro",nl:"Terug",ja:"戻る",zh:"返回",ru:"Назад",ar:"رجوع",hi:"वापस",ko:"뒤로",tr:"Geri",pl:"Wróć",sv:"Tillbaka",id:"Kembali",th:"กลับ"},
"payments.noPaymentsYet":{en:"You don't have any payments registered.",pt:"Você não tem pagamentos registrados.",fr:"Vous n'avez aucun paiement enregistré.",de:"Sie haben keine Zahlungen registriert.",it:"Non hai pagamenti registrati.",nl:"Je hebt geen betalingen geregistreerd.",ja:"登録された支払いはありません。",zh:"您没有已注册的支付。",ru:"У вас нет зарегистрированных платежей.",ar:"ليس لديك مدفوعات مسجلة.",hi:"आपके पास कोई पंजीकृत भुगतान नहीं है।",ko:"등록된 결제가 없습니다.",tr:"Kayıtlı ödemeniz yok.",pl:"Nie masz zarejestrowanych płatności.",sv:"Du har inga registrerade betalningar.",id:"Anda belum memiliki pembayaran terdaftar.",th:"คุณยังไม่มีการชำระเงินที่ลงทะเบียน"},
"payments.buyAd":{en:"Buy advertising",pt:"Comprar publicidade",fr:"Acheter de la publicité",de:"Werbung kaufen",it:"Acquista pubblicità",nl:"Advertentie kopen",ja:"広告を購入",zh:"购买广告",ru:"Купить рекламу",ar:"شراء إعلان",hi:"विज्ञापन खरीदें",ko:"광고 구매",tr:"Reklam satın al",pl:"Kup reklamę",sv:"Köp annonsering",id:"Beli iklan",th:"ซื้อโฆษณา"},
"payments.completePay":{en:"Complete payment",pt:"Completar pagamento",fr:"Compléter le paiement",de:"Zahlung abschließen",it:"Completa pagamento",nl:"Betaling voltooien",ja:"支払いを完了",zh:"完成支付",ru:"Завершить оплату",ar:"إكمال الدفع",hi:"भुगतान पूरा करें",ko:"결제 완료",tr:"Ödemeyi tamamla",pl:"Dokończ płatność",sv:"Slutför betalning",id:"Selesaikan pembayaran",th:"ชำระเงินให้เสร็จ"},
"payments.rejectionReason":{en:"Rejection reason",pt:"Motivo de rejeição",fr:"Motif de rejet",de:"Ablehnungsgrund",it:"Motivo del rifiuto",nl:"Reden van afwijzing",ja:"拒否理由",zh:"拒绝原因",ru:"Причина отказа",ar:"سبب الرفض",hi:"अस्वीकृति कारण",ko:"거부 사유",tr:"Ret nedeni",pl:"Powód odrzucenia",sv:"Avslagsorsak",id:"Alasan penolakan",th:"เหตุผลในการปฏิเสธ"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2f (payments - 55 keys) done!');
