const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj, p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat = flatten(es);
const T = {
"votos":{en:"votes",pt:"votos",fr:"votes",de:"Stimmen",it:"voti",nl:"stemmen",ja:"票",zh:"票",ru:"голосов",ar:"أصوات",hi:"वोट",ko:"투표",tr:"oy",pl:"głosów",sv:"röster",id:"suara",th:"โหวต"},
"Votar":{en:"Vote",pt:"Votar",fr:"Voter",de:"Abstimmen",it:"Vota",nl:"Stemmen",ja:"投票",zh:"投票",ru:"Голосовать",ar:"صوّت",hi:"वोट करें",ko:"투표",tr:"Oy ver",pl:"Głosuj",sv:"Rösta",id:"Vote",th:"โหวต"},
"Votando...":{en:"Voting...",pt:"Votando...",fr:"Vote en cours...",de:"Abstimmung...",it:"Voto in corso...",nl:"Stemmen...",ja:"投票中...",zh:"投票中...",ru:"Голосование...",ar:"جاري التصويت...",hi:"वोट हो रहा है...",ko:"투표 중...",tr:"Oy veriliyor...",pl:"Głosowanie...",sv:"Röstar...",id:"Memvote...",th:"กำลังโหวต..."},
"Tu voto ha sido registrado":{en:"Your vote has been recorded",pt:"Seu voto foi registrado",fr:"Votre vote a été enregistré",de:"Ihre Stimme wurde registriert",it:"Il tuo voto è stato registrato",nl:"Je stem is geregistreerd",ja:"投票が記録されました",zh:"您的投票已记录",ru:"Ваш голос учтён",ar:"تم تسجيل صوتك",hi:"आपका वोट दर्ज हो गया",ko:"투표가 기록되었습니다",tr:"Oyunuz kaydedildi",pl:"Twój głos został zarejestrowany",sv:"Din röst har registrerats",id:"Suara Anda telah dicatat",th:"บันทึกโหวตของคุณแล้ว"},
"Error al votar":{en:"Error voting",pt:"Erro ao votar",fr:"Erreur de vote",de:"Fehler beim Abstimmen",it:"Errore nel voto",nl:"Fout bij stemmen",ja:"投票エラー",zh:"投票出错",ru:"Ошибка голосования",ar:"خطأ في التصويت",hi:"वोट में त्रुटि",ko:"투표 오류",tr:"Oy verme hatası",pl:"Błąd głosowania",sv:"Fel vid röstning",id:"Error saat memvote",th:"เกิดข้อผิดพลาดในการโหวต"},
"Selecciona una opción":{en:"Select an option",pt:"Selecione uma opção",fr:"Sélectionnez une option",de:"Wählen Sie eine Option",it:"Seleziona un'opzione",nl:"Selecteer een optie",ja:"オプションを選択",zh:"选择一个选项",ru:"Выберите вариант",ar:"اختر خياراً",hi:"एक विकल्प चुनें",ko:"옵션을 선택하세요",tr:"Bir seçenek seçin",pl:"Wybierz opcję",sv:"Välj ett alternativ",id:"Pilih opsi",th:"เลือกตัวเลือก"},
"Inicia sesión para votar":{en:"Sign in to vote",pt:"Entre para votar",fr:"Connectez-vous pour voter",de:"Anmelden um abzustimmen",it:"Accedi per votare",nl:"Log in om te stemmen",ja:"投票するにはログイン",zh:"登录以投票",ru:"Войдите чтобы проголосовать",ar:"سجل دخولك للتصويت",hi:"वोट के लिए लॉगिन करें",ko:"투표하려면 로그인",tr:"Oy vermek için giriş yapın",pl:"Zaloguj się aby głosować",sv:"Logga in för att rösta",id:"Masuk untuk memvote",th:"เข้าสู่ระบบเพื่อโหวต"},
"Inicia sesión para participar en esta encuesta":{en:"Sign in to participate in this poll",pt:"Entre para participar desta enquete",fr:"Connectez-vous pour participer",de:"Anmelden um teilzunehmen",it:"Accedi per partecipare",nl:"Log in om deel te nemen",ja:"参加するにはログイン",zh:"登录以参与投票",ru:"Войдите для участия в опросе",ar:"سجل دخولك للمشاركة",hi:"भाग लेने के लिए लॉगिन करें",ko:"참여하려면 로그인",tr:"Katılmak için giriş yapın",pl:"Zaloguj się aby uczestniczyć",sv:"Logga in för att delta",id:"Masuk untuk berpartisipasi",th:"เข้าสู่ระบบเพื่อเข้าร่วม"},
"Esta encuesta ha finalizado":{en:"This poll has ended",pt:"Esta enquete terminou",fr:"Ce sondage est terminé",de:"Diese Umfrage ist beendet",it:"Sondaggio terminato",nl:"Peiling afgelopen",ja:"アンケート終了",zh:"投票已结束",ru:"Опрос завершён",ar:"انتهى الاستطلاع",hi:"सर्वे समाप्त",ko:"투표 종료",tr:"Anket sona erdi",pl:"Ankieta zakończona",sv:"Omröstning avslutad",id:"Jajak pendapat berakhir",th:"โพลสิ้นสุดแล้ว"},
"Finaliza en":{en:"Ends in",pt:"Termina em",fr:"Se termine dans",de:"Endet in",it:"Termina tra",nl:"Eindigt over",ja:"終了まで",zh:"结束于",ru:"Завершится через",ar:"ينتهي في",hi:"समाप्ति",ko:"종료까지",tr:"Bitiş",pl:"Kończy się za",sv:"Slutar om",id:"Berakhir dalam",th:"สิ้นสุดใน"},
"Puedes seleccionar varias opciones":{en:"You can select multiple options",pt:"Você pode selecionar várias opções",fr:"Vous pouvez sélectionner plusieurs options",de:"Mehrere Optionen auswählen",it:"Puoi selezionare più opzioni",nl:"Meerdere opties selecteren",ja:"複数選択可能",zh:"可选择多个",ru:"Можно выбрать несколько",ar:"يمكنك اختيار عدة خيارات",hi:"कई विकल्प चुन सकते हैं",ko:"여러 옵션 선택 가능",tr:"Birden fazla seçenek seçebilirsiniz",pl:"Możesz wybrać kilka opcji",sv:"Välj flera alternativ",id:"Dapat memilih beberapa opsi",th:"เลือกได้หลายตัวเลือก"},
"Crear encuesta":{en:"Create poll",pt:"Criar enquete",fr:"Créer un sondage",de:"Umfrage erstellen",it:"Crea sondaggio",nl:"Peiling maken",ja:"アンケート作成",zh:"创建投票",ru:"Создать опрос",ar:"إنشاء استطلاع",hi:"सर्वे बनाएं",ko:"투표 만들기",tr:"Anket oluştur",pl:"Utwórz ankietę",sv:"Skapa omröstning",id:"Buat jajak pendapat",th:"สร้างโพล"},
"¿Cuál es tu pregunta?":{en:"What is your question?",pt:"Qual é a sua pergunta?",fr:"Quelle est votre question ?",de:"Was ist Ihre Frage?",it:"Qual è la tua domanda?",nl:"Wat is je vraag?",ja:"質問は？",zh:"你的问题是什么？",ru:"Какой вопрос?",ar:"ما هو سؤالك؟",hi:"आपका प्रश्न?",ko:"질문은?",tr:"Sorunuz nedir?",pl:"Jakie jest pytanie?",sv:"Vad är din fråga?",id:"Apa pertanyaan Anda?",th:"คำถามของคุณ?"},
"La pregunta es obligatoria":{en:"Question is required",pt:"Pergunta obrigatória",fr:"Question obligatoire",de:"Frage erforderlich",it:"Domanda obbligatoria",nl:"Vraag verplicht",ja:"質問は必須",zh:"问题必填",ru:"Вопрос обязателен",ar:"السؤال مطلوب",hi:"प्रश्न आवश्यक",ko:"질문 필수",tr:"Soru zorunlu",pl:"Pytanie wymagane",sv:"Frågan obligatorisk",id:"Pertanyaan wajib",th:"ต้องกรอกคำถาม"},
"Opción":{en:"Option",pt:"Opção",fr:"Option",de:"Option",it:"Opzione",nl:"Optie",ja:"オプション",zh:"选项",ru:"Вариант",ar:"خيار",hi:"विकल्प",ko:"옵션",tr:"Seçenek",pl:"Opcja",sv:"Alternativ",id:"Opsi",th:"ตัวเลือก"},
"Añadir opción":{en:"Add option",pt:"Adicionar opção",fr:"Ajouter option",de:"Option hinzufügen",it:"Aggiungi opzione",nl:"Optie toevoegen",ja:"オプション追加",zh:"添加选项",ru:"Добавить вариант",ar:"إضافة خيار",hi:"विकल्प जोड़ें",ko:"옵션 추가",tr:"Seçenek ekle",pl:"Dodaj opcję",sv:"Lägg till alternativ",id:"Tambah opsi",th:"เพิ่มตัวเลือก"},
"Necesitas al menos 2 opciones":{en:"You need at least 2 options",pt:"Precisa de pelo menos 2 opções",fr:"Il faut au moins 2 options",de:"Mindestens 2 Optionen",it:"Almeno 2 opzioni",nl:"Minstens 2 opties nodig",ja:"最低2つ必要",zh:"至少需要2个选项",ru:"Минимум 2 варианта",ar:"تحتاج خيارين على الأقل",hi:"कम से कम 2 विकल्प",ko:"최소 2개 옵션 필요",tr:"En az 2 seçenek gerekli",pl:"Minimum 2 opcje",sv:"Minst 2 alternativ",id:"Minimal 2 opsi",th:"ต้องมีอย่างน้อย 2 ตัวเลือก"},
"Permitir múltiples respuestas":{en:"Allow multiple answers",pt:"Permitir múltiplas respostas",fr:"Autoriser les réponses multiples",de:"Mehrfachantworten erlauben",it:"Risposte multiple",nl:"Meerdere antwoorden toestaan",ja:"複数回答許可",zh:"允许多选",ru:"Множественный выбор",ar:"السماح بإجابات متعددة",hi:"एकाधिक उत्तर अनुमति",ko:"복수 응답 허용",tr:"Birden fazla yanıt izin ver",pl:"Wiele odpowiedzi",sv:"Tillåt flera svar",id:"Izinkan jawaban ganda",th:"อนุญาตตอบหลายข้อ"},
"Mostrar resultados antes de votar":{en:"Show results before voting",pt:"Mostrar resultados antes de votar",fr:"Afficher résultats avant vote",de:"Ergebnisse vor Abstimmung anzeigen",it:"Mostra risultati prima del voto",nl:"Resultaten tonen voor stemmen",ja:"投票前に結果表示",zh:"投票前显示结果",ru:"Показать результаты до голосования",ar:"عرض النتائج قبل التصويت",hi:"वोट से पहले परिणाम दिखाएं",ko:"투표 전 결과 표시",tr:"Sonuçları göster",pl:"Pokaż wyniki przed głosowaniem",sv:"Visa resultat före omröstning",id:"Tampilkan hasil sebelum vote",th:"แสดงผลก่อนโหวต"},
"Establecer fecha de cierre":{en:"Set closing date",pt:"Definir data de encerramento",fr:"Définir date de clôture",de:"Enddatum festlegen",it:"Data di chiusura",nl:"Sluitingsdatum instellen",ja:"締切日設定",zh:"设置截止日期",ru:"Дата окончания",ar:"تحديد تاريخ الإغلاق",hi:"समापन तिथि",ko:"마감일 설정",tr:"Kapanış tarihi belirle",pl:"Data zamknięcia",sv:"Ange slutdatum",id:"Tanggal penutupan",th:"กำหนดวันปิด"},
"Encuesta creada":{en:"Poll created",pt:"Enquete criada",fr:"Sondage créé",de:"Umfrage erstellt",it:"Sondaggio creato",nl:"Peiling aangemaakt",ja:"アンケート作成完了",zh:"投票已创建",ru:"Опрос создан",ar:"تم إنشاء الاستطلاع",hi:"सर्वे बनाया गया",ko:"투표 생성됨",tr:"Anket oluşturuldu",pl:"Ankieta utworzona",sv:"Omröstning skapad",id:"Jajak pendapat dibuat",th:"สร้างโพลแล้ว"},
"Error al crear la encuesta":{en:"Error creating poll",pt:"Erro ao criar enquete",fr:"Erreur de création",de:"Fehler beim Erstellen",it:"Errore creazione",nl:"Fout bij aanmaken",ja:"作成エラー",zh:"创建出错",ru:"Ошибка создания",ar:"خطأ في الإنشاء",hi:"बनाने में त्रुटि",ko:"생성 오류",tr:"Oluşturma hatası",pl:"Błąd tworzenia",sv:"Fel vid skapande",id:"Error membuat",th:"เกิดข้อผิดพลาด"},
"Creando...":{en:"Creating...",pt:"Criando...",fr:"Création...",de:"Erstellen...",it:"Creazione...",nl:"Aanmaken...",ja:"作成中...",zh:"创建中...",ru:"Создание...",ar:"جاري الإنشاء...",hi:"बना रहे हैं...",ko:"생성 중...",tr:"Oluşturuluyor...",pl:"Tworzenie...",sv:"Skapar...",id:"Membuat...",th:"กำลังสร้าง..."},
"Mi cuenta":{en:"My account",pt:"Minha conta",fr:"Mon compte",de:"Mein Konto",it:"Il mio account",nl:"Mijn account",ja:"マイアカウント",zh:"我的账户",ru:"Мой аккаунт",ar:"حسابي",hi:"मेरा खाता",ko:"내 계정",tr:"Hesabım",pl:"Moje konto",sv:"Mitt konto",id:"Akun saya",th:"บัญชีของฉัน"},
"Perfil":{en:"Profile",pt:"Perfil",fr:"Profil",de:"Profil",it:"Profilo",nl:"Profiel",ja:"プロフィール",zh:"个人资料",ru:"Профиль",ar:"الملف الشخصي",hi:"प्रोफ़ाइल",ko:"프로필",tr:"Profil",pl:"Profil",sv:"Profil",id:"Profil",th:"โปรไฟล์"},
"Mis hilos":{en:"My threads",pt:"Meus tópicos",fr:"Mes sujets",de:"Meine Themen",it:"Le mie discussioni",nl:"Mijn onderwerpen",ja:"マイスレッド",zh:"我的主题",ru:"Мои темы",ar:"مواضيعي",hi:"मेरे थ्रेड",ko:"내 스레드",tr:"Konularım",pl:"Moje wątki",sv:"Mina trådar",id:"Thread saya",th:"กระทู้ของฉัน"},
"Configuración":{en:"Settings",pt:"Configurações",fr:"Paramètres",de:"Einstellungen",it:"Impostazioni",nl:"Instellingen",ja:"設定",zh:"设置",ru:"Настройки",ar:"الإعدادات",hi:"सेटिंग्स",ko:"설정",tr:"Ayarlar",pl:"Ustawienia",sv:"Inställningar",id:"Pengaturan",th:"การตั้งค่า"},
"Actualiza tu información personal":{en:"Update your personal information",pt:"Atualize suas informações pessoais",fr:"Mettez à jour vos informations",de:"Persönliche Daten aktualisieren",it:"Aggiorna informazioni personali",nl:"Werk je gegevens bij",ja:"個人情報を更新",zh:"更新个人信息",ru:"Обновите личную информацию",ar:"حدّث معلوماتك",hi:"व्यक्तिगत जानकारी अपडेट करें",ko:"개인 정보 업데이트",tr:"Kişisel bilgilerinizi güncelleyin",pl:"Zaktualizuj dane osobowe",sv:"Uppdatera personlig information",id:"Perbarui informasi pribadi",th:"อัปเดตข้อมูลส่วนตัว"},
"El nombre de usuario no se puede cambiar":{en:"Username cannot be changed",pt:"Nome de usuário não pode ser alterado",fr:"Le nom d'utilisateur ne peut pas être modifié",de:"Benutzername kann nicht geändert werden",it:"Nome utente non modificabile",nl:"Gebruikersnaam kan niet worden gewijzigd",ja:"ユーザー名は変更不可",zh:"用户名不可更改",ru:"Имя пользователя нельзя изменить",ar:"لا يمكن تغيير اسم المستخدم",hi:"उपयोगकर्ता नाम नहीं बदला जा सकता",ko:"사용자 이름 변경 불가",tr:"Kullanıcı adı değiştirilemez",pl:"Nazwa użytkownika niezmienna",sv:"Användarnamnet kan inte ändras",id:"Nama pengguna tidak dapat diubah",th:"ไม่สามารถเปลี่ยนชื่อผู้ใช้ได้"},
"URL del avatar":{en:"Avatar URL",pt:"URL do avatar",fr:"URL de l'avatar",de:"Avatar-URL",it:"URL avatar",nl:"Avatar-URL",ja:"アバターURL",zh:"头像URL",ru:"URL аватара",ar:"رابط الصورة الرمزية",hi:"अवतार URL",ko:"아바타 URL",tr:"Avatar URL",pl:"URL awatara",sv:"Avatar-URL",id:"URL avatar",th:"URL อวาตาร์"},
"Cuéntanos sobre ti...":{en:"Tell us about yourself...",pt:"Conte sobre você...",fr:"Parlez-nous de vous...",de:"Erzählen Sie über sich...",it:"Parlaci di te...",nl:"Vertel over jezelf...",ja:"自己紹介...",zh:"介绍一下自己...",ru:"Расскажите о себе...",ar:"أخبرنا عن نفسك...",hi:"अपने बारे में बताएं...",ko:"자기소개...",tr:"Kendinizden bahsedin...",pl:"Opowiedz o sobie...",sv:"Berätta om dig själv...",id:"Ceritakan tentang diri Anda...",th:"บอกเล่าเกี่ยวกับตัวคุณ..."},
"Tu firma aparecerá al final de tus posts...":{en:"Your signature will appear at the end of your posts...",pt:"Sua assinatura aparecerá no final das publicações...",fr:"Votre signature apparaîtra en fin de messages...",de:"Signatur am Ende Ihrer Beiträge...",it:"Firma in fondo ai post...",nl:"Handtekening onderaan berichten...",ja:"署名は投稿末尾に表示...",zh:"签名将显示在帖子末尾...",ru:"Подпись будет в конце сообщений...",ar:"سيظهر توقيعك في نهاية مشاركاتك...",hi:"हस्ताक्षर पोस्ट के अंत में दिखेगा...",ko:"서명은 게시물 하단에 표시...",tr:"İmzanız gönderilerin sonunda görünecek...",pl:"Podpis na końcu postów...",sv:"Signatur visas i slutet av inlägg...",id:"Tanda tangan di akhir postingan...",th:"ลายเซ็นจะแสดงท้ายโพสต์..."},
"Ciudad":{en:"City",pt:"Cidade",fr:"Ville",de:"Stadt",it:"Città",nl:"Stad",ja:"都市",zh:"城市",ru:"Город",ar:"المدينة",hi:"शहर",ko:"도시",tr:"Şehir",pl:"Miasto",sv:"Stad",id:"Kota",th:"เมือง"},
"Guardar cambios":{en:"Save changes",pt:"Salvar alterações",fr:"Enregistrer",de:"Änderungen speichern",it:"Salva modifiche",nl:"Wijzigingen opslaan",ja:"変更を保存",zh:"保存更改",ru:"Сохранить изменения",ar:"حفظ التغييرات",hi:"बदलाव सहेजें",ko:"변경 저장",tr:"Değişiklikleri kaydet",pl:"Zapisz zmiany",sv:"Spara ändringar",id:"Simpan perubahan",th:"บันทึกการเปลี่ยนแปลง"},
"Guardando...":{en:"Saving...",pt:"Salvando...",fr:"Enregistrement...",de:"Speichern...",it:"Salvataggio...",nl:"Opslaan...",ja:"保存中...",zh:"保存中...",ru:"Сохранение...",ar:"جاري الحفظ...",hi:"सहेज रहे हैं...",ko:"저장 중...",tr:"Kaydediliyor...",pl:"Zapisywanie...",sv:"Sparar...",id:"Menyimpan...",th:"กำลังบันทึก..."},
"Perfil actualizado correctamente":{en:"Profile updated successfully",pt:"Perfil atualizado com sucesso",fr:"Profil mis à jour",de:"Profil aktualisiert",it:"Profilo aggiornato",nl:"Profiel bijgewerkt",ja:"プロフィール更新完了",zh:"资料已更新",ru:"Профиль обновлён",ar:"تم تحديث الملف الشخصي",hi:"प्रोफ़ाइल अपडेट हुआ",ko:"프로필 업데이트됨",tr:"Profil güncellendi",pl:"Profil zaktualizowany",sv:"Profil uppdaterad",id:"Profil diperbarui",th:"อัปเดตโปรไฟล์สำเร็จ"},
"Error al actualizar el perfil":{en:"Error updating profile",pt:"Erro ao atualizar perfil",fr:"Erreur de mise à jour",de:"Fehler beim Aktualisieren",it:"Errore aggiornamento",nl:"Fout bij bijwerken",ja:"更新エラー",zh:"更新出错",ru:"Ошибка обновления",ar:"خطأ في التحديث",hi:"अपडेट में त्रुटि",ko:"업데이트 오류",tr:"Güncelleme hatası",pl:"Błąd aktualizacji",sv:"Fel vid uppdatering",id:"Error memperbarui",th:"เกิดข้อผิดพลาด"},
"Hilos que has creado":{en:"Threads you've created",pt:"Tópicos que você criou",fr:"Sujets que vous avez créés",de:"Ihre erstellten Themen",it:"Discussioni create",nl:"Je aangemaakte onderwerpen",ja:"作成したスレッド",zh:"您创建的主题",ru:"Ваши темы",ar:"مواضيعك",hi:"आपके बनाए थ्रेड",ko:"생성한 스레드",tr:"Oluşturduğunuz konular",pl:"Twoje wątki",sv:"Dina trådar",id:"Thread yang Anda buat",th:"กระทู้ที่คุณสร้าง"},
"No has creado ningún hilo todavía":{en:"You haven't created any threads yet",pt:"Você ainda não criou nenhum tópico",fr:"Aucun sujet créé",de:"Noch keine Themen erstellt",it:"Nessuna discussione creata",nl:"Nog geen onderwerpen",ja:"スレッド未作成",zh:"还没有创建主题",ru:"Вы ещё не создали тем",ar:"لم تنشئ مواضيع بعد",hi:"कोई थ्रेड नहीं बनाया",ko:"스레드를 만들지 않았습니다",tr:"Henüz konu oluşturmadınız",pl:"Brak wątków",sv:"Inga trådar skapade",id:"Belum membuat thread",th:"ยังไม่ได้สร้างกระทู้"},
"Crear tu primer hilo":{en:"Create your first thread",pt:"Crie seu primeiro tópico",fr:"Créez votre premier sujet",de:"Erstes Thema erstellen",it:"Crea prima discussione",nl:"Maak eerste onderwerp",ja:"最初のスレッドを作成",zh:"创建第一个主题",ru:"Создайте первую тему",ar:"أنشئ أول موضوع",hi:"पहला थ्रेड बनाएं",ko:"첫 스레드 만들기",tr:"İlk konunuzu oluşturun",pl:"Utwórz pierwszy wątek",sv:"Skapa din första tråd",id:"Buat thread pertama",th:"สร้างกระทู้แรก"},
"Ajustes de la cuenta":{en:"Account settings",pt:"Configurações da conta",fr:"Paramètres du compte",de:"Kontoeinstellungen",it:"Impostazioni account",nl:"Accountinstellingen",ja:"アカウント設定",zh:"账户设置",ru:"Настройки аккаунта",ar:"إعدادات الحساب",hi:"खाता सेटिंग्स",ko:"계정 설정",tr:"Hesap ayarları",pl:"Ustawienia konta",sv:"Kontoinställningar",id:"Pengaturan akun",th:"การตั้งค่าบัญชี"},
"Gestiona tus preferencias de notificaciones":{en:"Manage notification preferences",pt:"Gerencie preferências de notificações",fr:"Gérez vos préférences de notifications",de:"Benachrichtigungseinstellungen verwalten",it:"Gestisci preferenze notifiche",nl:"Meldingsvoorkeuren beheren",ja:"通知設定を管理",zh:"管理通知偏好",ru:"Управление уведомлениями",ar:"إدارة تفضيلات الإشعارات",hi:"सूचना प्राथमिकताएँ प्रबंधित करें",ko:"알림 환경설정 관리",tr:"Bildirim tercihlerini yönet",pl:"Zarządzaj powiadomieniami",sv:"Hantera aviseringsinställningar",id:"Kelola preferensi notifikasi",th:"จัดการการตั้งค่าการแจ้งเตือน"},
"Privacidad":{en:"Privacy",pt:"Privacidade",fr:"Confidentialité",de:"Datenschutz",it:"Privacy",nl:"Privacy",ja:"プライバシー",zh:"隐私",ru:"Конфиденциальность",ar:"الخصوصية",hi:"गोपनीयता",ko:"개인정보",tr:"Gizlilik",pl:"Prywatność",sv:"Integritet",id:"Privasi",th:"ความเป็นส่วนตัว"},
"Controla quién puede ver tu perfil y contenido":{en:"Control who can see your profile and content",pt:"Controle quem vê seu perfil",fr:"Contrôlez qui voit votre profil",de:"Kontrollieren Sie die Sichtbarkeit",it:"Controlla la visibilità del profilo",nl:"Bepaal wie je profiel ziet",ja:"公開範囲を管理",zh:"控制谁可以查看",ru:"Управление видимостью профиля",ar:"تحكم في من يرى ملفك",hi:"प्रोफ़ाइल दृश्यता नियंत्रित करें",ko:"프로필 공개 범위 관리",tr:"Profil görünürlüğünü kontrol edin",pl:"Kontroluj widoczność profilu",sv:"Kontrollera vem som ser din profil",id:"Kontrol siapa yang melihat profil",th:"ควบคุมการมองเห็นโปรไฟล์"},
"Verificación":{en:"Verification",pt:"Verificação",fr:"Vérification",de:"Verifizierung",it:"Verifica",nl:"Verificatie",ja:"認証",zh:"验证",ru:"Верификация",ar:"التحقق",hi:"सत्यापन",ko:"인증",tr:"Doğrulama",pl:"Weryfikacja",sv:"Verifiering",id:"Verifikasi",th:"การยืนยัน"},
"Verifica tu cuenta para acceder a zonas privadas":{en:"Verify your account to access private areas",pt:"Verifique sua conta para áreas privadas",fr:"Vérifiez votre compte pour les zones privées",de:"Konto verifizieren für private Bereiche",it:"Verifica account per aree private",nl:"Verifieer voor privégebieden",ja:"プライベートエリアへのアクセスにはアカウント認証が必要",zh:"验证账户以访问私密区域",ru:"Подтвердите аккаунт для закрытых разделов",ar:"تحقق من حسابك للمناطق الخاصة",hi:"निजी क्षेत्रों के लिए सत्यापित करें",ko:"비공개 영역 액세스를 위해 인증",tr:"Özel alanlara erişim için doğrulayın",pl:"Zweryfikuj konto dla stref prywatnych",sv:"Verifiera för privata områden",id:"Verifikasi untuk area pribadi",th:"ยืนยันบัญชีเพื่อเข้าถึงพื้นที่ส่วนตัว"},
"Solicitar verificación":{en:"Request verification",pt:"Solicitar verificação",fr:"Demander vérification",de:"Verifizierung anfordern",it:"Richiedi verifica",nl:"Verificatie aanvragen",ja:"認証申請",zh:"申请验证",ru:"Запросить верификацию",ar:"طلب التحقق",hi:"सत्यापन अनुरोध",ko:"인증 요청",tr:"Doğrulama iste",pl:"Poproś o weryfikację",sv:"Begär verifiering",id:"Minta verifikasi",th:"ขอการยืนยัน"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){const fp=path.join(messagesDir,`${lang}.json`);const data=JSON.parse(fs.readFileSync(fp,'utf8'));const df=flatten(data);let ch=0;for(const key in esFlat){const ev=esFlat[key];const cv=df[key];if(cv===undefined||cv===ev){const t=T[ev];if(t&&t[lang]){df[key]=t[lang];ch++;}}}if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch} translations`);}else console.log(`${lang.toUpperCase()}: No changes`);}
console.log('Batch 3a done!');
