const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === ADMIN BADGES (64) ===
"adminBadges.title":{en:"Badge Management",pt:"Gestão de Insígnias",fr:"Gestion des Badges",de:"Badge-Verwaltung",it:"Gestione Badge",nl:"Badge Beheer",ja:"バッジ管理",zh:"徽章管理",ru:"Управление значками",ar:"إدارة الشارات",hi:"बैज प्रबंधन",ko:"배지 관리",tr:"Rozet Yönetimi",pl:"Zarządzanie Odznakami",sv:"Märkeshantering",id:"Manajemen Lencana",th:"การจัดการตรา"},
"adminBadges.description":{en:"Create and assign custom badges",pt:"Criar e atribuir insígnias personalizadas",fr:"Créer et attribuer des badges personnalisés",de:"Benutzerdefinierte Badges erstellen und zuweisen",it:"Crea e assegna badge personalizzati",nl:"Aangepaste badges maken en toewijzen",ja:"カスタムバッジの作成と割り当て",zh:"创建和分配自定义徽章",ru:"Создание и назначение пользовательских значков",ar:"إنشاء وتعيين شارات مخصصة",hi:"कस्टम बैज बनाएं और असाइन करें",ko:"맞춤 배지 생성 및 할당",tr:"Özel rozetler oluşturun ve atayın",pl:"Twórz i przypisuj niestandardowe odznaki",sv:"Skapa och tilldela anpassade märken",id:"Buat dan tetapkan lencana kustom",th:"สร้างและมอบตราที่กำหนดเอง"},
"adminBadges.backToPanel":{en:"← Back to panel",pt:"← Voltar ao painel",fr:"← Retour au panneau",de:"← Zurück zum Panel",it:"← Torna al pannello",nl:"← Terug naar paneel",ja:"← パネルに戻る",zh:"← 返回面板",ru:"← Вернуться к панели",ar:"← العودة إلى اللوحة",hi:"← पैनल पर वापस जाएं",ko:"← 패널로 돌아가기",tr:"← Panele dön",pl:"← Wróć do panelu",sv:"← Tillbaka till panelen",id:"← Kembali ke panel",th:"← กลับไปที่แผงควบคุม"},
"adminBadges.newBadge":{en:"New Badge",pt:"Nova Insígnia",fr:"Nouveau Badge",de:"Neues Badge",it:"Nuovo Badge",nl:"Nieuw Badge",ja:"新しいバッジ",zh:"新徽章",ru:"Новый значок",ar:"شارة جديدة",hi:"नया बैज",ko:"새 배지",tr:"Yeni Rozet",pl:"Nowa Odznaka",sv:"Nytt Märke",id:"Lencana Baru",th:"ตราใหม่"},
"adminBadges.createNewBadge":{en:"Create New Badge",pt:"Criar Nova Insígnia",fr:"Créer un Nouveau Badge",de:"Neues Badge erstellen",it:"Crea Nuovo Badge",nl:"Nieuw Badge Aanmaken",ja:"新しいバッジを作成",zh:"创建新徽章",ru:"Создать новый значок",ar:"إنشاء شارة جديدة",hi:"नया बैज बनाएं",ko:"새 배지 만들기",tr:"Yeni Rozet Oluştur",pl:"Utwórz Nową Odznakę",sv:"Skapa Nytt Märke",id:"Buat Lencana Baru",th:"สร้างตราใหม่"},
"adminBadges.internalName":{en:"Internal name",pt:"Nome interno",fr:"Nom interne",de:"Interner Name",it:"Nome interno",nl:"Interne naam",ja:"内部名",zh:"内部名称",ru:"Внутреннее название",ar:"الاسم الداخلي",hi:"आंतरिक नाम",ko:"내부 이름",tr:"Dahili ad",pl:"Nazwa wewnętrzna",sv:"Internt namn",id:"Nama internal",th:"ชื่อภายใน"},
"adminBadges.displayName":{en:"Display name",pt:"Nome visível",fr:"Nom affiché",de:"Anzeigename",it:"Nome visualizzato",nl:"Weergavenaam",ja:"表示名",zh:"显示名称",ru:"Отображаемое имя",ar:"اسم العرض",hi:"प्रदर्शन नाम",ko:"표시 이름",tr:"Görünen ad",pl:"Nazwa wyświetlana",sv:"Visningsnamn",id:"Nama tampilan",th:"ชื่อที่แสดง"},
"adminBadges.descriptionLabel":{en:"Description",pt:"Descrição",fr:"Description",de:"Beschreibung",it:"Descrizione",nl:"Beschrijving",ja:"説明",zh:"描述",ru:"Описание",ar:"الوصف",hi:"विवरण",ko:"설명",tr:"Açıklama",pl:"Opis",sv:"Beskrivning",id:"Deskripsi",th:"คำอธิบาย"},
"adminBadges.descriptionPlaceholder":{en:"Badge description...",pt:"Descrição da insígnia...",fr:"Description du badge...",de:"Badge-Beschreibung...",it:"Descrizione del badge...",nl:"Badge beschrijving...",ja:"バッジの説明...",zh:"徽章描述...",ru:"Описание значка...",ar:"وصف الشارة...",hi:"बैज विवरण...",ko:"배지 설명...",tr:"Rozet açıklaması...",pl:"Opis odznaki...",sv:"Märkesbeskrivning...",id:"Deskripsi lencana...",th:"คำอธิบายตรา..."},
"adminBadges.icon":{en:"Icon",pt:"Ícone",fr:"Icône",de:"Symbol",it:"Icona",nl:"Pictogram",ja:"アイコン",zh:"图标",ru:"Иконка",ar:"أيقونة",hi:"आइकन",ko:"아이콘",tr:"Simge",pl:"Ikona",sv:"Ikon",id:"Ikon",th:"ไอคอน"},
"adminBadges.color":{en:"Color",pt:"Cor",fr:"Couleur",de:"Farbe",it:"Colore",nl:"Kleur",ja:"色",zh:"颜色",ru:"Цвет",ar:"اللون",hi:"रंग",ko:"색상",tr:"Renk",pl:"Kolor",sv:"Färg",id:"Warna",th:"สี"},
"adminBadges.type":{en:"Type",pt:"Tipo",fr:"Type",de:"Typ",it:"Tipo",nl:"Type",ja:"タイプ",zh:"类型",ru:"Тип",ar:"النوع",hi:"प्रकार",ko:"유형",tr:"Tür",pl:"Typ",sv:"Typ",id:"Tipe",th:"ประเภท"},
"adminBadges.colorPurple":{en:"Purple",pt:"Roxo",fr:"Violet",de:"Lila",it:"Viola",nl:"Paars",ja:"紫",zh:"紫色",ru:"Пурпурный",ar:"بنفسجي",hi:"बैंगनी",ko:"보라",tr:"Mor",pl:"Fioletowy",sv:"Lila",id:"Ungu",th:"ม่วง"},
"adminBadges.colorGreen":{en:"Green",pt:"Verde",fr:"Vert",de:"Grün",it:"Verde",nl:"Groen",ja:"緑",zh:"绿色",ru:"Зелёный",ar:"أخضر",hi:"हरा",ko:"초록",tr:"Yeşil",pl:"Zielony",sv:"Grön",id:"Hijau",th:"เขียว"},
"adminBadges.colorBlue":{en:"Blue",pt:"Azul",fr:"Bleu",de:"Blau",it:"Blu",nl:"Blauw",ja:"青",zh:"蓝色",ru:"Синий",ar:"أزرق",hi:"नीला",ko:"파랑",tr:"Mavi",pl:"Niebieski",sv:"Blå",id:"Biru",th:"น้ำเงิน"},
"adminBadges.colorYellow":{en:"Yellow",pt:"Amarelo",fr:"Jaune",de:"Gelb",it:"Giallo",nl:"Geel",ja:"黄",zh:"黄色",ru:"Жёлтый",ar:"أصفر",hi:"पीला",ko:"노랑",tr:"Sarı",pl:"Żółty",sv:"Gul",id:"Kuning",th:"เหลือง"},
"adminBadges.colorRed":{en:"Red",pt:"Vermelho",fr:"Rouge",de:"Rot",it:"Rosso",nl:"Rood",ja:"赤",zh:"红色",ru:"Красный",ar:"أحمر",hi:"लाल",ko:"빨강",tr:"Kırmızı",pl:"Czerwony",sv:"Röd",id:"Merah",th:"แดง"},
"adminBadges.colorOrange":{en:"Orange",pt:"Laranja",fr:"Orange",de:"Orange",it:"Arancione",nl:"Oranje",ja:"オレンジ",zh:"橙色",ru:"Оранжевый",ar:"برتقالي",hi:"नारंगी",ko:"주황",tr:"Turuncu",pl:"Pomarańczowy",sv:"Orange",id:"Oranye",th:"ส้ม"},
"adminBadges.colorPink":{en:"Pink",pt:"Rosa",fr:"Rose",de:"Rosa",it:"Rosa",nl:"Roze",ja:"ピンク",zh:"粉色",ru:"Розовый",ar:"وردي",hi:"गुलाबी",ko:"분홍",tr:"Pembe",pl:"Różowy",sv:"Rosa",id:"Merah muda",th:"ชมพู"},
"adminBadges.colorFuchsia":{en:"Fuchsia",pt:"Fúcsia",fr:"Fuchsia",de:"Fuchsia",it:"Fucsia",nl:"Fuchsia",ja:"フクシア",zh:"紫红色",ru:"Фуксия",ar:"فوشيا",hi:"फ्यूशिया",ko:"자홍",tr:"Fuşya",pl:"Fuksja",sv:"Fuchsia",id:"Fuchsia",th:"ฟิวเชีย"},
"adminBadges.typePositive":{en:"Positive",pt:"Positiva",fr:"Positive",de:"Positiv",it:"Positiva",nl:"Positief",ja:"ポジティブ",zh:"积极",ru:"Позитивный",ar:"إيجابية",hi:"सकारात्मक",ko:"긍정적",tr:"Pozitif",pl:"Pozytywna",sv:"Positiv",id:"Positif",th:"เชิงบวก"},
"adminBadges.typeNegative":{en:"Negative",pt:"Negativa",fr:"Négative",de:"Negativ",it:"Negativa",nl:"Negatief",ja:"ネガティブ",zh:"消极",ru:"Негативный",ar:"سلبية",hi:"नकारात्मक",ko:"부정적",tr:"Negatif",pl:"Negatywna",sv:"Negativ",id:"Negatif",th:"เชิงลบ"},
"adminBadges.typeNeutral":{en:"Neutral",pt:"Neutra",fr:"Neutre",de:"Neutral",it:"Neutrale",nl:"Neutraal",ja:"中立",zh:"中性",ru:"Нейтральный",ar:"محايدة",hi:"तटस्थ",ko:"중립",tr:"Nötr",pl:"Neutralna",sv:"Neutral",id:"Netral",th:"กลาง"},
"adminBadges.typeSpecial":{en:"Special",pt:"Especial",fr:"Spéciale",de:"Spezial",it:"Speciale",nl:"Speciaal",ja:"スペシャル",zh:"特殊",ru:"Специальный",ar:"خاصة",hi:"विशेष",ko:"특별",tr:"Özel",pl:"Specjalna",sv:"Speciell",id:"Spesial",th:"พิเศษ"},
"adminBadges.whoCanAssign":{en:"Who can assign?",pt:"Quem pode atribuir?",fr:"Qui peut attribuer ?",de:"Wer kann zuweisen?",it:"Chi può assegnare?",nl:"Wie kan toewijzen?",ja:"誰が割り当て可能？",zh:"谁可以分配？",ru:"Кто может назначать?",ar:"من يمكنه التعيين؟",hi:"कौन असाइन कर सकता है?",ko:"누가 할당할 수 있나요?",tr:"Kim atayabilir?",pl:"Kto może przypisać?",sv:"Vem kan tilldela?",id:"Siapa yang dapat menetapkan?",th:"ใครสามารถมอบหมายได้?"},
"adminBadges.anyMod":{en:"Any moderator",pt:"Qualquer moderador",fr:"Tout modérateur",de:"Jeder Moderator",it:"Qualsiasi moderatore",nl:"Elke moderator",ja:"どのモデレーターでも",zh:"任何版主",ru:"Любой модератор",ar:"أي مشرف",hi:"कोई भी मॉडरेटर",ko:"모든 관리자",tr:"Herhangi bir moderatör",pl:"Dowolny moderator",sv:"Vilken moderator som helst",id:"Moderator mana pun",th:"ผู้ดูแลคนใดก็ได้"},
"adminBadges.superModOrAdmin":{en:"Super moderator or Admin",pt:"Super moderador ou Admin",fr:"Super modérateur ou Admin",de:"Super Moderator oder Admin",it:"Super moderatore o Admin",nl:"Super moderator of Admin",ja:"スーパーモデレーターまたは管理者",zh:"超级版主或管理员",ru:"Супер модератор или админ",ar:"مشرف عام أو مسؤول",hi:"सुपर मॉडरेटर या एडमिन",ko:"슈퍼 관리자 또는 어드민",tr:"Süper moderatör veya Admin",pl:"Super moderator lub Admin",sv:"Supermoderator eller Admin",id:"Super moderator atau Admin",th:"ซูเปอร์ผู้ดูแลหรือแอดมิน"},
"adminBadges.adminOnly":{en:"Admin only",pt:"Somente Admin",fr:"Admin uniquement",de:"Nur Admin",it:"Solo Admin",nl:"Alleen Admin",ja:"管理者のみ",zh:"仅管理员",ru:"Только админ",ar:"المسؤول فقط",hi:"केवल एडमिन",ko:"어드민만",tr:"Yalnızca Admin",pl:"Tylko Admin",sv:"Endast Admin",id:"Hanya Admin",th:"แอดมินเท่านั้น"},
"adminBadges.createBadge":{en:"Create Badge",pt:"Criar Insígnia",fr:"Créer le Badge",de:"Badge erstellen",it:"Crea Badge",nl:"Badge Aanmaken",ja:"バッジを作成",zh:"创建徽章",ru:"Создать значок",ar:"إنشاء شارة",hi:"बैज बनाएं",ko:"배지 만들기",tr:"Rozet Oluştur",pl:"Utwórz Odznakę",sv:"Skapa Märke",id:"Buat Lencana",th:"สร้างตรา"},
"adminBadges.editBadge":{en:"Edit Badge",pt:"Editar Insígnia",fr:"Modifier le Badge",de:"Badge bearbeiten",it:"Modifica Badge",nl:"Badge Bewerken",ja:"バッジを編集",zh:"编辑徽章",ru:"Редактировать значок",ar:"تعديل شارة",hi:"बैज संपादित करें",ko:"배지 편집",tr:"Rozet Düzenle",pl:"Edytuj Odznakę",sv:"Redigera Märke",id:"Edit Lencana",th:"แก้ไขตรา"},
"adminBadges.assignBadge":{en:"Assign Badge",pt:"Atribuir Insígnia",fr:"Attribuer le Badge",de:"Badge zuweisen",it:"Assegna Badge",nl:"Badge Toewijzen",ja:"バッジを割り当て",zh:"分配徽章",ru:"Назначить значок",ar:"تعيين شارة",hi:"बैज असाइन करें",ko:"배지 할당",tr:"Rozet Ata",pl:"Przypisz Odznakę",sv:"Tilldela Märke",id:"Tetapkan Lencana",th:"มอบหมายตรา"},
"adminBadges.assignBadgeToUser":{en:"Assign Badge to User",pt:"Atribuir Insígnia ao Usuário",fr:"Attribuer le Badge à l'Utilisateur",de:"Badge dem Benutzer zuweisen",it:"Assegna Badge all'Utente",nl:"Badge aan Gebruiker Toewijzen",ja:"ユーザーにバッジを割り当て",zh:"将徽章分配给用户",ru:"Назначить значок пользователю",ar:"تعيين شارة للمستخدم",hi:"उपयोगकर्ता को बैज असाइन करें",ko:"사용자에게 배지 할당",tr:"Kullanıcıya Rozet Ata",pl:"Przypisz Odznakę Użytkownikowi",sv:"Tilldela Märke till Användare",id:"Tetapkan Lencana ke Pengguna",th:"มอบหมายตราให้ผู้ใช้"},
"adminBadges.badge":{en:"Badge",pt:"Insígnia",fr:"Badge",de:"Badge",it:"Badge",nl:"Badge",ja:"バッジ",zh:"徽章",ru:"Значок",ar:"شارة",hi:"बैज",ko:"배지",tr:"Rozet",pl:"Odznaka",sv:"Märke",id:"Lencana",th:"ตรา"},
"adminBadges.selectBadge":{en:"Select badge",pt:"Selecionar insígnia",fr:"Sélectionner badge",de:"Badge auswählen",it:"Seleziona badge",nl:"Badge selecteren",ja:"バッジを選択",zh:"选择徽章",ru:"Выбрать значок",ar:"اختيار شارة",hi:"बैज चुनें",ko:"배지 선택",tr:"Rozet seç",pl:"Wybierz odznakę",sv:"Välj märke",id:"Pilih lencana",th:"เลือกตรา"},
"adminBadges.reasonOptional":{en:"Reason (optional)",pt:"Razão (opcional)",fr:"Raison (optionnelle)",de:"Grund (optional)",it:"Motivo (opzionale)",nl:"Reden (optioneel)",ja:"理由（任意）",zh:"原因（可选）",ru:"Причина (необязательно)",ar:"السبب (اختياري)",hi:"कारण (वैकल्पिक)",ko:"사유 (선택)",tr:"Sebep (isteğe bağlı)",pl:"Powód (opcjonalnie)",sv:"Anledning (valfritt)",id:"Alasan (opsional)",th:"เหตุผล (ไม่จำเป็น)"},
"adminBadges.reasonPlaceholder":{en:"Reason for assigning this badge...",pt:"Razão para atribuir esta insígnia...",fr:"Raison de l'attribution de ce badge...",de:"Grund für die Zuweisung dieses Badges...",it:"Motivo per assegnare questo badge...",nl:"Reden voor toewijzing van dit badge...",ja:"このバッジを割り当てる理由...",zh:"分配此徽章的原因...",ru:"Причина назначения этого значка...",ar:"سبب تعيين هذه الشارة...",hi:"यह बैज असाइन करने का कारण...",ko:"이 배지를 할당하는 사유...",tr:"Bu rozeti atama nedeni...",pl:"Powód przypisania tej odznaki...",sv:"Anledning till tilldelning av detta märke...",id:"Alasan menetapkan lencana ini...",th:"เหตุผลในการมอบหมายตรานี้..."},
"adminBadges.assign":{en:"Assign",pt:"Atribuir",fr:"Attribuer",de:"Zuweisen",it:"Assegna",nl:"Toewijzen",ja:"割り当て",zh:"分配",ru:"Назначить",ar:"تعيين",hi:"असाइन करें",ko:"할당",tr:"Ata",pl:"Przypisz",sv:"Tilldela",id:"Tetapkan",th:"มอบหมาย"},
"adminBadges.assignments":{en:"Assignments",pt:"Atribuições",fr:"Attributions",de:"Zuweisungen",it:"Assegnazioni",nl:"Toewijzingen",ja:"割り当て一覧",zh:"分配记录",ru:"Назначения",ar:"التعيينات",hi:"असाइनमेंट",ko:"할당 목록",tr:"Atamalar",pl:"Przypisania",sv:"Tilldelningar",id:"Penetapan",th:"การมอบหมาย"},
"adminBadges.availableBadges":{en:"Available Badges",pt:"Insígnias Disponíveis",fr:"Badges Disponibles",de:"Verfügbare Badges",it:"Badge Disponibili",nl:"Beschikbare Badges",ja:"利用可能なバッジ",zh:"可用徽章",ru:"Доступные значки",ar:"الشارات المتاحة",hi:"उपलब्ध बैज",ko:"사용 가능한 배지",tr:"Mevcut Rozetler",pl:"Dostępne Odznaki",sv:"Tillgängliga Märken",id:"Lencana Tersedia",th:"ตราที่พร้อมใช้งาน"},
"adminBadges.searchPlaceholder":{en:"Search by username...",pt:"Buscar por nome de usuário...",fr:"Rechercher par nom d'utilisateur...",de:"Nach Benutzername suchen...",it:"Cerca per nome utente...",nl:"Zoeken op gebruikersnaam...",ja:"ユーザー名で検索...",zh:"按用户名搜索...",ru:"Поиск по имени пользователя...",ar:"البحث باسم المستخدم...",hi:"उपयोगकर्ता नाम से खोजें...",ko:"사용자 이름으로 검색...",tr:"Kullanıcı adıyla ara...",pl:"Szukaj po nazwie użytkownika...",sv:"Sök efter användarnamn...",id:"Cari berdasarkan nama pengguna...",th:"ค้นหาด้วยชื่อผู้ใช้..."},
"adminBadges.noAssignments":{en:"No badges assigned",pt:"Nenhuma insígnia atribuída",fr:"Aucun badge attribué",de:"Keine Badges zugewiesen",it:"Nessun badge assegnato",nl:"Geen badges toegewezen",ja:"バッジの割り当てなし",zh:"没有分配徽章",ru:"Значки не назначены",ar:"لا توجد شارات معينة",hi:"कोई बैज असाइन नहीं",ko:"할당된 배지 없음",tr:"Atanmış rozet yok",pl:"Brak przypisanych odznak",sv:"Inga märken tilldelade",id:"Tidak ada lencana yang ditetapkan",th:"ไม่มีตราที่มอบหมาย"},
"adminBadges.reason":{en:"Reason",pt:"Razão",fr:"Raison",de:"Grund",it:"Motivo",nl:"Reden",ja:"理由",zh:"原因",ru:"Причина",ar:"السبب",hi:"कारण",ko:"사유",tr:"Sebep",pl:"Powód",sv:"Anledning",id:"Alasan",th:"เหตุผล"},
"adminBadges.assignedBy":{en:"Assigned by",pt:"Atribuída por",fr:"Attribué par",de:"Zugewiesen von",it:"Assegnato da",nl:"Toegewezen door",ja:"割り当て者",zh:"分配者",ru:"Назначено",ar:"معين من قبل",hi:"द्वारा असाइन",ko:"할당자",tr:"Atayan",pl:"Przypisane przez",sv:"Tilldelad av",id:"Ditetapkan oleh",th:"มอบหมายโดย"},
"adminBadges.removeBadge":{en:"Remove badge",pt:"Remover insígnia",fr:"Retirer le badge",de:"Badge entfernen",it:"Rimuovi badge",nl:"Badge verwijderen",ja:"バッジを削除",zh:"移除徽章",ru:"Убрать значок",ar:"إزالة الشارة",hi:"बैज हटाएं",ko:"배지 제거",tr:"Rozeti kaldır",pl:"Usuń odznakę",sv:"Ta bort märke",id:"Hapus lencana",th:"ลบตรา"},
"adminBadges.assignableBy":{en:"Assignable by",pt:"Atribuível por",fr:"Attribuable par",de:"Zuweisbar durch",it:"Assegnabile da",nl:"Toewijsbaar door",ja:"割り当て可能者",zh:"可由...分配",ru:"Может назначать",ar:"يمكن تعيينها بواسطة",hi:"द्वारा असाइन करने योग्य",ko:"할당 가능 대상",tr:"Atanabilir",pl:"Przypisywane przez",sv:"Tilldelningsbar av",id:"Dapat ditetapkan oleh",th:"มอบหมายได้โดย"},
"adminBadges.moderators":{en:"Moderators",pt:"Moderadores",fr:"Modérateurs",de:"Moderatoren",it:"Moderatori",nl:"Moderators",ja:"モデレーター",zh:"版主",ru:"Модераторы",ar:"المشرفون",hi:"मॉडरेटर",ko:"관리자",tr:"Moderatörler",pl:"Moderatorzy",sv:"Moderatorer",id:"Moderator",th:"ผู้ดูแล"},
"adminBadges.superMods":{en:"Super Mods",pt:"Super Mods",fr:"Super Mods",de:"Super Mods",it:"Super Mods",nl:"Super Mods",ja:"スーパーモデレーター",zh:"超级版主",ru:"Супер моды",ar:"المشرفون العامون",hi:"सुपर मॉड",ko:"슈퍼 관리자",tr:"Süper Modlar",pl:"Super Modowie",sv:"Supermoderatorer",id:"Super Mod",th:"ซูเปอร์ผู้ดูแล"},
"adminBadges.admins":{en:"Admins",pt:"Admins",fr:"Admins",de:"Admins",it:"Admin",nl:"Admins",ja:"管理者",zh:"管理员",ru:"Админы",ar:"المسؤولون",hi:"एडमिन",ko:"어드민",tr:"Adminler",pl:"Admini",sv:"Administratörer",id:"Admin",th:"แอดมิน"},
"adminBadges.deactivate":{en:"Deactivate",pt:"Desativar",fr:"Désactiver",de:"Deaktivieren",it:"Disattiva",nl:"Deactiveren",ja:"無効化",zh:"停用",ru:"Деактивировать",ar:"تعطيل",hi:"निष्क्रिय करें",ko:"비활성화",tr:"Devre dışı bırak",pl:"Dezaktywuj",sv:"Inaktivera",id:"Nonaktifkan",th:"ปิดใช้งาน"},
"adminBadges.activate":{en:"Activate",pt:"Ativar",fr:"Activer",de:"Aktivieren",it:"Attiva",nl:"Activeren",ja:"有効化",zh:"启用",ru:"Активировать",ar:"تفعيل",hi:"सक्रिय करें",ko:"활성화",tr:"Etkinleştir",pl:"Aktywuj",sv:"Aktivera",id:"Aktifkan",th:"เปิดใช้งาน"},
"adminBadges.nameAndDisplayRequired":{en:"Name and display name are required",pt:"Nome e nome de exibição são obrigatórios",fr:"Le nom et le nom affiché sont requis",de:"Name und Anzeigename sind erforderlich",it:"Nome e nome visualizzato sono obbligatori",nl:"Naam en weergavenaam zijn vereist",ja:"名前と表示名は必須です",zh:"名称和显示名称为必填项",ru:"Название и отображаемое имя обязательны",ar:"الاسم واسم العرض مطلوبان",hi:"नाम और प्रदर्शन नाम आवश्यक हैं",ko:"이름과 표시 이름은 필수입니다",tr:"Ad ve görünen ad gereklidir",pl:"Nazwa i nazwa wyświetlana są wymagane",sv:"Namn och visningsnamn krävs",id:"Nama dan nama tampilan wajib diisi",th:"ต้องระบุชื่อและชื่อที่แสดง"},
"adminBadges.errorCreating":{en:"Error creating badge",pt:"Erro ao criar insígnia",fr:"Erreur de création du badge",de:"Fehler beim Erstellen des Badges",it:"Errore nella creazione del badge",nl:"Fout bij aanmaken badge",ja:"バッジ作成エラー",zh:"创建徽章出错",ru:"Ошибка создания значка",ar:"خطأ في إنشاء الشارة",hi:"बैज बनाने में त्रुटि",ko:"배지 생성 오류",tr:"Rozet oluşturma hatası",pl:"Błąd tworzenia odznaki",sv:"Fel vid skapande av märke",id:"Error membuat lencana",th:"เกิดข้อผิดพลาดในการสร้างตรา"},
"adminBadges.badgeCreated":{en:"Badge created",pt:"Insígnia criada",fr:"Badge créé",de:"Badge erstellt",it:"Badge creato",nl:"Badge aangemaakt",ja:"バッジが作成されました",zh:"徽章已创建",ru:"Значок создан",ar:"تم إنشاء الشارة",hi:"बैज बनाया गया",ko:"배지 생성됨",tr:"Rozet oluşturuldu",pl:"Odznaka utworzona",sv:"Märke skapat",id:"Lencana dibuat",th:"สร้างตราแล้ว"},
"adminBadges.errorUpdating":{en:"Error updating badge",pt:"Erro ao atualizar insígnia",fr:"Erreur de mise à jour du badge",de:"Fehler beim Aktualisieren des Badges",it:"Errore nell'aggiornamento del badge",nl:"Fout bij bijwerken badge",ja:"バッジ更新エラー",zh:"更新徽章出错",ru:"Ошибка обновления значка",ar:"خطأ في تحديث الشارة",hi:"बैज अपडेट में त्रुटि",ko:"배지 업데이트 오류",tr:"Rozet güncelleme hatası",pl:"Błąd aktualizacji odznaki",sv:"Fel vid uppdatering av märke",id:"Error memperbarui lencana",th:"เกิดข้อผิดพลาดในการอัปเดตตรา"},
"adminBadges.badgeUpdated":{en:"Badge updated",pt:"Insígnia atualizada",fr:"Badge mis à jour",de:"Badge aktualisiert",it:"Badge aggiornato",nl:"Badge bijgewerkt",ja:"バッジが更新されました",zh:"徽章已更新",ru:"Значок обновлён",ar:"تم تحديث الشارة",hi:"बैज अपडेट किया गया",ko:"배지 업데이트됨",tr:"Rozet güncellendi",pl:"Odznaka zaktualizowana",sv:"Märke uppdaterat",id:"Lencana diperbarui",th:"อัปเดตตราแล้ว"},
"adminBadges.confirmDelete":{en:"Delete this badge? It will be removed from all users.",pt:"Excluir esta insígnia? Será removida de todos os usuários.",fr:"Supprimer ce badge ? Il sera retiré de tous les utilisateurs.",de:"Dieses Badge löschen? Es wird von allen Benutzern entfernt.",it:"Eliminare questo badge? Verrà rimosso da tutti gli utenti.",nl:"Dit badge verwijderen? Het wordt bij alle gebruikers verwijderd.",ja:"このバッジを削除しますか？すべてのユーザーから削除されます。",zh:"删除此徽章？将从所有用户中移除。",ru:"Удалить этот значок? Он будет убран у всех пользователей.",ar:"حذف هذه الشارة؟ ستتم إزالتها من جميع المستخدمين.",hi:"यह बैज हटाएं? सभी उपयोगकर्ताओं से हटा दिया जाएगा।",ko:"이 배지를 삭제하시겠습니까? 모든 사용자에게서 제거됩니다.",tr:"Bu rozeti sil? Tüm kullanıcılardan kaldırılacak.",pl:"Usunąć tę odznakę? Zostanie usunięta od wszystkich użytkowników.",sv:"Ta bort detta märke? Det tas bort från alla användare.",id:"Hapus lencana ini? Akan dihapus dari semua pengguna.",th:"ลบตรานี้? จะถูกลบจากผู้ใช้ทั้งหมด"},
"adminBadges.errorDeleting":{en:"Error deleting badge",pt:"Erro ao excluir insígnia",fr:"Erreur de suppression du badge",de:"Fehler beim Löschen des Badges",it:"Errore nell'eliminazione del badge",nl:"Fout bij verwijderen badge",ja:"バッジ削除エラー",zh:"删除徽章出错",ru:"Ошибка удаления значка",ar:"خطأ في حذف الشارة",hi:"बैज हटाने में त्रुटि",ko:"배지 삭제 오류",tr:"Rozet silme hatası",pl:"Błąd usuwania odznaki",sv:"Fel vid borttagning av märke",id:"Error menghapus lencana",th:"เกิดข้อผิดพลาดในการลบตรา"},
"adminBadges.badgeDeleted":{en:"Badge deleted",pt:"Insígnia excluída",fr:"Badge supprimé",de:"Badge gelöscht",it:"Badge eliminato",nl:"Badge verwijderd",ja:"バッジが削除されました",zh:"徽章已删除",ru:"Значок удалён",ar:"تم حذف الشارة",hi:"बैज हटाया गया",ko:"배지 삭제됨",tr:"Rozet silindi",pl:"Odznaka usunięta",sv:"Märke borttaget",id:"Lencana dihapus",th:"ลบตราแล้ว"},
"adminBadges.userAndBadgeRequired":{en:"User and badge are required",pt:"Usuário e insígnia são obrigatórios",fr:"L'utilisateur et le badge sont requis",de:"Benutzer und Badge sind erforderlich",it:"Utente e badge sono obbligatori",nl:"Gebruiker en badge zijn vereist",ja:"ユーザーとバッジは必須です",zh:"用户和徽章为必填项",ru:"Пользователь и значок обязательны",ar:"المستخدم والشارة مطلوبان",hi:"उपयोगकर्ता और बैज आवश्यक हैं",ko:"사용자와 배지는 필수입니다",tr:"Kullanıcı ve rozet gereklidir",pl:"Użytkownik i odznaka są wymagane",sv:"Användare och märke krävs",id:"Pengguna dan lencana wajib diisi",th:"ต้องระบุผู้ใช้และตรา"},
"adminBadges.userNotFound":{en:"User not found",pt:"Usuário não encontrado",fr:"Utilisateur introuvable",de:"Benutzer nicht gefunden",it:"Utente non trovato",nl:"Gebruiker niet gevonden",ja:"ユーザーが見つかりません",zh:"用户未找到",ru:"Пользователь не найден",ar:"المستخدم غير موجود",hi:"उपयोगकर्ता नहीं मिला",ko:"사용자를 찾을 수 없음",tr:"Kullanıcı bulunamadı",pl:"Użytkownik nie znaleziony",sv:"Användare hittades inte",id:"Pengguna tidak ditemukan",th:"ไม่พบผู้ใช้"},
"adminBadges.userAlreadyHasBadge":{en:"User already has this badge",pt:"O usuário já possui esta insígnia",fr:"L'utilisateur a déjà ce badge",de:"Benutzer hat dieses Badge bereits",it:"L'utente ha già questo badge",nl:"Gebruiker heeft dit badge al",ja:"ユーザーはすでにこのバッジを持っています",zh:"用户已拥有此徽章",ru:"У пользователя уже есть этот значок",ar:"المستخدم لديه هذه الشارة بالفعل",hi:"उपयोगकर्ता के पास पहले से यह बैज है",ko:"사용자가 이미 이 배지를 보유하고 있습니다",tr:"Kullanıcının zaten bu rozeti var",pl:"Użytkownik już ma tę odznakę",sv:"Användaren har redan detta märke",id:"Pengguna sudah memiliki lencana ini",th:"ผู้ใช้มีตรานี้แล้ว"},
"adminBadges.errorAssigning":{en:"Error assigning badge",pt:"Erro ao atribuir insígnia",fr:"Erreur d'attribution du badge",de:"Fehler beim Zuweisen des Badges",it:"Errore nell'assegnazione del badge",nl:"Fout bij toewijzen badge",ja:"バッジ割り当てエラー",zh:"分配徽章出错",ru:"Ошибка назначения значка",ar:"خطأ في تعيين الشارة",hi:"बैज असाइन करने में त्रुटि",ko:"배지 할당 오류",tr:"Rozet atama hatası",pl:"Błąd przypisywania odznaki",sv:"Fel vid tilldelning av märke",id:"Error menetapkan lencana",th:"เกิดข้อผิดพลาดในการมอบหมายตรา"},
"adminBadges.badgeAssigned":{en:"Badge assigned",pt:"Insígnia atribuída",fr:"Badge attribué",de:"Badge zugewiesen",it:"Badge assegnato",nl:"Badge toegewezen",ja:"バッジが割り当てられました",zh:"徽章已分配",ru:"Значок назначен",ar:"تم تعيين الشارة",hi:"बैज असाइन किया गया",ko:"배지 할당됨",tr:"Rozet atandı",pl:"Odznaka przypisana",sv:"Märke tilldelat",id:"Lencana ditetapkan",th:"มอบหมายตราแล้ว"},
"adminBadges.badgeRemoved":{en:"Badge removed",pt:"Insígnia removida",fr:"Badge retiré",de:"Badge entfernt",it:"Badge rimosso",nl:"Badge verwijderd",ja:"バッジが削除されました",zh:"徽章已移除",ru:"Значок удалён",ar:"تم إزالة الشارة",hi:"बैज हटाया गया",ko:"배지 제거됨",tr:"Rozet kaldırıldı",pl:"Odznaka usunięta",sv:"Märke borttaget",id:"Lencana dihapus",th:"ลบตราแล้ว"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2d (adminBadges - 64 keys) done!');
