const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === CONTACT (remaining 27) ===
"contact.description":{en:"Get in touch with us",pt:"Entre em contato conosco",fr:"Contactez-nous",de:"Kontaktieren Sie uns",it:"Contattaci",nl:"Neem contact met ons op",ja:"お問い合わせください",zh:"联系我们",ru:"Свяжитесь с нами",ar:"تواصل معنا",hi:"हमसे संपर्क करें",ko:"문의하기",tr:"Bize ulaşın",pl:"Skontaktuj się z nami",sv:"Kontakta oss",id:"Hubungi kami",th:"ติดต่อเรา"},
"contact.emailLabel":{en:"Email",pt:"Email",fr:"Email",de:"E-Mail",it:"Email",nl:"E-mail",ja:"メール",zh:"邮箱",ru:"Электронная почта",ar:"البريد الإلكتروني",hi:"ईमेल",ko:"이메일",tr:"E-posta",pl:"Email",sv:"E-post",id:"Email",th:"อีเมล"},
"contact.responseTimeValue":{en:"24-48 business hours",pt:"24-48 horas úteis",fr:"24-48 heures ouvrables",de:"24-48 Geschäftsstunden",it:"24-48 ore lavorative",nl:"24-48 werkuren",ja:"24〜48営業時間",zh:"24-48个工作时间",ru:"24-48 рабочих часов",ar:"24-48 ساعة عمل",hi:"24-48 कार्य घंटे",ko:"영업시간 24-48시간",tr:"24-48 iş saati",pl:"24-48 godzin roboczych",sv:"24-48 arbetstimmar",id:"24-48 jam kerja",th:"24-48 ชั่วโมงทำการ"},
"contact.prioritySupport":{en:"Priority support",pt:"Suporte prioritário",fr:"Support prioritaire",de:"Prioritätsunterstützung",it:"Supporto prioritario",nl:"Prioritaire ondersteuning",ja:"優先サポート",zh:"优先支持",ru:"Приоритетная поддержка",ar:"دعم ذو أولوية",hi:"प्राथमिकता सहायता",ko:"우선 지원",tr:"Öncelikli destek",pl:"Priorytetowe wsparcie",sv:"Prioriterat stöd",id:"Dukungan prioritas",th:"การสนับสนุนระดับพิเศษ"},
"contact.prioritySupportDesc":{en:"For VIP and verified users",pt:"Para usuários VIP e verificados",fr:"Pour les utilisateurs VIP et vérifiés",de:"Für VIP- und verifizierte Benutzer",it:"Per utenti VIP e verificati",nl:"Voor VIP- en geverifieerde gebruikers",ja:"VIPおよび認証済みユーザー向け",zh:"面向VIP和已验证用户",ru:"Для VIP и верифицированных пользователей",ar:"للمستخدمين VIP والموثقين",hi:"VIP और सत्यापित उपयोगकर्ताओं के लिए",ko:"VIP 및 인증된 사용자용",tr:"VIP ve doğrulanmış kullanıcılar için",pl:"Dla użytkowników VIP i zweryfikowanych",sv:"För VIP och verifierade användare",id:"Untuk pengguna VIP dan terverifikasi",th:"สำหรับผู้ใช้ VIP และที่ยืนยันแล้ว"},
"contact.sendMessage":{en:"Send us a message",pt:"Envie-nos uma mensagem",fr:"Envoyez-nous un message",de:"Senden Sie uns eine Nachricht",it:"Inviaci un messaggio",nl:"Stuur ons een bericht",ja:"メッセージを送信",zh:"给我们发送消息",ru:"Отправьте нам сообщение",ar:"أرسل لنا رسالة",hi:"हमें संदेश भेजें",ko:"메시지 보내기",tr:"Bize mesaj gönderin",pl:"Wyślij nam wiadomość",sv:"Skicka oss ett meddelande",id:"Kirim pesan kepada kami",th:"ส่งข้อความถึงเรา"},
"contact.sendMessageDesc":{en:"Fill out the form and we'll respond as soon as possible",pt:"Preencha o formulário e responderemos o mais rápido possível",fr:"Remplissez le formulaire et nous vous répondrons",de:"Füllen Sie das Formular aus und wir antworten so bald wie möglich",it:"Compila il modulo e ti risponderemo",nl:"Vul het formulier in en we reageren zo snel mogelijk",ja:"フォームに記入してください。できるだけ早くお返事します",zh:"填写表格，我们将尽快回复",ru:"Заполните форму, и мы ответим как можно скорее",ar:"املأ النموذج وسنرد في أقرب وقت",hi:"फ़ॉर्म भरें और हम जल्द से जल्द जवाब देंगे",ko:"양식을 작성해 주시면 빨리 답변 드리겠습니다",tr:"Formu doldurun, en kısa sürede yanıt vereceğiz",pl:"Wypełnij formularz, a odpowiemy jak najszybciej",sv:"Fyll i formuläret så svarar vi så snart som möjligt",id:"Isi formulir dan kami akan merespons sesegera mungkin",th:"กรอกแบบฟอร์มและเราจะตอบกลับโดยเร็วที่สุด"},
"contact.beforeContact":{en:"Before contacting us",pt:"Antes de nos contatar",fr:"Avant de nous contacter",de:"Bevor Sie uns kontaktieren",it:"Prima di contattarci",nl:"Voordat je contact opneemt",ja:"お問い合わせの前に",zh:"联系我们之前",ru:"Перед обращением к нам",ar:"قبل التواصل معنا",hi:"हमसे संपर्क करने से पहले",ko:"문의하기 전에",tr:"Bize ulaşmadan önce",pl:"Zanim się z nami skontaktujesz",sv:"Innan du kontaktar oss",id:"Sebelum menghubungi kami",th:"ก่อนติดต่อเรา"},
"contact.beforeContactDesc":{en:"We recommend checking our FAQ section where you can find answers to the most common questions",pt:"Recomendamos verificar nossa seção de Perguntas Frequentes onde encontrará respostas para as consultas mais comuns",fr:"Nous recommandons de consulter notre section FAQ où vous trouverez des réponses aux questions courantes",de:"Wir empfehlen, unseren FAQ-Bereich zu überprüfen",it:"Ti consigliamo di consultare la sezione FAQ dove troverai risposte alle domande più comuni",nl:"We raden aan onze FAQ-sectie te bekijken",ja:"よくある質問セクションを確認することをお勧めします",zh:"我们建议查看常见问题部分",ru:"Рекомендуем проверить раздел FAQ",ar:"نوصي بالاطلاع على قسم الأسئلة الشائعة",hi:"हम FAQ अनुभाग की जांच करने की अनुशंसा करते हैं",ko:"자주 묻는 질문 섹션을 먼저 확인해 보세요",tr:"SSS bölümümüzü kontrol etmenizi öneririz",pl:"Zalecamy sprawdzenie sekcji FAQ",sv:"Vi rekommenderar att kolla vår FAQ-sektion",id:"Kami sarankan memeriksa bagian FAQ kami",th:"เราแนะนำให้ตรวจสอบส่วนคำถามที่พบบ่อยก่อน"},
"contact.moderationNote":{en:"If your inquiry is about moderation or reports, use the forum's built-in report system for a faster response",pt:"Se sua consulta é sobre moderação ou reportes, use o sistema de reportes integrado para uma resposta mais rápida",fr:"Si votre demande concerne la modération, utilisez le système intégré pour une réponse plus rapide",de:"Wenn Ihre Anfrage Moderation betrifft, nutzen Sie das integrierte Meldesystem",it:"Se la richiesta riguarda la moderazione, usa il sistema integrato per una risposta più rapida",nl:"Als je vraag over moderatie gaat, gebruik dan het ingebouwde rapportsysteem",ja:"モデレーションに関する場合は、フォーラムの組み込みレポートシステムをご利用ください",zh:"如果是关于管理或举报的咨询，请使用论坛内置的举报系统以获得更快的回复",ru:"Если вопрос касается модерации, используйте встроенную систему жалоб форума",ar:"إذا كان استفسارك عن الإشراف، استخدم نظام البلاغات المدمج",hi:"मॉडरेशन संबंधी पूछताछ के लिए फ़ोरम की अंतर्निहित रिपोर्ट प्रणाली का उपयोग करें",ko:"관리나 신고 관련 문의라면 포럼 내장 신고 시스템을 사용하세요",tr:"Moderasyonla ilgili sorunuz varsa dahili bildirim sistemini kullanın",pl:"Jeśli zapytanie dotyczy moderacji, użyj wbudowanego systemu zgłoszeń",sv:"Om din fråga gäller moderering, använd forumets inbyggda rapportsystem",id:"Jika pertanyaan Anda tentang moderasi, gunakan sistem laporan bawaan forum",th:"หากคำถามเกี่ยวกับการดูแล ใช้ระบบรายงานในตัวของฟอรั่ม"},
"contact.queryTypes":{en:"Types of inquiries",pt:"Tipos de consultas",fr:"Types de demandes",de:"Arten von Anfragen",it:"Tipi di richieste",nl:"Soorten vragen",ja:"お問い合わせの種類",zh:"咨询类型",ru:"Типы обращений",ar:"أنواع الاستفسارات",hi:"पूछताछ के प्रकार",ko:"문의 유형",tr:"Soru türleri",pl:"Rodzaje zapytań",sv:"Typer av förfrågningar",id:"Jenis pertanyaan",th:"ประเภทของคำถาม"},
"contact.technicalProblems":{en:"Technical account problems",pt:"Problemas técnicos com a conta",fr:"Problèmes techniques du compte",de:"Technische Kontoprobleme",it:"Problemi tecnici dell'account",nl:"Technische accountproblemen",ja:"アカウントの技術的な問題",zh:"账户技术问题",ru:"Технические проблемы с аккаунтом",ar:"مشاكل تقنية في الحساب",hi:"तकनीकी खाता समस्याएं",ko:"기술적 계정 문제",tr:"Teknik hesap sorunları",pl:"Problemy techniczne z kontem",sv:"Tekniska kontoproblem",id:"Masalah teknis akun",th:"ปัญหาทางเทคนิคของบัญชี"},
"contact.verificationQueries":{en:"Verification inquiries",pt:"Consultas sobre verificação",fr:"Questions sur la vérification",de:"Fragen zur Verifizierung",it:"Domande sulla verifica",nl:"Verificatievragen",ja:"認証に関するお問い合わせ",zh:"验证咨询",ru:"Вопросы о верификации",ar:"استفسارات التحقق",hi:"सत्यापन पूछताछ",ko:"인증 문의",tr:"Doğrulama soruları",pl:"Pytania o weryfikację",sv:"Verifieringsfrågor",id:"Pertanyaan verifikasi",th:"คำถามเกี่ยวกับการยืนยัน"},
"contact.suggestionsImprovements":{en:"Suggestions and improvements",pt:"Sugestões e melhorias",fr:"Suggestions et améliorations",de:"Vorschläge und Verbesserungen",it:"Suggerimenti e miglioramenti",nl:"Suggesties en verbeteringen",ja:"提案と改善",zh:"建议和改进",ru:"Предложения и улучшения",ar:"اقتراحات وتحسينات",hi:"सुझाव और सुधार",ko:"제안 및 개선",tr:"Öneriler ve iyileştirmeler",pl:"Sugestie i ulepszenia",sv:"Förslag och förbättringar",id:"Saran dan perbaikan",th:"ข้อเสนอแนะและการปรับปรุง"},
"contact.collaborationsAdvertising":{en:"Collaborations and advertising",pt:"Colaborações e publicidade",fr:"Collaborations et publicité",de:"Kooperationen und Werbung",it:"Collaborazioni e pubblicità",nl:"Samenwerkingen en advertenties",ja:"コラボレーションと広告",zh:"合作与广告",ru:"Сотрудничество и реклама",ar:"تعاون وإعلانات",hi:"सहयोग और विज्ञापन",ko:"협업 및 광고",tr:"İş birlikleri ve reklam",pl:"Współpraca i reklama",sv:"Samarbeten och annonsering",id:"Kolaborasi dan iklan",th:"ความร่วมมือและโฆษณา"},
"contact.dataDeleteRequests":{en:"Data deletion requests",pt:"Solicitações de exclusão de dados",fr:"Demandes de suppression de données",de:"Datenlöschanfragen",it:"Richieste di eliminazione dati",nl:"Verzoeken om gegevensverwijdering",ja:"データ削除リクエスト",zh:"数据删除请求",ru:"Запросы на удаление данных",ar:"طلبات حذف البيانات",hi:"डेटा हटाने के अनुरोध",ko:"데이터 삭제 요청",tr:"Veri silme talepleri",pl:"Wnioski o usunięcie danych",sv:"Begäran om dataradering",id:"Permintaan penghapusan data",th:"คำขอลบข้อมูล"},
"contact.formDesc":{en:"Fill out the form and we'll respond as soon as possible",pt:"Preencha o formulário e responderemos o mais rápido possível",fr:"Remplissez le formulaire et nous vous répondrons",de:"Füllen Sie das Formular aus und wir antworten schnellstmöglich",it:"Compila il modulo e ti risponderemo",nl:"Vul het formulier in en we reageren zo snel mogelijk",ja:"フォームに記入してください",zh:"填写表格，我们将尽快回复",ru:"Заполните форму, и мы ответим",ar:"املأ النموذج وسنرد عليك",hi:"फ़ॉर्म भरें और हम जल्द जवाब देंगे",ko:"양식을 작성하시면 답변 드리겠습니다",tr:"Formu doldurun, yanıt vereceğiz",pl:"Wypełnij formularz, odpowiemy",sv:"Fyll i formuläret så svarar vi",id:"Isi formulir dan kami akan merespons",th:"กรอกแบบฟอร์มและเราจะตอบกลับ"},
"contact.messageSent":{en:"Message sent",pt:"Mensagem enviada",fr:"Message envoyé",de:"Nachricht gesendet",it:"Messaggio inviato",nl:"Bericht verzonden",ja:"メッセージ送信済み",zh:"消息已发送",ru:"Сообщение отправлено",ar:"تم إرسال الرسالة",hi:"संदेश भेजा गया",ko:"메시지 전송됨",tr:"Mesaj gönderildi",pl:"Wiadomość wysłana",sv:"Meddelande skickat",id:"Pesan terkirim",th:"ส่งข้อความแล้ว"},
"contact.messageSentDesc":{en:"We'll respond as soon as possible",pt:"Responderemos o mais rápido possível",fr:"Nous vous répondrons dès que possible",de:"Wir antworten so bald wie möglich",it:"Risponderemo il prima possibile",nl:"We reageren zo snel mogelijk",ja:"できるだけ早くお返事します",zh:"我们将尽快回复",ru:"Мы ответим как можно скорее",ar:"سنرد في أقرب وقت",hi:"हम जल्द से जल्द जवाब देंगे",ko:"가능한 빨리 답변 드리겠습니다",tr:"En kısa sürede yanıt vereceğiz",pl:"Odpowiemy jak najszybciej",sv:"Vi svarar så snart som möjligt",id:"Kami akan merespons sesegera mungkin",th:"เราจะตอบกลับโดยเร็วที่สุด"},
"contact.beforeContactDesc1":{en:"We recommend checking our",pt:"Recomendamos verificar nossa seção de",fr:"Nous recommandons de consulter notre",de:"Wir empfehlen, unsere",it:"Ti consigliamo di consultare le nostre",nl:"We raden aan onze",ja:"お問い合わせの前に",zh:"我们建议查看我们的",ru:"Рекомендуем ознакомиться с",ar:"نوصي بالاطلاع على",hi:"हम अनुशंसा करते हैं",ko:"먼저 확인해 보세요",tr:"Kontrol etmenizi öneririz",pl:"Zalecamy sprawdzenie",sv:"Vi rekommenderar att kolla vår",id:"Kami sarankan memeriksa",th:"เราแนะนำให้ตรวจสอบ"},
"contact.faq":{en:"Frequently Asked Questions",pt:"Perguntas Frequentes",fr:"Foire aux Questions",de:"Häufig gestellte Fragen",it:"Domande Frequenti",nl:"Veelgestelde Vragen",ja:"よくある質問",zh:"常见问题",ru:"Часто задаваемые вопросы",ar:"الأسئلة الشائعة",hi:"अक्सर पूछे जाने वाले प्रश्न",ko:"자주 묻는 질문",tr:"Sık Sorulan Sorular",pl:"Najczęściej Zadawane Pytania",sv:"Vanliga Frågor",id:"Pertanyaan Umum",th:"คำถามที่พบบ่อย"},
"contact.beforeContactDesc2":{en:"where you can find answers to the most common questions.",pt:"onde poderá encontrar respostas para as consultas mais comuns.",fr:"où vous trouverez les réponses aux questions courantes.",de:"wo Sie Antworten auf die häufigsten Fragen finden.",it:"dove potrai trovare risposte alle domande più comuni.",nl:"waar je antwoorden vindt op de meest gestelde vragen.",ja:"最もよくある質問への回答を見つけることができます。",zh:"您可以找到最常见问题的答案。",ru:"где вы найдёте ответы на частые вопросы.",ar:"حيث يمكنك العثور على إجابات للأسئلة الشائعة.",hi:"जहां आप सबसे आम सवालों के जवाब पा सकते हैं।",ko:"가장 일반적인 질문에 대한 답변을 찾을 수 있습니다.",tr:"en sık sorulan soruların cevaplarını bulabilirsiniz.",pl:"gdzie znajdziesz odpowiedzi na najczęstsze pytania.",sv:"där du hittar svar på vanliga frågor.",id:"di mana Anda dapat menemukan jawaban pertanyaan umum.",th:"ที่คุณสามารถค้นหาคำตอบสำหรับคำถามที่พบบ่อย"},
"contact.queryType1":{en:"Technical account problems",pt:"Problemas técnicos com a conta",fr:"Problèmes techniques du compte",de:"Technische Kontoprobleme",it:"Problemi tecnici dell'account",nl:"Technische accountproblemen",ja:"アカウントの技術的な問題",zh:"账户技术问题",ru:"Технические проблемы с аккаунтом",ar:"مشاكل تقنية في الحساب",hi:"तकनीकी खाता समस्याएं",ko:"기술적 계정 문제",tr:"Teknik hesap sorunları",pl:"Problemy techniczne z kontem",sv:"Tekniska kontoproblem",id:"Masalah teknis akun",th:"ปัญหาทางเทคนิคของบัญชี"},
"contact.queryType2":{en:"Verification inquiries",pt:"Consultas sobre verificação",fr:"Questions sur la vérification",de:"Fragen zur Verifizierung",it:"Domande sulla verifica",nl:"Verificatievragen",ja:"認証に関するお問い合わせ",zh:"验证咨询",ru:"Вопросы о верификации",ar:"استفسارات التحقق",hi:"सत्यापन पूछताछ",ko:"인증 문의",tr:"Doğrulama soruları",pl:"Pytania o weryfikację",sv:"Verifieringsfrågor",id:"Pertanyaan verifikasi",th:"คำถามเกี่ยวกับการยืนยัน"},
"contact.queryType3":{en:"Suggestions and improvements",pt:"Sugestões e melhorias",fr:"Suggestions et améliorations",de:"Vorschläge und Verbesserungen",it:"Suggerimenti e miglioramenti",nl:"Suggesties en verbeteringen",ja:"提案と改善",zh:"建议和改进",ru:"Предложения и улучшения",ar:"اقتراحات وتحسينات",hi:"सुझाव और सुधार",ko:"제안 및 개선",tr:"Öneriler ve iyileştirmeler",pl:"Sugestie i ulepszenia",sv:"Förslag och förbättringar",id:"Saran dan perbaikan",th:"ข้อเสนอแนะและการปรับปรุง"},
"contact.queryType4":{en:"Collaborations and advertising",pt:"Colaborações e publicidade",fr:"Collaborations et publicité",de:"Kooperationen und Werbung",it:"Collaborazioni e pubblicità",nl:"Samenwerkingen en advertenties",ja:"コラボレーションと広告",zh:"合作与广告",ru:"Сотрудничество и реклама",ar:"تعاون وإعلانات",hi:"सहयोग और विज्ञापन",ko:"협업 및 광고",tr:"İş birlikleri ve reklam",pl:"Współpraca i reklama",sv:"Samarbeten och annonsering",id:"Kolaborasi dan iklan",th:"ความร่วมมือและโฆษณา"},
"contact.queryType5":{en:"Data deletion requests",pt:"Solicitações de exclusão de dados",fr:"Demandes de suppression de données",de:"Datenlöschanfragen",it:"Richieste di eliminazione dati",nl:"Verzoeken om gegevensverwijdering",ja:"データ削除リクエスト",zh:"数据删除请求",ru:"Запросы на удаление данных",ar:"طلبات حذف البيانات",hi:"डेटा हटाने के अनुरोध",ko:"데이터 삭제 요청",tr:"Veri silme talepleri",pl:"Wnioski o usunięcie danych",sv:"Begäran om dataradering",id:"Permintaan penghapusan data",th:"คำขอลบข้อมูล"},

// === REPORT (remaining 21) ===
"report.reportContent":{en:"Report content",pt:"Reportar conteúdo",fr:"Signaler un contenu",de:"Inhalt melden",it:"Segnala contenuto",nl:"Inhoud rapporteren",ja:"コンテンツを報告",zh:"举报内容",ru:"Пожаловаться на контент",ar:"الإبلاغ عن محتوى",hi:"सामग्री की रिपोर्ट",ko:"콘텐츠 신고",tr:"İçerik bildir",pl:"Zgłoś treść",sv:"Rapportera innehåll",id:"Laporkan konten",th:"รายงานเนื้อหา"},
"report.description":{en:"Tell us why you think this content violates the community guidelines.",pt:"Explique por que este conteúdo viola as normas da comunidade.",fr:"Dites-nous pourquoi ce contenu enfreint les règles.",de:"Erklären Sie, warum dieser Inhalt gegen die Richtlinien verstößt.",it:"Spiegaci perché questo contenuto viola le linee guida.",nl:"Vertel ons waarom deze inhoud de richtlijnen schendt.",ja:"このコンテンツがガイドライン違反と思う理由を教えてください。",zh:"请说明为什么您认为此内容违反了社区准则。",ru:"Расскажите, почему этот контент нарушает правила сообщества.",ar:"أخبرنا لماذا تعتقد أن هذا المحتوى ينتهك إرشادات المجتمع.",hi:"बताएं कि यह सामग्री दिशानिर्देशों का उल्लंघन क्यों करती है।",ko:"이 콘텐츠가 가이드라인을 위반하는 이유를 알려주세요.",tr:"Bu içeriğin topluluk kurallarını neden ihlal ettiğini açıklayın.",pl:"Powiedz dlaczego ta treść narusza zasady społeczności.",sv:"Berätta varför detta innehåll bryter mot riktlinjerna.",id:"Jelaskan mengapa konten ini melanggar pedoman komunitas.",th:"บอกเราว่าทำไมเนื้อหานี้ละเมิดแนวปฏิบัติของชุมชน"},
"report.descriptionPlaceholder":{en:"Provide more details...",pt:"Forneça mais detalhes...",fr:"Fournissez plus de détails...",de:"Weitere Details angeben...",it:"Fornisci più dettagli...",nl:"Geef meer details...",ja:"詳細を記入...",zh:"提供更多详情...",ru:"Предоставьте больше деталей...",ar:"قدم المزيد من التفاصيل...",hi:"अधिक विवरण दें...",ko:"자세한 내용을 입력하세요...",tr:"Daha fazla ayrıntı verin...",pl:"Podaj więcej szczegółów...",sv:"Ange mer detaljer...",id:"Berikan detail lebih lanjut...",th:"ให้รายละเอียดเพิ่มเติม..."},
"report.reasons.off_topic":{en:"Off topic",pt:"Fora de tópico",fr:"Hors sujet",de:"Off-Topic",it:"Fuori tema",nl:"Off-topic",ja:"トピック外",zh:"离题",ru:"Не по теме",ar:"خارج الموضوع",hi:"विषय से हटकर",ko:"주제와 무관",tr:"Konu dışı",pl:"Nie na temat",sv:"Utanför ämnet",id:"Di luar topik",th:"นอกเรื่อง"},
"report.reasons.misinformation":{en:"Misinformation",pt:"Desinformação",fr:"Désinformation",de:"Falschinformation",it:"Disinformazione",nl:"Misinformatie",ja:"誤情報",zh:"虚假信息",ru:"Дезинформация",ar:"معلومات مضللة",hi:"गलत जानकारी",ko:"오보",tr:"Yanlış bilgi",pl:"Dezinformacja",sv:"Desinformation",id:"Misinformasi",th:"ข้อมูลเท็จ"},
"report.harassment":{en:"Harassment or bullying",pt:"Assédio ou bullying",fr:"Harcèlement ou intimidation",de:"Belästigung oder Mobbing",it:"Molestie o bullismo",nl:"Intimidatie of pesten",ja:"嫌がらせまたはいじめ",zh:"骚扰或欺凌",ru:"Преследование или травля",ar:"تحرش أو تنمر",hi:"उत्पीड़न या बदमाशी",ko:"괴롭힘 또는 왕따",tr:"Taciz veya zorbalık",pl:"Nękanie lub zastraszanie",sv:"Trakasserier eller mobbning",id:"Pelecehan atau intimidasi",th:"การคุกคามหรือการกลั่นแกล้ง"},
"report.inappropriate":{en:"Inappropriate content",pt:"Conteúdo inapropriado",fr:"Contenu inapproprié",de:"Unangemessener Inhalt",it:"Contenuto inappropriato",nl:"Ongepaste inhoud",ja:"不適切なコンテンツ",zh:"不当内容",ru:"Неприемлемый контент",ar:"محتوى غير لائق",hi:"अनुचित सामग्री",ko:"부적절한 콘텐츠",tr:"Uygunsuz içerik",pl:"Nieodpowiednia treść",sv:"Olämpligt innehåll",id:"Konten tidak pantas",th:"เนื้อหาไม่เหมาะสม"},
"report.offTopic":{en:"Off topic",pt:"Fora de tópico",fr:"Hors sujet",de:"Off-Topic",it:"Fuori tema",nl:"Off-topic",ja:"トピック外",zh:"离题",ru:"Не по теме",ar:"خارج الموضوع",hi:"विषय से हटकर",ko:"주제와 무관",tr:"Konu dışı",pl:"Nie na temat",sv:"Utanför ämnet",id:"Di luar topik",th:"นอกเรื่อง"},
"report.duplicate":{en:"Duplicate",pt:"Duplicado",fr:"Doublon",de:"Duplikat",it:"Duplicato",nl:"Duplicaat",ja:"重複",zh:"重复",ru:"Дубликат",ar:"مكرر",hi:"डुप्लिकेट",ko:"중복",tr:"Kopya",pl:"Duplikat",sv:"Duplikat",id:"Duplikat",th:"ซ้ำ"},
"report.misinformation":{en:"Misinformation",pt:"Desinformação",fr:"Désinformation",de:"Falschinformation",it:"Disinformazione",nl:"Misinformatie",ja:"誤情報",zh:"虚假信息",ru:"Дезинформация",ar:"معلومات مضللة",hi:"गलत जानकारी",ko:"오보",tr:"Yanlış bilgi",pl:"Dezinformacja",sv:"Desinformation",id:"Misinformasi",th:"ข้อมูลเท็จ"},
"report.illegal":{en:"Illegal content",pt:"Conteúdo ilegal",fr:"Contenu illégal",de:"Illegaler Inhalt",it:"Contenuto illegale",nl:"Illegale inhoud",ja:"違法コンテンツ",zh:"违法内容",ru:"Нелегальный контент",ar:"محتوى غير قانوني",hi:"अवैध सामग्री",ko:"불법 콘텐츠",tr:"Yasadışı içerik",pl:"Nielegalna treść",sv:"Olagligt innehåll",id:"Konten ilegal",th:"เนื้อหาผิดกฎหมาย"},
"report.fake":{en:"Fake account or impersonation",pt:"Conta falsa ou falsificação",fr:"Faux compte ou usurpation",de:"Falsches Konto oder Identitätsdiebstahl",it:"Account falso o impersonificazione",nl:"Nep account of nabootsing",ja:"偽アカウントまたはなりすまし",zh:"虚假账户或冒充",ru:"Поддельный аккаунт или выдача себя за другого",ar:"حساب مزيف أو انتحال شخصية",hi:"नकली खाता या प्रतिरूपण",ko:"가짜 계정 또는 사칭",tr:"Sahte hesap veya kimliğe bürünme",pl:"Fałszywe konto lub podszywanie się",sv:"Falskt konto eller imitation",id:"Akun palsu atau peniruan",th:"บัญชีปลอมหรือการแอบอ้าง"},
"report.other":{en:"Other",pt:"Outro",fr:"Autre",de:"Sonstiges",it:"Altro",nl:"Anders",ja:"その他",zh:"其他",ru:"Другое",ar:"أخرى",hi:"अन्य",ko:"기타",tr:"Diğer",pl:"Inne",sv:"Övrigt",id:"Lainnya",th:"อื่นๆ"},
"report.sendReport":{en:"Send report",pt:"Enviar reporte",fr:"Envoyer le signalement",de:"Bericht senden",it:"Invia segnalazione",nl:"Rapport verzenden",ja:"報告を送信",zh:"发送举报",ru:"Отправить жалобу",ar:"إرسال البلاغ",hi:"रिपोर्ट भेजें",ko:"신고 보내기",tr:"Rapor gönder",pl:"Wyślij zgłoszenie",sv:"Skicka rapport",id:"Kirim laporan",th:"ส่งรายงาน"},
"report.sending":{en:"Sending...",pt:"Enviando...",fr:"Envoi...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"发送中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"भेज रहे हैं...",ko:"전송 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"report.errorSending":{en:"Error sending report",pt:"Erro ao enviar o reporte",fr:"Erreur d'envoi du signalement",de:"Fehler beim Senden des Berichts",it:"Errore nell'invio della segnalazione",nl:"Fout bij verzenden rapport",ja:"報告送信エラー",zh:"发送举报出错",ru:"Ошибка отправки жалобы",ar:"خطأ في إرسال البلاغ",hi:"रिपोर्ट भेजने में त्रुटि",ko:"신고 전송 오류",tr:"Rapor gönderme hatası",pl:"Błąd wysyłania zgłoszenia",sv:"Fel vid sändning av rapport",id:"Error mengirim laporan",th:"เกิดข้อผิดพลาดในการส่งรายงาน"},
"report.loginToReport":{en:"Sign in to report",pt:"Entre para reportar",fr:"Connectez-vous pour signaler",de:"Anmelden zum Melden",it:"Accedi per segnalare",nl:"Log in om te rapporteren",ja:"報告するにはログイン",zh:"登录以举报",ru:"Войдите, чтобы пожаловаться",ar:"سجل دخولك للإبلاغ",hi:"रिपोर्ट करने के लिए लॉगिन करें",ko:"신고하려면 로그인하세요",tr:"Bildirmek için giriş yapın",pl:"Zaloguj się aby zgłosić",sv:"Logga in för att rapportera",id:"Masuk untuk melaporkan",th:"เข้าสู่ระบบเพื่อรายงาน"},
"report.selectReasonError":{en:"Select a reason",pt:"Selecione um motivo",fr:"Sélectionnez un motif",de:"Wählen Sie einen Grund",it:"Seleziona un motivo",nl:"Selecteer een reden",ja:"理由を選択してください",zh:"请选择原因",ru:"Выберите причину",ar:"اختر سبباً",hi:"एक कारण चुनें",ko:"사유를 선택하세요",tr:"Bir neden seçin",pl:"Wybierz powód",sv:"Välj en anledning",id:"Pilih alasan",th:"เลือกเหตุผล"},
"report.helpCommunity":{en:"Help us keep the community safe. Select the reason for reporting.",pt:"Ajude-nos a manter a comunidade segura. Selecione o motivo do reporte.",fr:"Aidez-nous à garder la communauté sûre. Sélectionnez le motif.",de:"Helfen Sie uns, die Community sicher zu halten. Wählen Sie den Grund.",it:"Aiutaci a mantenere la comunità sicura. Seleziona il motivo.",nl:"Help ons de community veilig te houden. Selecteer de reden.",ja:"コミュニティの安全維持にご協力ください。報告理由を選択してください。",zh:"帮助我们保持社区安全。选择举报原因。",ru:"Помогите нам поддерживать безопасность сообщества. Выберите причину жалобы.",ar:"ساعدنا في الحفاظ على سلامة المجتمع. اختر سبب الإبلاغ.",hi:"समुदाय को सुरक्षित रखने में मदद करें। रिपोर्ट का कारण चुनें।",ko:"커뮤니티를 안전하게 유지하도록 도와주세요. 신고 사유를 선택하세요.",tr:"Topluluğu güvende tutmamıza yardım edin. Bildirim nedenini seçin.",pl:"Pomóż nam utrzymać bezpieczeństwo społeczności. Wybierz powód zgłoszenia.",sv:"Hjälp oss hålla gemenskapen säker. Välj anledning.",id:"Bantu kami menjaga keamanan komunitas. Pilih alasan pelaporan.",th:"ช่วยเรารักษาชุมชนให้ปลอดภัย เลือกเหตุผลในการรายงาน"},
"report.reportSuccess":{en:"Report sent",pt:"Reporte enviado",fr:"Signalement envoyé",de:"Bericht gesendet",it:"Segnalazione inviata",nl:"Rapport verzonden",ja:"報告送信済み",zh:"举报已发送",ru:"Жалоба отправлена",ar:"تم إرسال البلاغ",hi:"रिपोर्ट भेजा गया",ko:"신고가 전송되었습니다",tr:"Rapor gönderildi",pl:"Zgłoszenie wysłane",sv:"Rapport skickad",id:"Laporan terkirim",th:"ส่งรายงานแล้ว"},
"report.reportSuccessDesc":{en:"Our team will review your report soon",pt:"Nossa equipe revisará seu reporte em breve",fr:"Notre équipe examinera votre signalement bientôt",de:"Unser Team wird Ihren Bericht bald prüfen",it:"Il nostro team esaminerà la tua segnalazione presto",nl:"Ons team zal je rapport binnenkort beoordelen",ja:"チームがまもなくあなたの報告を確認します",zh:"我们的团队将很快审核您的举报",ru:"Наша команда скоро рассмотрит вашу жалобу",ar:"سيراجع فريقنا بلاغك قريباً",hi:"हमारी टीम जल्द ही आपकी रिपोर्ट की समीक्षा करेगी",ko:"팀이 곧 신고를 검토합니다",tr:"Ekibimiz raporunuzu yakında inceleyecek",pl:"Nasz zespół wkrótce sprawdzi twoje zgłoszenie",sv:"Vårt team granskar din rapport snart",id:"Tim kami akan meninjau laporan Anda segera",th:"ทีมของเราจะตรวจสอบรายงานของคุณเร็วๆ นี้"},

// === LANGUAGE (4) ===
"language.es":{en:"Español",pt:"Español",fr:"Español",de:"Español",it:"Español",nl:"Español",ja:"Español",zh:"Español",ru:"Español",ar:"Español",hi:"Español",ko:"Español",tr:"Español",pl:"Español",sv:"Español",id:"Español",th:"Español"},
"language.en":{en:"English",pt:"English",fr:"English",de:"English",it:"English",nl:"English",ja:"English",zh:"English",ru:"English",ar:"English",hi:"English",ko:"English",tr:"English",pl:"English",sv:"English",id:"English",th:"English"},
"language.pt":{en:"Português",pt:"Português",fr:"Português",de:"Português",it:"Português",nl:"Português",ja:"Português",zh:"Português",ru:"Português",ar:"Português",hi:"Português",ko:"Português",tr:"Português",pl:"Português",sv:"Português",id:"Português",th:"Português"},
"language.fr":{en:"Français",pt:"Français",fr:"Français",de:"Français",it:"Français",nl:"Français",ja:"Français",zh:"Français",ru:"Français",ar:"Français",hi:"Français",ko:"Français",tr:"Français",pl:"Français",sv:"Français",id:"Français",th:"Français"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 1c (contact+report+language) done!');
