const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === ALERTS ===
"alerts.selectCountry":{en:"Select country",pt:"Selecionar país",fr:"Sélectionner un pays",de:"Land auswählen",it:"Seleziona paese",nl:"Land selecteren",ja:"国を選択",zh:"选择国家",ru:"Выбрать страну",ar:"اختر البلد",hi:"देश चुनें",ko:"국가 선택",tr:"Ülke seçin",pl:"Wybierz kraj",sv:"Välj land",id:"Pilih negara",th:"เลือกประเทศ"},
"alerts.allRegions":{en:"All regions",pt:"Todas as regiões",fr:"Toutes les régions",de:"Alle Regionen",it:"Tutte le regioni",nl:"Alle regio's",ja:"全地域",zh:"所有地区",ru:"Все регионы",ar:"جميع المناطق",hi:"सभी क्षेत्र",ko:"모든 지역",tr:"Tüm bölgeler",pl:"Wszystkie regiony",sv:"Alla regioner",id:"Semua wilayah",th:"ทุกภูมิภาค"},
"alerts.add":{en:"Add",pt:"Adicionar",fr:"Ajouter",de:"Hinzufügen",it:"Aggiungi",nl:"Toevoegen",ja:"追加",zh:"添加",ru:"Добавить",ar:"إضافة",hi:"जोड़ें",ko:"추가",tr:"Ekle",pl:"Dodaj",sv:"Lägg till",id:"Tambah",th:"เพิ่ม"},
"alerts.noAlertsDescription":{en:"Add an alert to receive notifications for new posts",pt:"Adicione um alerta para receber notificações de novos anúncios",fr:"Ajoutez une alerte pour recevoir des notifications",de:"Fügen Sie eine Benachrichtigung hinzu",it:"Aggiungi un avviso per ricevere notifiche",nl:"Voeg een melding toe voor nieuwe berichten",ja:"新しい投稿の通知を受け取るアラートを追加",zh:"添加提醒以接收新帖子的通知",ru:"Добавьте оповещение для уведомлений о новых объявлениях",ar:"أضف تنبيهاً لتلقي إشعارات بالمنشورات الجديدة",hi:"नई पोस्ट की सूचना प्राप्त करने के लिए अलर्ट जोड़ें",ko:"새 게시물 알림을 받을 알림을 추가하세요",tr:"Yeni gönderiler için bildirim almak üzere uyarı ekleyin",pl:"Dodaj alert aby otrzymywać powiadomienia",sv:"Lägg till en avisering för nya inlägg",id:"Tambahkan peringatan untuk notifikasi posting baru",th:"เพิ่มการแจ้งเตือนเพื่อรับการแจ้งเตือนโพสต์ใหม่"},
"alerts.alertEnabled":{en:"Alert enabled",pt:"Alerta ativado",fr:"Alerte activée",de:"Benachrichtigung aktiviert",it:"Avviso attivato",nl:"Melding ingeschakeld",ja:"アラート有効",zh:"提醒已启用",ru:"Оповещение включено",ar:"تم تفعيل التنبيه",hi:"अलर्ट सक्षम",ko:"알림 활성화됨",tr:"Uyarı etkinleştirildi",pl:"Alert włączony",sv:"Avisering aktiverad",id:"Peringatan diaktifkan",th:"เปิดการแจ้งเตือน"},
"alerts.alertDisabled":{en:"Alert disabled",pt:"Alerta desativado",fr:"Alerte désactivée",de:"Benachrichtigung deaktiviert",it:"Avviso disattivato",nl:"Melding uitgeschakeld",ja:"アラート無効",zh:"提醒已禁用",ru:"Оповещение отключено",ar:"تم إيقاف التنبيه",hi:"अलर्ट अक्षम",ko:"알림 비활성화됨",tr:"Uyarı devre dışı",pl:"Alert wyłączony",sv:"Avisering inaktiverad",id:"Peringatan dinonaktifkan",th:"ปิดการแจ้งเตือน"},
"alerts.alertExists":{en:"You already have an alert for this area",pt:"Você já tem um alerta para esta zona",fr:"Vous avez déjà une alerte pour cette zone",de:"Sie haben bereits eine Benachrichtigung für dieses Gebiet",it:"Hai già un avviso per questa zona",nl:"Je hebt al een melding voor dit gebied",ja:"このエリアのアラートは既に設定済みです",zh:"您已为此区域设置了提醒",ru:"У вас уже есть оповещение для этой зоны",ar:"لديك تنبيه بالفعل لهذه المنطقة",hi:"इस क्षेत्र के लिए आपके पास पहले से अलर्ट है",ko:"이 지역에 대한 알림이 이미 있습니다",tr:"Bu bölge için zaten bir uyarınız var",pl:"Masz już alert dla tej strefy",sv:"Du har redan en avisering för detta område",id:"Anda sudah memiliki peringatan untuk area ini",th:"คุณมีการแจ้งเตือนสำหรับพื้นที่นี้แล้ว"},
"alerts.errorLoading":{en:"Error loading alerts",pt:"Erro ao carregar alertas",fr:"Erreur de chargement des alertes",de:"Fehler beim Laden der Benachrichtigungen",it:"Errore caricamento avvisi",nl:"Fout bij laden meldingen",ja:"アラートの読み込みエラー",zh:"加载提醒出错",ru:"Ошибка загрузки оповещений",ar:"خطأ في تحميل التنبيهات",hi:"अलर्ट लोड करने में त्रुटि",ko:"알림 로딩 오류",tr:"Uyarıları yükleme hatası",pl:"Błąd ładowania alertów",sv:"Fel vid laddning av aviseringar",id:"Error memuat peringatan",th:"เกิดข้อผิดพลาดในการโหลดการแจ้งเตือน"},
"alerts.errorAdding":{en:"Error adding alert",pt:"Erro ao adicionar alerta",fr:"Erreur d'ajout d'alerte",de:"Fehler beim Hinzufügen",it:"Errore aggiunta avviso",nl:"Fout bij toevoegen",ja:"アラート追加エラー",zh:"添加提醒出错",ru:"Ошибка добавления оповещения",ar:"خطأ في إضافة التنبيه",hi:"अलर्ट जोड़ने में त्रुटि",ko:"알림 추가 오류",tr:"Uyarı ekleme hatası",pl:"Błąd dodawania alertu",sv:"Fel vid tillägg av avisering",id:"Error menambah peringatan",th:"เกิดข้อผิดพลาดในการเพิ่มการแจ้งเตือน"},
"alerts.errorUpdating":{en:"Error updating alert",pt:"Erro ao atualizar alerta",fr:"Erreur de mise à jour",de:"Fehler beim Aktualisieren",it:"Errore aggiornamento avviso",nl:"Fout bij bijwerken",ja:"アラート更新エラー",zh:"更新提醒出错",ru:"Ошибка обновления оповещения",ar:"خطأ في تحديث التنبيه",hi:"अलर्ट अपडेट में त्रुटि",ko:"알림 업데이트 오류",tr:"Uyarı güncelleme hatası",pl:"Błąd aktualizacji alertu",sv:"Fel vid uppdatering",id:"Error memperbarui peringatan",th:"เกิดข้อผิดพลาดในการอัปเดต"},
"alerts.errorDeleting":{en:"Error deleting alert",pt:"Erro ao eliminar alerta",fr:"Erreur de suppression",de:"Fehler beim Löschen",it:"Errore eliminazione avviso",nl:"Fout bij verwijderen",ja:"アラート削除エラー",zh:"删除提醒出错",ru:"Ошибка удаления оповещения",ar:"خطأ في حذف التنبيه",hi:"अलर्ट हटाने में त्रुटि",ko:"알림 삭제 오류",tr:"Uyarı silme hatası",pl:"Błąd usuwania alertu",sv:"Fel vid borttagning",id:"Error menghapus peringatan",th:"เกิดข้อผิดพลาดในการลบ"},

// === USER ===
"user.nowFollowing":{en:"Now following {username}",pt:"Agora seguindo {username}",fr:"Vous suivez {username}",de:"Du folgst jetzt {username}",it:"Ora segui {username}",nl:"Je volgt nu {username}",ja:"{username}をフォローしました",zh:"正在关注{username}",ru:"Вы подписались на {username}",ar:"أنت الآن تتابع {username}",hi:"अब {username} को फ़ॉलो कर रहे हैं",ko:"{username}을(를) 팔로우합니다",tr:"{username} takip ediliyor",pl:"Obserwujesz {username}",sv:"Följer nu {username}",id:"Sekarang mengikuti {username}",th:"กำลังติดตาม {username}"},
"user.unfollowed":{en:"Unfollowed {username}",pt:"Deixou de seguir {username}",fr:"Vous ne suivez plus {username}",de:"Du folgst {username} nicht mehr",it:"Non segui più {username}",nl:"Je volgt {username} niet meer",ja:"{username}のフォローを解除しました",zh:"已取消关注{username}",ru:"Вы отписались от {username}",ar:"ألغيت متابعة {username}",hi:"{username} को अनफ़ॉलो किया",ko:"{username} 팔로우 해제",tr:"{username} takipten çıkıldı",pl:"Przestałeś obserwować {username}",sv:"Slutade följa {username}",id:"Berhenti mengikuti {username}",th:"เลิกติดตาม {username}"},
"user.followError":{en:"Error changing follow status",pt:"Erro ao mudar seguimento",fr:"Erreur de suivi",de:"Fehler beim Folgen",it:"Errore nel seguire",nl:"Fout bij volgen",ja:"フォロー変更エラー",zh:"更改关注状态出错",ru:"Ошибка подписки",ar:"خطأ في تغيير المتابعة",hi:"फ़ॉलो बदलने में त्रुटि",ko:"팔로우 변경 오류",tr:"Takip değiştirme hatası",pl:"Błąd obserwowania",sv:"Fel vid följning",id:"Error mengubah status ikuti",th:"เกิดข้อผิดพลาดในการเปลี่ยนการติดตาม"},
"user.mustLoginToBlock":{en:"Sign in to block users",pt:"Entre para bloquear usuários",fr:"Connectez-vous pour bloquer",de:"Anmelden zum Blockieren",it:"Accedi per bloccare",nl:"Log in om te blokkeren",ja:"ブロックするにはログイン",zh:"登录以屏蔽用户",ru:"Войдите для блокировки",ar:"سجل دخولك للحظر",hi:"ब्लॉक करने के लिए लॉगिन",ko:"차단하려면 로그인",tr:"Engellemek için giriş yapın",pl:"Zaloguj się aby blokować",sv:"Logga in för att blockera",id:"Masuk untuk memblokir",th:"เข้าสู่ระบบเพื่อบล็อก"},
"user.blocked":{en:"You have blocked {username}",pt:"Você bloqueou {username}",fr:"Vous avez bloqué {username}",de:"Du hast {username} blockiert",it:"Hai bloccato {username}",nl:"Je hebt {username} geblokkeerd",ja:"{username}をブロックしました",zh:"已屏蔽{username}",ru:"Вы заблокировали {username}",ar:"لقد حظرت {username}",hi:"आपने {username} को ब्लॉक किया",ko:"{username}을(를) 차단했습니다",tr:"{username} engellendi",pl:"Zablokowałeś {username}",sv:"Du har blockerat {username}",id:"Anda telah memblokir {username}",th:"คุณบล็อก {username} แล้ว"},
"user.unblocked":{en:"You have unblocked {username}",pt:"Você desbloqueou {username}",fr:"Vous avez débloqué {username}",de:"Du hast {username} entblockt",it:"Hai sbloccato {username}",nl:"Je hebt {username} gedeblokkeerd",ja:"{username}のブロックを解除しました",zh:"已取消屏蔽{username}",ru:"Вы разблокировали {username}",ar:"ألغيت حظر {username}",hi:"आपने {username} को अनब्लॉक किया",ko:"{username} 차단 해제",tr:"{username} engeli kaldırıldı",pl:"Odblokowałeś {username}",sv:"Du har avblockerat {username}",id:"Anda membuka blokir {username}",th:"คุณเลิกบล็อก {username} แล้ว"},
"user.blockError":{en:"Error changing block status",pt:"Erro ao mudar bloqueio",fr:"Erreur de blocage",de:"Fehler beim Blockieren",it:"Errore nel blocco",nl:"Fout bij blokkeren",ja:"ブロック変更エラー",zh:"更改屏蔽状态出错",ru:"Ошибка блокировки",ar:"خطأ في تغيير الحظر",hi:"ब्लॉक बदलने में त्रुटि",ko:"차단 변경 오류",tr:"Engelleme değiştirme hatası",pl:"Błąd blokowania",sv:"Fel vid blockering",id:"Error mengubah status blokir",th:"เกิดข้อผิดพลาดในการเปลี่ยนการบล็อก"},
"user.blockConfirmTitle":{en:"Block {username}?",pt:"Bloquear {username}?",fr:"Bloquer {username} ?",de:"{username} blockieren?",it:"Bloccare {username}?",nl:"{username} blokkeren?",ja:"{username}をブロックしますか？",zh:"屏蔽{username}？",ru:"Заблокировать {username}?",ar:"حظر {username}؟",hi:"{username} को ब्लॉक करें?",ko:"{username}을(를) 차단하시겠습니까?",tr:"{username} engellensin mi?",pl:"Zablokować {username}?",sv:"Blockera {username}?",id:"Blokir {username}?",th:"บล็อก {username}?"},
"user.blockConfirmDesc":{en:"By blocking this user:",pt:"Ao bloquear este usuário:",fr:"En bloquant cet utilisateur :",de:"Beim Blockieren dieses Benutzers:",it:"Bloccando questo utente:",nl:"Door deze gebruiker te blokkeren:",ja:"このユーザーをブロックすると：",zh:"屏蔽此用户后：",ru:"Заблокировав этого пользователя:",ar:"عند حظر هذا المستخدم:",hi:"इस उपयोगकर्ता को ब्लॉक करने पर:",ko:"이 사용자를 차단하면:",tr:"Bu kullanıcıyı engelleyerek:",pl:"Blokując tego użytkownika:",sv:"Genom att blockera denna användare:",id:"Dengan memblokir pengguna ini:",th:"เมื่อบล็อกผู้ใช้นี้:"},
"user.blockEffect1":{en:"You won't see their posts or threads",pt:"Não verá publicações nem tópicos",fr:"Vous ne verrez plus ses publications",de:"Du siehst keine Beiträge mehr",it:"Non vedrai i suoi post o thread",nl:"Je ziet geen berichten meer",ja:"投稿やスレッドが非表示になります",zh:"您将看不到其帖子或主题",ru:"Вы не увидите их публикации и темы",ar:"لن ترى منشوراتهم أو مواضيعهم",hi:"उनकी पोस्ट या थ्रेड नहीं दिखेंगे",ko:"게시물이나 스레드가 표시되지 않습니다",tr:"Gönderilerini veya konularını görmezsiniz",pl:"Nie zobaczysz ich postów ani wątków",sv:"Du ser inte deras inlägg eller trådar",id:"Anda tidak akan melihat postingan mereka",th:"คุณจะไม่เห็นโพสต์หรือกระทู้ของพวกเขา"},
"user.blockEffect2":{en:"They won't be able to send you private messages",pt:"Não poderá enviar mensagens privadas",fr:"Il/elle ne pourra pas vous envoyer de messages privés",de:"Kann keine Privatnachrichten senden",it:"Non potrà inviarti messaggi privati",nl:"Kan geen privéberichten sturen",ja:"プライベートメッセージを送れなくなります",zh:"对方无法给您发送私信",ru:"Не сможет отправлять вам личные сообщения",ar:"لن يتمكن من إرسال رسائل خاصة لك",hi:"निजी संदेश नहीं भेज सकेंगे",ko:"비공개 메시지를 보낼 수 없습니다",tr:"Size özel mesaj gönderemez",pl:"Nie będzie mógł wysyłać prywatnych wiadomości",sv:"Kan inte skicka privata meddelanden",id:"Tidak dapat mengirim pesan pribadi",th:"จะไม่สามารถส่งข้อความส่วนตัวได้"},
"user.blockEffect3":{en:"Any mutual following will be cancelled",pt:"Qualquer seguimento mútuo será cancelado",fr:"Tout suivi mutuel sera annulé",de:"Gegenseitiges Folgen wird aufgehoben",it:"Qualsiasi follow reciproco verrà annullato",nl:"Wederzijds volgen wordt geannuleerd",ja:"相互フォローがキャンセルされます",zh:"任何相互关注将被取消",ru:"Взаимная подписка будет отменена",ar:"سيتم إلغاء أي متابعة متبادلة",hi:"कोई भी पारस्परिक फ़ॉलो रद्द हो जाएगा",ko:"상호 팔로우가 취소됩니다",tr:"Karşılıklı takip iptal edilir",pl:"Wzajemne obserwowanie zostanie anulowane",sv:"Ömsesidig följning avbryts",id:"Saling mengikuti akan dibatalkan",th:"การติดตามซึ่งกันและกันจะถูกยกเลิก"},
"user.blockEffect4":{en:"You won't receive notifications from this user",pt:"Não receberá notificações deste usuário",fr:"Vous ne recevrez plus de notifications",de:"Keine Benachrichtigungen mehr",it:"Non riceverai notifiche da questo utente",nl:"Geen meldingen meer van deze gebruiker",ja:"このユーザーからの通知を受け取りません",zh:"您不会收到此用户的通知",ru:"Вы не будете получать уведомления от этого пользователя",ar:"لن تتلقى إشعارات من هذا المستخدم",hi:"इस उपयोगकर्ता से सूचनाएं नहीं मिलेंगी",ko:"이 사용자의 알림을 받지 않습니다",tr:"Bu kullanıcıdan bildirim almazsınız",pl:"Nie otrzymasz powiadomień od tego użytkownika",sv:"Du får inga aviseringar från denna användare",id:"Anda tidak akan menerima notifikasi dari pengguna ini",th:"คุณจะไม่ได้รับการแจ้งเตือนจากผู้ใช้นี้"},

// === ONLINE STATUS ===
"onlineStatus.usersOnline":{en:"Users online",pt:"Usuários online",fr:"Utilisateurs en ligne",de:"Benutzer online",it:"Utenti online",nl:"Gebruikers online",ja:"オンラインユーザー",zh:"在线用户",ru:"Пользователи онлайн",ar:"المستخدمون المتصلون",hi:"ऑनलाइन उपयोगकर्ता",ko:"온라인 사용자",tr:"Çevrimiçi kullanıcılar",pl:"Użytkownicy online",sv:"Användare online",id:"Pengguna online",th:"ผู้ใช้ออนไลน์"},

// === FAVORITES PAGE ===
"favoritesPage.itemsSaved":{en:"{count} items saved",pt:"{count} itens salvos",fr:"{count} éléments enregistrés",de:"{count} Elemente gespeichert",it:"{count} elementi salvati",nl:"{count} items opgeslagen",ja:"{count}件保存済み",zh:"已保存{count}项",ru:"{count} элементов сохранено",ar:"{count} عناصر محفوظة",hi:"{count} आइटम सहेजे गए",ko:"{count}개 저장됨",tr:"{count} öğe kaydedildi",pl:"{count} zapisanych elementów",sv:"{count} objekt sparade",id:"{count} item disimpan",th:"บันทึก {count} รายการ"},
"favoritesPage.searchPlaceholder":{en:"Search favorites...",pt:"Buscar nos favoritos...",fr:"Rechercher dans les favoris...",de:"Favoriten durchsuchen...",it:"Cerca nei preferiti...",nl:"Zoeken in favorieten...",ja:"お気に入りを検索...",zh:"搜索收藏...",ru:"Поиск в избранном...",ar:"البحث في المفضلة...",hi:"पसंदीदा में खोजें...",ko:"즐겨찾기 검색...",tr:"Favorilerde ara...",pl:"Szukaj w ulubionych...",sv:"Sök i favoriter...",id:"Cari di favorit...",th:"ค้นหาในรายการโปรด..."},
"favoritesPage.noThreads":{en:"No saved threads",pt:"Nenhum tópico salvo",fr:"Aucun sujet sauvegardé",de:"Keine gespeicherten Themen",it:"Nessun thread salvato",nl:"Geen opgeslagen onderwerpen",ja:"保存したスレッドはありません",zh:"没有保存的主题",ru:"Нет сохранённых тем",ar:"لا توجد مواضيع محفوظة",hi:"कोई सहेजे गए थ्रेड नहीं",ko:"저장된 스레드 없음",tr:"Kayıtlı konu yok",pl:"Brak zapisanych wątków",sv:"Inga sparade trådar",id:"Tidak ada thread tersimpan",th:"ไม่มีกระทู้ที่บันทึก"},
"favoritesPage.noThreadsDesc":{en:"Save interesting threads by clicking the favorites button",pt:"Salve tópicos interessantes clicando no botão de favoritos",fr:"Sauvegardez des sujets en cliquant sur le bouton favoris",de:"Speichern Sie interessante Themen mit dem Favoriten-Button",it:"Salva thread interessanti cliccando sul pulsante preferiti",nl:"Sla interessante onderwerpen op via de favorieten-knop",ja:"お気に入りボタンをクリックして興味深いスレッドを保存",zh:"点击收藏按钮保存感兴趣的主题",ru:"Сохраняйте интересные темы, нажимая кнопку избранного",ar:"احفظ المواضيع المثيرة بالنقر على زر المفضلة",hi:"पसंदीदा बटन क्लिक करके दिलचस्प थ्रेड सहेजें",ko:"즐겨찾기 버튼으로 관심 스레드를 저장하세요",tr:"Favori butonuna tıklayarak ilginç konuları kaydedin",pl:"Zapisuj wątki klikając przycisk ulubionych",sv:"Spara intressanta trådar med favoritknappen",id:"Simpan thread menarik dengan mengklik tombol favorit",th:"บันทึกกระทู้ที่น่าสนใจโดยคลิกปุ่มรายการโปรด"},
"favoritesPage.noPosts":{en:"No saved posts",pt:"Nenhum post salvo",fr:"Aucun post sauvegardé",de:"Keine gespeicherten Beiträge",it:"Nessun post salvato",nl:"Geen opgeslagen berichten",ja:"保存した投稿はありません",zh:"没有保存的帖子",ru:"Нет сохранённых постов",ar:"لا توجد منشورات محفوظة",hi:"कोई सहेजे गए पोस्ट नहीं",ko:"저장된 게시물 없음",tr:"Kayıtlı gönderi yok",pl:"Brak zapisanych postów",sv:"Inga sparade inlägg",id:"Tidak ada postingan tersimpan",th:"ไม่มีโพสต์ที่บันทึก"},
"favoritesPage.noPostsDesc":{en:"Save specific posts by clicking the favorites button",pt:"Salve posts específicos clicando no botão de favoritos",fr:"Sauvegardez des posts en cliquant sur le bouton favoris",de:"Speichern Sie Beiträge mit dem Favoriten-Button",it:"Salva post specifici cliccando sul pulsante preferiti",nl:"Sla berichten op via de favorieten-knop",ja:"お気に入りボタンをクリックして投稿を保存",zh:"点击收藏按钮保存特定帖子",ru:"Сохраняйте посты, нажимая кнопку избранного",ar:"احفظ المنشورات بالنقر على زر المفضلة",hi:"पसंदीदा बटन क्लिक करके पोस्ट सहेजें",ko:"즐겨찾기 버튼으로 게시물을 저장하세요",tr:"Favori butonuna tıklayarak gönderileri kaydedin",pl:"Zapisuj posty klikając przycisk ulubionych",sv:"Spara inlägg med favoritknappen",id:"Simpan postingan dengan mengklik tombol favorit",th:"บันทึกโพสต์โดยคลิกปุ่มรายการโปรด"},
"favoritesPage.removeBookmark":{en:"Remove favorite?",pt:"Remover favorito?",fr:"Supprimer le favori ?",de:"Favorit entfernen?",it:"Rimuovere il preferito?",nl:"Favoriet verwijderen?",ja:"お気に入りを削除しますか？",zh:"移除收藏？",ru:"Удалить из избранного?",ar:"إزالة من المفضلة؟",hi:"पसंदीदा हटाएं?",ko:"즐겨찾기 제거?",tr:"Favori kaldırılsın mı?",pl:"Usunąć z ulubionych?",sv:"Ta bort favorit?",id:"Hapus favorit?",th:"ลบรายการโปรด?"},
"favoritesPage.removeThreadDesc":{en:"This thread will be removed from your favorites.",pt:"Este tópico será removido dos seus favoritos.",fr:"Ce sujet sera supprimé de vos favoris.",de:"Dieses Thema wird aus Ihren Favoriten entfernt.",it:"Questo thread sarà rimosso dai preferiti.",nl:"Dit onderwerp wordt verwijderd uit je favorieten.",ja:"このスレッドはお気に入りから削除されます。",zh:"此主题将从收藏中移除。",ru:"Эта тема будет удалена из избранного.",ar:"سيتم إزالة هذا الموضوع من المفضلة.",hi:"यह थ्रेड पसंदीदा से हटा दिया जाएगा।",ko:"이 스레드가 즐겨찾기에서 제거됩니다.",tr:"Bu konu favorilerinizden kaldırılacak.",pl:"Ten wątek zostanie usunięty z ulubionych.",sv:"Denna tråd tas bort från dina favoriter.",id:"Thread ini akan dihapus dari favorit Anda.",th:"กระทู้นี้จะถูกลบออกจากรายการโปรด"},
"favoritesPage.removePostDesc":{en:"This post will be removed from your favorites.",pt:"Este post será removido dos seus favoritos.",fr:"Ce post sera supprimé de vos favoris.",de:"Dieser Beitrag wird aus Ihren Favoriten entfernt.",it:"Questo post sarà rimosso dai preferiti.",nl:"Dit bericht wordt verwijderd uit je favorieten.",ja:"この投稿はお気に入りから削除されます。",zh:"此帖子将从收藏中移除。",ru:"Этот пост будет удалён из избранного.",ar:"سيتم إزالة هذا المنشور من المفضلة.",hi:"यह पोस्ट पसंदीदा से हटा दिया जाएगा।",ko:"이 게시물이 즐겨찾기에서 제거됩니다.",tr:"Bu gönderi favorilerinizden kaldırılacak.",pl:"Ten post zostanie usunięty z ulubionych.",sv:"Detta inlägg tas bort från dina favoriter.",id:"Postingan ini akan dihapus dari favorit Anda.",th:"โพสต์นี้จะถูกลบออกจากรายการโปรด"},
"favoritesPage.bookmarkRemoved":{en:"Favorite removed",pt:"Favorito removido",fr:"Favori supprimé",de:"Favorit entfernt",it:"Preferito rimosso",nl:"Favoriet verwijderd",ja:"お気に入りを削除しました",zh:"已取消收藏",ru:"Удалено из избранного",ar:"تمت إزالة المفضلة",hi:"पसंदीदा हटाया गया",ko:"즐겨찾기 제거됨",tr:"Favori kaldırıldı",pl:"Usunięto z ulubionych",sv:"Favorit borttagen",id:"Favorit dihapus",th:"ลบรายการโปรดแล้ว"},
"favoritesPage.loadError":{en:"Error loading favorites",pt:"Erro ao carregar favoritos",fr:"Erreur de chargement",de:"Fehler beim Laden",it:"Errore caricamento",nl:"Fout bij laden",ja:"読み込みエラー",zh:"加载出错",ru:"Ошибка загрузки избранного",ar:"خطأ في التحميل",hi:"लोड करने में त्रुटि",ko:"로딩 오류",tr:"Yükleme hatası",pl:"Błąd ładowania",sv:"Laddningsfel",id:"Error memuat",th:"เกิดข้อผิดพลาดในการโหลด"},
"favoritesPage.removeError":{en:"Error removing favorite",pt:"Erro ao remover favorito",fr:"Erreur de suppression",de:"Fehler beim Entfernen",it:"Errore rimozione",nl:"Fout bij verwijderen",ja:"削除エラー",zh:"移除出错",ru:"Ошибка удаления",ar:"خطأ في الإزالة",hi:"हटाने में त्रुटि",ko:"제거 오류",tr:"Kaldırma hatası",pl:"Błąd usuwania",sv:"Borttagningsfel",id:"Error menghapus",th:"เกิดข้อผิดพลาดในการลบ"},

// === CREATE THREAD ===
"createThread.titleHint":{en:"Minimum 5 characters, maximum 200",pt:"Mínimo 5 caracteres, máximo 200",fr:"Minimum 5 caractères, maximum 200",de:"Mindestens 5 Zeichen, maximal 200",it:"Minimo 5 caratteri, massimo 200",nl:"Minimaal 5 tekens, maximaal 200",ja:"5〜200文字",zh:"最少5个字符，最多200个",ru:"Минимум 5, максимум 200 символов",ar:"الحد الأدنى 5 أحرف، الأقصى 200",hi:"न्यूनतम 5, अधिकतम 200 अक्षर",ko:"최소 5자, 최대 200자",tr:"Minimum 5, maksimum 200 karakter",pl:"Minimum 5, maksimum 200 znaków",sv:"Minst 5, max 200 tecken",id:"Minimum 5, maksimum 200 karakter",th:"ขั้นต่ำ 5 ตัวอักษร สูงสุด 200"},
"createThread.contentPlaceholder":{en:"Write the content of your thread...",pt:"Escreva o conteúdo do seu tópico...",fr:"Écrivez le contenu de votre sujet...",de:"Schreiben Sie den Inhalt Ihres Themas...",it:"Scrivi il contenuto del tuo thread...",nl:"Schrijf de inhoud van je onderwerp...",ja:"スレッドの内容を入力...",zh:"写下你的主题内容...",ru:"Напишите содержание вашей темы...",ar:"اكتب محتوى موضوعك...",hi:"अपने थ्रेड की सामग्री लिखें...",ko:"스레드 내용을 작성하세요...",tr:"Konu içeriğinizi yazın...",pl:"Napisz treść wątku...",sv:"Skriv innehållet i din tråd...",id:"Tulis konten thread Anda...",th:"เขียนเนื้อหากระทู้ของคุณ..."},
"createThread.contentHint":{en:"Minimum 10 characters, maximum 50000",pt:"Mínimo 10 caracteres, máximo 50000",fr:"Minimum 10 caractères, maximum 50000",de:"Mindestens 10, maximal 50000 Zeichen",it:"Minimo 10, massimo 50000 caratteri",nl:"Minimaal 10, maximaal 50000 tekens",ja:"10〜50000文字",zh:"最少10个字符，最多50000个",ru:"Минимум 10, максимум 50000 символов",ar:"الحد الأدنى 10، الأقصى 50000 حرف",hi:"न्यूनतम 10, अधिकतम 50000 अक्षर",ko:"최소 10자, 최대 50000자",tr:"Minimum 10, maksimum 50000 karakter",pl:"Minimum 10, maksimum 50000 znaków",sv:"Minst 10, max 50000 tecken",id:"Minimum 10, maksimum 50000 karakter",th:"ขั้นต่ำ 10 สูงสุด 50000 ตัวอักษร"},

// === NOT FOUND ===
"notFound.description":{en:"Sorry, the page you're looking for doesn't exist or has been moved. The link may be broken or you may have mistyped the URL.",pt:"A página que você procura não existe ou foi movida.",fr:"La page que vous cherchez n'existe pas ou a été déplacée.",de:"Die gesuchte Seite existiert nicht oder wurde verschoben.",it:"La pagina cercata non esiste o è stata spostata.",nl:"De pagina die je zoekt bestaat niet of is verplaatst.",ja:"お探しのページは存在しないか、移動されました。",zh:"抱歉，您要查找的页面不存在或已被移动。",ru:"Страница не найдена или была перемещена.",ar:"الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",hi:"आप जिस पृष्ठ की तलाश कर रहे हैं वह मौजूद नहीं है।",ko:"찾으시는 페이지가 존재하지 않거나 이동되었습니다.",tr:"Aradığınız sayfa mevcut değil veya taşınmış.",pl:"Strona nie istnieje lub została przeniesiona.",sv:"Sidan du letar efter finns inte eller har flyttats.",id:"Halaman yang Anda cari tidak ada atau telah dipindahkan.",th:"ขออภัย หน้าที่คุณกำลังมองหาไม่มีอยู่หรือถูกย้ายแล้ว"},
"notFound.helpDescription":{en:"If you believe this is an error or need help finding something specific:",pt:"Se você acha que é um erro ou precisa de ajuda:",fr:"Si vous pensez que c'est une erreur ou avez besoin d'aide :",de:"Wenn Sie glauben, dass dies ein Fehler ist oder Hilfe benötigen:",it:"Se pensi sia un errore o hai bisogno di aiuto:",nl:"Als je denkt dat dit een fout is of hulp nodig hebt:",ja:"エラーだと思われる場合やお探しの場合：",zh:"如果您认为这是错误或需要帮助：",ru:"Если вы считаете это ошибкой или нужна помощь:",ar:"إذا كنت تعتقد أن هذا خطأ أو تحتاج مساعدة:",hi:"अगर आपको लगता है कि यह त्रुटि है या मदद चाहिए:",ko:"오류라고 생각되거나 도움이 필요하시면:",tr:"Bunun bir hata olduğunu düşünüyorsanız veya yardıma ihtiyacınız varsa:",pl:"Jeśli uważasz, że to błąd lub potrzebujesz pomocy:",sv:"Om du tror att detta är ett fel eller behöver hjälp:",id:"Jika Anda merasa ini kesalahan atau butuh bantuan:",th:"หากคุณคิดว่านี่เป็นข้อผิดพลาดหรือต้องการความช่วยเหลือ:"},

// === PASSWORD RECOVERY ===
"passwordRecovery.email":{en:"Email",pt:"Email",fr:"Email",de:"E-Mail",it:"Email",nl:"E-mail",ja:"メール",zh:"邮箱",ru:"Электронная почта",ar:"البريد الإلكتروني",hi:"ईमेल",ko:"이메일",tr:"E-posta",pl:"Email",sv:"E-post",id:"Email",th:"อีเมล"},
"passwordRecovery.emailPlaceholder":{en:"your@email.com",pt:"seu@email.com",fr:"votre@email.com",de:"ihre@email.com",it:"tua@email.com",nl:"jouw@email.com",ja:"your@email.com",zh:"your@email.com",ru:"ваш@email.com",ar:"your@email.com",hi:"your@email.com",ko:"your@email.com",tr:"email@adresiniz.com",pl:"twoj@email.com",sv:"din@email.com",id:"anda@email.com",th:"your@email.com"},
"passwordRecovery.sending":{en:"Sending...",pt:"Enviando...",fr:"Envoi...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"发送中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"भेज रहे हैं...",ko:"전송 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"passwordRecovery.sentTo":{en:"We have sent a recovery link to:",pt:"Enviamos um link de recuperação para:",fr:"Nous avons envoyé un lien de récupération à :",de:"Wir haben einen Wiederherstellungslink gesendet an:",it:"Abbiamo inviato un link di recupero a:",nl:"We hebben een herstelkoppeling gestuurd naar:",ja:"回復リンクを送信しました：",zh:"我们已发送恢复链接至：",ru:"Мы отправили ссылку для восстановления на:",ar:"أرسلنا رابط الاستعادة إلى:",hi:"हमने पुनर्प्राप्ति लिंक भेजा है:",ko:"복구 링크를 보냈습니다:",tr:"Kurtarma bağlantısı gönderildi:",pl:"Wysłaliśmy link do odzyskiwania na:",sv:"Vi har skickat en återställningslänk till:",id:"Kami telah mengirim link pemulihan ke:",th:"เราได้ส่งลิงก์กู้คืนไปที่:"},
"passwordRecovery.checkInbox":{en:"Check your inbox and follow the instructions to reset your password.",pt:"Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.",fr:"Vérifiez votre boîte de réception et suivez les instructions.",de:"Prüfen Sie Ihren Posteingang und folgen Sie den Anweisungen.",it:"Controlla la tua casella e segui le istruzioni.",nl:"Controleer je inbox en volg de instructies.",ja:"受信トレイを確認し、パスワードリセットの手順に従ってください。",zh:"请查收邮箱并按照说明重置密码。",ru:"Проверьте почту и следуйте инструкциям для сброса пароля.",ar:"تحقق من بريدك واتبع التعليمات لإعادة تعيين كلمة المرور.",hi:"अपना इनबॉक्स जांचें और पासवर्ड रीसेट करने के निर्देशों का पालन करें।",ko:"받은 편지함을 확인하고 비밀번호 재설정 지침을 따르세요.",tr:"Gelen kutunuzu kontrol edin ve şifrenizi sıfırlamak için talimatları izleyin.",pl:"Sprawdź skrzynkę i postępuj zgodnie z instrukcjami.",sv:"Kontrollera din inkorg och följ instruktionerna.",id:"Periksa kotak masuk dan ikuti instruksi untuk mengatur ulang kata sandi.",th:"ตรวจสอบกล่องจดหมายและทำตามคำแนะนำเพื่อรีเซ็ตรหัสผ่าน"},

// === ERRORS ===
"errors.unexpectedError":{en:"An unexpected error occurred. Our team has been notified and we're working on fixing it.",pt:"Ocorreu um erro inesperado. Nossa equipe foi notificada.",fr:"Une erreur inattendue s'est produite. Notre équipe a été informée.",de:"Ein unerwarteter Fehler ist aufgetreten. Unser Team wurde benachrichtigt.",it:"Si è verificato un errore imprevisto. Il nostro team è stato avvisato.",nl:"Er is een onverwachte fout opgetreden. Ons team is op de hoogte gebracht.",ja:"予期しないエラーが発生しました。チームに通知され、修正に取り組んでいます。",zh:"发生了意外错误。我们的团队已收到通知。",ru:"Произошла непредвиденная ошибка. Наша команда уведомлена.",ar:"حدث خطأ غير متوقع. تم إبلاغ فريقنا.",hi:"एक अप्रत्याशित त्रुटि हुई। हमारी टीम को सूचित किया गया है।",ko:"예상치 못한 오류가 발생했습니다. 팀에 알림이 전달되었습니다.",tr:"Beklenmeyen bir hata oluştu. Ekibimiz bilgilendirildi.",pl:"Wystąpił nieoczekiwany błąd. Nasz zespół został powiadomiony.",sv:"Ett oväntat fel uppstod. Vårt team har meddelats.",id:"Terjadi error tidak terduga. Tim kami telah diberitahu.",th:"เกิดข้อผิดพลาดที่ไม่คาดคิด ทีมของเราได้รับแจ้งแล้ว"},
"errors.problemPersists":{en:"If the problem persists, please:",pt:"Se o problema persistir, por favor:",fr:"Si le problème persiste, veuillez :",de:"Wenn das Problem weiterhin besteht:",it:"Se il problema persiste:",nl:"Als het probleem aanhoudt:",ja:"問題が続く場合：",zh:"如果问题持续存在，请：",ru:"Если проблема сохраняется:",ar:"إذا استمرت المشكلة:",hi:"यदि समस्या बनी रहे:",ko:"문제가 지속되면:",tr:"Sorun devam ederse:",pl:"Jeśli problem się powtarza:",sv:"Om problemet kvarstår:",id:"Jika masalah berlanjut:",th:"หากปัญหายังคงอยู่:"},
"errors.step1":{en:"Try reloading the page or clearing your browser cache",pt:"Tente recarregar a página ou limpar o cache",fr:"Essayez de recharger la page ou de vider le cache",de:"Versuchen Sie, die Seite neu zu laden oder den Cache zu leeren",it:"Prova a ricaricare la pagina o svuotare la cache",nl:"Probeer de pagina te herladen of cache te wissen",ja:"ページの再読み込みまたはキャッシュのクリアをお試しください",zh:"尝试刷新页面或清除浏览器缓存",ru:"Попробуйте перезагрузить страницу или очистить кэш",ar:"حاول إعادة تحميل الصفحة أو مسح ذاكرة التخزين",hi:"पेज रीलोड या कैश साफ़ करने का प्रयास करें",ko:"페이지를 새로고침하거나 브라우저 캐시를 지워보세요",tr:"Sayfayı yenilemeyi veya önbelleği temizlemeyi deneyin",pl:"Spróbuj odświeżyć stronę lub wyczyścić pamięć",sv:"Prova ladda om sidan eller rensa cachen",id:"Coba muat ulang halaman atau bersihkan cache",th:"ลองโหลดหน้าใหม่หรือล้างแคชของเบราว์เซอร์"},
"errors.step2":{en:"Check your internet connection",pt:"Verifique sua conexão com a internet",fr:"Vérifiez votre connexion internet",de:"Überprüfen Sie Ihre Internetverbindung",it:"Verifica la tua connessione internet",nl:"Controleer je internetverbinding",ja:"インターネット接続を確認してください",zh:"检查您的网络连接",ru:"Проверьте подключение к интернету",ar:"تحقق من اتصالك بالإنترنت",hi:"अपना इंटरनेट कनेक्शन जांचें",ko:"인터넷 연결을 확인하세요",tr:"İnternet bağlantınızı kontrol edin",pl:"Sprawdź połączenie z internetem",sv:"Kontrollera din internetanslutning",id:"Periksa koneksi internet Anda",th:"ตรวจสอบการเชื่อมต่ออินเทอร์เน็ต"},
"errors.includeErrorId":{en:"and include the error ID if available",pt:"e inclua o ID do erro se disponível",fr:"et incluez l'ID d'erreur si disponible",de:"und geben Sie die Fehler-ID an, falls verfügbar",it:"e includi l'ID errore se disponibile",nl:"en vermeld het fout-ID indien beschikbaar",ja:"エラーIDがあれば含めてください",zh:"并提供错误ID（如果有）",ru:"и укажите ID ошибки, если доступен",ar:"وأدرج معرف الخطأ إن وجد",hi:"और उपलब्ध होने पर त्रुटि आईडी शामिल करें",ko:"가능하면 오류 ID를 포함하세요",tr:"ve varsa hata ID'sini ekleyin",pl:"i dołącz ID błędu jeśli dostępne",sv:"och inkludera fel-ID om tillgängligt",id:"dan sertakan ID error jika tersedia",th:"และรวม ID ข้อผิดพลาดถ้ามี"},
"errors.devErrorDetails":{en:"Error details (only visible in development)",pt:"Detalhes do erro (visível apenas em desenvolvimento)",fr:"Détails de l'erreur (visible en développement)",de:"Fehlerdetails (nur in Entwicklung sichtbar)",it:"Dettagli errore (visibile solo in sviluppo)",nl:"Foutdetails (alleen zichtbaar in ontwikkeling)",ja:"エラー詳細（開発環境でのみ表示）",zh:"错误详情（仅在开发环境可见）",ru:"Детали ошибки (видно только в режиме разработки)",ar:"تفاصيل الخطأ (مرئية في التطوير فقط)",hi:"त्रुटि विवरण (केवल विकास में दिखाई देता है)",ko:"오류 세부정보 (개발 환경에서만 표시)",tr:"Hata detayları (yalnızca geliştirmede görünür)",pl:"Szczegóły błędu (widoczne tylko w trybie dev)",sv:"Feldetaljer (synlig i utveckling)",id:"Detail error (hanya terlihat saat pengembangan)",th:"รายละเอียดข้อผิดพลาด (มองเห็นได้ในโหมดพัฒนาเท่านั้น)"},

// === SEARCH ===
"search.tryOther":{en:"Try different search terms",pt:"Tente outros termos de pesquisa",fr:"Essayez d'autres termes de recherche",de:"Versuchen Sie andere Suchbegriffe",it:"Prova altri termini di ricerca",nl:"Probeer andere zoektermen",ja:"別の検索語をお試しください",zh:"尝试其他搜索词",ru:"Попробуйте другие поисковые запросы",ar:"جرب مصطلحات بحث أخرى",hi:"अन्य खोज शब्द आज़माएं",ko:"다른 검색어를 시도해보세요",tr:"Farklı arama terimleri deneyin",pl:"Spróbuj innych słów kluczowych",sv:"Prova andra söktermer",id:"Coba kata pencarian lain",th:"ลองใช้คำค้นหาอื่น"},
"search.resultsFor":{en:"{count} results found for \"{query}\"",pt:"{count} resultados encontrados para \"{query}\"",fr:"{count} résultats trouvés pour \"{query}\"",de:"{count} Ergebnisse für \"{query}\"",it:"{count} risultati per \"{query}\"",nl:"{count} resultaten voor \"{query}\"",ja:"\"{query}\"の検索結果{count}件",zh:"找到{count}个\"{query}\"的结果",ru:"Найдено {count} результатов по запросу \"{query}\"",ar:"تم العثور على {count} نتيجة لـ \"{query}\"",hi:"\"{query}\" के लिए {count} परिणाम",ko:"\"{query}\"에 대한 {count}개의 결과",tr:"\"{query}\" için {count} sonuç bulundu",pl:"{count} wyników dla \"{query}\"",sv:"{count} resultat för \"{query}\"",id:"{count} hasil ditemukan untuk \"{query}\"",th:"พบ {count} ผลลัพธ์สำหรับ \"{query}\""},
"search.enterTerm":{en:"Enter a search term to begin",pt:"Insira um termo de pesquisa para começar",fr:"Saisissez un terme de recherche",de:"Geben Sie einen Suchbegriff ein",it:"Inserisci un termine di ricerca",nl:"Voer een zoekterm in",ja:"検索語を入力して開始",zh:"输入搜索词开始搜索",ru:"Введите поисковый запрос",ar:"أدخل مصطلح بحث للبدء",hi:"शुरू करने के लिए खोज शब्द दर्ज करें",ko:"검색어를 입력하세요",tr:"Aramaya başlamak için bir terim girin",pl:"Wpisz frazę aby szukać",sv:"Ange en sökterm för att börja",id:"Masukkan kata pencarian untuk memulai",th:"ป้อนคำค้นหาเพื่อเริ่มต้น"},
"search.verified":{en:"Verified",pt:"Verificada",fr:"Vérifiée",de:"Verifiziert",it:"Verificata",nl:"Geverifieerd",ja:"認証済み",zh:"已验证",ru:"Верифицирован",ar:"موثق",hi:"सत्यापित",ko:"인증됨",tr:"Doğrulanmış",pl:"Zweryfikowany",sv:"Verifierad",id:"Terverifikasi",th:"ยืนยันแล้ว"},

// === MISC small sections ===
"language.es":{en:"Español",pt:"Español",fr:"Español",de:"Español",it:"Español",nl:"Español",ja:"Español",zh:"Español",ru:"Español",ar:"Español",hi:"Español",ko:"Español",tr:"Español",pl:"Español",sv:"Español",id:"Español",th:"Español"},
"language.en":{en:"English",pt:"English",fr:"English",de:"English",it:"English",nl:"English",ja:"English",zh:"English",ru:"English",ar:"English",hi:"English",ko:"English",tr:"English",pl:"English",sv:"English",id:"English",th:"English"},
"language.pt":{en:"Português",pt:"Português",fr:"Português",de:"Português",it:"Português",nl:"Português",ja:"Português",zh:"Português",ru:"Português",ar:"Português",hi:"Português",ko:"Português",tr:"Português",pl:"Português",sv:"Português",id:"Português",th:"Português"},
"language.fr":{en:"Français",pt:"Français",fr:"Français",de:"Français",it:"Français",nl:"Français",ja:"Français",zh:"Français",ru:"Français",ar:"Français",hi:"Français",ko:"Français",tr:"Français",pl:"Français",sv:"Français",id:"Français",th:"Français"},
"home.migrationRequired":{en:"Database migration required",pt:"Migração de banco de dados necessária",fr:"Migration de base de données requise",de:"Datenbankmigration erforderlich",it:"Migrazione database richiesta",nl:"Databasemigratie vereist",ja:"データベースの移行が必要です",zh:"需要执行数据库迁移",ru:"Требуется миграция базы данных",ar:"يتطلب ترحيل قاعدة البيانات",hi:"डेटाबेस माइग्रेशन आवश्यक है",ko:"데이터베이스 마이그레이션 필요",tr:"Veritabanı geçişi gerekli",pl:"Wymagana migracja bazy danych",sv:"Databasmigrering krävs",id:"Migrasi database diperlukan",th:"ต้องการการโยกย้ายฐานข้อมูล"},
"home.runCommand":{en:"Run the following command in your terminal:",pt:"Execute o seguinte comando no terminal:",fr:"Exécutez la commande suivante dans votre terminal :",de:"Führen Sie folgenden Befehl im Terminal aus:",it:"Esegui il seguente comando nel terminale:",nl:"Voer het volgende commando uit in je terminal:",ja:"ターミナルで次のコマンドを実行：",zh:"在终端中运行以下命令：",ru:"Выполните следующую команду в терминале:",ar:"قم بتنفيذ الأمر التالي في الطرفية:",hi:"अपने टर्मिनल में निम्न कमांड चलाएं:",ko:"터미널에서 다음 명령을 실행하세요:",tr:"Terminalinizde şu komutu çalıştırın:",pl:"Uruchom następujące polecenie w terminalu:",sv:"Kör följande kommando i din terminal:",id:"Jalankan perintah berikut di terminal Anda:",th:"รันคำสั่งต่อไปนี้ในเทอร์มินัล:"},
"home.orCopy":{en:"Or copy the content of",pt:"Ou copie o conteúdo de",fr:"Ou copiez le contenu de",de:"Oder kopieren Sie den Inhalt von",it:"O copia il contenuto di",nl:"Of kopieer de inhoud van",ja:"または以下のコンテンツをコピー",zh:"或复制以下内容",ru:"Или скопируйте содержимое",ar:"أو انسخ محتوى",hi:"या सामग्री कॉपी करें",ko:"또는 내용 복사",tr:"Veya içeriği kopyalayın",pl:"Lub skopiuj zawartość",sv:"Eller kopiera innehållet av",id:"Atau salin konten dari",th:"หรือคัดลอกเนื้อหาของ"},
"account.countryPlaceholder":{en:"Mexico",pt:"Brasil",fr:"France",de:"Deutschland",it:"Italia",nl:"Nederland",ja:"日本",zh:"中国",ru:"Россия",ar:"السعودية",hi:"भारत",ko:"한국",tr:"Türkiye",pl:"Polska",sv:"Sverige",id:"Indonesia",th:"ไทย"},
"account.cityPlaceholder":{en:"New York",pt:"São Paulo",fr:"Paris",de:"Berlin",it:"Roma",nl:"Amsterdam",ja:"東京",zh:"北京",ru:"Москва",ar:"الرياض",hi:"मुंबई",ko:"서울",tr:"İstanbul",pl:"Warszawa",sv:"Stockholm",id:"Jakarta",th:"กรุงเทพ"},
"account.views":{en:"views",pt:"visualizações",fr:"vues",de:"Aufrufe",it:"visualizzazioni",nl:"weergaven",ja:"閲覧",zh:"浏览",ru:"просмотров",ar:"مشاهدات",hi:"दृश्य",ko:"조회",tr:"görüntüleme",pl:"wyświetleń",sv:"visningar",id:"tampilan",th:"การดู"},
"favorites.description":{en:"Threads you've saved as favorites",pt:"Tópicos que você salvou como favoritos",fr:"Sujets que vous avez sauvegardés",de:"Themen, die Sie als Favoriten gespeichert haben",it:"Thread salvati nei preferiti",nl:"Onderwerpen die je als favoriet hebt opgeslagen",ja:"お気に入りに保存したスレッド",zh:"您收藏的主题",ru:"Темы, сохранённые в избранном",ar:"المواضيع التي حفظتها كمفضلة",hi:"पसंदीदा के रूप में सहेजे गए थ्रेड",ko:"즐겨찾기에 저장한 스레드",tr:"Favori olarak kaydettiğiniz konular",pl:"Wątki zapisane jako ulubione",sv:"Trådar du sparat som favoriter",id:"Thread yang Anda simpan sebagai favorit",th:"กระทู้ที่คุณบันทึกเป็นรายการโปรด"},
"favorites.empty":{en:"No favorites yet",pt:"Nenhum favorito ainda",fr:"Pas encore de favoris",de:"Noch keine Favoriten",it:"Nessun preferito ancora",nl:"Nog geen favorieten",ja:"まだお気に入りはありません",zh:"暂无收藏",ru:"Пока нет избранного",ar:"لا توجد مفضلات بعد",hi:"अभी कोई पसंदीदा नहीं",ko:"아직 즐겨찾기 없음",tr:"Henüz favori yok",pl:"Brak ulubionych",sv:"Inga favoriter ännu",id:"Belum ada favorit",th:"ยังไม่มีรายการโปรด"},
"favorites.emptyDesc":{en:"Click the heart on any thread to add it to your favorites",pt:"Clique no coração de qualquer tópico para adicioná-lo",fr:"Cliquez sur le cœur d'un sujet pour l'ajouter aux favoris",de:"Klicken Sie auf das Herz eines Themas, um es hinzuzufügen",it:"Clicca sul cuore di qualsiasi thread per aggiungerlo",nl:"Klik op het hart om een onderwerp toe te voegen",ja:"スレッドのハートをクリックしてお気に入りに追加",zh:"点击任何主题的心形图标将其添加到收藏",ru:"Нажмите на сердечко темы, чтобы добавить в избранное",ar:"انقر على القلب في أي موضوع لإضافته للمفضلة",hi:"पसंदीदा में जोड़ने के लिए किसी भी थ्रेड पर दिल पर क्लिक करें",ko:"스레드의 하트를 클릭하여 즐겨찾기에 추가",tr:"Herhangi bir konunun kalbine tıklayarak favorilere ekleyin",pl:"Kliknij serce na wątku, aby dodać do ulubionych",sv:"Klicka på hjärtat på en tråd för att lägga till i favoriter",id:"Klik hati pada thread untuk menambahkan ke favorit",th:"คลิกหัวใจบนกระทู้เพื่อเพิ่มในรายการโปรด"},
"auth.emailPlaceholder":{en:"your@email.com",pt:"seu@email.com",fr:"votre@email.com",de:"ihre@email.com",it:"tua@email.com",nl:"jouw@email.com",ja:"your@email.com",zh:"your@email.com",ru:"ваш@email.com",ar:"your@email.com",hi:"your@email.com",ko:"your@email.com",tr:"email@adresiniz.com",pl:"twoj@email.com",sv:"din@email.com",id:"anda@email.com",th:"your@email.com"},
"auth.captchaFailed":{en:"Security verification failed. Try again",pt:"Verificação de segurança falhou. Tente novamente",fr:"Vérification de sécurité échouée. Réessayez",de:"Sicherheitsüberprüfung fehlgeschlagen. Erneut versuchen",it:"Verifica di sicurezza fallita. Riprova",nl:"Beveiligingsverificatie mislukt. Probeer opnieuw",ja:"セキュリティ認証に失敗しました。再試行してください",zh:"安全验证失败。请重试",ru:"Проверка безопасности не пройдена. Попробуйте снова",ar:"فشل التحقق الأمني. حاول مرة أخرى",hi:"सुरक्षा सत्यापन विफल। पुनः प्रयास करें",ko:"보안 인증 실패. 다시 시도하세요",tr:"Güvenlik doğrulaması başarısız. Tekrar deneyin",pl:"Weryfikacja bezpieczeństwa nie powiodła się. Spróbuj ponownie",sv:"Säkerhetsverifiering misslyckades. Försök igen",id:"Verifikasi keamanan gagal. Coba lagi",th:"การตรวจสอบความปลอดภัยล้มเหลว ลองอีกครั้ง"},
"nav.vip":{en:"VIP",pt:"VIP",fr:"VIP",de:"VIP",it:"VIP",nl:"VIP",ja:"VIP",zh:"VIP",ru:"VIP",ar:"VIP",hi:"VIP",ko:"VIP",tr:"VIP",pl:"VIP",sv:"VIP",id:"VIP",th:"VIP"},
"reply.placeholder":{en:"Write your reply...",pt:"Escreva sua resposta...",fr:"Écrivez votre réponse...",de:"Schreiben Sie Ihre Antwort...",it:"Scrivi la tua risposta...",nl:"Schrijf je antwoord...",ja:"返信を入力...",zh:"写下您的回复...",ru:"Напишите ваш ответ...",ar:"اكتب ردك...",hi:"अपना जवाब लिखें...",ko:"답글을 작성하세요...",tr:"Yanıtınızı yazın...",pl:"Napisz odpowiedź...",sv:"Skriv ditt svar...",id:"Tulis balasan Anda...",th:"เขียนคำตอบของคุณ..."},
"sidebar.modRole":{en:"Mod",pt:"Mod",fr:"Mod",de:"Mod",it:"Mod",nl:"Mod",ja:"モデレーター",zh:"版主",ru:"Модератор",ar:"مشرف",hi:"मॉड",ko:"모더레이터",tr:"Mod",pl:"Mod",sv:"Mod",id:"Mod",th:"ผู้ดูแล"},
"notifications.markAll":{en:"Mark all",pt:"Marcar todas",fr:"Tout marquer",de:"Alle markieren",it:"Segna tutte",nl:"Alles markeren",ja:"すべてマーク",zh:"全部标记",ru:"Отметить все",ar:"تحديد الكل",hi:"सभी चिह्नित करें",ko:"모두 표시",tr:"Tümünü işaretle",pl:"Zaznacz wszystkie",sv:"Markera alla",id:"Tandai semua",th:"ทำเครื่องหมายทั้งหมด"},
"cookies.description":{en:"We use essential cookies for site functionality and optional cookies to enhance your experience. By clicking \"Accept all\", you agree to use all cookies. You can manage your preferences at any time.",pt:"Usamos cookies essenciais e opcionais para melhorar sua experiência. Ao clicar \"Aceitar tudo\", você aceita todos os cookies.",fr:"Nous utilisons des cookies essentiels et optionnels. En cliquant sur \"Tout accepter\", vous acceptez tous les cookies.",de:"Wir verwenden essentielle und optionale Cookies. Mit \"Alle akzeptieren\" stimmen Sie allen Cookies zu.",it:"Utilizziamo cookie essenziali e opzionali. Cliccando \"Accetta tutto\" accetti tutti i cookie.",nl:"We gebruiken essentiële en optionele cookies. Door \"Alles accepteren\" te klikken ga je akkoord.",ja:"必須Cookieとオプションのcookieを使用しています。「すべて受け入れ」をクリックすると、すべてのcookieに同意します。",zh:"我们使用必要和可选的Cookie。点击\"全部接受\"即表示同意使用所有Cookie。",ru:"Мы используем обязательные и опциональные файлы cookie. Нажимая \"Принять все\", вы соглашаетесь на использование всех cookie.",ar:"نستخدم ملفات تعريف الارتباط الأساسية والاختيارية. بالنقر على \"قبول الكل\"، توافق على استخدام جميع ملفات تعريف الارتباط.",hi:"हम आवश्यक और वैकल्पिक कुकीज़ का उपयोग करते हैं। \"सभी स्वीकार\" पर क्लिक करके आप सभी कुकीज़ से सहमत होते हैं।",ko:"필수 및 선택적 쿠키를 사용합니다. \"모두 수락\"을 클릭하면 모든 쿠키에 동의합니다.",tr:"Temel ve isteğe bağlı çerezler kullanıyoruz. \"Tümünü kabul et\"e tıklayarak tüm çerezleri kabul edersiniz.",pl:"Używamy niezbędnych i opcjonalnych plików cookie. Klikając \"Akceptuj wszystkie\" zgadzasz się na wszystkie.",sv:"Vi använder nödvändiga och valfria cookies. Genom att klicka \"Acceptera alla\" godkänner du alla cookies.",id:"Kami menggunakan cookie esensial dan opsional. Dengan mengklik \"Terima semua\", Anda menyetujui semua cookie.",th:"เราใช้คุกกี้ที่จำเป็นและเสริม การคลิก \"ยอมรับทั้งหมด\" แสดงว่าคุณยอมรับคุกกี้ทั้งหมด"},
"legal.cookieBannerTitle":{en:"🍪 This site uses cookies",pt:"🍪 Este site usa cookies",fr:"🍪 Ce site utilise des cookies",de:"🍪 Diese Seite verwendet Cookies",it:"🍪 Questo sito usa cookie",nl:"🍪 Deze site gebruikt cookies",ja:"🍪 このサイトはCookieを使用しています",zh:"🍪 本站使用Cookie",ru:"🍪 Этот сайт использует cookie",ar:"🍪 هذا الموقع يستخدم ملفات تعريف الارتباط",hi:"🍪 यह साइट कुकीज़ का उपयोग करती है",ko:"🍪 이 사이트는 쿠키를 사용합니다",tr:"🍪 Bu site çerez kullanmaktadır",pl:"🍪 Ta strona używa plików cookie",sv:"🍪 Denna sida använder cookies",id:"🍪 Situs ini menggunakan cookie",th:"🍪 เว็บไซต์นี้ใช้คุกกี้"},
"legal.cookieBannerDescription":{en:"We use essential cookies for site functionality and optional cookies to enhance your experience. By clicking \"Accept all\", you agree to use all cookies. You can manage your preferences at any time.",pt:"Usamos cookies essenciais e opcionais. Ao clicar \"Aceitar tudo\", você aceita todos os cookies.",fr:"Nous utilisons des cookies essentiels et optionnels. En cliquant \"Tout accepter\", vous acceptez tous les cookies.",de:"Wir verwenden essentielle und optionale Cookies. Mit \"Alle akzeptieren\" stimmen Sie allen Cookies zu.",it:"Utilizziamo cookie essenziali e opzionali. Cliccando \"Accetta tutto\" accetti tutti i cookie.",nl:"We gebruiken essentiële en optionele cookies. Door \"Alles accepteren\" te klikken ga je akkoord met alle cookies.",ja:"必須Cookieとオプションのcookieを使用しています。「すべて受け入れ」をクリックすると同意したことになります。",zh:"我们使用必要和可选的Cookie来提升体验。点击\"全部接受\"即同意所有Cookie。",ru:"Мы используем обязательные и опциональные cookie. Нажимая \"Принять все\", вы соглашаетесь с использованием всех cookie.",ar:"نستخدم ملفات تعريف الارتباط الأساسية والاختيارية. بالنقر على \"قبول الكل\" توافق على جميع ملفات تعريف الارتباط.",hi:"हम आवश्यक और वैकल्पिक कुकीज़ का उपयोग करते हैं। \"सभी स्वीकार\" क्लिक करके आप सभी कुकीज़ के उपयोग से सहमत होते हैं।",ko:"필수 및 선택적 쿠키를 사용합니다. \"모두 수락\" 클릭 시 모든 쿠키에 동의합니다.",tr:"Temel ve isteğe bağlı çerezler kullanıyoruz. \"Tümünü kabul et\" diyerek tüm çerezleri kabul edersiniz.",pl:"Używamy niezbędnych i opcjonalnych plików cookie. Klikając \"Akceptuj wszystkie\" zgadzasz się na wszystkie cookie.",sv:"Vi använder nödvändiga och valfria cookies. Genom att klicka \"Acceptera alla\" godkänner du alla cookies.",id:"Kami menggunakan cookie esensial dan opsional. Dengan mengklik \"Terima semua\" Anda menyetujui semua cookie.",th:"เราใช้คุกกี้ที่จำเป็นและเสริมเพื่อปรับปรุงประสบการณ์ การคลิก \"ยอมรับทั้งหมด\" แสดงว่าคุณยอมรับคุกกี้ทั้งหมด"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Batch 4d done!');
