const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === THREAD ===
"thread.createDescription":{en:"Share your content with the community",pt:"Compartilhe seu conteúdo com a comunidade",fr:"Partagez votre contenu avec la communauté",de:"Teilen Sie Ihren Inhalt mit der Community",it:"Condividi il tuo contenuto con la comunità",nl:"Deel je inhoud met de community",ja:"コミュニティとコンテンツを共有",zh:"与社区分享您的内容",ru:"Поделитесь контентом с сообществом",ar:"شارك محتواك مع المجتمع",hi:"समुदाय के साथ अपनी सामग्री साझा करें",ko:"커뮤니티와 콘텐츠를 공유하세요",tr:"İçeriğinizi toplulukla paylaşın",pl:"Podziel się treścią ze społecznością",sv:"Dela ditt innehåll med gemenskapen",id:"Bagikan konten Anda dengan komunitas",th:"แชร์เนื้อหาของคุณกับชุมชน"},
"thread.titlePlaceholder":{en:"E.g.: Services in Polanco - Available",pt:"Ex: Serviços em Polanco - Disponível",fr:"Ex : Services à Polanco - Disponible",de:"Z.B.: Dienste in Polanco - Verfügbar",it:"Es: Servizi a Polanco - Disponibile",nl:"Bijv.: Diensten in Polanco - Beschikbaar",ja:"例：ポランコのサービス - 利用可能",zh:"例：Polanco的服务 - 可用",ru:"Пример: Услуги в Поланко - Доступно",ar:"مثال: خدمات في بولانكو - متاح",hi:"उदा.: पोलैंको में सेवाएं - उपलब्ध",ko:"예: 폴란코 서비스 - 가능",tr:"Örn: Polanco'da hizmetler - Mevcut",pl:"Np.: Usługi w Polanco - Dostępne",sv:"T.ex.: Tjänster i Polanco - Tillgänglig",id:"Contoh: Layanan di Polanco - Tersedia",th:"เช่น: บริการใน Polanco - พร้อมให้บริการ"},
"thread.contentPlaceholder":{en:"Write the content of your thread...",pt:"Escreva o conteúdo do seu tópico...",fr:"Écrivez le contenu de votre sujet...",de:"Schreiben Sie den Inhalt Ihres Themas...",it:"Scrivi il contenuto del tuo thread...",nl:"Schrijf de inhoud van je onderwerp...",ja:"スレッドの内容を入力...",zh:"写下你的主题内容...",ru:"Напишите содержание вашей темы...",ar:"اكتب محتوى موضوعك...",hi:"अपने थ्रेड की सामग्री लिखें...",ko:"스레드 내용을 작성하세요...",tr:"Konu içeriğinizi yazın...",pl:"Napisz treść wątku...",sv:"Skriv innehållet i din tråd...",id:"Tulis konten thread Anda...",th:"เขียนเนื้อหากระทู้ของคุณ..."},
"thread.selectForum":{en:"Select a forum",pt:"Selecione um fórum",fr:"Sélectionnez un forum",de:"Forum auswählen",it:"Seleziona un forum",nl:"Selecteer een forum",ja:"フォーラムを選択",zh:"选择论坛",ru:"Выберите форум",ar:"اختر منتدى",hi:"फ़ोरम चुनें",ko:"포럼 선택",tr:"Forum seçin",pl:"Wybierz forum",sv:"Välj ett forum",id:"Pilih forum",th:"เลือกฟอรั่ม"},
"thread.forumLabel":{en:"Forum",pt:"Fórum",fr:"Forum",de:"Forum",it:"Forum",nl:"Forum",ja:"フォーラム",zh:"论坛",ru:"Форум",ar:"المنتدى",hi:"फ़ोरम",ko:"포럼",tr:"Forum",pl:"Forum",sv:"Forum",id:"Forum",th:"ฟอรั่ม"},
"thread.postingIn":{en:"Posting in:",pt:"Publicando em:",fr:"Publication dans :",de:"Veröffentlichen in:",it:"Pubblicazione in:",nl:"Plaatsen in:",ja:"投稿先：",zh:"发布在：",ru:"Публикация в:",ar:"النشر في:",hi:"में पोस्ट कर रहे हैं:",ko:"게시 위치:",tr:"Paylaşım yeri:",pl:"Publikujesz w:",sv:"Publicerar i:",id:"Memposting di:",th:"โพสต์ใน:"},
"thread.change":{en:"Change",pt:"Mudar",fr:"Changer",de:"Ändern",it:"Cambia",nl:"Wijzigen",ja:"変更",zh:"更改",ru:"Изменить",ar:"تغيير",hi:"बदलें",ko:"변경",tr:"Değiştir",pl:"Zmień",sv:"Ändra",id:"Ubah",th:"เปลี่ยน"},
"thread.minTitleHint":{en:"Minimum 5 characters. Use a descriptive title.",pt:"Mínimo 5 caracteres. Use um título descritivo.",fr:"Minimum 5 caractères. Utilisez un titre descriptif.",de:"Mindestens 5 Zeichen. Verwenden Sie einen beschreibenden Titel.",it:"Minimo 5 caratteri. Usa un titolo descrittivo.",nl:"Minimaal 5 tekens. Gebruik een beschrijvende titel.",ja:"最低5文字。わかりやすいタイトルを使用してください。",zh:"最少5个字符。使用描述性标题。",ru:"Минимум 5 символов. Используйте описательный заголовок.",ar:"الحد الأدنى 5 أحرف. استخدم عنواناً وصفياً.",hi:"न्यूनतम 5 अक्षर। वर्णनात्मक शीर्षक का उपयोग करें।",ko:"최소 5자. 설명적인 제목을 사용하세요.",tr:"Minimum 5 karakter. Açıklayıcı bir başlık kullanın.",pl:"Minimum 5 znaków. Użyj opisowego tytułu.",sv:"Minst 5 tecken. Använd en beskrivande titel.",id:"Minimum 5 karakter. Gunakan judul yang deskriptif.",th:"ขั้นต่ำ 5 ตัวอักษร ใช้ชื่อเรื่องที่อธิบายรายละเอียด"},
"thread.minContentHint":{en:"Minimum 10 characters. You can insert images by pasting or using the image button.",pt:"Mínimo 10 caracteres. Insira imagens colando ou usando o botão.",fr:"Minimum 10 caractères. Insérez des images en collant ou via le bouton.",de:"Mindestens 10 Zeichen. Bilder einfügen durch Einfügen oder Bild-Button.",it:"Minimo 10 caratteri. Inserisci immagini incollando o con il pulsante.",nl:"Minimaal 10 tekens. Voeg afbeeldingen in door te plakken of via de knop.",ja:"最低10文字。画像は貼り付けまたはボタンで挿入できます。",zh:"最少10个字符。可通过粘贴或图片按钮插入图片。",ru:"Минимум 10 символов. Вставляйте изображения, вставив их или используя кнопку.",ar:"الحد الأدنى 10 أحرف. يمكنك إدراج صور بالنسخ أو زر الصورة.",hi:"न्यूनतम 10 अक्षर। छवियाँ पेस्ट या बटन से डालें।",ko:"최소 10자. 이미지를 붙여넣기 또는 버튼으로 삽입하세요.",tr:"Minimum 10 karakter. Görselleri yapıştırarak veya butonla ekleyin.",pl:"Minimum 10 znaków. Wstaw obrazy wklejając lub używając przycisku.",sv:"Minst 10 tecken. Infoga bilder genom att klistra in eller använda knappen.",id:"Minimum 10 karakter. Sisipkan gambar dengan menempel atau tombol gambar.",th:"ขั้นต่ำ 10 ตัวอักษร สามารถแทรกรูปภาพได้"},
"thread.minTitle":{en:"Minimum 5 characters",pt:"Mínimo 5 caracteres",fr:"Minimum 5 caractères",de:"Mindestens 5 Zeichen",it:"Minimo 5 caratteri",nl:"Minimaal 5 tekens",ja:"最低5文字",zh:"最少5个字符",ru:"Минимум 5 символов",ar:"الحد الأدنى 5 أحرف",hi:"न्यूनतम 5 अक्षर",ko:"최소 5자",tr:"Minimum 5 karakter",pl:"Minimum 5 znaków",sv:"Minst 5 tecken",id:"Minimum 5 karakter",th:"ขั้นต่ำ 5 ตัวอักษร"},
"thread.minContent":{en:"Minimum 10 characters",pt:"Mínimo 10 caracteres",fr:"Minimum 10 caractères",de:"Mindestens 10 Zeichen",it:"Minimo 10 caratteri",nl:"Minimaal 10 tekens",ja:"最低10文字",zh:"最少10个字符",ru:"Минимум 10 символов",ar:"الحد الأدنى 10 أحرف",hi:"न्यूनतम 10 अक्षर",ko:"최소 10자",tr:"Minimum 10 karakter",pl:"Minimum 10 znaków",sv:"Minst 10 tecken",id:"Minimum 10 karakter",th:"ขั้นต่ำ 10 ตัวอักษร"},
"thread.nsfwLabel":{en:"NSFW Content",pt:"Conteúdo NSFW",fr:"Contenu NSFW",de:"NSFW-Inhalt",it:"Contenuto NSFW",nl:"NSFW-inhoud",ja:"NSFWコンテンツ",zh:"NSFW内容",ru:"Контент NSFW",ar:"محتوى NSFW",hi:"NSFW सामग्री",ko:"NSFW 콘텐츠",tr:"NSFW İçerik",pl:"Treść NSFW",sv:"NSFW-innehåll",id:"Konten NSFW",th:"เนื้อหา NSFW"},
"thread.nsfwDescription":{en:"Mark if it contains explicit content",pt:"Marque se contém conteúdo explícito",fr:"Cocher si contenu explicite",de:"Markieren, wenn expliziter Inhalt",it:"Segna se contiene contenuto esplicito",nl:"Markeer bij expliciete inhoud",ja:"露骨なコンテンツの場合はマーク",zh:"如果包含露骨内容请标记",ru:"Отметьте, если содержит откровенный контент",ar:"حدد إذا كان يحتوي على محتوى صريح",hi:"स्पष्ट सामग्री होने पर चिह्नित करें",ko:"노골적인 콘텐츠인 경우 표시",tr:"Açık içerik varsa işaretleyin",pl:"Zaznacz jeśli zawiera treści dla dorosłych",sv:"Markera om det innehåller explicit innehåll",id:"Tandai jika berisi konten eksplisit",th:"ทำเครื่องหมายหากมีเนื้อหาที่ชัดเจน"},
"thread.loadingEditor":{en:"Loading editor...",pt:"Carregando editor...",fr:"Chargement de l'éditeur...",de:"Editor wird geladen...",it:"Caricamento editor...",nl:"Editor laden...",ja:"エディタ読み込み中...",zh:"加载编辑器...",ru:"Загрузка редактора...",ar:"جاري تحميل المحرر...",hi:"एडिटर लोड हो रहा है...",ko:"에디터 로딩 중...",tr:"Editör yükleniyor...",pl:"Ładowanie edytora...",sv:"Laddar redigerare...",id:"Memuat editor...",th:"กำลังโหลดตัวแก้ไข..."},
"thread.loginRequired":{en:"You must sign in",pt:"Você deve entrar",fr:"Vous devez vous connecter",de:"Sie müssen sich anmelden",it:"Devi accedere",nl:"Je moet inloggen",ja:"ログインが必要です",zh:"您必须登录",ru:"Необходимо войти",ar:"يجب تسجيل الدخول",hi:"आपको लॉगिन करना होगा",ko:"로그인해야 합니다",tr:"Giriş yapmalısınız",pl:"Musisz się zalogować",sv:"Du måste logga in",id:"Anda harus masuk",th:"คุณต้องเข้าสู่ระบบ"},
"thread.titleMinError":{en:"Title must be at least 5 characters",pt:"O título deve ter pelo menos 5 caracteres",fr:"Le titre doit contenir au moins 5 caractères",de:"Titel muss mindestens 5 Zeichen lang sein",it:"Il titolo deve avere almeno 5 caratteri",nl:"Titel moet minimaal 5 tekens bevatten",ja:"タイトルは5文字以上必要です",zh:"标题至少需要5个字符",ru:"Заголовок должен содержать минимум 5 символов",ar:"يجب أن يكون العنوان 5 أحرف على الأقل",hi:"शीर्षक कम से कम 5 अक्षर का होना चाहिए",ko:"제목은 최소 5자여야 합니다",tr:"Başlık en az 5 karakter olmalıdır",pl:"Tytuł musi mieć co najmniej 5 znaków",sv:"Titeln måste vara minst 5 tecken",id:"Judul harus minimal 5 karakter",th:"ชื่อเรื่องต้องมีอย่างน้อย 5 ตัวอักษร"},
"thread.contentMinError":{en:"Content must be at least 10 characters",pt:"O conteúdo deve ter pelo menos 10 caracteres",fr:"Le contenu doit contenir au moins 10 caractères",de:"Inhalt muss mindestens 10 Zeichen lang sein",it:"Il contenuto deve avere almeno 10 caratteri",nl:"Inhoud moet minimaal 10 tekens bevatten",ja:"コンテンツは10文字以上必要です",zh:"内容至少需要10个字符",ru:"Содержание должно содержать минимум 10 символов",ar:"يجب أن يكون المحتوى 10 أحرف على الأقل",hi:"सामग्री कम से कम 10 अक्षर की होनी चाहिए",ko:"내용은 최소 10자여야 합니다",tr:"İçerik en az 10 karakter olmalıdır",pl:"Treść musi mieć co najmniej 10 znaków",sv:"Innehållet måste vara minst 10 tecken",id:"Konten harus minimal 10 karakter",th:"เนื้อหาต้องมีอย่างน้อย 10 ตัวอักษร"},
"thread.selectForumError":{en:"Select a subforum",pt:"Selecione um subfórum",fr:"Sélectionnez un sous-forum",de:"Wählen Sie ein Unterforum",it:"Seleziona un sottoforum",nl:"Selecteer een subforum",ja:"サブフォーラムを選択してください",zh:"请选择子论坛",ru:"Выберите подфорум",ar:"اختر منتدى فرعي",hi:"एक सबफ़ोरम चुनें",ko:"하위 포럼을 선택하세요",tr:"Bir alt forum seçin",pl:"Wybierz podforum",sv:"Välj ett underforum",id:"Pilih subforum",th:"เลือกฟอรั่มย่อย"},
"thread.pollDescription":{en:"Add a poll to your thread",pt:"Adicione uma enquete ao seu tópico",fr:"Ajoutez un sondage à votre sujet",de:"Umfrage hinzufügen",it:"Aggiungi un sondaggio al tuo thread",nl:"Voeg een poll toe aan je onderwerp",ja:"スレッドにアンケートを追加",zh:"为主题添加投票",ru:"Добавьте опрос к вашей теме",ar:"أضف استطلاعاً لموضوعك",hi:"अपने थ्रेड में पोल जोड़ें",ko:"스레드에 투표 추가",tr:"Konunuza anket ekleyin",pl:"Dodaj ankietę do wątku",sv:"Lägg till en omröstning i din tråd",id:"Tambahkan polling ke thread Anda",th:"เพิ่มโพลในกระทู้ของคุณ"},

// === MESSAGES ===
"messages.noMessagesDescription":{en:"Messages you send and receive will appear here",pt:"Mensagens que você enviar e receber aparecerão aqui",fr:"Les messages que vous envoyez et recevez apparaîtront ici",de:"Nachrichten die Sie senden und empfangen erscheinen hier",it:"I messaggi inviati e ricevuti appariranno qui",nl:"Berichten die je verstuurt en ontvangt verschijnen hier",ja:"送受信したメッセージはここに表示されます",zh:"您发送和接收的消息将显示在这里",ru:"Отправленные и полученные сообщения появятся здесь",ar:"الرسائل التي ترسلها وتستقبلها ستظهر هنا",hi:"आपके भेजे और प्राप्त संदेश यहाँ दिखेंगे",ko:"보내고 받은 메시지가 여기에 표시됩니다",tr:"Gönderdiğiniz ve aldığınız mesajlar burada görünür",pl:"Wysłane i otrzymane wiadomości pojawią się tutaj",sv:"Meddelanden du skickar och tar emot visas här",id:"Pesan yang Anda kirim dan terima akan muncul di sini",th:"ข้อความที่คุณส่งและรับจะปรากฏที่นี่"},
"messages.sending":{en:"Sending...",pt:"Enviando...",fr:"Envoi...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"发送中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"भेज रहे हैं...",ko:"전송 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"messages.loading":{en:"Loading conversations...",pt:"Carregando conversas...",fr:"Chargement des conversations...",de:"Konversationen laden...",it:"Caricamento conversazioni...",nl:"Gesprekken laden...",ja:"会話を読み込み中...",zh:"加载对话...",ru:"Загрузка бесед...",ar:"جاري تحميل المحادثات...",hi:"वार्तालाप लोड हो रहे हैं...",ko:"대화 로딩 중...",tr:"Konuşmalar yükleniyor...",pl:"Ładowanie rozmów...",sv:"Laddar konversationer...",id:"Memuat percakapan...",th:"กำลังโหลดบทสนทนา..."},
"messages.searchConversations":{en:"Search conversations...",pt:"Buscar conversas...",fr:"Rechercher des conversations...",de:"Konversationen suchen...",it:"Cerca conversazioni...",nl:"Gesprekken zoeken...",ja:"会話を検索...",zh:"搜索对话...",ru:"Поиск бесед...",ar:"البحث في المحادثات...",hi:"वार्तालाप खोजें...",ko:"대화 검색...",tr:"Konuşmaları ara...",pl:"Szukaj rozmów...",sv:"Sök konversationer...",id:"Cari percakapan...",th:"ค้นหาบทสนทนา..."},
"messages.searchUsers":{en:"Search users...",pt:"Buscar usuários...",fr:"Rechercher des utilisateurs...",de:"Benutzer suchen...",it:"Cerca utenti...",nl:"Gebruikers zoeken...",ja:"ユーザーを検索...",zh:"搜索用户...",ru:"Поиск пользователей...",ar:"البحث عن مستخدمين...",hi:"उपयोगकर्ता खोजें...",ko:"사용자 검색...",tr:"Kullanıcıları ara...",pl:"Szukaj użytkowników...",sv:"Sök användare...",id:"Cari pengguna...",th:"ค้นหาผู้ใช้..."},
"messages.noUsersFound":{en:"No users found",pt:"Nenhum usuário encontrado",fr:"Aucun utilisateur trouvé",de:"Keine Benutzer gefunden",it:"Nessun utente trovato",nl:"Geen gebruikers gevonden",ja:"ユーザーが見つかりません",zh:"未找到用户",ru:"Пользователи не найдены",ar:"لم يتم العثور على مستخدمين",hi:"कोई उपयोगकर्ता नहीं मिला",ko:"사용자를 찾을 수 없음",tr:"Kullanıcı bulunamadı",pl:"Nie znaleziono użytkowników",sv:"Inga användare hittades",id:"Tidak ada pengguna ditemukan",th:"ไม่พบผู้ใช้"},
"messages.selectConversation":{en:"Select a conversation to begin",pt:"Selecione uma conversa para começar",fr:"Sélectionnez une conversation",de:"Wählen Sie eine Konversation",it:"Seleziona una conversazione",nl:"Selecteer een gesprek",ja:"会話を選択して開始",zh:"选择对话开始",ru:"Выберите беседу",ar:"اختر محادثة للبدء",hi:"शुरू करने के लिए वार्तालाप चुनें",ko:"대화를 선택하세요",tr:"Başlamak için bir konuşma seçin",pl:"Wybierz rozmowę aby rozpocząć",sv:"Välj en konversation för att börja",id:"Pilih percakapan untuk memulai",th:"เลือกบทสนทนาเพื่อเริ่มต้น"},
"messages.emptyMessageError":{en:"Message cannot be empty",pt:"A mensagem não pode estar vazia",fr:"Le message ne peut pas être vide",de:"Nachricht darf nicht leer sein",it:"Il messaggio non può essere vuoto",nl:"Bericht mag niet leeg zijn",ja:"メッセージは空にできません",zh:"消息不能为空",ru:"Сообщение не может быть пустым",ar:"لا يمكن أن تكون الرسالة فارغة",hi:"संदेश खाली नहीं हो सकता",ko:"메시지는 비워둘 수 없습니다",tr:"Mesaj boş olamaz",pl:"Wiadomość nie może być pusta",sv:"Meddelandet kan inte vara tomt",id:"Pesan tidak boleh kosong",th:"ข้อความไม่สามารถว่างเปล่าได้"},
"messages.sendError":{en:"Error sending message",pt:"Erro ao enviar mensagem",fr:"Erreur d'envoi",de:"Fehler beim Senden",it:"Errore di invio",nl:"Fout bij verzenden",ja:"送信エラー",zh:"发送出错",ru:"Ошибка отправки",ar:"خطأ في الإرسال",hi:"भेजने में त्रुटि",ko:"전송 오류",tr:"Gönderme hatası",pl:"Błąd wysyłania",sv:"Sändningsfel",id:"Error mengirim",th:"เกิดข้อผิดพลาดในการส่ง"},
"messages.messageSent":{en:"Message sent",pt:"Mensagem enviada",fr:"Message envoyé",de:"Nachricht gesendet",it:"Messaggio inviato",nl:"Bericht verzonden",ja:"メッセージ送信済み",zh:"消息已发送",ru:"Сообщение отправлено",ar:"تم إرسال الرسالة",hi:"संदेश भेजा गया",ko:"메시지 전송됨",tr:"Mesaj gönderildi",pl:"Wiadomość wysłana",sv:"Meddelande skickat",id:"Pesan terkirim",th:"ส่งข้อความแล้ว"},
"messages.loadingConversation":{en:"Loading conversation...",pt:"Carregando conversa...",fr:"Chargement de la conversation...",de:"Konversation laden...",it:"Caricamento conversazione...",nl:"Gesprek laden...",ja:"会話を読み込み中...",zh:"加载对话...",ru:"Загрузка беседы...",ar:"جاري تحميل المحادثة...",hi:"वार्तालाप लोड हो रहा है...",ko:"대화 로딩 중...",tr:"Konuşma yükleniyor...",pl:"Ładowanie rozmowy...",sv:"Laddar konversation...",id:"Memuat percakapan...",th:"กำลังโหลดบทสนทนา..."},
"messages.noMessagesInConversation":{en:"No messages in this conversation",pt:"Nenhuma mensagem nesta conversa",fr:"Aucun message dans cette conversation",de:"Keine Nachrichten in dieser Konversation",it:"Nessun messaggio in questa conversazione",nl:"Geen berichten in dit gesprek",ja:"この会話にメッセージはありません",zh:"此对话中没有消息",ru:"В этой беседе нет сообщений",ar:"لا توجد رسائل في هذه المحادثة",hi:"इस वार्तालाप में कोई संदेश नहीं",ko:"이 대화에 메시지가 없습니다",tr:"Bu konuşmada mesaj yok",pl:"Brak wiadomości w tej rozmowie",sv:"Inga meddelanden i denna konversation",id:"Tidak ada pesan dalam percakapan ini",th:"ไม่มีข้อความในบทสนทนานี้"},
"messages.sendFirstMessage":{en:"Send the first message to begin",pt:"Envie a primeira mensagem para começar",fr:"Envoyez le premier message",de:"Senden Sie die erste Nachricht",it:"Invia il primo messaggio",nl:"Stuur het eerste bericht",ja:"最初のメッセージを送信して開始",zh:"发送第一条消息开始",ru:"Отправьте первое сообщение",ar:"أرسل الرسالة الأولى للبدء",hi:"शुरू करने के लिए पहला संदेश भेजें",ko:"첫 메시지를 보내 시작하세요",tr:"Başlamak için ilk mesajı gönderin",pl:"Wyślij pierwszą wiadomość",sv:"Skicka det första meddelandet",id:"Kirim pesan pertama untuk memulai",th:"ส่งข้อความแรกเพื่อเริ่มต้น"},
"messages.enterToSend":{en:"Press Enter to send, Shift+Enter for new line",pt:"Pressione Enter para enviar, Shift+Enter para nova linha",fr:"Appuyez sur Entrée pour envoyer, Shift+Entrée pour sauter une ligne",de:"Enter zum Senden, Shift+Enter für neue Zeile",it:"Premi Invio per inviare, Shift+Invio per nuova riga",nl:"Enter om te verzenden, Shift+Enter voor nieuwe regel",ja:"Enterで送信、Shift+Enterで改行",zh:"按Enter发送，Shift+Enter换行",ru:"Enter для отправки, Shift+Enter для новой строки",ar:"اضغط Enter للإرسال، Shift+Enter لسطر جديد",hi:"भेजने के लिए Enter, नई लाइन के लिए Shift+Enter",ko:"Enter로 전송, Shift+Enter로 줄바꿈",tr:"Göndermek için Enter, yeni satır için Shift+Enter",pl:"Enter aby wysłać, Shift+Enter nowa linia",sv:"Enter för att skicka, Shift+Enter för ny rad",id:"Tekan Enter untuk mengirim, Shift+Enter untuk baris baru",th:"กด Enter เพื่อส่ง, Shift+Enter เพื่อขึ้นบรรทัดใหม่"},

// === FORUM ===
"forum.runMigration":{en:"Run the database migration to enable this feature.",pt:"Execute a migração de banco de dados para habilitar esta funcionalidade.",fr:"Exécutez la migration de base de données pour activer cette fonctionnalité.",de:"Führen Sie die Datenbankmigration aus, um diese Funktion zu aktivieren.",it:"Esegui la migrazione del database per abilitare questa funzionalità.",nl:"Voer de databasemigratie uit om deze functie in te schakelen.",ja:"この機能を有効にするためにデータベースの移行を実行してください。",zh:"运行数据库迁移以启用此功能。",ru:"Выполните миграцию базы данных для активации этой функции.",ar:"قم بتنفيذ ترحيل قاعدة البيانات لتفعيل هذه الميزة.",hi:"इस सुविधा को सक्षम करने के लिए डेटाबेस माइग्रेशन चलाएं।",ko:"이 기능을 활성화하려면 데이터베이스 마이그레이션을 실행하세요.",tr:"Bu özelliği etkinleştirmek için veritabanı geçişini çalıştırın.",pl:"Uruchom migrację bazy danych aby włączyć tę funkcję.",sv:"Kör databasmigreringen för att aktivera denna funktion.",id:"Jalankan migrasi database untuk mengaktifkan fitur ini.",th:"รันการโยกย้ายฐานข้อมูลเพื่อเปิดใช้งานฟีเจอร์นี้"},
"forum.noRegionsConfigured":{en:"No cities or regions configured for this country yet.",pt:"Nenhuma cidade ou região configurada para este país ainda.",fr:"Aucune ville ou région configurée pour ce pays.",de:"Keine Städte oder Regionen für dieses Land konfiguriert.",it:"Nessuna città o regione configurata per questo paese.",nl:"Geen steden of regio's geconfigureerd voor dit land.",ja:"この国にはまだ都市や地域が設定されていません。",zh:"此国家尚未配置城市或地区。",ru:"Для этой страны ещё не настроены города или регионы.",ar:"لا توجد مدن أو مناطق مضبوطة لهذا البلد حتى الآن.",hi:"इस देश के लिए अभी तक कोई शहर या क्षेत्र कॉन्फ़िगर नहीं है।",ko:"이 국가에 대해 아직 도시나 지역이 구성되지 않았습니다.",tr:"Bu ülke için henüz şehir veya bölge yapılandırılmamış.",pl:"Brak skonfigurowanych miast lub regionów dla tego kraju.",sv:"Inga städer eller regioner konfigurerade för detta land.",id:"Belum ada kota atau wilayah yang dikonfigurasi untuk negara ini.",th:"ยังไม่มีเมืองหรือภูมิภาคที่กำหนดค่าสำหรับประเทศนี้"},
"forum.generalForumsOf":{en:"General forums of {country}",pt:"Fóruns gerais de {country}",fr:"Forums généraux de {country}",de:"Allgemeine Foren von {country}",it:"Forum generali di {country}",nl:"Algemene forums van {country}",ja:"{country}の一般フォーラム",zh:"{country}的综合论坛",ru:"Общие форумы {country}",ar:"المنتديات العامة لـ {country}",hi:"{country} के सामान्य फ़ोरम",ko:"{country}의 일반 포럼",tr:"{country} genel forumları",pl:"Ogólne fora {country}",sv:"Allmänna forum för {country}",id:"Forum umum {country}",th:"ฟอรั่มทั่วไปของ {country}"},
"forum.beFirstToCreate":{en:"Be the first to create a thread in {name}",pt:"Seja o primeiro a criar um tópico em {name}",fr:"Soyez le premier à créer un sujet dans {name}",de:"Erstellen Sie als Erster ein Thema in {name}",it:"Sii il primo a creare un thread in {name}",nl:"Wees de eerste om een onderwerp te maken in {name}",ja:"{name}で最初のスレッドを作成しましょう",zh:"成为{name}中第一个创建主题的人",ru:"Станьте первым, кто создаст тему в {name}",ar:"كن أول من ينشئ موضوعاً في {name}",hi:"{name} में पहला थ्रेड बनाएं",ko:"{name}에서 첫 스레드를 만들어보세요",tr:"{name} içinde ilk konuyu oluşturun",pl:"Bądź pierwszy i utwórz wątek w {name}",sv:"Var den första att skapa en tråd i {name}",id:"Jadilah yang pertama membuat thread di {name}",th:"เป็นคนแรกที่สร้างกระทู้ใน {name}"},
"forum.minutesAgo":{en:"{count} min ago",pt:"Há {count} min",fr:"Il y a {count} min",de:"Vor {count} Min",it:"{count} min fa",nl:"{count} min geleden",ja:"{count}分前",zh:"{count}分钟前",ru:"{count} мин назад",ar:"منذ {count} دقيقة",hi:"{count} मिनट पहले",ko:"{count}분 전",tr:"{count} dk önce",pl:"{count} min temu",sv:"{count} min sedan",id:"{count} menit lalu",th:"{count} นาทีที่แล้ว"},
"forum.subscribeError":{en:"Error changing subscription",pt:"Erro ao mudar inscrição",fr:"Erreur d'abonnement",de:"Fehler beim Abonnieren",it:"Errore abbonamento",nl:"Fout bij abonnement",ja:"購読変更エラー",zh:"更改订阅出错",ru:"Ошибка подписки",ar:"خطأ في تغيير الاشتراك",hi:"सदस्यता बदलने में त्रुटि",ko:"구독 변경 오류",tr:"Abonelik değiştirme hatası",pl:"Błąd subskrypcji",sv:"Fel vid prenumeration",id:"Error mengubah langganan",th:"เกิดข้อผิดพลาดในการเปลี่ยนการสมัคร"},
"forum.mustLoginToThank":{en:"You must sign in to thank",pt:"Você deve entrar para agradecer",fr:"Connectez-vous pour remercier",de:"Anmelden zum Danken",it:"Accedi per ringraziare",nl:"Log in om te bedanken",ja:"感謝するにはログインが必要です",zh:"登录以感谢",ru:"Войдите, чтобы поблагодарить",ar:"سجل دخولك للشكر",hi:"धन्यवाद देने के लिए लॉगिन करें",ko:"감사하려면 로그인하세요",tr:"Teşekkür etmek için giriş yapın",pl:"Zaloguj się aby podziękować",sv:"Logga in för att tacka",id:"Masuk untuk berterima kasih",th:"เข้าสู่ระบบเพื่อขอบคุณ"},
"forum.cantThankOwnPost":{en:"You can't thank your own post",pt:"Você não pode agradecer seu próprio post",fr:"Vous ne pouvez pas remercier votre propre post",de:"Sie können Ihren eigenen Beitrag nicht bedanken",it:"Non puoi ringraziare il tuo stesso post",nl:"Je kunt je eigen bericht niet bedanken",ja:"自分の投稿には感謝できません",zh:"不能感谢自己的帖子",ru:"Нельзя благодарить свой собственный пост",ar:"لا يمكنك شكر منشورك الخاص",hi:"आप अपनी खुद की पोस्ट को धन्यवाद नहीं दे सकते",ko:"자신의 게시물에 감사할 수 없습니다",tr:"Kendi gönderinize teşekkür edemezsiniz",pl:"Nie możesz podziękować za swój post",sv:"Du kan inte tacka ditt eget inlägg",id:"Anda tidak bisa berterima kasih pada postingan sendiri",th:"คุณไม่สามารถขอบคุณโพสต์ของตัวเองได้"},
"forum.thanksSent":{en:"Thanks sent!",pt:"Agradecimento enviado!",fr:"Merci envoyé !",de:"Danke gesendet!",it:"Grazie inviato!",nl:"Bedankt verzonden!",ja:"感謝を送信しました！",zh:"感谢已发送！",ru:"Благодарность отправлена!",ar:"تم إرسال الشكر!",hi:"धन्यवाद भेजा गया!",ko:"감사가 전송되었습니다!",tr:"Teşekkür gönderildi!",pl:"Podziękowanie wysłane!",sv:"Tack skickat!",id:"Terima kasih terkirim!",th:"ส่งขอบคุณแล้ว!"},
"forum.thanksError":{en:"Error thanking",pt:"Erro ao agradecer",fr:"Erreur de remerciement",de:"Fehler beim Danken",it:"Errore nel ringraziare",nl:"Fout bij bedanken",ja:"感謝送信エラー",zh:"感谢出错",ru:"Ошибка благодарности",ar:"خطأ في الشكر",hi:"धन्यवाद में त्रुटि",ko:"감사 오류",tr:"Teşekkür hatası",pl:"Błąd podziękowania",sv:"Fel vid tack",id:"Error berterima kasih",th:"เกิดข้อผิดพลาดในการขอบคุณ"},
"forum.thanked":{en:"Thanked",pt:"Agradecido",fr:"Remercié",de:"Bedankt",it:"Ringraziato",nl:"Bedankt",ja:"感謝済み",zh:"已感谢",ru:"Благодарность отправлена",ar:"تم الشكر",hi:"धन्यवाद दिया",ko:"감사함",tr:"Teşekkür edildi",pl:"Podziękowano",sv:"Tackat",id:"Berterima kasih",th:"ขอบคุณแล้ว"},
"forum.removeThanks":{en:"Remove thanks",pt:"Remover agradecimento",fr:"Retirer le merci",de:"Danke entfernen",it:"Rimuovi ringraziamento",nl:"Bedankt verwijderen",ja:"感謝を取り消す",zh:"取消感谢",ru:"Убрать благодарность",ar:"إزالة الشكر",hi:"धन्यवाद हटाएं",ko:"감사 취소",tr:"Teşekkürü kaldır",pl:"Usuń podziękowanie",sv:"Ta bort tack",id:"Hapus terima kasih",th:"ลบการขอบคุณ"},
"forum.thankThisPost":{en:"Thank this post",pt:"Agradecer este post",fr:"Remercier ce post",de:"Diesem Beitrag danken",it:"Ringrazia questo post",nl:"Dit bericht bedanken",ja:"この投稿に感謝する",zh:"感谢此帖子",ru:"Поблагодарить за этот пост",ar:"شكر هذا المنشور",hi:"इस पोस्ट को धन्यवाद दें",ko:"이 게시물에 감사",tr:"Bu gönderiyi teşekkür et",pl:"Podziękuj za ten post",sv:"Tacka detta inlägg",id:"Berterima kasih untuk postingan ini",th:"ขอบคุณโพสต์นี้"},
"forum.mustLoginToQuote":{en:"You must sign in to quote",pt:"Você deve entrar para citar",fr:"Connectez-vous pour citer",de:"Anmelden zum Zitieren",it:"Accedi per citare",nl:"Log in om te citeren",ja:"引用するにはログインが必要です",zh:"登录以引用",ru:"Войдите, чтобы цитировать",ar:"سجل دخولك للاقتباس",hi:"उद्धृत करने के लिए लॉगिन करें",ko:"인용하려면 로그인하세요",tr:"Alıntı yapmak için giriş yapın",pl:"Zaloguj się aby cytować",sv:"Logga in för att citera",id:"Masuk untuk mengutip",th:"เข้าสู่ระบบเพื่ออ้างอิง"},
"forum.quoteAdded":{en:"Quote added",pt:"Citação adicionada",fr:"Citation ajoutée",de:"Zitat hinzugefügt",it:"Citazione aggiunta",nl:"Citaat toegevoegd",ja:"引用が追加されました",zh:"引用已添加",ru:"Цитата добавлена",ar:"تمت إضافة الاقتباس",hi:"उद्धरण जोड़ा गया",ko:"인용이 추가되었습니다",tr:"Alıntı eklendi",pl:"Cytat dodany",sv:"Citat tillagt",id:"Kutipan ditambahkan",th:"เพิ่มการอ้างอิงแล้ว"},
"forum.quoteThisPost":{en:"Quote this post",pt:"Citar este post",fr:"Citer ce post",de:"Diesen Beitrag zitieren",it:"Cita questo post",nl:"Dit bericht citeren",ja:"この投稿を引用",zh:"引用此帖子",ru:"Цитировать этот пост",ar:"اقتبس هذا المنشور",hi:"इस पोस्ट को उद्धृत करें",ko:"이 게시물 인용",tr:"Bu gönderiyi alıntıla",pl:"Cytuj ten post",sv:"Citera detta inlägg",id:"Kutip postingan ini",th:"อ้างอิงโพสต์นี้"},
"forum.mustLoginToReact":{en:"Sign in to react",pt:"Entre para reagir",fr:"Connectez-vous pour réagir",de:"Anmelden zum Reagieren",it:"Accedi per reagire",nl:"Log in om te reageren",ja:"リアクションするにはログイン",zh:"登录以回应",ru:"Войдите, чтобы отреагировать",ar:"سجل دخولك للتفاعل",hi:"प्रतिक्रिया के लिए लॉगिन करें",ko:"반응하려면 로그인",tr:"Tepki vermek için giriş yapın",pl:"Zaloguj się aby zareagować",sv:"Logga in för att reagera",id:"Masuk untuk bereaksi",th:"เข้าสู่ระบบเพื่อรีแอ็ค"},
"forum.reactError":{en:"Error reacting",pt:"Erro ao reagir",fr:"Erreur de réaction",de:"Fehler beim Reagieren",it:"Errore reazione",nl:"Fout bij reageren",ja:"リアクションエラー",zh:"回应出错",ru:"Ошибка реакции",ar:"خطأ في التفاعل",hi:"प्रतिक्रिया में त्रुटि",ko:"반응 오류",tr:"Tepki hatası",pl:"Błąd reakcji",sv:"Reaktionsfel",id:"Error bereaksi",th:"เกิดข้อผิดพลาดในการรีแอ็ค"},

// === COMMON ===
"common.deleteImage":{en:"Delete image",pt:"Excluir imagem",fr:"Supprimer l'image",de:"Bild löschen",it:"Elimina immagine",nl:"Afbeelding verwijderen",ja:"画像を削除",zh:"删除图片",ru:"Удалить изображение",ar:"حذف الصورة",hi:"छवि हटाएं",ko:"이미지 삭제",tr:"Görseli sil",pl:"Usuń obraz",sv:"Ta bort bild",id:"Hapus gambar",th:"ลบรูปภาพ"},
"common.deleting":{en:"Deleting...",pt:"Excluindo...",fr:"Suppression...",de:"Wird gelöscht...",it:"Eliminazione...",nl:"Verwijderen...",ja:"削除中...",zh:"删除中...",ru:"Удаление...",ar:"جاري الحذف...",hi:"हटा रहे हैं...",ko:"삭제 중...",tr:"Siliniyor...",pl:"Usuwanie...",sv:"Tar bort...",id:"Menghapus...",th:"กำลังลบ..."},
"common.sending":{en:"Sending...",pt:"Enviando...",fr:"Envoi...",de:"Wird gesendet...",it:"Invio...",nl:"Verzenden...",ja:"送信中...",zh:"发送中...",ru:"Отправка...",ar:"جاري الإرسال...",hi:"भेज रहे हैं...",ko:"전송 중...",tr:"Gönderiliyor...",pl:"Wysyłanie...",sv:"Skickar...",id:"Mengirim...",th:"กำลังส่ง..."},
"common.sendReport":{en:"Send report",pt:"Enviar reporte",fr:"Envoyer le signalement",de:"Bericht senden",it:"Invia segnalazione",nl:"Rapport verzenden",ja:"報告を送信",zh:"发送举报",ru:"Отправить жалобу",ar:"إرسال البلاغ",hi:"रिपोर्ट भेजें",ko:"신고 보내기",tr:"Rapor gönder",pl:"Wyślij zgłoszenie",sv:"Skicka rapport",id:"Kirim laporan",th:"ส่งรายงาน"},
"common.searchConversations":{en:"Search conversations...",pt:"Buscar conversas...",fr:"Rechercher des conversations...",de:"Konversationen suchen...",it:"Cerca conversazioni...",nl:"Gesprekken zoeken...",ja:"会話を検索...",zh:"搜索对话...",ru:"Поиск бесед...",ar:"البحث في المحادثات...",hi:"वार्तालाप खोजें...",ko:"대화 검색...",tr:"Konuşmaları ara...",pl:"Szukaj rozmów...",sv:"Sök konversationer...",id:"Cari percakapan...",th:"ค้นหาบทสนทนา..."},
"common.maxImagesError":{en:"Maximum {max} images allowed",pt:"Máximo de {max} imagens permitidas",fr:"Maximum {max} images autorisées",de:"Maximal {max} Bilder erlaubt",it:"Massimo {max} immagini consentite",nl:"Maximaal {max} afbeeldingen toegestaan",ja:"最大{max}枚の画像が許可されています",zh:"最多允许{max}张图片",ru:"Максимум {max} изображений",ar:"الحد الأقصى {max} صور مسموح بها",hi:"अधिकतम {max} छवियाँ अनुमत",ko:"최대 {max}개의 이미지 허용",tr:"Maksimum {max} görsel izni",pl:"Maksymalnie {max} obrazów",sv:"Max {max} bilder tillåtna",id:"Maksimal {max} gambar diizinkan",th:"อนุญาตสูงสุด {max} รูปภาพ"},
"common.invalidFile":{en:"Invalid file",pt:"Arquivo inválido",fr:"Fichier invalide",de:"Ungültige Datei",it:"File non valido",nl:"Ongeldig bestand",ja:"無効なファイル",zh:"无效的文件",ru:"Недопустимый файл",ar:"ملف غير صالح",hi:"अमान्य फ़ाइल",ko:"유효하지 않은 파일",tr:"Geçersiz dosya",pl:"Nieprawidłowy plik",sv:"Ogiltig fil",id:"File tidak valid",th:"ไฟล์ไม่ถูกต้อง"},
"common.imageUploaded":{en:"Image uploaded successfully",pt:"Imagem enviada com sucesso",fr:"Image téléchargée avec succès",de:"Bild erfolgreich hochgeladen",it:"Immagine caricata con successo",nl:"Afbeelding succesvol geüpload",ja:"画像アップロード完了",zh:"图片上传成功",ru:"Изображение загружено",ar:"تم رفع الصورة بنجاح",hi:"छवि सफलतापूर्वक अपलोड",ko:"이미지 업로드 성공",tr:"Görsel başarıyla yüklendi",pl:"Obraz przesłany pomyślnie",sv:"Bild uppladdad",id:"Gambar berhasil diunggah",th:"อัปโหลดรูปสำเร็จ"},
"common.imageUploadError":{en:"Error uploading image",pt:"Erro ao enviar imagem",fr:"Erreur de téléchargement d'image",de:"Fehler beim Hochladen des Bildes",it:"Errore caricamento immagine",nl:"Fout bij uploaden afbeelding",ja:"画像アップロードエラー",zh:"上传图片出错",ru:"Ошибка загрузки изображения",ar:"خطأ في رفع الصورة",hi:"छवि अपलोड त्रुटि",ko:"이미지 업로드 오류",tr:"Görsel yükleme hatası",pl:"Błąd przesyłania obrazu",sv:"Fel vid bilduppladdning",id:"Error mengunggah gambar",th:"เกิดข้อผิดพลาดในการอัปโหลด"},
"common.unexpectedUploadError":{en:"Unexpected error uploading images",pt:"Erro inesperado ao enviar imagens",fr:"Erreur inattendue lors du téléchargement",de:"Unerwarteter Fehler beim Hochladen",it:"Errore imprevisto durante il caricamento",nl:"Onverwachte fout bij uploaden",ja:"画像アップロード中に予期しないエラー",zh:"上传图片时发生意外错误",ru:"Непредвиденная ошибка при загрузке",ar:"خطأ غير متوقع في رفع الصور",hi:"छवियाँ अपलोड करते समय अप्रत्याशित त्रुटि",ko:"이미지 업로드 중 예상치 못한 오류",tr:"Görsel yüklerken beklenmeyen hata",pl:"Nieoczekiwany błąd przesyłania",sv:"Oväntat fel vid uppladdning",id:"Error tidak terduga saat mengunggah",th:"เกิดข้อผิดพลาดที่ไม่คาดคิดในการอัปโหลด"},
"common.avatarUpdated":{en:"Avatar updated",pt:"Avatar atualizado",fr:"Avatar mis à jour",de:"Avatar aktualisiert",it:"Avatar aggiornato",nl:"Avatar bijgewerkt",ja:"アバター更新済み",zh:"头像已更新",ru:"Аватар обновлён",ar:"تم تحديث الصورة الرمزية",hi:"अवतार अपडेट किया गया",ko:"아바타 업데이트됨",tr:"Avatar güncellendi",pl:"Avatar zaktualizowany",sv:"Avatar uppdaterad",id:"Avatar diperbarui",th:"อัปเดตอวาตาร์แล้ว"},
"common.avatarUploadError":{en:"Error uploading avatar",pt:"Erro ao enviar avatar",fr:"Erreur de téléchargement d'avatar",de:"Fehler beim Avatar-Upload",it:"Errore caricamento avatar",nl:"Fout bij avatar-upload",ja:"アバターアップロードエラー",zh:"上传头像出错",ru:"Ошибка загрузки аватара",ar:"خطأ في رفع الصورة الرمزية",hi:"अवतार अपलोड त्रुटि",ko:"아바타 업로드 오류",tr:"Avatar yükleme hatası",pl:"Błąd przesyłania avatara",sv:"Fel vid avatar-uppladdning",id:"Error mengunggah avatar",th:"เกิดข้อผิดพลาดในการอัปโหลดอวาตาร์"},
"common.allNotificationsRead":{en:"All notifications marked as read",pt:"Todas as notificações marcadas como lidas",fr:"Toutes les notifications marquées comme lues",de:"Alle Benachrichtigungen als gelesen markiert",it:"Tutte le notifiche contrassegnate come lette",nl:"Alle meldingen als gelezen gemarkeerd",ja:"すべての通知を既読にしました",zh:"所有通知已标记为已读",ru:"Все уведомления отмечены как прочитанные",ar:"تم تحديد جميع الإشعارات كمقروءة",hi:"सभी सूचनाएं पढ़ी गई के रूप में चिह्नित",ko:"모든 알림 읽음 처리됨",tr:"Tüm bildirimler okundu olarak işaretlendi",pl:"Wszystkie powiadomienia oznaczone jako przeczytane",sv:"Alla aviseringar markerade som lästa",id:"Semua notifikasi ditandai sudah dibaca",th:"ทำเครื่องหมายอ่านแล้วทั้งหมด"},
"common.messageSendError":{en:"Error sending message",pt:"Erro ao enviar mensagem",fr:"Erreur d'envoi de message",de:"Fehler beim Senden der Nachricht",it:"Errore invio messaggio",nl:"Fout bij verzenden bericht",ja:"メッセージ送信エラー",zh:"发送消息出错",ru:"Ошибка отправки сообщения",ar:"خطأ في إرسال الرسالة",hi:"संदेश भेजने में त्रुटि",ko:"메시지 전송 오류",tr:"Mesaj gönderme hatası",pl:"Błąd wysyłania wiadomości",sv:"Fel vid meddelandesändning",id:"Error mengirim pesan",th:"เกิดข้อผิดพลาดในการส่งข้อความ"},
"common.viewOriginal":{en:"View original",pt:"Ver original",fr:"Voir l'original",de:"Original ansehen",it:"Vedi originale",nl:"Origineel bekijken",ja:"原文を見る",zh:"查看原文",ru:"Просмотреть оригинал",ar:"عرض الأصلي",hi:"मूल देखें",ko:"원본 보기",tr:"Orijinali görüntüle",pl:"Zobacz oryginał",sv:"Visa original",id:"Lihat asli",th:"ดูต้นฉบับ"},
"common.deletedUser":{en:"Deleted user",pt:"Usuário excluído",fr:"Utilisateur supprimé",de:"Gelöschter Benutzer",it:"Utente eliminato",nl:"Verwijderde gebruiker",ja:"削除されたユーザー",zh:"已删除的用户",ru:"Удалённый пользователь",ar:"مستخدم محذوف",hi:"हटाया गया उपयोगकर्ता",ko:"삭제된 사용자",tr:"Silinmiş kullanıcı",pl:"Usunięty użytkownik",sv:"Borttagen användare",id:"Pengguna dihapus",th:"ผู้ใช้ที่ถูกลบ"},
"common.editNumber":{en:"Edit #{num}",pt:"Edição #{num}",fr:"Édition #{num}",de:"Bearbeitung #{num}",it:"Modifica #{num}",nl:"Bewerking #{num}",ja:"編集 #{num}",zh:"编辑 #{num}",ru:"Редакция #{num}",ar:"تعديل #{num}",hi:"संपादन #{num}",ko:"편집 #{num}",tr:"Düzenleme #{num}",pl:"Edycja #{num}",sv:"Redigering #{num}",id:"Edit #{num}",th:"แก้ไข #{num}"},
"common.editReason":{en:"Reason: {reason}",pt:"Razão: {reason}",fr:"Raison : {reason}",de:"Grund: {reason}",it:"Motivo: {reason}",nl:"Reden: {reason}",ja:"理由: {reason}",zh:"原因：{reason}",ru:"Причина: {reason}",ar:"السبب: {reason}",hi:"कारण: {reason}",ko:"사유: {reason}",tr:"Sebep: {reason}",pl:"Powód: {reason}",sv:"Anledning: {reason}",id:"Alasan: {reason}",th:"เหตุผล: {reason}"},
"common.collapse":{en:"Collapse",pt:"Recolher",fr:"Réduire",de:"Einklappen",it:"Comprimi",nl:"Samenvouwen",ja:"折りたたむ",zh:"折叠",ru:"Свернуть",ar:"طي",hi:"संक्षिप्त करें",ko:"접기",tr:"Daralt",pl:"Zwiń",sv:"Fäll ihop",id:"Ciutkan",th:"ย่อ"},
"common.expand":{en:"Expand",pt:"Expandir",fr:"Développer",de:"Ausklappen",it:"Espandi",nl:"Uitvouwen",ja:"展開",zh:"展开",ru:"Развернуть",ar:"توسيع",hi:"विस्तृत करें",ko:"펼치기",tr:"Genişlet",pl:"Rozwiń",sv:"Expandera",id:"Perluas",th:"ขยาย"},
"common.markAllAsRead":{en:"Mark all",pt:"Marcar todas",fr:"Tout marquer",de:"Alle markieren",it:"Segna tutte",nl:"Alles markeren",ja:"すべてマーク",zh:"全部标记",ru:"Отметить все",ar:"تحديد الكل",hi:"सभी चिह्नित करें",ko:"모두 표시",tr:"Tümünü işaretle",pl:"Zaznacz wszystkie",sv:"Markera alla",id:"Tandai semua",th:"ทำเครื่องหมายทั้งหมด"},
"common.noConversations":{en:"No conversations",pt:"Nenhuma conversa",fr:"Aucune conversation",de:"Keine Konversationen",it:"Nessuna conversazione",nl:"Geen gesprekken",ja:"会話なし",zh:"没有对话",ru:"Нет бесед",ar:"لا توجد محادثات",hi:"कोई वार्तालाप नहीं",ko:"대화 없음",tr:"Konuşma yok",pl:"Brak rozmów",sv:"Inga konversationer",id:"Tidak ada percakapan",th:"ไม่มีบทสนทนา"},
"common.startNew":{en:"Start a new one",pt:"Iniciar uma nova",fr:"Commencer une nouvelle",de:"Neue starten",it:"Iniziane una nuova",nl:"Nieuw starten",ja:"新しい会話を開始",zh:"开始新的对话",ru:"Начать новую",ar:"ابدأ جديدة",hi:"नया शुरू करें",ko:"새로 시작",tr:"Yeni başlat",pl:"Rozpocznij nową",sv:"Starta en ny",id:"Mulai yang baru",th:"เริ่มใหม่"},
"common.backToPreviousPage":{en:"Back to previous page",pt:"Voltar à página anterior",fr:"Retour à la page précédente",de:"Zurück zur vorherigen Seite",it:"Torna alla pagina precedente",nl:"Terug naar vorige pagina",ja:"前のページに戻る",zh:"返回上一页",ru:"Вернуться на предыдущую страницу",ar:"العودة إلى الصفحة السابقة",hi:"पिछले पृष्ठ पर वापस जाएं",ko:"이전 페이지로 돌아가기",tr:"Önceki sayfaya dön",pl:"Wróć do poprzedniej strony",sv:"Tillbaka till föregående sida",id:"Kembali ke halaman sebelumnya",th:"กลับไปหน้าก่อนหน้า"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Batch 4e done!');
