const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === ADMIN SUSPENSIONS (43) ===
"adminSuspensions.title":{en:"Suspension Management",pt:"Gestão de Suspensões",fr:"Gestion des Suspensions",de:"Sperrungsverwaltung",it:"Gestione Sospensioni",nl:"Schorsingsbeheer",ja:"停止管理",zh:"暂停管理",ru:"Управление блокировками",ar:"إدارة الإيقافات",hi:"निलंबन प्रबंधन",ko:"정지 관리",tr:"Askıya Alma Yönetimi",pl:"Zarządzanie Zawieszeniami",sv:"Avstängningshantering",id:"Manajemen Penangguhan",th:"การจัดการการระงับ"},
"adminSuspensions.description":{en:"Manage suspensions and bans",pt:"Administrar suspensões e expulsões",fr:"Gérer les suspensions et bannissements",de:"Sperrungen und Ausschlüsse verwalten",it:"Gestisci sospensioni ed espulsioni",nl:"Beheer schorsingen en verbanningen",ja:"停止措置とBANを管理",zh:"管理暂停和封禁",ru:"Управление блокировками и банами",ar:"إدارة الإيقافات والطرد",hi:"निलंबन और प्रतिबंध प्रबंधित करें",ko:"정지 및 차단 관리",tr:"Askıya almaları ve yasaklamaları yönet",pl:"Zarządzaj zawieszeniami i banami",sv:"Hantera avstängningar och bannlysningar",id:"Kelola penangguhan dan pemblokiran",th:"จัดการการระงับและการแบน"},
"adminSuspensions.backToPanel":{en:"← Back to panel",pt:"← Voltar ao painel",fr:"← Retour au panneau",de:"← Zurück zum Panel",it:"← Torna al pannello",nl:"← Terug naar paneel",ja:"← パネルに戻る",zh:"← 返回面板",ru:"← Вернуться к панели",ar:"← العودة إلى اللوحة",hi:"← पैनल पर वापस जाएं",ko:"← 패널로 돌아가기",tr:"← Panele dön",pl:"← Wróć do panelu",sv:"← Tillbaka till panelen",id:"← Kembali ke panel",th:"← กลับไปที่แผงควบคุม"},
"adminSuspensions.newSuspension":{en:"New Suspension",pt:"Nova Suspensão",fr:"Nouvelle Suspension",de:"Neue Sperrung",it:"Nuova Sospensione",nl:"Nieuwe Schorsing",ja:"新しい停止措置",zh:"新暂停",ru:"Новая блокировка",ar:"إيقاف جديد",hi:"नया निलंबन",ko:"새 정지",tr:"Yeni Askıya Alma",pl:"Nowe Zawieszenie",sv:"Ny Avstängning",id:"Penangguhan Baru",th:"การระงับใหม่"},
"adminSuspensions.type":{en:"Type",pt:"Tipo",fr:"Type",de:"Typ",it:"Tipo",nl:"Type",ja:"タイプ",zh:"类型",ru:"Тип",ar:"النوع",hi:"प्रकार",ko:"유형",tr:"Tür",pl:"Typ",sv:"Typ",id:"Tipe",th:"ประเภท"},
"adminSuspensions.temporary":{en:"Temporary",pt:"Temporária",fr:"Temporaire",de:"Temporär",it:"Temporanea",nl:"Tijdelijk",ja:"一時的",zh:"临时",ru:"Временная",ar:"مؤقت",hi:"अस्थायी",ko:"임시",tr:"Geçici",pl:"Tymczasowe",sv:"Tillfällig",id:"Sementara",th:"ชั่วคราว"},
"adminSuspensions.permanentBan":{en:"Permanent (Ban)",pt:"Permanente (Expulsão)",fr:"Permanent (Bannissement)",de:"Permanent (Ausschluss)",it:"Permanente (Espulsione)",nl:"Permanent (Verbanning)",ja:"永久（BAN）",zh:"永久（封禁）",ru:"Постоянная (бан)",ar:"دائم (طرد)",hi:"स्थायी (प्रतिबंध)",ko:"영구 (차단)",tr:"Kalıcı (Yasak)",pl:"Permanentne (Ban)",sv:"Permanent (Bannlysning)",id:"Permanen (Blokir)",th:"ถาวร (แบน)"},
"adminSuspensions.permanent":{en:"Permanent",pt:"Permanente",fr:"Permanent",de:"Permanent",it:"Permanente",nl:"Permanent",ja:"永久",zh:"永久",ru:"Постоянная",ar:"دائم",hi:"स्थायी",ko:"영구",tr:"Kalıcı",pl:"Permanentne",sv:"Permanent",id:"Permanen",th:"ถาวร"},
"adminSuspensions.durationDays":{en:"Duration (days)",pt:"Duração (dias)",fr:"Durée (jours)",de:"Dauer (Tage)",it:"Durata (giorni)",nl:"Duur (dagen)",ja:"期間（日）",zh:"期限（天）",ru:"Длительность (дней)",ar:"المدة (أيام)",hi:"अवधि (दिन)",ko:"기간 (일)",tr:"Süre (gün)",pl:"Czas trwania (dni)",sv:"Varaktighet (dagar)",id:"Durasi (hari)",th:"ระยะเวลา (วัน)"},
"adminSuspensions.reason":{en:"Reason",pt:"Razão",fr:"Raison",de:"Grund",it:"Motivo",nl:"Reden",ja:"理由",zh:"原因",ru:"Причина",ar:"السبب",hi:"कारण",ko:"사유",tr:"Sebep",pl:"Powód",sv:"Anledning",id:"Alasan",th:"เหตุผล"},
"adminSuspensions.reasonPlaceholder":{en:"Reason for suspension",pt:"Razão da suspensão",fr:"Raison de la suspension",de:"Grund der Sperrung",it:"Motivo della sospensione",nl:"Reden voor schorsing",ja:"停止の理由",zh:"暂停原因",ru:"Причина блокировки",ar:"سبب الإيقاف",hi:"निलंबन का कारण",ko:"정지 사유",tr:"Askıya alma nedeni",pl:"Powód zawieszenia",sv:"Anledning till avstängning",id:"Alasan penangguhan",th:"เหตุผลของการระงับ"},
"adminSuspensions.descriptionLabel":{en:"Description (max 200 characters)",pt:"Descrição (máx 200 caracteres)",fr:"Description (max 200 caractères)",de:"Beschreibung (max. 200 Zeichen)",it:"Descrizione (max 200 caratteri)",nl:"Beschrijving (max 200 tekens)",ja:"説明（最大200文字）",zh:"描述（最多200个字符）",ru:"Описание (макс. 200 символов)",ar:"الوصف (حد أقصى 200 حرف)",hi:"विवरण (अधिकतम 200 अक्षर)",ko:"설명 (최대 200자)",tr:"Açıklama (maks. 200 karakter)",pl:"Opis (maks. 200 znaków)",sv:"Beskrivning (max 200 tecken)",id:"Deskripsi (maks 200 karakter)",th:"คำอธิบาย (สูงสุด 200 ตัวอักษร)"},
"adminSuspensions.descriptionPlaceholder":{en:"Detailed description...",pt:"Descrição detalhada...",fr:"Description détaillée...",de:"Detaillierte Beschreibung...",it:"Descrizione dettagliata...",nl:"Gedetailleerde beschrijving...",ja:"詳細な説明...",zh:"详细描述...",ru:"Подробное описание...",ar:"وصف مفصل...",hi:"विस्तृत विवरण...",ko:"상세 설명...",tr:"Ayrıntılı açıklama...",pl:"Szczegółowy opis...",sv:"Detaljerad beskrivning...",id:"Deskripsi detail...",th:"คำอธิบายโดยละเอียด..."},
"adminSuspensions.createSuspension":{en:"Create Suspension",pt:"Criar Suspensão",fr:"Créer une Suspension",de:"Sperrung erstellen",it:"Crea Sospensione",nl:"Schorsing Aanmaken",ja:"停止措置を作成",zh:"创建暂停",ru:"Создать блокировку",ar:"إنشاء إيقاف",hi:"निलंबन बनाएं",ko:"정지 생성",tr:"Askıya Alma Oluştur",pl:"Utwórz Zawieszenie",sv:"Skapa Avstängning",id:"Buat Penangguhan",th:"สร้างการระงับ"},
"adminSuspensions.searchPlaceholder":{en:"Search by username...",pt:"Buscar por nome de usuário...",fr:"Rechercher par nom d'utilisateur...",de:"Nach Benutzername suchen...",it:"Cerca per nome utente...",nl:"Zoeken op gebruikersnaam...",ja:"ユーザー名で検索...",zh:"按用户名搜索...",ru:"Поиск по имени пользователя...",ar:"البحث باسم المستخدم...",hi:"उपयोगकर्ता नाम से खोजें...",ko:"사용자 이름으로 검색...",tr:"Kullanıcı adıyla ara...",pl:"Szukaj po nazwie użytkownika...",sv:"Sök efter användarnamn...",id:"Cari berdasarkan nama pengguna...",th:"ค้นหาด้วยชื่อผู้ใช้..."},
"adminSuspensions.filterActive":{en:"Active",pt:"Ativas",fr:"Actives",de:"Aktive",it:"Attive",nl:"Actief",ja:"アクティブ",zh:"活跃",ru:"Активные",ar:"نشطة",hi:"सक्रिय",ko:"활성",tr:"Aktif",pl:"Aktywne",sv:"Aktiva",id:"Aktif",th:"ใช้งานอยู่"},
"adminSuspensions.filterLifted":{en:"Lifted",pt:"Levantadas",fr:"Levées",de:"Aufgehoben",it:"Rimosse",nl:"Opgeheven",ja:"解除済み",zh:"已解除",ru:"Снятые",ar:"مرفوعة",hi:"हटाई गई",ko:"해제됨",tr:"Kaldırılan",pl:"Zniesione",sv:"Upphävda",id:"Dicabut",th:"ยกเลิกแล้ว"},
"adminSuspensions.noSuspensions":{en:"No suspensions",pt:"Sem suspensões",fr:"Aucune suspension",de:"Keine Sperrungen",it:"Nessuna sospensione",nl:"Geen schorsingen",ja:"停止措置なし",zh:"没有暂停",ru:"Нет блокировок",ar:"لا توجد إيقافات",hi:"कोई निलंबन नहीं",ko:"정지 없음",tr:"Askıya alma yok",pl:"Brak zawieszeń",sv:"Inga avstängningar",id:"Tidak ada penangguhan",th:"ไม่มีการระงับ"},
"adminSuspensions.expires":{en:"Expires",pt:"Expira",fr:"Expire",de:"Läuft ab",it:"Scade",nl:"Verloopt",ja:"期限",zh:"到期",ru:"Истекает",ar:"ينتهي",hi:"समाप्ति",ko:"만료",tr:"Bitiş",pl:"Wygasa",sv:"Löper ut",id:"Kedaluwarsa",th:"หมดอายุ"},
"adminSuspensions.status":{en:"Status",pt:"Estado",fr:"Statut",de:"Status",it:"Stato",nl:"Status",ja:"ステータス",zh:"状态",ru:"Статус",ar:"الحالة",hi:"स्थिति",ko:"상태",tr:"Durum",pl:"Status",sv:"Status",id:"Status",th:"สถานะ"},
"adminSuspensions.suspendedBy":{en:"Suspended by",pt:"Suspendido por",fr:"Suspendu par",de:"Gesperrt von",it:"Sospeso da",nl:"Geschorst door",ja:"停止実行者",zh:"暂停者",ru:"Заблокировано",ar:"أوقف بواسطة",hi:"द्वारा निलंबित",ko:"정지 실행자",tr:"Askıya alan",pl:"Zawieszony przez",sv:"Avstängd av",id:"Ditangguhkan oleh",th:"ระงับโดย"},
"adminSuspensions.never":{en:"Never",pt:"Nunca",fr:"Jamais",de:"Nie",it:"Mai",nl:"Nooit",ja:"なし",zh:"永不",ru:"Никогда",ar:"أبداً",hi:"कभी नहीं",ko:"없음",tr:"Asla",pl:"Nigdy",sv:"Aldrig",id:"Tidak pernah",th:"ไม่มี"},
"adminSuspensions.active":{en:"Active",pt:"Ativa",fr:"Active",de:"Aktiv",it:"Attiva",nl:"Actief",ja:"アクティブ",zh:"活跃",ru:"Активная",ar:"نشطة",hi:"सक्रिय",ko:"활성",tr:"Aktif",pl:"Aktywne",sv:"Aktiv",id:"Aktif",th:"ใช้งานอยู่"},
"adminSuspensions.lifted":{en:"Lifted",pt:"Levantada",fr:"Levée",de:"Aufgehoben",it:"Rimossa",nl:"Opgeheven",ja:"解除済み",zh:"已解除",ru:"Снята",ar:"مرفوعة",hi:"हटाई गई",ko:"해제됨",tr:"Kaldırıldı",pl:"Zniesione",sv:"Upphävd",id:"Dicabut",th:"ยกเลิกแล้ว"},
"adminSuspensions.liftSuspension":{en:"Lift suspension",pt:"Levantar suspensão",fr:"Lever la suspension",de:"Sperrung aufheben",it:"Rimuovi sospensione",nl:"Schorsing opheffen",ja:"停止を解除",zh:"解除暂停",ru:"Снять блокировку",ar:"رفع الإيقاف",hi:"निलंबन हटाएं",ko:"정지 해제",tr:"Askıyı kaldır",pl:"Zdejmij zawieszenie",sv:"Häv avstängning",id:"Cabut penangguhan",th:"ยกเลิกการระงับ"},
"adminSuspensions.editSuspension":{en:"Edit Suspension",pt:"Editar Suspensão",fr:"Modifier la Suspension",de:"Sperrung bearbeiten",it:"Modifica Sospensione",nl:"Schorsing Bewerken",ja:"停止措置を編集",zh:"编辑暂停",ru:"Редактировать блокировку",ar:"تعديل الإيقاف",hi:"निलंबन संपादित करें",ko:"정지 편집",tr:"Askıyı Düzenle",pl:"Edytuj Zawieszenie",sv:"Redigera Avstängning",id:"Edit Penangguhan",th:"แก้ไขการระงับ"},
"adminSuspensions.userAndReasonRequired":{en:"User and reason are required",pt:"Usuário e razão são obrigatórios",fr:"L'utilisateur et la raison sont requis",de:"Benutzer und Grund sind erforderlich",it:"Utente e motivo sono obbligatori",nl:"Gebruiker en reden zijn vereist",ja:"ユーザーと理由は必須です",zh:"用户和原因为必填项",ru:"Пользователь и причина обязательны",ar:"المستخدم والسبب مطلوبان",hi:"उपयोगकर्ता और कारण आवश्यक हैं",ko:"사용자와 사유는 필수입니다",tr:"Kullanıcı ve sebep gereklidir",pl:"Użytkownik i powód są wymagane",sv:"Användare och anledning krävs",id:"Pengguna dan alasan wajib diisi",th:"ต้องระบุผู้ใช้และเหตุผล"},
"adminSuspensions.userNotFound":{en:"User not found",pt:"Usuário não encontrado",fr:"Utilisateur introuvable",de:"Benutzer nicht gefunden",it:"Utente non trovato",nl:"Gebruiker niet gevonden",ja:"ユーザーが見つかりません",zh:"用户未找到",ru:"Пользователь не найден",ar:"المستخدم غير موجود",hi:"उपयोगकर्ता नहीं मिला",ko:"사용자를 찾을 수 없음",tr:"Kullanıcı bulunamadı",pl:"Użytkownik nie znaleziony",sv:"Användare hittades inte",id:"Pengguna tidak ditemukan",th:"ไม่พบผู้ใช้"},
"adminSuspensions.errorCreating":{en:"Error creating suspension",pt:"Erro ao criar suspensão",fr:"Erreur de création de suspension",de:"Fehler beim Erstellen der Sperrung",it:"Errore nella creazione della sospensione",nl:"Fout bij aanmaken schorsing",ja:"停止措置の作成エラー",zh:"创建暂停出错",ru:"Ошибка создания блокировки",ar:"خطأ في إنشاء الإيقاف",hi:"निलंबन बनाने में त्रुटि",ko:"정지 생성 오류",tr:"Askıya alma oluşturma hatası",pl:"Błąd tworzenia zawieszenia",sv:"Fel vid skapande av avstängning",id:"Error membuat penangguhan",th:"เกิดข้อผิดพลาดในการสร้างการระงับ"},
"adminSuspensions.notifBanned":{en:"You have been banned",pt:"Você foi banido",fr:"Vous avez été banni",de:"Sie wurden ausgeschlossen",it:"Sei stato espulso",nl:"Je bent verbannen",ja:"あなたはBANされました",zh:"您已被封禁",ru:"Вы были забанены",ar:"تم حظرك",hi:"आपको प्रतिबंधित कर दिया गया है",ko:"차단되었습니다",tr:"Yasaklandınız",pl:"Zostałeś zbanowany",sv:"Du har blivit bannlyst",id:"Anda telah diblokir",th:"คุณถูกแบน"},
"adminSuspensions.notifSuspended":{en:"You have been suspended",pt:"Você foi suspenso",fr:"Vous avez été suspendu",de:"Sie wurden gesperrt",it:"Sei stato sospeso",nl:"Je bent geschorst",ja:"あなたは停止されました",zh:"您已被暂停",ru:"Вы были заблокированы",ar:"تم إيقافك",hi:"आपको निलंबित कर दिया गया है",ko:"정지되었습니다",tr:"Askıya alındınız",pl:"Zostałeś zawieszony",sv:"Du har blivit avstängd",id:"Anda telah ditangguhkan",th:"คุณถูกระงับ"},
"adminSuspensions.durationLabel":{en:"Duration",pt:"Duração",fr:"Durée",de:"Dauer",it:"Durata",nl:"Duur",ja:"期間",zh:"期限",ru:"Длительность",ar:"المدة",hi:"अवधि",ko:"기간",tr:"Süre",pl:"Czas trwania",sv:"Varaktighet",id:"Durasi",th:"ระยะเวลา"},
"adminSuspensions.days":{en:"days",pt:"dias",fr:"jours",de:"Tage",it:"giorni",nl:"dagen",ja:"日",zh:"天",ru:"дней",ar:"أيام",hi:"दिन",ko:"일",tr:"gün",pl:"dni",sv:"dagar",id:"hari",th:"วัน"},
"adminSuspensions.permanentAction":{en:"This action is permanent.",pt:"Esta ação é permanente.",fr:"Cette action est permanente.",de:"Diese Aktion ist permanent.",it:"Questa azione è permanente.",nl:"Deze actie is permanent.",ja:"この操作は永久的です。",zh:"此操作是永久性的。",ru:"Это действие необратимо.",ar:"هذا الإجراء دائم.",hi:"यह कार्रवाई स्थायी है।",ko:"이 작업은 영구적입니다.",tr:"Bu eylem kalıcıdır.",pl:"Ta akcja jest trwała.",sv:"Denna åtgärd är permanent.",id:"Tindakan ini bersifat permanen.",th:"การดำเนินการนี้เป็นแบบถาวร"},
"adminSuspensions.created":{en:"Suspension created",pt:"Suspensão criada",fr:"Suspension créée",de:"Sperrung erstellt",it:"Sospensione creata",nl:"Schorsing aangemaakt",ja:"停止措置が作成されました",zh:"暂停已创建",ru:"Блокировка создана",ar:"تم إنشاء الإيقاف",hi:"निलंबन बनाया गया",ko:"정지 생성됨",tr:"Askıya alma oluşturuldu",pl:"Zawieszenie utworzone",sv:"Avstängning skapad",id:"Penangguhan dibuat",th:"สร้างการระงับแล้ว"},
"adminSuspensions.errorUpdating":{en:"Error updating",pt:"Erro ao atualizar",fr:"Erreur de mise à jour",de:"Fehler beim Aktualisieren",it:"Errore nell'aggiornamento",nl:"Fout bij bijwerken",ja:"更新エラー",zh:"更新出错",ru:"Ошибка обновления",ar:"خطأ في التحديث",hi:"अपडेट में त्रुटि",ko:"업데이트 오류",tr:"Güncelleme hatası",pl:"Błąd aktualizacji",sv:"Uppdateringsfel",id:"Error memperbarui",th:"เกิดข้อผิดพลาดในการอัปเดต"},
"adminSuspensions.updated":{en:"Suspension updated",pt:"Suspensão atualizada",fr:"Suspension mise à jour",de:"Sperrung aktualisiert",it:"Sospensione aggiornata",nl:"Schorsing bijgewerkt",ja:"停止措置が更新されました",zh:"暂停已更新",ru:"Блокировка обновлена",ar:"تم تحديث الإيقاف",hi:"निलंबन अपडेट किया गया",ko:"정지 업데이트됨",tr:"Askıya alma güncellendi",pl:"Zawieszenie zaktualizowane",sv:"Avstängning uppdaterad",id:"Penangguhan diperbarui",th:"อัปเดตการระงับแล้ว"},
"adminSuspensions.errorLifting":{en:"Error lifting suspension",pt:"Erro ao levantar suspensão",fr:"Erreur de levée de suspension",de:"Fehler beim Aufheben der Sperrung",it:"Errore nella rimozione della sospensione",nl:"Fout bij opheffen schorsing",ja:"停止解除エラー",zh:"解除暂停出错",ru:"Ошибка снятия блокировки",ar:"خطأ في رفع الإيقاف",hi:"निलंबन हटाने में त्रुटि",ko:"정지 해제 오류",tr:"Askıyı kaldırma hatası",pl:"Błąd zdejmowania zawieszenia",sv:"Fel vid hävning av avstängning",id:"Error mencabut penangguhan",th:"เกิดข้อผิดพลาดในการยกเลิกการระงับ"},
"adminSuspensions.liftedManually":{en:"Suspension lifted manually",pt:"Suspensão levantada manualmente",fr:"Suspension levée manuellement",de:"Sperrung manuell aufgehoben",it:"Sospensione rimossa manualmente",nl:"Schorsing handmatig opgeheven",ja:"停止措置が手動で解除されました",zh:"手动解除暂停",ru:"Блокировка снята вручную",ar:"تم رفع الإيقاف يدوياً",hi:"निलंबन मैन्युअल रूप से हटाया गया",ko:"수동으로 정지 해제됨",tr:"Askıya alma manuel olarak kaldırıldı",pl:"Zawieszenie zdjęte ręcznie",sv:"Avstängning hävd manuellt",id:"Penangguhan dicabut secara manual",th:"ยกเลิกการระงับด้วยตนเอง"},
"adminSuspensions.liftedSuccess":{en:"Suspension lifted",pt:"Suspensão levantada",fr:"Suspension levée",de:"Sperrung aufgehoben",it:"Sospensione rimossa",nl:"Schorsing opgeheven",ja:"停止が解除されました",zh:"暂停已解除",ru:"Блокировка снята",ar:"تم رفع الإيقاف",hi:"निलंबन हटाया गया",ko:"정지 해제됨",tr:"Askıya alma kaldırıldı",pl:"Zawieszenie zdjęte",sv:"Avstängning hävd",id:"Penangguhan dicabut",th:"ยกเลิกการระงับแล้ว"},
"adminSuspensions.confirmDelete":{en:"Delete this suspension from history?",pt:"Excluir esta suspensão do histórico?",fr:"Supprimer cette suspension de l'historique ?",de:"Diese Sperrung aus dem Verlauf löschen?",it:"Eliminare questa sospensione dalla cronologia?",nl:"Deze schorsing uit de geschiedenis verwijderen?",ja:"この停止措置を履歴から削除しますか？",zh:"从历史记录中删除此暂停？",ru:"Удалить эту блокировку из истории?",ar:"حذف هذا الإيقاف من السجل؟",hi:"इस निलंबन को इतिहास से हटाएं?",ko:"이 정지를 기록에서 삭제하시겠습니까?",tr:"Bu askıya almayı geçmişten sil?",pl:"Usunąć to zawieszenie z historii?",sv:"Ta bort denna avstängning från historiken?",id:"Hapus penangguhan ini dari riwayat?",th:"ลบการระงับนี้จากประวัติ?"},
"adminSuspensions.errorDeleting":{en:"Error deleting",pt:"Erro ao excluir",fr:"Erreur de suppression",de:"Fehler beim Löschen",it:"Errore nell'eliminazione",nl:"Fout bij verwijderen",ja:"削除エラー",zh:"删除出错",ru:"Ошибка удаления",ar:"خطأ في الحذف",hi:"हटाने में त्रुटि",ko:"삭제 오류",tr:"Silme hatası",pl:"Błąd usuwania",sv:"Borttagningsfel",id:"Error menghapus",th:"เกิดข้อผิดพลาดในการลบ"},
"adminSuspensions.deleted":{en:"Suspension deleted",pt:"Suspensão excluída",fr:"Suspension supprimée",de:"Sperrung gelöscht",it:"Sospensione eliminata",nl:"Schorsing verwijderd",ja:"停止措置が削除されました",zh:"暂停已删除",ru:"Блокировка удалена",ar:"تم حذف الإيقاف",hi:"निलंबन हटाया गया",ko:"정지 삭제됨",tr:"Askıya alma silindi",pl:"Zawieszenie usunięte",sv:"Avstängning borttagen",id:"Penangguhan dihapus",th:"ลบการระงับแล้ว"},
// === ADMIN PAYMENTS (38) ===
"adminPayments.title":{en:"Payment Management",pt:"Gestão de Pagamentos",fr:"Gestion des Paiements",de:"Zahlungsverwaltung",it:"Gestione Pagamenti",nl:"Betalingsbeheer",ja:"支払い管理",zh:"支付管理",ru:"Управление платежами",ar:"إدارة المدفوعات",hi:"भुगतान प्रबंधन",ko:"결제 관리",tr:"Ödeme Yönetimi",pl:"Zarządzanie Płatnościami",sv:"Betalningshantering",id:"Manajemen Pembayaran",th:"การจัดการการชำระเงิน"},
"adminPayments.subtitle":{en:"Review and manage advertising payments.",pt:"Revise e gerencie pagamentos de publicidade.",fr:"Examinez et gérez les paiements de publicité.",de:"Überprüfen und verwalten Sie Werbezahlungen.",it:"Rivedi e gestisci i pagamenti pubblicitari.",nl:"Beoordeel en beheer advertentiebetalingen.",ja:"広告の支払いを確認・管理",zh:"审核和管理广告支付。",ru:"Проверяйте и управляйте рекламными платежами.",ar:"راجع وأدر مدفوعات الإعلانات.",hi:"विज्ञापन भुगतान की समीक्षा और प्रबंधन करें।",ko:"광고 결제를 검토하고 관리하세요.",tr:"Reklam ödemelerini inceleyin ve yönetin.",pl:"Przeglądaj i zarządzaj płatnościami za reklamy.",sv:"Granska och hantera annonsbetalningar.",id:"Tinjau dan kelola pembayaran iklan.",th:"ตรวจสอบและจัดการการชำระเงินโฆษณา"},
"adminPayments.pendingPayments":{en:"Pending",pt:"Pendentes",fr:"En attente",de:"Ausstehend",it:"In attesa",nl:"In afwachting",ja:"保留中",zh:"待处理",ru:"Ожидающие",ar:"معلقة",hi:"लंबित",ko:"대기 중",tr:"Beklemede",pl:"Oczekujące",sv:"Väntande",id:"Menunggu",th:"รอดำเนินการ"},
"adminPayments.awaitingReview":{en:"Awaiting review",pt:"Aguardando revisão",fr:"En attente de révision",de:"Wartet auf Prüfung",it:"In attesa di revisione",nl:"Wacht op beoordeling",ja:"レビュー待ち",zh:"等待审核",ru:"Ожидает проверки",ar:"بانتظار المراجعة",hi:"समीक्षा की प्रतीक्षा",ko:"검토 대기",tr:"İnceleme bekliyor",pl:"Oczekuje na przegląd",sv:"Väntar på granskning",id:"Menunggu tinjauan",th:"รอการตรวจสอบ"},
"adminPayments.confirmed":{en:"Confirmed",pt:"Confirmados",fr:"Confirmés",de:"Bestätigt",it:"Confermati",nl:"Bevestigd",ja:"確認済み",zh:"已确认",ru:"Подтверждённые",ar:"مؤكدة",hi:"पुष्टि",ko:"확인됨",tr:"Onaylanan",pl:"Potwierdzone",sv:"Bekräftade",id:"Dikonfirmasi",th:"ยืนยันแล้ว"},
"adminPayments.totalRevenue":{en:"Total revenue",pt:"Receita total",fr:"Revenu total",de:"Gesamtumsatz",it:"Entrate totali",nl:"Totale inkomsten",ja:"総収益",zh:"总收入",ru:"Общий доход",ar:"إجمالي الإيرادات",hi:"कुल राजस्व",ko:"총 수익",tr:"Toplam gelir",pl:"Łączny przychód",sv:"Total intäkt",id:"Total pendapatan",th:"รายได้รวม"},
"adminPayments.filterByStatus":{en:"Filter by status",pt:"Filtrar por estado",fr:"Filtrer par statut",de:"Nach Status filtern",it:"Filtra per stato",nl:"Filter op status",ja:"ステータスで絞り込み",zh:"按状态筛选",ru:"Фильтр по статусу",ar:"تصفية حسب الحالة",hi:"स्थिति के अनुसार फ़िल्टर",ko:"상태별 필터",tr:"Duruma göre filtrele",pl:"Filtruj wg statusu",sv:"Filtrera efter status",id:"Filter berdasarkan status",th:"กรองตามสถานะ"},
"adminPayments.statusPending":{en:"Pending",pt:"Pendente",fr:"En attente",de:"Ausstehend",it:"In attesa",nl:"In afwachting",ja:"保留中",zh:"待处理",ru:"Ожидающий",ar:"معلق",hi:"लंबित",ko:"대기",tr:"Beklemede",pl:"Oczekujący",sv:"Väntande",id:"Menunggu",th:"รอดำเนินการ"},
"adminPayments.statusSubmitted":{en:"Proof submitted",pt:"Comprovante enviado",fr:"Justificatif envoyé",de:"Beleg eingereicht",it:"Ricevuta inviata",nl:"Bewijs ingediend",ja:"証明書提出済み",zh:"凭证已提交",ru:"Подтверждение отправлено",ar:"تم إرسال الإثبات",hi:"प्रमाण सबमिट",ko:"증빙 제출됨",tr:"Kanıt gönderildi",pl:"Dowód wysłany",sv:"Kvitto inskickat",id:"Bukti dikirim",th:"ส่งหลักฐานแล้ว"},
"adminPayments.statusConfirmed":{en:"Confirmed",pt:"Confirmado",fr:"Confirmé",de:"Bestätigt",it:"Confermato",nl:"Bevestigd",ja:"確認済み",zh:"已确认",ru:"Подтверждён",ar:"مؤكد",hi:"पुष्टि",ko:"확인됨",tr:"Onaylandı",pl:"Potwierdzony",sv:"Bekräftad",id:"Dikonfirmasi",th:"ยืนยันแล้ว"},
"adminPayments.statusRejected":{en:"Rejected",pt:"Rejeitado",fr:"Rejeté",de:"Abgelehnt",it:"Rifiutato",nl:"Afgewezen",ja:"拒否",zh:"已拒绝",ru:"Отклонён",ar:"مرفوض",hi:"अस्वीकृत",ko:"거부됨",tr:"Reddedildi",pl:"Odrzucony",sv:"Avvisad",id:"Ditolak",th:"ถูกปฏิเสธ"},
"adminPayments.searchPlaceholder":{en:"Search by reference or user...",pt:"Buscar por referência ou usuário...",fr:"Rechercher par référence ou utilisateur...",de:"Nach Referenz oder Benutzer suchen...",it:"Cerca per riferimento o utente...",nl:"Zoeken op referentie of gebruiker...",ja:"参照番号またはユーザーで検索...",zh:"按参考编号或用户搜索...",ru:"Поиск по номеру или пользователю...",ar:"البحث بالمرجع أو المستخدم...",hi:"संदर्भ या उपयोगकर्ता से खोजें...",ko:"참조번호 또는 사용자로 검색...",tr:"Referans veya kullanıcıyla ara...",pl:"Szukaj po referencji lub użytkowniku...",sv:"Sök efter referens eller användare...",id:"Cari berdasarkan referensi atau pengguna...",th:"ค้นหาด้วยอ้างอิงหรือผู้ใช้..."},
"adminPayments.noPayments":{en:"No payments registered.",pt:"Nenhum pagamento registrado.",fr:"Aucun paiement enregistré.",de:"Keine Zahlungen registriert.",it:"Nessun pagamento registrato.",nl:"Geen betalingen geregistreerd.",ja:"登録された支払いはありません。",zh:"没有已注册的支付。",ru:"Нет зарегистрированных платежей.",ar:"لا توجد مدفوعات مسجلة.",hi:"कोई भुगतान पंजीकृत नहीं।",ko:"등록된 결제가 없습니다.",tr:"Kayıtlı ödeme yok.",pl:"Brak zarejestrowanych płatności.",sv:"Inga registrerade betalningar.",id:"Tidak ada pembayaran terdaftar.",th:"ไม่มีการชำระเงินที่ลงทะเบียน"},
"adminPayments.status_pending":{en:"Pending",pt:"Pendente",fr:"En attente",de:"Ausstehend",it:"In attesa",nl:"In afwachting",ja:"保留中",zh:"待处理",ru:"Ожидающий",ar:"معلق",hi:"लंबित",ko:"대기",tr:"Beklemede",pl:"Oczekujący",sv:"Väntande",id:"Menunggu",th:"รอดำเนินการ"},
"adminPayments.status_submitted":{en:"Submitted",pt:"Enviado",fr:"Envoyé",de:"Eingereicht",it:"Inviato",nl:"Ingediend",ja:"提出済み",zh:"已提交",ru:"Отправлен",ar:"مرسل",hi:"सबमिट",ko:"제출됨",tr:"Gönderildi",pl:"Wysłany",sv:"Inskickad",id:"Dikirim",th:"ส่งแล้ว"},
"adminPayments.status_confirmed":{en:"Confirmed",pt:"Confirmado",fr:"Confirmé",de:"Bestätigt",it:"Confermato",nl:"Bevestigd",ja:"確認済み",zh:"已确认",ru:"Подтверждён",ar:"مؤكد",hi:"पुष्टि",ko:"확인됨",tr:"Onaylandı",pl:"Potwierdzony",sv:"Bekräftad",id:"Dikonfirmasi",th:"ยืนยันแล้ว"},
"adminPayments.status_rejected":{en:"Rejected",pt:"Rejeitado",fr:"Rejeté",de:"Abgelehnt",it:"Rifiutato",nl:"Afgewezen",ja:"拒否",zh:"已拒绝",ru:"Отклонён",ar:"مرفوض",hi:"अस्वीकृत",ko:"거부됨",tr:"Reddedildi",pl:"Odrzucony",sv:"Avvisad",id:"Ditolak",th:"ถูกปฏิเสธ"},
"adminPayments.status_refunded":{en:"Refunded",pt:"Reembolsado",fr:"Remboursé",de:"Erstattet",it:"Rimborsato",nl:"Terugbetaald",ja:"返金済み",zh:"已退款",ru:"Возвращён",ar:"مسترد",hi:"रिफ़ंड",ko:"환불됨",tr:"İade edildi",pl:"Zwrócony",sv:"Återbetald",id:"Dikembalikan",th:"คืนเงินแล้ว"},
"adminPayments.status_cancelled":{en:"Cancelled",pt:"Cancelado",fr:"Annulé",de:"Storniert",it:"Cancellato",nl:"Geannuleerd",ja:"キャンセル済み",zh:"已取消",ru:"Отменён",ar:"ملغى",hi:"रद्द",ko:"취소됨",tr:"İptal edildi",pl:"Anulowany",sv:"Avbruten",id:"Dibatalkan",th:"ยกเลิกแล้ว"},
"adminPayments.paymentDetails":{en:"Payment details",pt:"Detalhes do pagamento",fr:"Détails du paiement",de:"Zahlungsdetails",it:"Dettagli del pagamento",nl:"Betalingsdetails",ja:"支払い詳細",zh:"支付详情",ru:"Детали платежа",ar:"تفاصيل الدفع",hi:"भुगतान विवरण",ko:"결제 상세",tr:"Ödeme detayları",pl:"Szczegóły płatności",sv:"Betalningsdetaljer",id:"Detail pembayaran",th:"รายละเอียดการชำระเงิน"},
"adminPayments.reference":{en:"Reference",pt:"Referência",fr:"Référence",de:"Referenz",it:"Riferimento",nl:"Referentie",ja:"参照番号",zh:"参考编号",ru:"Номер",ar:"المرجع",hi:"संदर्भ",ko:"참조번호",tr:"Referans",pl:"Numer referencyjny",sv:"Referens",id:"Referensi",th:"อ้างอิง"},
"adminPayments.amount":{en:"Amount",pt:"Valor",fr:"Montant",de:"Betrag",it:"Importo",nl:"Bedrag",ja:"金額",zh:"金额",ru:"Сумма",ar:"المبلغ",hi:"राशि",ko:"금액",tr:"Tutar",pl:"Kwota",sv:"Belopp",id:"Jumlah",th:"จำนวน"},
"adminPayments.method":{en:"Method",pt:"Método",fr:"Méthode",de:"Methode",it:"Metodo",nl:"Methode",ja:"方法",zh:"方式",ru:"Метод",ar:"الطريقة",hi:"विधि",ko:"방법",tr:"Yöntem",pl:"Metoda",sv:"Metod",id:"Metode",th:"วิธี"},
"adminPayments.proofNotes":{en:"Proof notes",pt:"Notas do comprovante",fr:"Notes du justificatif",de:"Belegnotizen",it:"Note della ricevuta",nl:"Bewijsnotities",ja:"証明書メモ",zh:"凭证备注",ru:"Заметки к подтверждению",ar:"ملاحظات الإثبات",hi:"प्रमाण नोट्स",ko:"증빙 메모",tr:"Kanıt notları",pl:"Notatki do dowodu",sv:"Kvittoanteckningar",id:"Catatan bukti",th:"หมายเหตุหลักฐาน"},
"adminPayments.proofFile":{en:"Proof file",pt:"Arquivo de comprovante",fr:"Fichier justificatif",de:"Belegdatei",it:"File ricevuta",nl:"Bewijsbestand",ja:"証明書ファイル",zh:"凭证文件",ru:"Файл подтверждения",ar:"ملف الإثبات",hi:"प्रमाण फ़ाइल",ko:"증빙 파일",tr:"Kanıt dosyası",pl:"Plik dowodu",sv:"Kvittofil",id:"File bukti",th:"ไฟล์หลักฐาน"},
"adminPayments.viewProof":{en:"View proof",pt:"Ver comprovante",fr:"Voir le justificatif",de:"Beleg ansehen",it:"Vedi ricevuta",nl:"Bewijs bekijken",ja:"証明書を表示",zh:"查看凭证",ru:"Просмотреть подтверждение",ar:"عرض الإثبات",hi:"प्रमाण देखें",ko:"증빙 보기",tr:"Kanıtı gör",pl:"Zobacz dowód",sv:"Visa kvitto",id:"Lihat bukti",th:"ดูหลักฐาน"},
"adminPayments.confirmPaymentTitle":{en:"Confirm payment",pt:"Confirmar pagamento",fr:"Confirmer le paiement",de:"Zahlung bestätigen",it:"Conferma pagamento",nl:"Betaling bevestigen",ja:"支払いを確認",zh:"确认支付",ru:"Подтвердить платёж",ar:"تأكيد الدفع",hi:"भुगतान की पुष्टि करें",ko:"결제 확인",tr:"Ödemeyi onayla",pl:"Potwierdź płatność",sv:"Bekräfta betalning",id:"Konfirmasi pembayaran",th:"ยืนยันการชำระเงิน"},
"adminPayments.confirmPaymentDesc":{en:"Confirm payment {ref}? This will approve the banner and generate an invoice.",pt:"Confirmar pagamento {ref}? Isto aprovará o banner e gerará uma fatura.",fr:"Confirmer le paiement {ref} ? Cela approuvera la bannière et générera une facture.",de:"Zahlung {ref} bestätigen? Dies genehmigt das Banner und erstellt eine Rechnung.",it:"Confermare pagamento {ref}? Questo approverà il banner e genererà una fattura.",nl:"Betaling {ref} bevestigen? Dit keurt de banner goed en genereert een factuur.",ja:"支払い{ref}を確認しますか？バナーが承認され請求書が生成されます。",zh:"确认支付{ref}？这将批准横幅并生成发票。",ru:"Подтвердить платёж {ref}? Это одобрит баннер и создаст счёт.",ar:"تأكيد الدفع {ref}؟ سيوافق على الإعلان وينشئ فاتورة.",hi:"भुगतान {ref} की पुष्टि करें? यह बैनर को स्वीकृत करेगा और चालान बनाएगा।",ko:"결제 {ref}를 확인하시겠습니까? 배너가 승인되고 청구서가 생성됩니다.",tr:"{ref} ödemesini onayla? Banner onaylanacak ve fatura oluşturulacak.",pl:"Potwierdzić płatność {ref}? Baner zostanie zatwierdzony i wygenerowana faktura.",sv:"Bekräfta betalning {ref}? Bannern godkänns och en faktura skapas.",id:"Konfirmasi pembayaran {ref}? Ini akan menyetujui banner dan membuat faktur.",th:"ยืนยันการชำระเงิน {ref}? จะอนุมัติแบนเนอร์และสร้างใบแจ้งหนี้"},
"adminPayments.adminNotesPlaceholder":{en:"Administrator notes (optional)",pt:"Notas do administrador (opcional)",fr:"Notes de l'administrateur (optionnel)",de:"Administratornotizen (optional)",it:"Note dell'amministratore (opzionale)",nl:"Beheerdernotities (optioneel)",ja:"管理者メモ（任意）",zh:"管理员备注（可选）",ru:"Заметки администратора (необязательно)",ar:"ملاحظات المسؤول (اختياري)",hi:"व्यवस्थापक नोट्स (वैकल्पिक)",ko:"관리자 메모 (선택사항)",tr:"Yönetici notları (isteğe bağlı)",pl:"Notatki administratora (opcjonalnie)",sv:"Administratörsanteckningar (valfritt)",id:"Catatan administrator (opsional)",th:"หมายเหตุผู้ดูแลระบบ (ไม่จำเป็น)"},
"adminPayments.confirmBtn":{en:"Confirm payment",pt:"Confirmar pagamento",fr:"Confirmer le paiement",de:"Zahlung bestätigen",it:"Conferma pagamento",nl:"Betaling bevestigen",ja:"支払いを確認",zh:"确认支付",ru:"Подтвердить платёж",ar:"تأكيد الدفع",hi:"भुगतान की पुष्टि करें",ko:"결제 확인",tr:"Ödemeyi onayla",pl:"Potwierdź płatność",sv:"Bekräfta betalning",id:"Konfirmasi pembayaran",th:"ยืนยันการชำระเงิน"},
"adminPayments.paymentConfirmed":{en:"Payment confirmed",pt:"Pagamento confirmado",fr:"Paiement confirmé",de:"Zahlung bestätigt",it:"Pagamento confermato",nl:"Betaling bevestigd",ja:"支払い確認済み",zh:"支付已确认",ru:"Платёж подтверждён",ar:"تم تأكيد الدفع",hi:"भुगतान पुष्टि",ko:"결제 확인됨",tr:"Ödeme onaylandı",pl:"Płatność potwierdzona",sv:"Betalning bekräftad",id:"Pembayaran dikonfirmasi",th:"ยืนยันการชำระเงินแล้ว"},
"adminPayments.invoice":{en:"Invoice",pt:"Fatura",fr:"Facture",de:"Rechnung",it:"Fattura",nl:"Factuur",ja:"請求書",zh:"发票",ru:"Счёт",ar:"فاتورة",hi:"चालान",ko:"청구서",tr:"Fatura",pl:"Faktura",sv:"Faktura",id:"Faktur",th:"ใบแจ้งหนี้"},
"adminPayments.rejectPaymentTitle":{en:"Reject payment",pt:"Rejeitar pagamento",fr:"Rejeter le paiement",de:"Zahlung ablehnen",it:"Rifiuta pagamento",nl:"Betaling afwijzen",ja:"支払いを拒否",zh:"拒绝支付",ru:"Отклонить платёж",ar:"رفض الدفع",hi:"भुगतान अस्वीकार करें",ko:"결제 거부",tr:"Ödemeyi reddet",pl:"Odrzuć płatność",sv:"Avvisa betalning",id:"Tolak pembayaran",th:"ปฏิเสธการชำระเงิน"},
"adminPayments.rejectPaymentDesc":{en:"Indicate the reason for rejection. The user will be notified.",pt:"Indique o motivo da rejeição. O usuário será notificado.",fr:"Indiquez le motif du rejet. L'utilisateur sera notifié.",de:"Geben Sie den Ablehnungsgrund an. Der Benutzer wird benachrichtigt.",it:"Indica il motivo del rifiuto. L'utente sarà notificato.",nl:"Geef de reden van afwijzing aan. De gebruiker wordt op de hoogte gesteld.",ja:"拒否理由を記入してください。ユーザーに通知されます。",zh:"请注明拒绝原因。用户将被通知。",ru:"Укажите причину отказа. Пользователь будет уведомлён.",ar:"حدد سبب الرفض. سيتم إخطار المستخدم.",hi:"अस्वीकृति का कारण बताएं। उपयोगकर्ता को सूचित किया जाएगा।",ko:"거부 사유를 입력하세요. 사용자에게 알림이 전송됩니다.",tr:"Ret nedenini belirtin. Kullanıcı bilgilendirilecek.",pl:"Podaj powód odrzucenia. Użytkownik zostanie powiadomiony.",sv:"Ange orsaken till avvisning. Användaren meddelas.",id:"Tunjukkan alasan penolakan. Pengguna akan diberitahu.",th:"ระบุเหตุผลของการปฏิเสธ ผู้ใช้จะได้รับการแจ้งเตือน"},
"adminPayments.rejectReasonPlaceholder":{en:"Reason for rejection...",pt:"Motivo da rejeição...",fr:"Motif du rejet...",de:"Ablehnungsgrund...",it:"Motivo del rifiuto...",nl:"Reden van afwijzing...",ja:"拒否の理由...",zh:"拒绝原因...",ru:"Причина отказа...",ar:"سبب الرفض...",hi:"अस्वीकृति का कारण...",ko:"거부 사유...",tr:"Ret nedeni...",pl:"Powód odrzucenia...",sv:"Orsak till avvisning...",id:"Alasan penolakan...",th:"เหตุผลในการปฏิเสธ..."},
"adminPayments.rejectBtn":{en:"Reject payment",pt:"Rejeitar pagamento",fr:"Rejeter le paiement",de:"Zahlung ablehnen",it:"Rifiuta pagamento",nl:"Betaling afwijzen",ja:"支払いを拒否",zh:"拒绝支付",ru:"Отклонить платёж",ar:"رفض الدفع",hi:"भुगतान अस्वीकार",ko:"결제 거부",tr:"Ödemeyi reddet",pl:"Odrzuć płatność",sv:"Avvisa betalning",id:"Tolak pembayaran",th:"ปฏิเสธการชำระเงิน"},
"adminPayments.paymentRejected":{en:"Payment rejected",pt:"Pagamento rejeitado",fr:"Paiement rejeté",de:"Zahlung abgelehnt",it:"Pagamento rifiutato",nl:"Betaling afgewezen",ja:"支払い拒否",zh:"支付被拒绝",ru:"Платёж отклонён",ar:"تم رفض الدفع",hi:"भुगतान अस्वीकृत",ko:"결제 거부됨",tr:"Ödeme reddedildi",pl:"Płatność odrzucona",sv:"Betalning avvisad",id:"Pembayaran ditolak",th:"การชำระเงินถูกปฏิเสธ"},
"adminPayments.provideReason":{en:"You must indicate a reason for rejection.",pt:"Você deve indicar um motivo de rejeição.",fr:"Vous devez indiquer un motif de rejet.",de:"Sie müssen einen Ablehnungsgrund angeben.",it:"Devi indicare un motivo di rifiuto.",nl:"Je moet een reden voor afwijzing opgeven.",ja:"拒否理由を入力してください。",zh:"您必须注明拒绝原因。",ru:"Необходимо указать причину отказа.",ar:"يجب تحديد سبب الرفض.",hi:"आपको अस्वीकृति का कारण बताना होगा।",ko:"거부 사유를 입력해야 합니다.",tr:"Ret nedeni belirtmelisiniz.",pl:"Musisz podać powód odrzucenia.",sv:"Du måste ange en orsak till avvisning.",id:"Anda harus memberikan alasan penolakan.",th:"คุณต้องระบุเหตุผลของการปฏิเสธ"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2h (adminSuspensions 43 + adminPayments 38 = 81 keys) done!');
