const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === ADS (84 keys) ===
"ads.createAdDescription":{en:"Fill out the form to publish your ad",pt:"Preencha o formulário para publicar seu anúncio",fr:"Remplissez le formulaire pour publier votre annonce",de:"Füllen Sie das Formular aus, um Ihre Anzeige zu veröffentlichen",it:"Compila il modulo per pubblicare il tuo annuncio",nl:"Vul het formulier in om je advertentie te plaatsen",ja:"広告を掲載するためにフォームに記入してください",zh:"填写表格以发布您的广告",ru:"Заполните форму для публикации объявления",ar:"أكمل النموذج لنشر إعلانك",hi:"अपना विज्ञापन प्रकाशित करने के लिए फ़ॉर्म भरें",ko:"광고를 게시하려면 양식을 작성하세요",tr:"İlanınızı yayınlamak için formu doldurun",pl:"Wypełnij formularz, aby opublikować ogłoszenie",sv:"Fyll i formuläret för att publicera din annons",id:"Isi formulir untuk mempublikasikan iklan Anda",th:"กรอกแบบฟอร์มเพื่อเผยแพร่โฆษณาของคุณ"},
"ads.noAdsDescription":{en:"Be the first to post an ad in this area",pt:"Seja o primeiro a publicar um anúncio nesta área",fr:"Soyez la première à publier une annonce dans cette zone",de:"Seien Sie die Erste, die eine Anzeige in diesem Bereich veröffentlicht",it:"Sii la prima a pubblicare un annuncio in questa zona",nl:"Wees de eerste die een advertentie plaatst in dit gebied",ja:"このエリアで最初の広告を投稿しましょう",zh:"成为该地区第一个发布广告的人",ru:"Станьте первой, кто разместит объявление в этом районе",ar:"كن أول من ينشر إعلاناً في هذه المنطقة",hi:"इस क्षेत्र में पहला विज्ञापन पोस्ट करें",ko:"이 지역에서 첫 광고를 게시하세요",tr:"Bu bölgede ilk ilanı yayınlayan olun",pl:"Bądź pierwsza, która opublikuje ogłoszenie w tej okolicy",sv:"Var den första att publicera en annons i detta område",id:"Jadilah yang pertama memasang iklan di area ini",th:"เป็นคนแรกที่ลงโฆษณาในพื้นที่นี้"},
"ads.relatedAds":{en:"Related ads",pt:"Anúncios relacionados",fr:"Annonces similaires",de:"Verwandte Anzeigen",it:"Annunci correlati",nl:"Gerelateerde advertenties",ja:"関連広告",zh:"相关广告",ru:"Похожие объявления",ar:"إعلانات ذات صلة",hi:"संबंधित विज्ञापन",ko:"관련 광고",tr:"İlgili ilanlar",pl:"Powiązane ogłoszenia",sv:"Relaterade annonser",id:"Iklan terkait",th:"โฆษณาที่เกี่ยวข้อง"},
"ads.loginRequired":{en:"Sign in to continue",pt:"Entre para continuar",fr:"Connectez-vous pour continuer",de:"Anmelden um fortzufahren",it:"Accedi per continuare",nl:"Log in om door te gaan",ja:"続行するにはログイン",zh:"登录以继续",ru:"Войдите, чтобы продолжить",ar:"سجل دخولك للمتابعة",hi:"जारी रखने के लिए लॉगिन करें",ko:"계속하려면 로그인하세요",tr:"Devam etmek için giriş yapın",pl:"Zaloguj się aby kontynuować",sv:"Logga in för att fortsätta",id:"Masuk untuk melanjutkan",th:"เข้าสู่ระบบเพื่อดำเนินการต่อ"},
"ads.error":{en:"An error occurred",pt:"Ocorreu um erro",fr:"Une erreur est survenue",de:"Ein Fehler ist aufgetreten",it:"Si è verificato un errore",nl:"Er is een fout opgetreden",ja:"エラーが発生しました",zh:"发生了错误",ru:"Произошла ошибка",ar:"حدث خطأ",hi:"एक त्रुटि हुई",ko:"오류가 발생했습니다",tr:"Bir hata oluştu",pl:"Wystąpił błąd",sv:"Ett fel inträffade",id:"Terjadi kesalahan",th:"เกิดข้อผิดพลาด"},
"ads.noServicesListed":{en:"No services listed",pt:"Nenhum serviço listado",fr:"Aucun service listé",de:"Keine Dienste aufgeführt",it:"Nessun servizio elencato",nl:"Geen diensten vermeld",ja:"サービスが登録されていません",zh:"没有列出服务",ru:"Нет перечисленных услуг",ar:"لا توجد خدمات مدرجة",hi:"कोई सेवा सूचीबद्ध नहीं",ko:"등록된 서비스 없음",tr:"Listelenen hizmet yok",pl:"Brak usług",sv:"Inga tjänster listade",id:"Tidak ada layanan terdaftar",th:"ไม่มีบริการที่ระบุ"},
"ads.contactForAvailability":{en:"Contact to check availability",pt:"Entre em contato para consultar disponibilidade",fr:"Contactez pour vérifier la disponibilité",de:"Kontaktieren Sie für Verfügbarkeit",it:"Contatta per verificare la disponibilità",nl:"Neem contact op voor beschikbaarheid",ja:"空き状況についてお問い合わせください",zh:"联系查询空闲情况",ru:"Свяжитесь для уточнения доступности",ar:"تواصل للاستفسار عن التوفر",hi:"उपलब्धता जानने के लिए संपर्क करें",ko:"가용성 확인을 위해 연락하세요",tr:"Müsaitlik için iletişime geçin",pl:"Skontaktuj się w sprawie dostępności",sv:"Kontakta för tillgänglighet",id:"Hubungi untuk ketersediaan",th:"ติดต่อเพื่อตรวจสอบความพร้อม"},
"ads.basicInfo":{en:"Basic information",pt:"Informações básicas",fr:"Informations de base",de:"Grundinformationen",it:"Informazioni di base",nl:"Basisinformatie",ja:"基本情報",zh:"基本信息",ru:"Основная информация",ar:"المعلومات الأساسية",hi:"बुनियादी जानकारी",ko:"기본 정보",tr:"Temel bilgiler",pl:"Podstawowe informacje",sv:"Grundläggande information",id:"Informasi dasar",th:"ข้อมูลพื้นฐาน"},
"ads.basicInfoDescription":{en:"Title and description of your ad",pt:"Título e descrição do seu anúncio",fr:"Titre et description de votre annonce",de:"Titel und Beschreibung Ihrer Anzeige",it:"Titolo e descrizione del tuo annuncio",nl:"Titel en beschrijving van je advertentie",ja:"広告のタイトルと説明",zh:"您的广告标题和描述",ru:"Заголовок и описание вашего объявления",ar:"عنوان ووصف إعلانك",hi:"आपके विज्ञापन का शीर्षक और विवरण",ko:"광고의 제목과 설명",tr:"İlanınızın başlığı ve açıklaması",pl:"Tytuł i opis ogłoszenia",sv:"Titel och beskrivning av din annons",id:"Judul dan deskripsi iklan Anda",th:"ชื่อเรื่องและคำอธิบายโฆษณาของคุณ"},
"ads.adTitle":{en:"Ad title",pt:"Título do anúncio",fr:"Titre de l'annonce",de:"Anzeigentitel",it:"Titolo annuncio",nl:"Advertentietitel",ja:"広告タイトル",zh:"广告标题",ru:"Заголовок объявления",ar:"عنوان الإعلان",hi:"विज्ञापन शीर्षक",ko:"광고 제목",tr:"İlan başlığı",pl:"Tytuł ogłoszenia",sv:"Annonsrubrik",id:"Judul iklan",th:"ชื่อโฆษณา"},
"ads.adTitlePlaceholder":{en:"E.g.: Latin trans available in Madrid",pt:"Ex: Trans latina disponível em Madrid",fr:"Ex : Trans latine disponible à Madrid",de:"Z.B.: Lateinamerikanische Trans verfügbar in Madrid",it:"Es: Trans latina disponibile a Madrid",nl:"Bijv.: Latijns-Amerikaanse trans beschikbaar in Madrid",ja:"例：マドリードで利用可能なラテン系トランス",zh:"例：马德里可预约的拉丁裔跨性别",ru:"Пример: Транс латина доступна в Мадриде",ar:"مثال: ترانس لاتينية متاحة في مدريد",hi:"उदा.: मैड्रिड में उपलब्ध लैटिन ट्रांस",ko:"예: 마드리드에서 가능한 라틴 트랜스",tr:"Örn: Madrid'de mevcut Latin trans",pl:"Np.: Trans Latynka dostępna w Madrycie",sv:"T.ex.: Latinsk trans tillgänglig i Madrid",id:"Contoh: Trans Latin tersedia di Madrid",th:"เช่น: ทรานส์ลาตินพร้อมให้บริการในมาดริด"},
"ads.adDescription":{en:"Description",pt:"Descrição",fr:"Description",de:"Beschreibung",it:"Descrizione",nl:"Beschrijving",ja:"説明",zh:"描述",ru:"Описание",ar:"الوصف",hi:"विवरण",ko:"설명",tr:"Açıklama",pl:"Opis",sv:"Beskrivning",id:"Deskripsi",th:"คำอธิบาย"},
"ads.adDescriptionPlaceholder":{en:"Describe your services, personality, what you offer...",pt:"Descreva seus serviços, personalidade, o que você oferece...",fr:"Décrivez vos services, votre personnalité, ce que vous proposez...",de:"Beschreiben Sie Ihre Dienste, Persönlichkeit, was Sie anbieten...",it:"Descrivi i tuoi servizi, personalità, cosa offri...",nl:"Beschrijf je diensten, persoonlijkheid, wat je aanbiedt...",ja:"サービス、性格、提供内容を説明してください...",zh:"描述您的服务、个性、提供的内容...",ru:"Опишите свои услуги, характер, что вы предлагаете...",ar:"صف خدماتك وشخصيتك وما تقدمه...",hi:"अपनी सेवाएं, व्यक्तित्व, आप क्या पेश करते हैं वर्णन करें...",ko:"서비스, 성격, 제공 사항을 설명하세요...",tr:"Hizmetlerinizi, kişiliğinizi, sunduklarınızı açıklayın...",pl:"Opisz swoje usługi, osobowość, co oferujesz...",sv:"Beskriv dina tjänster, personlighet, vad du erbjuder...",id:"Jelaskan layanan, kepribadian, apa yang Anda tawarkan...",th:"อธิบายบริการ บุคลิกภาพ สิ่งที่คุณนำเสนอ..."},
"ads.cityPlaceholder":{en:"E.g.: Madrid",pt:"Ex: Madrid",fr:"Ex : Madrid",de:"Z.B.: Madrid",it:"Es: Madrid",nl:"Bijv.: Madrid",ja:"例：マドリード",zh:"例：马德里",ru:"Пример: Мадрид",ar:"مثال: مدريد",hi:"उदा.: मैड्रिड",ko:"예: 마드리드",tr:"Örn: Madrid",pl:"Np.: Madryt",sv:"T.ex.: Madrid",id:"Contoh: Madrid",th:"เช่น: มาดริด"},
"ads.neighborhood":{en:"Neighborhood/Area",pt:"Bairro/Zona",fr:"Quartier/Zone",de:"Viertel/Gebiet",it:"Quartiere/Zona",nl:"Wijk/Gebied",ja:"地区/エリア",zh:"街区/区域",ru:"Район/Зона",ar:"الحي/المنطقة",hi:"पड़ोस/क्षेत्र",ko:"동네/지역",tr:"Semt/Bölge",pl:"Dzielnica/Strefa",sv:"Stadsdel/Område",id:"Lingkungan/Area",th:"ย่าน/พื้นที่"},
"ads.neighborhoodPlaceholder":{en:"E.g.: Downtown",pt:"Ex: Centro",fr:"Ex : Centre",de:"Z.B.: Zentrum",it:"Es: Centro",nl:"Bijv.: Centrum",ja:"例：中心部",zh:"例：市中心",ru:"Пример: Центр",ar:"مثال: وسط المدينة",hi:"उदा.: डाउनटाउन",ko:"예: 시내",tr:"Örn: Şehir merkezi",pl:"Np.: Centrum",sv:"T.ex.: Centrum",id:"Contoh: Pusat kota",th:"เช่น: ใจกลางเมือง"},
"ads.contactInfo":{en:"Contact information",pt:"Informações de contato",fr:"Informations de contact",de:"Kontaktinformationen",it:"Informazioni di contatto",nl:"Contactinformatie",ja:"連絡先情報",zh:"联系信息",ru:"Контактная информация",ar:"معلومات الاتصال",hi:"संपर्क जानकारी",ko:"연락처 정보",tr:"İletişim bilgileri",pl:"Informacje kontaktowe",sv:"Kontaktinformation",id:"Informasi kontak",th:"ข้อมูลติดต่อ"},
"ads.phone":{en:"Phone",pt:"Telefone",fr:"Téléphone",de:"Telefon",it:"Telefono",nl:"Telefoon",ja:"電話",zh:"电话",ru:"Телефон",ar:"الهاتف",hi:"फ़ोन",ko:"전화",tr:"Telefon",pl:"Telefon",sv:"Telefon",id:"Telepon",th:"โทรศัพท์"},
"ads.email":{en:"Email",pt:"Email",fr:"Email",de:"E-Mail",it:"Email",nl:"E-mail",ja:"メール",zh:"邮箱",ru:"Электронная почта",ar:"البريد الإلكتروني",hi:"ईमेल",ko:"이메일",tr:"E-posta",pl:"Email",sv:"E-post",id:"Email",th:"อีเมล"},
"ads.physicalDetails":{en:"Physical details",pt:"Características físicas",fr:"Caractéristiques physiques",de:"Körperliche Merkmale",it:"Caratteristiche fisiche",nl:"Fysieke kenmerken",ja:"身体的特徴",zh:"身体特征",ru:"Физические характеристики",ar:"التفاصيل الجسدية",hi:"शारीरिक विवरण",ko:"신체적 특징",tr:"Fiziksel özellikler",pl:"Cechy fizyczne",sv:"Fysiska detaljer",id:"Detail fisik",th:"รายละเอียดทางกายภาพ"},
"ads.age":{en:"Age",pt:"Idade",fr:"Âge",de:"Alter",it:"Età",nl:"Leeftijd",ja:"年齢",zh:"年龄",ru:"Возраст",ar:"العمر",hi:"उम्र",ko:"나이",tr:"Yaş",pl:"Wiek",sv:"Ålder",id:"Usia",th:"อายุ"},
"ads.height":{en:"Height",pt:"Altura",fr:"Taille",de:"Größe",it:"Altezza",nl:"Lengte",ja:"身長",zh:"身高",ru:"Рост",ar:"الطول",hi:"ऊंचाई",ko:"키",tr:"Boy",pl:"Wzrost",sv:"Längd",id:"Tinggi",th:"ส่วนสูง"},
"ads.weight":{en:"Weight",pt:"Peso",fr:"Poids",de:"Gewicht",it:"Peso",nl:"Gewicht",ja:"体重",zh:"体重",ru:"Вес",ar:"الوزن",hi:"वजन",ko:"체중",tr:"Kilo",pl:"Waga",sv:"Vikt",id:"Berat",th:"น้ำหนัก"},
"ads.bodyType":{en:"Body type",pt:"Tipo de corpo",fr:"Type de corps",de:"Körpertyp",it:"Tipo di corpo",nl:"Lichaamstype",ja:"体型",zh:"体型",ru:"Тип телосложения",ar:"نوع الجسم",hi:"शरीर का प्रकार",ko:"체형",tr:"Vücut tipi",pl:"Typ budowy",sv:"Kroppstyp",id:"Tipe tubuh",th:"ประเภทร่างกาย"},
"ads.ethnicity":{en:"Ethnicity",pt:"Etnia",fr:"Ethnicité",de:"Ethnie",it:"Etnia",nl:"Etniciteit",ja:"民族",zh:"民族",ru:"Этническая принадлежность",ar:"العرق",hi:"जातीयता",ko:"민족",tr:"Etnisite",pl:"Pochodzenie",sv:"Etnicitet",id:"Etnis",th:"ชาติพันธุ์"},
"ads.hairColor":{en:"Hair color",pt:"Cor do cabelo",fr:"Couleur de cheveux",de:"Haarfarbe",it:"Colore capelli",nl:"Haarkleur",ja:"髪の色",zh:"发色",ru:"Цвет волос",ar:"لون الشعر",hi:"बालों का रंग",ko:"머리색",tr:"Saç rengi",pl:"Kolor włosów",sv:"Hårfärg",id:"Warna rambut",th:"สีผม"},
"ads.eyeColor":{en:"Eye color",pt:"Cor dos olhos",fr:"Couleur des yeux",de:"Augenfarbe",it:"Colore occhi",nl:"Oogkleur",ja:"目の色",zh:"眼睛颜色",ru:"Цвет глаз",ar:"لون العيون",hi:"आंखों का रंग",ko:"눈 색깔",tr:"Göz rengi",pl:"Kolor oczu",sv:"Ögonfärg",id:"Warna mata",th:"สีตา"},
"ads.select":{en:"Select",pt:"Selecionar",fr:"Sélectionner",de:"Auswählen",it:"Seleziona",nl:"Selecteren",ja:"選択",zh:"选择",ru:"Выбрать",ar:"اختيار",hi:"चुनें",ko:"선택",tr:"Seç",pl:"Wybierz",sv:"Välj",id:"Pilih",th:"เลือก"},
"ads.servicesOffered":{en:"Services offered",pt:"Serviços oferecidos",fr:"Services proposés",de:"Angebotene Dienste",it:"Servizi offerti",nl:"Aangeboden diensten",ja:"提供サービス",zh:"提供的服务",ru:"Предлагаемые услуги",ar:"الخدمات المقدمة",hi:"प्रदान की जाने वाली सेवाएं",ko:"제공 서비스",tr:"Sunulan hizmetler",pl:"Oferowane usługi",sv:"Tjänster som erbjuds",id:"Layanan yang ditawarkan",th:"บริการที่เสนอ"},
"ads.currency":{en:"Currency",pt:"Moeda",fr:"Devise",de:"Währung",it:"Valuta",nl:"Valuta",ja:"通貨",zh:"货币",ru:"Валюта",ar:"العملة",hi:"मुद्रा",ko:"통화",tr:"Para birimi",pl:"Waluta",sv:"Valuta",id:"Mata uang",th:"สกุลเงิน"},
"ads.photos":{en:"Photos",pt:"Fotos",fr:"Photos",de:"Fotos",it:"Foto",nl:"Foto's",ja:"写真",zh:"照片",ru:"Фото",ar:"الصور",hi:"तस्वीरें",ko:"사진",tr:"Fotoğraflar",pl:"Zdjęcia",sv:"Foton",id:"Foto",th:"รูปภาพ"},
"ads.photosDescription":{en:"Upload up to 10 photos. The first will be the main one.",pt:"Envie até 10 fotos. A primeira será a principal.",fr:"Téléchargez jusqu'à 10 photos. La première sera la principale.",de:"Laden Sie bis zu 10 Fotos hoch. Das erste wird das Hauptbild.",it:"Carica fino a 10 foto. La prima sarà quella principale.",nl:"Upload tot 10 foto's. De eerste wordt de hoofdfoto.",ja:"最大10枚の写真をアップロード。最初の写真がメイン画像になります。",zh:"最多上传10张照片。第一张将作为主图。",ru:"Загрузите до 10 фото. Первое будет основным.",ar:"ارفع حتى 10 صور. الأولى ستكون الرئيسية.",hi:"10 तक तस्वीरें अपलोड करें। पहली मुख्य होगी।",ko:"최대 10장의 사진을 업로드하세요. 첫 번째가 대표 이미지가 됩니다.",tr:"10'a kadar fotoğraf yükleyin. İlki ana fotoğraf olacak.",pl:"Prześlij do 10 zdjęć. Pierwsze będzie głównym.",sv:"Ladda upp till 10 foton. Det första blir huvudbilden.",id:"Unggah hingga 10 foto. Yang pertama akan menjadi foto utama.",th:"อัปโหลดได้สูงสุด 10 รูป รูปแรกจะเป็นรูปหลัก"},
"ads.addPhoto":{en:"Add photo",pt:"Adicionar foto",fr:"Ajouter une photo",de:"Foto hinzufügen",it:"Aggiungi foto",nl:"Foto toevoegen",ja:"写真を追加",zh:"添加照片",ru:"Добавить фото",ar:"إضافة صورة",hi:"फ़ोटो जोड़ें",ko:"사진 추가",tr:"Fotoğraf ekle",pl:"Dodaj zdjęcie",sv:"Lägg till foto",id:"Tambah foto",th:"เพิ่มรูปภาพ"},
"ads.primaryPhoto":{en:"Primary",pt:"Principal",fr:"Principale",de:"Hauptbild",it:"Principale",nl:"Hoofdfoto",ja:"メイン",zh:"主图",ru:"Основное",ar:"رئيسية",hi:"मुख्य",ko:"대표",tr:"Ana",pl:"Główne",sv:"Huvudbild",id:"Utama",th:"หลัก"},
"ads.maxPhotos":{en:"Maximum 10 photos allowed",pt:"Máximo 10 fotos permitidas",fr:"Maximum 10 photos autorisées",de:"Maximal 10 Fotos erlaubt",it:"Massimo 10 foto consentite",nl:"Maximaal 10 foto's toegestaan",ja:"最大10枚の写真が許可されています",zh:"最多允许10张照片",ru:"Максимум 10 фото",ar:"الحد الأقصى 10 صور",hi:"अधिकतम 10 तस्वीरें अनुमत",ko:"최대 10장의 사진 허용",tr:"Maksimum 10 fotoğraf izni",pl:"Maksymalnie 10 zdjęć",sv:"Max 10 foton tillåtna",id:"Maksimal 10 foto diizinkan",th:"อนุญาตสูงสุด 10 รูป"},
"ads.publishAd":{en:"Publish ad",pt:"Publicar anúncio",fr:"Publier l'annonce",de:"Anzeige veröffentlichen",it:"Pubblica annuncio",nl:"Advertentie plaatsen",ja:"広告を掲載",zh:"发布广告",ru:"Опубликовать объявление",ar:"نشر الإعلان",hi:"विज्ञापन प्रकाशित करें",ko:"광고 게시",tr:"İlan yayınla",pl:"Opublikuj ogłoszenie",sv:"Publicera annons",id:"Publikasikan iklan",th:"เผยแพร่โฆษณา"},
"ads.adCreated":{en:"Ad created successfully",pt:"Anúncio criado com sucesso",fr:"Annonce créée avec succès",de:"Anzeige erfolgreich erstellt",it:"Annuncio creato con successo",nl:"Advertentie succesvol aangemaakt",ja:"広告が正常に作成されました",zh:"广告创建成功",ru:"Объявление успешно создано",ar:"تم إنشاء الإعلان بنجاح",hi:"विज्ञापन सफलतापूर्वक बनाया गया",ko:"광고가 성공적으로 생성되었습니다",tr:"İlan başarıyla oluşturuldu",pl:"Ogłoszenie utworzone pomyślnie",sv:"Annons skapad",id:"Iklan berhasil dibuat",th:"สร้างโฆษณาสำเร็จ"},
"ads.errorCreating":{en:"Error creating ad",pt:"Erro ao criar anúncio",fr:"Erreur de création de l'annonce",de:"Fehler beim Erstellen der Anzeige",it:"Errore nella creazione dell'annuncio",nl:"Fout bij aanmaken advertentie",ja:"広告作成エラー",zh:"创建广告出错",ru:"Ошибка создания объявления",ar:"خطأ في إنشاء الإعلان",hi:"विज्ञापन बनाने में त्रुटि",ko:"광고 생성 오류",tr:"İlan oluşturma hatası",pl:"Błąd tworzenia ogłoszenia",sv:"Fel vid skapande av annons",id:"Error membuat iklan",th:"เกิดข้อผิดพลาดในการสร้างโฆษณา"},
"ads.requiredFields":{en:"Complete the required fields",pt:"Preencha os campos obrigatórios",fr:"Complétez les champs obligatoires",de:"Füllen Sie die Pflichtfelder aus",it:"Completa i campi obbligatori",nl:"Vul de verplichte velden in",ja:"必須フィールドを入力してください",zh:"请填写必填项",ru:"Заполните обязательные поля",ar:"أكمل الحقول المطلوبة",hi:"आवश्यक फ़ील्ड भरें",ko:"필수 필드를 작성하세요",tr:"Zorunlu alanları doldurun",pl:"Wypełnij wymagane pola",sv:"Fyll i obligatoriska fält",id:"Lengkapi kolom yang wajib diisi",th:"กรอกช่องที่จำเป็น"},
"ads.bodyTypes.slim":{en:"Slim",pt:"Magra",fr:"Mince",de:"Schlank",it:"Magra",nl:"Slank",ja:"スリム",zh:"苗条",ru:"Стройная",ar:"نحيفة",hi:"पतला",ko:"슬림",tr:"İnce",pl:"Szczupła",sv:"Smal",id:"Ramping",th:"ผอม"},
"ads.bodyTypes.athletic":{en:"Athletic",pt:"Atlética",fr:"Athlétique",de:"Athletisch",it:"Atletica",nl:"Atletisch",ja:"アスレチック",zh:"运动型",ru:"Атлетичная",ar:"رياضية",hi:"एथलेटिक",ko:"운동형",tr:"Atletik",pl:"Atletyczna",sv:"Atletisk",id:"Atletis",th:"กล้ามเนื้อ"},
"ads.bodyTypes.average":{en:"Average",pt:"Normal",fr:"Normale",de:"Normal",it:"Normale",nl:"Gemiddeld",ja:"普通",zh:"普通",ru:"Обычная",ar:"عادية",hi:"सामान्य",ko:"보통",tr:"Normal",pl:"Przeciętna",sv:"Genomsnittlig",id:"Rata-rata",th:"ปกติ"},
"ads.bodyTypes.curvy":{en:"Curvy",pt:"Curvilínea",fr:"Pulpeuse",de:"Kurvig",it:"Formosa",nl:"Bochtig",ja:"カーヴィー",zh:"丰满",ru:"Фигуристая",ar:"ممتلئة",hi:"कर्वी",ko:"글래머",tr:"Dolgun",pl:"Kształtna",sv:"Kurvig",id:"Berisi",th:"อวบ"},
"ads.bodyTypes.plus_size":{en:"Plus size",pt:"Talla grande",fr:"Grande taille",de:"Übergröße",it:"Taglie forti",nl:"Plus size",ja:"プラスサイズ",zh:"大码",ru:"Плюс сайз",ar:"مقاس كبير",hi:"प्लस साइज़",ko:"플러스 사이즈",tr:"Büyük beden",pl:"Plus size",sv:"Plus storlek",id:"Plus size",th:"พลัสไซส์"},
"ads.ethnicities.latina":{en:"Latina",pt:"Latina",fr:"Latine",de:"Latina",it:"Latina",nl:"Latina",ja:"ラティーナ",zh:"拉丁裔",ru:"Латина",ar:"لاتينية",hi:"लैटिना",ko:"라티나",tr:"Latin",pl:"Latynoska",sv:"Latina",id:"Latina",th:"ลาติน"},
"ads.ethnicities.caucasian":{en:"Caucasian",pt:"Caucasiana",fr:"Caucasienne",de:"Kaukasisch",it:"Caucasica",nl:"Kaukasisch",ja:"白人",zh:"高加索人",ru:"Европейка",ar:"قوقازية",hi:"कॉकेशियन",ko:"백인",tr:"Kafkas",pl:"Kaukaska",sv:"Kaukasisk",id:"Kaukasia",th:"คอเคเซียน"},
"ads.ethnicities.asian":{en:"Asian",pt:"Asiática",fr:"Asiatique",de:"Asiatisch",it:"Asiatica",nl:"Aziatisch",ja:"アジア系",zh:"亚洲人",ru:"Азиатка",ar:"آسيوية",hi:"एशियन",ko:"아시안",tr:"Asyalı",pl:"Azjatka",sv:"Asiatisk",id:"Asia",th:"เอเชีย"},
"ads.ethnicities.african":{en:"African",pt:"Africana",fr:"Africaine",de:"Afrikanisch",it:"Africana",nl:"Afrikaans",ja:"アフリカ系",zh:"非洲人",ru:"Африканка",ar:"أفريقية",hi:"अफ्रीकन",ko:"아프리칸",tr:"Afrikalı",pl:"Afrykanka",sv:"Afrikansk",id:"Afrika",th:"แอฟริกัน"},
"ads.ethnicities.mixed":{en:"Mixed",pt:"Mestiça",fr:"Métisse",de:"Gemischt",it:"Mista",nl:"Gemengd",ja:"ミックス",zh:"混血",ru:"Смешанная",ar:"مختلطة",hi:"मिश्रित",ko:"혼혈",tr:"Karma",pl:"Mieszana",sv:"Blandad",id:"Campuran",th:"ลูกครึ่ง"},
"ads.hairColors.black":{en:"Black",pt:"Preto",fr:"Noir",de:"Schwarz",it:"Nero",nl:"Zwart",ja:"黒",zh:"黑色",ru:"Чёрный",ar:"أسود",hi:"काला",ko:"검정",tr:"Siyah",pl:"Czarny",sv:"Svart",id:"Hitam",th:"ดำ"},
"ads.hairColors.brown":{en:"Brown",pt:"Castanho",fr:"Châtain",de:"Braun",it:"Castano",nl:"Bruin",ja:"茶色",zh:"棕色",ru:"Каштановый",ar:"بني",hi:"भूरा",ko:"갈색",tr:"Kahverengi",pl:"Brązowy",sv:"Brun",id:"Cokelat",th:"น้ำตาล"},
"ads.hairColors.blonde":{en:"Blonde",pt:"Loiro",fr:"Blond",de:"Blond",it:"Biondo",nl:"Blond",ja:"金色",zh:"金色",ru:"Блонд",ar:"أشقر",hi:"गोरा",ko:"금발",tr:"Sarı",pl:"Blond",sv:"Blond",id:"Pirang",th:"บลอนด์"},
"ads.hairColors.red":{en:"Red",pt:"Ruivo",fr:"Roux",de:"Rot",it:"Rosso",nl:"Rood",ja:"赤",zh:"红色",ru:"Рыжий",ar:"أحمر",hi:"लाल",ko:"빨강",tr:"Kızıl",pl:"Rudy",sv:"Röd",id:"Merah",th:"แดง"},
"ads.hairColors.gray":{en:"Gray",pt:"Grisalho",fr:"Gris",de:"Grau",it:"Grigio",nl:"Grijs",ja:"灰色",zh:"灰色",ru:"Серый",ar:"رمادي",hi:"सफ़ेद",ko:"회색",tr:"Gri",pl:"Siwy",sv:"Grå",id:"Abu-abu",th:"เทา"},
"ads.hairColors.other":{en:"Other",pt:"Outro",fr:"Autre",de:"Andere",it:"Altro",nl:"Anders",ja:"その他",zh:"其他",ru:"Другой",ar:"آخر",hi:"अन्य",ko:"기타",tr:"Diğer",pl:"Inny",sv:"Annat",id:"Lainnya",th:"อื่นๆ"},
"ads.eyeColors.black":{en:"Black",pt:"Pretos",fr:"Noirs",de:"Schwarz",it:"Neri",nl:"Zwart",ja:"黒",zh:"黑色",ru:"Чёрные",ar:"أسود",hi:"काला",ko:"검정",tr:"Siyah",pl:"Czarne",sv:"Svarta",id:"Hitam",th:"ดำ"},
"ads.eyeColors.brown":{en:"Brown",pt:"Castanhos",fr:"Marron",de:"Braun",it:"Marroni",nl:"Bruin",ja:"茶色",zh:"棕色",ru:"Карие",ar:"بني",hi:"भूरा",ko:"갈색",tr:"Kahverengi",pl:"Brązowe",sv:"Bruna",id:"Cokelat",th:"น้ำตาล"},
"ads.eyeColors.blonde":{en:"Hazel",pt:"Mel",fr:"Noisette",de:"Haselnuss",it:"Nocciola",nl:"Hazelnoot",ja:"ヘーゼル",zh:"淡褐色",ru:"Ореховые",ar:"عسلي",hi:"हेज़ल",ko:"헤이즐",tr:"Ela",pl:"Piwne",sv:"Hasselnöt",id:"Hazel",th:"สีน้ำผึ้ง"},
"ads.eyeColors.red":{en:"Green",pt:"Verdes",fr:"Verts",de:"Grün",it:"Verdi",nl:"Groen",ja:"緑",zh:"绿色",ru:"Зелёные",ar:"أخضر",hi:"हरा",ko:"초록",tr:"Yeşil",pl:"Zielone",sv:"Gröna",id:"Hijau",th:"เขียว"},
"ads.eyeColors.gray":{en:"Gray",pt:"Cinzentos",fr:"Gris",de:"Grau",it:"Grigi",nl:"Grijs",ja:"灰色",zh:"灰色",ru:"Серые",ar:"رمادي",hi:"सफ़ेद",ko:"회색",tr:"Gri",pl:"Szare",sv:"Grå",id:"Abu-abu",th:"เทา"},
"ads.eyeColors.other":{en:"Other",pt:"Outro",fr:"Autre",de:"Andere",it:"Altro",nl:"Anders",ja:"その他",zh:"其他",ru:"Другие",ar:"آخر",hi:"अन्य",ko:"기타",tr:"Diğer",pl:"Inne",sv:"Annat",id:"Lainnya",th:"อื่นๆ"},
"ads.durations.30min":{en:"30 minutes",pt:"30 minutos",fr:"30 minutes",de:"30 Minuten",it:"30 minuti",nl:"30 minuten",ja:"30分",zh:"30分钟",ru:"30 минут",ar:"30 دقيقة",hi:"30 मिनट",ko:"30분",tr:"30 dakika",pl:"30 minut",sv:"30 minuter",id:"30 menit",th:"30 นาที"},
"ads.durations.1hour":{en:"1 hour",pt:"1 hora",fr:"1 heure",de:"1 Stunde",it:"1 ora",nl:"1 uur",ja:"1時間",zh:"1小时",ru:"1 час",ar:"ساعة واحدة",hi:"1 घंटा",ko:"1시간",tr:"1 saat",pl:"1 godzina",sv:"1 timme",id:"1 jam",th:"1 ชั่วโมง"},
"ads.durations.2hours":{en:"2 hours",pt:"2 horas",fr:"2 heures",de:"2 Stunden",it:"2 ore",nl:"2 uur",ja:"2時間",zh:"2小时",ru:"2 часа",ar:"ساعتان",hi:"2 घंटे",ko:"2시간",tr:"2 saat",pl:"2 godziny",sv:"2 timmar",id:"2 jam",th:"2 ชั่วโมง"},
"ads.durations.3hours":{en:"3 hours",pt:"3 horas",fr:"3 heures",de:"3 Stunden",it:"3 ore",nl:"3 uur",ja:"3時間",zh:"3小时",ru:"3 часа",ar:"3 ساعات",hi:"3 घंटे",ko:"3시간",tr:"3 saat",pl:"3 godziny",sv:"3 timmar",id:"3 jam",th:"3 ชั่วโมง"},
"ads.durations.overnight":{en:"Overnight",pt:"Toda a noite",fr:"Toute la nuit",de:"Über Nacht",it:"Tutta la notte",nl:"Overnachting",ja:"一晩",zh:"过夜",ru:"На ночь",ar:"طوال الليل",hi:"रात भर",ko:"하룻밤",tr:"Gecelik",pl:"Na noc",sv:"Över natten",id:"Semalam",th:"ค้างคืน"},
"ads.durations.weekend":{en:"Weekend",pt:"Fim de semana",fr:"Week-end",de:"Wochenende",it:"Fine settimana",nl:"Weekend",ja:"週末",zh:"周末",ru:"Выходные",ar:"نهاية الأسبوع",hi:"सप्ताहांत",ko:"주말",tr:"Hafta sonu",pl:"Weekend",sv:"Helg",id:"Akhir pekan",th:"สุดสัปดาห์"},
"ads.servicesList.service_girlfriend_experience":{en:"Girlfriend Experience",pt:"Girlfriend Experience",fr:"Girlfriend Experience",de:"Girlfriend Experience",it:"Girlfriend Experience",nl:"Girlfriend Experience",ja:"ガールフレンド体験",zh:"女友体验",ru:"Girlfriend Experience",ar:"تجربة الصديقة",hi:"गर्लफ्रेंड एक्सपीरियंस",ko:"걸프렌드 익스피리언스",tr:"Girlfriend Experience",pl:"Girlfriend Experience",sv:"Girlfriend Experience",id:"Girlfriend Experience",th:"Girlfriend Experience"},
"ads.servicesList.service_massage":{en:"Massage",pt:"Massagens",fr:"Massages",de:"Massagen",it:"Massaggi",nl:"Massages",ja:"マッサージ",zh:"按摩",ru:"Массаж",ar:"مساج",hi:"मसाज",ko:"마사지",tr:"Masaj",pl:"Masaże",sv:"Massage",id:"Pijat",th:"นวด"},
"ads.servicesList.service_oral":{en:"Oral",pt:"Oral",fr:"Oral",de:"Oral",it:"Orale",nl:"Oraal",ja:"オーラル",zh:"口交",ru:"Оральный",ar:"فموي",hi:"ओरल",ko:"오럴",tr:"Oral",pl:"Oralny",sv:"Oral",id:"Oral",th:"ออรัล"},
"ads.servicesList.service_anal":{en:"Anal",pt:"Anal",fr:"Anal",de:"Anal",it:"Anale",nl:"Anaal",ja:"アナル",zh:"肛交",ru:"Анальный",ar:"شرجي",hi:"एनल",ko:"애널",tr:"Anal",pl:"Analny",sv:"Anal",id:"Anal",th:"ทวารหนัก"},
"ads.servicesList.service_fetish":{en:"Fetish",pt:"Fetiche",fr:"Fétiche",de:"Fetisch",it:"Feticismo",nl:"Fetisj",ja:"フェティッシュ",zh:"恋物",ru:"Фетиш",ar:"فيتيش",hi:"फेटिश",ko:"페티시",tr:"Fetiş",pl:"Fetysz",sv:"Fetisch",id:"Fetish",th:"เฟติช"},
"ads.servicesList.service_bdsm":{en:"BDSM",pt:"BDSM",fr:"BDSM",de:"BDSM",it:"BDSM",nl:"BDSM",ja:"BDSM",zh:"BDSM",ru:"BDSM",ar:"BDSM",hi:"BDSM",ko:"BDSM",tr:"BDSM",pl:"BDSM",sv:"BDSM",id:"BDSM",th:"BDSM"},
"ads.servicesList.service_duo":{en:"Duo",pt:"Duo",fr:"Duo",de:"Duo",it:"Duo",nl:"Duo",ja:"デュオ",zh:"双人",ru:"Дуо",ar:"ثنائي",hi:"डुओ",ko:"듀오",tr:"Duo",pl:"Duo",sv:"Duo",id:"Duo",th:"ดูโอ"},
"ads.servicesList.service_overnight":{en:"Overnight",pt:"Toda a noite",fr:"Toute la nuit",de:"Über Nacht",it:"Tutta la notte",nl:"Overnachting",ja:"一晩",zh:"过夜",ru:"На ночь",ar:"طوال الليل",hi:"रात भर",ko:"하룻밤",tr:"Gecelik",pl:"Na noc",sv:"Över natten",id:"Semalam",th:"ค้างคืน"},
"ads.servicesList.service_travel":{en:"Travel",pt:"Viagens",fr:"Voyages",de:"Reisen",it:"Viaggi",nl:"Reizen",ja:"旅行",zh:"旅行",ru:"Путешествия",ar:"سفر",hi:"यात्रा",ko:"여행",tr:"Seyahat",pl:"Podróże",sv:"Resor",id:"Perjalanan",th:"ท่องเที่ยว"},
"ads.servicesList.service_video_call":{en:"Video call",pt:"Videochamada",fr:"Appel vidéo",de:"Videoanruf",it:"Videochiamata",nl:"Videogesprek",ja:"ビデオ通話",zh:"视频通话",ru:"Видеозвонок",ar:"مكالمة فيديو",hi:"वीडियो कॉल",ko:"영상 통화",tr:"Görüntülü arama",pl:"Wideorozmowa",sv:"Videosamtal",id:"Panggilan video",th:"วิดีโอคอล"},
"ads.days.monday":{en:"Monday",pt:"Segunda-feira",fr:"Lundi",de:"Montag",it:"Lunedì",nl:"Maandag",ja:"月曜日",zh:"星期一",ru:"Понедельник",ar:"الإثنين",hi:"सोमवार",ko:"월요일",tr:"Pazartesi",pl:"Poniedziałek",sv:"Måndag",id:"Senin",th:"วันจันทร์"},
"ads.days.tuesday":{en:"Tuesday",pt:"Terça-feira",fr:"Mardi",de:"Dienstag",it:"Martedì",nl:"Dinsdag",ja:"火曜日",zh:"星期二",ru:"Вторник",ar:"الثلاثاء",hi:"मंगलवार",ko:"화요일",tr:"Salı",pl:"Wtorek",sv:"Tisdag",id:"Selasa",th:"วันอังคาร"},
"ads.days.wednesday":{en:"Wednesday",pt:"Quarta-feira",fr:"Mercredi",de:"Mittwoch",it:"Mercoledì",nl:"Woensdag",ja:"水曜日",zh:"星期三",ru:"Среда",ar:"الأربعاء",hi:"बुधवार",ko:"수요일",tr:"Çarşamba",pl:"Środa",sv:"Onsdag",id:"Rabu",th:"วันพุธ"},
"ads.days.thursday":{en:"Thursday",pt:"Quinta-feira",fr:"Jeudi",de:"Donnerstag",it:"Giovedì",nl:"Donderdag",ja:"木曜日",zh:"星期四",ru:"Четверг",ar:"الخميس",hi:"गुरुवार",ko:"목요일",tr:"Perşembe",pl:"Czwartek",sv:"Torsdag",id:"Kamis",th:"วันพฤหัสบดี"},
"ads.days.friday":{en:"Friday",pt:"Sexta-feira",fr:"Vendredi",de:"Freitag",it:"Venerdì",nl:"Vrijdag",ja:"金曜日",zh:"星期五",ru:"Пятница",ar:"الجمعة",hi:"शुक्रवार",ko:"금요일",tr:"Cuma",pl:"Piątek",sv:"Fredag",id:"Jumat",th:"วันศุกร์"},
"ads.days.saturday":{en:"Saturday",pt:"Sábado",fr:"Samedi",de:"Samstag",it:"Sabato",nl:"Zaterdag",ja:"土曜日",zh:"星期六",ru:"Суббота",ar:"السبت",hi:"शनिवार",ko:"토요일",tr:"Cumartesi",pl:"Sobota",sv:"Lördag",id:"Sabtu",th:"วันเสาร์"},
"ads.days.sunday":{en:"Sunday",pt:"Domingo",fr:"Dimanche",de:"Sonntag",it:"Domenica",nl:"Zondag",ja:"日曜日",zh:"星期日",ru:"Воскресенье",ar:"الأحد",hi:"रविवार",ko:"일요일",tr:"Pazar",pl:"Niedziela",sv:"Söndag",id:"Minggu",th:"วันอาทิตย์"},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2c (ads - 84 keys) done!');
