const fs = require('fs');
const path = require('path');
const messagesDir = path.join(__dirname, '..', 'messages');
const es = JSON.parse(fs.readFileSync(path.join(messagesDir, 'es.json'), 'utf8'));
function flatten(obj,p=''){const r={};for(const k in obj){const pp=p?`${p}.${k}`:k;if(typeof obj[k]==='object'&&obj[k]!==null)Object.assign(r,flatten(obj[k],pp));else r[pp]=obj[k];}return r;}
function unflatten(obj){const r={};for(const key in obj){const parts=key.split('.');let c=r;for(let i=0;i<parts.length-1;i++){if(!c[parts[i]])c[parts[i]]={};c=c[parts[i]];}c[parts[parts.length-1]]=obj[key];}return r;}
const esFlat=flatten(es);
const K={
// === MODERATION part 2 (remaining ~61 keys) ===
"moderation.warnings.noWarnings":{en:"No warnings",pt:"Nenhuma advertência",fr:"Aucun avertissement",de:"Keine Verwarnungen",it:"Nessun avvertimento",nl:"Geen waarschuwingen",ja:"警告なし",zh:"没有警告",ru:"Нет предупреждений",ar:"لا توجد تحذيرات",hi:"कोई चेतावनी नहीं",ko:"경고 없음",tr:"Uyarı yok",pl:"Brak ostrzeżeń",sv:"Inga varningar",id:"Tidak ada peringatan",th:"ไม่มีคำเตือน"},
"moderation.filters.title":{en:"Content Filters",pt:"Filtros de Conteúdo",fr:"Filtres de Contenu",de:"Inhaltsfilter",it:"Filtri di Contenuto",nl:"Inhoudsfilters",ja:"コンテンツフィルター",zh:"内容过滤器",ru:"Фильтры контента",ar:"فلاتر المحتوى",hi:"सामग्री फ़िल्टर",ko:"콘텐츠 필터",tr:"İçerik Filtreleri",pl:"Filtry Treści",sv:"Innehållsfilter",id:"Filter Konten",th:"ตัวกรองเนื้อหา"},
"moderation.filters.newFilter":{en:"New Filter",pt:"Novo Filtro",fr:"Nouveau Filtre",de:"Neuer Filter",it:"Nuovo Filtro",nl:"Nieuw Filter",ja:"新しいフィルター",zh:"新过滤器",ru:"Новый фильтр",ar:"فلتر جديد",hi:"नया फ़िल्टर",ko:"새 필터",tr:"Yeni Filtre",pl:"Nowy Filtr",sv:"Nytt Filter",id:"Filter Baru",th:"ตัวกรองใหม่"},
"moderation.filters.word":{en:"Word",pt:"Palavra",fr:"Mot",de:"Wort",it:"Parola",nl:"Woord",ja:"単語",zh:"词语",ru:"Слово",ar:"كلمة",hi:"शब्द",ko:"단어",tr:"Kelime",pl:"Słowo",sv:"Ord",id:"Kata",th:"คำ"},
"moderation.filters.url":{en:"URL",pt:"URL",fr:"URL",de:"URL",it:"URL",nl:"URL",ja:"URL",zh:"URL",ru:"URL",ar:"URL",hi:"URL",ko:"URL",tr:"URL",pl:"URL",sv:"URL",id:"URL",th:"URL"},
"moderation.filters.phrase":{en:"Phrase",pt:"Frase",fr:"Phrase",de:"Phrase",it:"Frase",nl:"Zin",ja:"フレーズ",zh:"短语",ru:"Фраза",ar:"عبارة",hi:"वाक्यांश",ko:"구문",tr:"İfade",pl:"Fraza",sv:"Fras",id:"Frasa",th:"วลี"},
"moderation.filters.pattern":{en:"Pattern",pt:"Padrão",fr:"Modèle",de:"Muster",it:"Pattern",nl:"Patroon",ja:"パターン",zh:"模式",ru:"Шаблон",ar:"نمط",hi:"पैटर्न",ko:"패턴",tr:"Desen",pl:"Wzorzec",sv:"Mönster",id:"Pola",th:"รูปแบบ"},
"moderation.filters.replacement":{en:"Replacement",pt:"Substituição",fr:"Remplacement",de:"Ersetzung",it:"Sostituzione",nl:"Vervanging",ja:"置換",zh:"替换",ru:"Замена",ar:"بديل",hi:"प्रतिस्थापन",ko:"대체",tr:"Değiştirme",pl:"Zamiennik",sv:"Ersättning",id:"Pengganti",th:"การแทนที่"},
"moderation.filters.regex":{en:"Regular expression",pt:"Expressão regular",fr:"Expression régulière",de:"Regulärer Ausdruck",it:"Espressione regolare",nl:"Reguliere expressie",ja:"正規表現",zh:"正则表达式",ru:"Регулярное выражение",ar:"تعبير نمطي",hi:"रेगुलर एक्सप्रेशन",ko:"정규 표현식",tr:"Düzenli ifade",pl:"Wyrażenie regularne",sv:"Reguljärt uttryck",id:"Ekspresi reguler",th:"นิพจน์ปกติ"},
"moderation.filters.inactive":{en:"Inactive",pt:"Inativo",fr:"Inactif",de:"Inaktiv",it:"Inattivo",nl:"Inactief",ja:"非アクティブ",zh:"非活跃",ru:"Неактивный",ar:"غير نشط",hi:"निष्क्रिय",ko:"비활성",tr:"Pasif",pl:"Nieaktywny",sv:"Inaktiv",id:"Tidak aktif",th:"ไม่ใช้งาน"},
"moderation.reports.title":{en:"Reports",pt:"Reportes",fr:"Signalements",de:"Meldungen",it:"Segnalazioni",nl:"Rapporten",ja:"報告",zh:"举报",ru:"Жалобы",ar:"البلاغات",hi:"रिपोर्ट",ko:"신고",tr:"Raporlar",pl:"Zgłoszenia",sv:"Rapporter",id:"Laporan",th:"รายงาน"},
"moderation.reports.pending":{en:"Pending",pt:"Pendentes",fr:"En attente",de:"Ausstehend",it:"In attesa",nl:"In behandeling",ja:"保留中",zh:"待处理",ru:"Ожидающие",ar:"معلقة",hi:"लंबित",ko:"대기 중",tr:"Beklemede",pl:"Oczekujące",sv:"Väntande",id:"Menunggu",th:"รอดำเนินการ"},
"moderation.reports.reviewing":{en:"Reviewing",pt:"Em revisão",fr:"En cours de révision",de:"In Prüfung",it:"In revisione",nl:"In beoordeling",ja:"レビュー中",zh:"审核中",ru:"На рассмотрении",ar:"قيد المراجعة",hi:"समीक्षा में",ko:"검토 중",tr:"İnceleniyor",pl:"W trakcie przeglądu",sv:"Under granskning",id:"Sedang ditinjau",th:"กำลังตรวจสอบ"},
"moderation.reports.resolved":{en:"Resolved",pt:"Resolvidos",fr:"Résolus",de:"Erledigt",it:"Risolti",nl:"Opgelost",ja:"解決済み",zh:"已解决",ru:"Решённые",ar:"تم حلها",hi:"हल किया गया",ko:"해결됨",tr:"Çözüldü",pl:"Rozwiązane",sv:"Lösta",id:"Diselesaikan",th:"แก้ไขแล้ว"},
"moderation.reports.dismissed":{en:"Dismissed",pt:"Descartados",fr:"Rejetés",de:"Abgewiesen",it:"Scartati",nl:"Afgewezen",ja:"却下",zh:"已驳回",ru:"Отклонённые",ar:"مرفوضة",hi:"खारिज",ko:"기각됨",tr:"Reddedildi",pl:"Odrzucone",sv:"Avvisade",id:"Ditolak",th:"ปฏิเสธแล้ว"},
"moderation.reports.priority":{en:"Priority",pt:"Prioridade",fr:"Priorité",de:"Priorität",it:"Priorità",nl:"Prioriteit",ja:"優先度",zh:"优先级",ru:"Приоритет",ar:"الأولوية",hi:"प्राथमिकता",ko:"우선순위",tr:"Öncelik",pl:"Priorytet",sv:"Prioritet",id:"Prioritas",th:"ลำดับความสำคัญ"},
"moderation.reports.category":{en:"Category",pt:"Categoria",fr:"Catégorie",de:"Kategorie",it:"Categoria",nl:"Categorie",ja:"カテゴリ",zh:"类别",ru:"Категория",ar:"الفئة",hi:"श्रेणी",ko:"카테고리",tr:"Kategori",pl:"Kategoria",sv:"Kategori",id:"Kategori",th:"หมวดหมู่"},
"moderation.reports.assignToMe":{en:"Assign to me",pt:"Atribuir a mim",fr:"M'attribuer",de:"Mir zuweisen",it:"Assegna a me",nl:"Aan mij toewijzen",ja:"自分に割り当て",zh:"分配给我",ru:"Назначить мне",ar:"تعيين لي",hi:"मुझे सौंपें",ko:"나에게 할당",tr:"Bana ata",pl:"Przypisz do mnie",sv:"Tilldela mig",id:"Tugaskan ke saya",th:"มอบหมายให้ฉัน"},
"moderation.reports.resolve":{en:"Resolve",pt:"Resolver",fr:"Résoudre",de:"Erledigen",it:"Risolvere",nl:"Oplossen",ja:"解決",zh:"解决",ru:"Решить",ar:"حل",hi:"हल करें",ko:"해결",tr:"Çöz",pl:"Rozwiąż",sv:"Lös",id:"Selesaikan",th:"แก้ไข"},
"moderation.reports.dismiss":{en:"Dismiss",pt:"Descartar",fr:"Rejeter",de:"Abweisen",it:"Scartare",nl:"Afwijzen",ja:"却下",zh:"驳回",ru:"Отклонить",ar:"رفض",hi:"खारिज करें",ko:"기각",tr:"Reddet",pl:"Odrzuć",sv:"Avvisa",id:"Tolak",th:"ปฏิเสธ"},
"moderation.roles.superMod":{en:"Super Moderator",pt:"Super Moderador",fr:"Super Modérateur",de:"Super Moderator",it:"Super Moderatore",nl:"Super Moderator",ja:"スーパーモデレーター",zh:"超级版主",ru:"Супер Модератор",ar:"مشرف عام",hi:"सुपर मॉडरेटर",ko:"슈퍼 관리자",tr:"Süper Moderatör",pl:"Super Moderator",sv:"Supermoderator",id:"Super Moderator",th:"ซูเปอร์ผู้ดูแล"},
"moderation.roles.countryMod":{en:"Country Moderator",pt:"Moderador de País",fr:"Modérateur de Pays",de:"Ländermoderator",it:"Moderatore di Paese",nl:"Landmoderator",ja:"国モデレーター",zh:"国家版主",ru:"Модератор страны",ar:"مشرف البلد",hi:"देश मॉडरेटर",ko:"국가 관리자",tr:"Ülke Moderatörü",pl:"Moderator Kraju",sv:"Landsmoderator",id:"Moderator Negara",th:"ผู้ดูแลประเทศ"},
"moderation.superBan.title":{en:"Super Ban",pt:"Super Expulsão",fr:"Super Bannissement",de:"Super Bann",it:"Super Espulsione",nl:"Super Verbanning",ja:"スーパーBAN",zh:"超级封禁",ru:"Супер Бан",ar:"حظر شامل",hi:"सुपर प्रतिबंध",ko:"슈퍼 차단",tr:"Süper Yasak",pl:"Super Ban",sv:"Superavstängning",id:"Super Blokir",th:"ซูเปอร์แบน"},
"moderation.superBan.warning":{en:"This action will permanently delete the user and all their content",pt:"Esta ação excluirá permanentemente o usuário e todo seu conteúdo",fr:"Cette action supprimera définitivement l'utilisateur et tout son contenu",de:"Diese Aktion wird den Benutzer und alle Inhalte dauerhaft löschen",it:"Questa azione eliminerà permanentemente l'utente e tutti i suoi contenuti",nl:"Deze actie verwijdert de gebruiker en alle inhoud permanent",ja:"この操作はユーザーとすべてのコンテンツを完全に削除します",zh:"此操作将永久删除用户及其所有内容",ru:"Это действие навсегда удалит пользователя и весь его контент",ar:"هذا الإجراء سيحذف المستخدم وجميع محتواه نهائياً",hi:"यह कार्रवाई उपयोगकर्ता और उनकी सभी सामग्री को स्थायी रूप से हटा देगी",ko:"이 작업은 사용자와 모든 콘텐츠를 영구적으로 삭제합니다",tr:"Bu eylem kullanıcıyı ve tüm içeriğini kalıcı olarak silecek",pl:"Ta akcja trwale usunie użytkownika i całą jego treść",sv:"Denna åtgärd tar permanent bort användaren och allt innehåll",id:"Tindakan ini akan menghapus pengguna dan semua kontennya secara permanen",th:"การดำเนินการนี้จะลบผู้ใช้และเนื้อหาทั้งหมดอย่างถาวร"},
"moderation.superBan.confirm":{en:"Are you absolutely sure?",pt:"Tem absoluta certeza?",fr:"Êtes-vous absolument sûr ?",de:"Sind Sie absolut sicher?",it:"Sei assolutamente sicuro?",nl:"Weet je het absoluut zeker?",ja:"本当によろしいですか？",zh:"您绝对确定吗？",ru:"Вы абсолютно уверены?",ar:"هل أنت متأكد تماماً؟",hi:"क्या आप बिल्कुल सुनिश्चित हैं?",ko:"정말 확실합니까?",tr:"Kesinlikle emin misiniz?",pl:"Czy jesteś absolutnie pewien?",sv:"Är du helt säker?",id:"Apakah Anda benar-benar yakin?",th:"คุณแน่ใจจริงๆ หรือไม่?"},
"moderation.deletePost":{en:"Delete post",pt:"Excluir post",fr:"Supprimer le post",de:"Beitrag löschen",it:"Elimina post",nl:"Bericht verwijderen",ja:"投稿を削除",zh:"删除帖子",ru:"Удалить пост",ar:"حذف المنشور",hi:"पोस्ट हटाएं",ko:"게시물 삭제",tr:"Gönderiyi sil",pl:"Usuń post",sv:"Ta bort inlägg",id:"Hapus postingan",th:"ลบโพสต์"},
"moderation.deleteThread":{en:"Delete thread",pt:"Excluir tópico",fr:"Supprimer le sujet",de:"Thema löschen",it:"Elimina thread",nl:"Onderwerp verwijderen",ja:"スレッドを削除",zh:"删除主题",ru:"Удалить тему",ar:"حذف الموضوع",hi:"थ्रेड हटाएं",ko:"스레드 삭제",tr:"Konuyu sil",pl:"Usuń wątek",sv:"Ta bort tråd",id:"Hapus thread",th:"ลบกระทู้"},
"moderation.lockThread":{en:"Lock thread",pt:"Bloquear tópico",fr:"Verrouiller le sujet",de:"Thema sperren",it:"Blocca thread",nl:"Onderwerp vergrendelen",ja:"スレッドをロック",zh:"锁定主题",ru:"Заблокировать тему",ar:"قفل الموضوع",hi:"थ्रेड लॉक करें",ko:"스레드 잠금",tr:"Konuyu kilitle",pl:"Zablokuj wątek",sv:"Lås tråd",id:"Kunci thread",th:"ล็อกกระทู้"},
"moderation.unlockThread":{en:"Unlock thread",pt:"Desbloquear tópico",fr:"Déverrouiller le sujet",de:"Thema entsperren",it:"Sblocca thread",nl:"Onderwerp ontgrendelen",ja:"スレッドのロック解除",zh:"解锁主题",ru:"Разблокировать тему",ar:"فتح الموضوع",hi:"थ्रेड अनलॉक करें",ko:"스레드 잠금 해제",tr:"Konunun kilidini aç",pl:"Odblokuj wątek",sv:"Lås upp tråd",id:"Buka kunci thread",th:"ปลดล็อกกระทู้"},
"moderation.suspendUser":{en:"Suspend user",pt:"Suspender usuário",fr:"Suspendre l'utilisateur",de:"Benutzer sperren",it:"Sospendi utente",nl:"Gebruiker schorsen",ja:"ユーザーを停止",zh:"暂停用户",ru:"Заблокировать пользователя",ar:"إيقاف المستخدم",hi:"उपयोगकर्ता निलंबित करें",ko:"사용자 정지",tr:"Kullanıcıyı askıya al",pl:"Zawieś użytkownika",sv:"Stäng av användare",id:"Tangguhkan pengguna",th:"ระงับผู้ใช้"},
"moderation.prohibitLinks":{en:"Prohibit links",pt:"Proibir links",fr:"Interdire les liens",de:"Links verbieten",it:"Proibisci link",nl:"Links verbieden",ja:"リンクを禁止",zh:"禁止链接",ru:"Запретить ссылки",ar:"حظر الروابط",hi:"लिंक प्रतिबंधित करें",ko:"링크 금지",tr:"Bağlantıları yasakla",pl:"Zabroń linków",sv:"Förbjud länkar",id:"Larang tautan",th:"ห้ามลิงก์"},
"moderation.banPermanently":{en:"Ban permanently",pt:"Banir permanentemente",fr:"Bannir définitivement",de:"Permanent bannen",it:"Espelli permanentemente",nl:"Permanent verbannen",ja:"永久追放",zh:"永久封禁",ru:"Забанить навсегда",ar:"حظر نهائياً",hi:"स्थायी रूप से प्रतिबंधित करें",ko:"영구 차단",tr:"Kalıcı olarak yasakla",pl:"Zbanuj permanentnie",sv:"Stäng av permanent",id:"Blokir permanen",th:"แบนถาวร"},
"moderation.deleteAllContent":{en:"Delete all content",pt:"Excluir todo o conteúdo",fr:"Supprimer tout le contenu",de:"Alle Inhalte löschen",it:"Elimina tutti i contenuti",nl:"Alle inhoud verwijderen",ja:"すべてのコンテンツを削除",zh:"删除所有内容",ru:"Удалить весь контент",ar:"حذف جميع المحتوى",hi:"सभी सामग्री हटाएं",ko:"모든 콘텐츠 삭제",tr:"Tüm içeriği sil",pl:"Usuń całą treść",sv:"Ta bort allt innehåll",id:"Hapus semua konten",th:"ลบเนื้อหาทั้งหมด"},
"moderation.postDeleted":{en:"Post deleted",pt:"Post excluído",fr:"Post supprimé",de:"Beitrag gelöscht",it:"Post eliminato",nl:"Bericht verwijderd",ja:"投稿が削除されました",zh:"帖子已删除",ru:"Пост удалён",ar:"تم حذف المنشور",hi:"पोस्ट हटाया गया",ko:"게시물 삭제됨",tr:"Gönderi silindi",pl:"Post usunięty",sv:"Inlägg borttaget",id:"Postingan dihapus",th:"ลบโพสต์แล้ว"},
"moderation.postDeleteError":{en:"Error deleting post",pt:"Erro ao excluir post",fr:"Erreur de suppression du post",de:"Fehler beim Löschen des Beitrags",it:"Errore nell'eliminazione del post",nl:"Fout bij verwijderen bericht",ja:"投稿の削除エラー",zh:"删除帖子出错",ru:"Ошибка удаления поста",ar:"خطأ في حذف المنشور",hi:"पोस्ट हटाने में त्रुटि",ko:"게시물 삭제 오류",tr:"Gönderi silme hatası",pl:"Błąd usuwania postu",sv:"Fel vid borttagning av inlägg",id:"Error menghapus postingan",th:"เกิดข้อผิดพลาดในการลบโพสต์"},
"moderation.threadDeleted":{en:"Thread deleted",pt:"Tópico excluído",fr:"Sujet supprimé",de:"Thema gelöscht",it:"Thread eliminato",nl:"Onderwerp verwijderd",ja:"スレッドが削除されました",zh:"主题已删除",ru:"Тема удалена",ar:"تم حذف الموضوع",hi:"थ्रेड हटाया गया",ko:"스레드 삭제됨",tr:"Konu silindi",pl:"Wątek usunięty",sv:"Tråd borttagen",id:"Thread dihapus",th:"ลบกระทู้แล้ว"},
"moderation.threadDeleteError":{en:"Error deleting thread",pt:"Erro ao excluir tópico",fr:"Erreur de suppression du sujet",de:"Fehler beim Löschen des Themas",it:"Errore nell'eliminazione del thread",nl:"Fout bij verwijderen onderwerp",ja:"スレッドの削除エラー",zh:"删除主题出错",ru:"Ошибка удаления темы",ar:"خطأ في حذف الموضوع",hi:"थ्रेड हटाने में त्रुटि",ko:"스레드 삭제 오류",tr:"Konu silme hatası",pl:"Błąd usuwania wątku",sv:"Fel vid borttagning av tråd",id:"Error menghapus thread",th:"เกิดข้อผิดพลาดในการลบกระทู้"},
"moderation.threadLocked":{en:"Thread locked",pt:"Tópico bloqueado",fr:"Sujet verrouillé",de:"Thema gesperrt",it:"Thread bloccato",nl:"Onderwerp vergrendeld",ja:"スレッドがロックされました",zh:"主题已锁定",ru:"Тема заблокирована",ar:"تم قفل الموضوع",hi:"थ्रेड लॉक किया गया",ko:"스레드 잠김",tr:"Konu kilitlendi",pl:"Wątek zablokowany",sv:"Tråd låst",id:"Thread dikunci",th:"ล็อกกระทู้แล้ว"},
"moderation.threadUnlocked":{en:"Thread unlocked",pt:"Tópico desbloqueado",fr:"Sujet déverrouillé",de:"Thema entsperrt",it:"Thread sbloccato",nl:"Onderwerp ontgrendeld",ja:"スレッドのロックが解除されました",zh:"主题已解锁",ru:"Тема разблокирована",ar:"تم فتح الموضوع",hi:"थ्रेड अनलॉक किया गया",ko:"스레드 잠금 해제됨",tr:"Konunun kilidi açıldı",pl:"Wątek odblokowany",sv:"Tråd upplåst",id:"Thread dibuka kuncinya",th:"ปลดล็อกกระทู้แล้ว"},
"moderation.threadModError":{en:"Error modifying thread",pt:"Erro ao modificar tópico",fr:"Erreur de modification du sujet",de:"Fehler beim Ändern des Themas",it:"Errore nella modifica del thread",nl:"Fout bij wijzigen onderwerp",ja:"スレッドの変更エラー",zh:"修改主题出错",ru:"Ошибка изменения темы",ar:"خطأ في تعديل الموضوع",hi:"थ्रेड संशोधन त्रुटि",ko:"스레드 수정 오류",tr:"Konu değiştirme hatası",pl:"Błąd modyfikacji wątku",sv:"Fel vid ändring av tråd",id:"Error mengubah thread",th:"เกิดข้อผิดพลาดในการแก้ไขกระทู้"},
"moderation.provideReason":{en:"You must provide a reason",pt:"Você deve fornecer um motivo",fr:"Vous devez fournir un motif",de:"Sie müssen einen Grund angeben",it:"Devi fornire un motivo",nl:"Je moet een reden opgeven",ja:"理由を入力してください",zh:"您必须提供原因",ru:"Необходимо указать причину",ar:"يجب تقديم سبب",hi:"आपको एक कारण देना होगा",ko:"사유를 입력해야 합니다",tr:"Bir sebep belirtmelisiniz",pl:"Musisz podać powód",sv:"Du måste ange en anledning",id:"Anda harus memberikan alasan",th:"คุณต้องระบุเหตุผล"},
"moderation.userSuspended":{en:"User suspended for {days} days",pt:"Usuário suspenso por {days} dias",fr:"Utilisateur suspendu pour {days} jours",de:"Benutzer für {days} Tage gesperrt",it:"Utente sospeso per {days} giorni",nl:"Gebruiker geschorst voor {days} dagen",ja:"ユーザーが{days}日間停止されました",zh:"用户已暂停{days}天",ru:"Пользователь заблокирован на {days} дней",ar:"المستخدم معلق لمدة {days} يوم",hi:"उपयोगकर्ता {days} दिनों के लिए निलंबित",ko:"사용자가 {days}일 정지됨",tr:"Kullanıcı {days} gün askıya alındı",pl:"Użytkownik zawieszony na {days} dni",sv:"Användare avstängd i {days} dagar",id:"Pengguna ditangguhkan selama {days} hari",th:"ผู้ใช้ถูกระงับ {days} วัน"},
"moderation.suspendError":{en:"Error suspending user",pt:"Erro ao suspender usuário",fr:"Erreur de suspension",de:"Fehler beim Sperren",it:"Errore nella sospensione",nl:"Fout bij schorsing",ja:"ユーザー停止エラー",zh:"暂停用户出错",ru:"Ошибка блокировки пользователя",ar:"خطأ في إيقاف المستخدم",hi:"निलंबन त्रुटि",ko:"사용자 정지 오류",tr:"Askıya alma hatası",pl:"Błąd zawieszenia",sv:"Avstängningsfel",id:"Error menangguhkan pengguna",th:"เกิดข้อผิดพลาดในการระงับผู้ใช้"},
"moderation.adminOnlyBan":{en:"Only administrators can ban users",pt:"Apenas administradores podem banir usuários",fr:"Seuls les administrateurs peuvent bannir",de:"Nur Administratoren können Benutzer bannen",it:"Solo gli amministratori possono espellere utenti",nl:"Alleen beheerders kunnen gebruikers verbannen",ja:"管理者のみがユーザーを追放できます",zh:"只有管理员可以封禁用户",ru:"Только администраторы могут банить пользователей",ar:"فقط المسؤولون يمكنهم حظر المستخدمين",hi:"केवल व्यवस्थापक उपयोगकर्ताओं को प्रतिबंधित कर सकते हैं",ko:"관리자만 사용자를 차단할 수 있습니다",tr:"Yalnızca yöneticiler kullanıcıları yasaklayabilir",pl:"Tylko administratorzy mogą banować",sv:"Endast administratörer kan stänga av användare",id:"Hanya administrator yang dapat memblokir pengguna",th:"เฉพาะผู้ดูแลระบบเท่านั้นที่สามารถแบนผู้ใช้ได้"},
"moderation.userBanned":{en:"User permanently banned",pt:"Usuário banido permanentemente",fr:"Utilisateur banni définitivement",de:"Benutzer permanent gebannt",it:"Utente espulso permanentemente",nl:"Gebruiker permanent verbannen",ja:"ユーザーが永久追放されました",zh:"用户已被永久封禁",ru:"Пользователь забанен навсегда",ar:"تم حظر المستخدم نهائياً",hi:"उपयोगकर्ता स्थायी रूप से प्रतिबंधित",ko:"사용자 영구 차단됨",tr:"Kullanıcı kalıcı olarak yasaklandı",pl:"Użytkownik permanentnie zbanowany",sv:"Användare permanent avstängd",id:"Pengguna diblokir permanen",th:"ผู้ใช้ถูกแบนถาวร"},
"moderation.banError":{en:"Error banning user",pt:"Erro ao banir usuário",fr:"Erreur de bannissement",de:"Fehler beim Bannen",it:"Errore nell'espulsione",nl:"Fout bij verbanning",ja:"ユーザー追放エラー",zh:"封禁用户出错",ru:"Ошибка бана пользователя",ar:"خطأ في حظر المستخدم",hi:"प्रतिबंध त्रुटि",ko:"사용자 차단 오류",tr:"Yasaklama hatası",pl:"Błąd banowania",sv:"Avstängningsfel",id:"Error memblokir pengguna",th:"เกิดข้อผิดพลาดในการแบนผู้ใช้"},
"moderation.adminOnlyDelete":{en:"Only administrators can delete all content",pt:"Apenas administradores podem excluir todo o conteúdo",fr:"Seuls les administrateurs peuvent supprimer tout le contenu",de:"Nur Administratoren können alle Inhalte löschen",it:"Solo gli amministratori possono eliminare tutti i contenuti",nl:"Alleen beheerders kunnen alle inhoud verwijderen",ja:"管理者のみがすべてのコンテンツを削除できます",zh:"只有管理员可以删除所有内容",ru:"Только администраторы могут удалить весь контент",ar:"فقط المسؤولون يمكنهم حذف جميع المحتوى",hi:"केवल व्यवस्थापक सभी सामग्री हटा सकते हैं",ko:"관리자만 모든 콘텐츠를 삭제할 수 있습니다",tr:"Yalnızca yöneticiler tüm içeriği silebilir",pl:"Tylko administratorzy mogą usunąć całą treść",sv:"Endast administratörer kan ta bort allt innehåll",id:"Hanya administrator yang dapat menghapus semua konten",th:"เฉพาะผู้ดูแลระบบเท่านั้นที่สามารถลบเนื้อหาทั้งหมดได้"},
"moderation.allContentDeleted":{en:"All user content has been deleted",pt:"Todo o conteúdo do usuário foi excluído",fr:"Tout le contenu de l'utilisateur a été supprimé",de:"Alle Benutzerinhalte wurden gelöscht",it:"Tutti i contenuti dell'utente sono stati eliminati",nl:"Alle gebruikersinhoud is verwijderd",ja:"ユーザーのすべてのコンテンツが削除されました",zh:"所有用户内容已被删除",ru:"Весь контент пользователя удалён",ar:"تم حذف جميع محتوى المستخدم",hi:"उपयोगकर्ता की सभी सामग्री हटा दी गई",ko:"모든 사용자 콘텐츠가 삭제되었습니다",tr:"Kullanıcının tüm içeriği silindi",pl:"Cała treść użytkownika została usunięta",sv:"Allt användarinnehåll har tagits bort",id:"Semua konten pengguna telah dihapus",th:"เนื้อหาทั้งหมดของผู้ใช้ถูกลบแล้ว"},
"moderation.linksAllowed":{en:"User can post links",pt:"Usuário pode publicar links",fr:"L'utilisateur peut publier des liens",de:"Benutzer kann Links posten",it:"L'utente può pubblicare link",nl:"Gebruiker kan links plaatsen",ja:"ユーザーはリンクを投稿できます",zh:"用户可以发布链接",ru:"Пользователь может публиковать ссылки",ar:"المستخدم يمكنه نشر روابط",hi:"उपयोगकर्ता लिंक पोस्ट कर सकता है",ko:"사용자가 링크를 게시할 수 있습니다",tr:"Kullanıcı bağlantı paylaşabilir",pl:"Użytkownik może publikować linki",sv:"Användare kan publicera länkar",id:"Pengguna dapat memposting tautan",th:"ผู้ใช้สามารถโพสต์ลิงก์ได้"},
"moderation.linksForbidden":{en:"Links forbidden for this user",pt:"Links proibidos para este usuário",fr:"Liens interdits pour cet utilisateur",de:"Links für diesen Benutzer verboten",it:"Link vietati per questo utente",nl:"Links verboden voor deze gebruiker",ja:"このユーザーのリンクは禁止されています",zh:"禁止此用户发布链接",ru:"Ссылки запрещены для этого пользователя",ar:"الروابط محظورة لهذا المستخدم",hi:"इस उपयोगकर्ता के लिए लिंक प्रतिबंधित",ko:"이 사용자의 링크 금지",tr:"Bu kullanıcı için bağlantılar yasak",pl:"Linki zabronione dla tego użytkownika",sv:"Länkar förbjudna för denna användare",id:"Tautan dilarang untuk pengguna ini",th:"ห้ามลิงก์สำหรับผู้ใช้นี้"},
"moderation.permissionError":{en:"Error modifying permissions",pt:"Erro ao modificar permissões",fr:"Erreur de modification des permissions",de:"Fehler beim Ändern der Berechtigungen",it:"Errore nella modifica dei permessi",nl:"Fout bij wijzigen machtigingen",ja:"権限変更エラー",zh:"修改权限出错",ru:"Ошибка изменения прав",ar:"خطأ في تعديل الصلاحيات",hi:"अनुमति संशोधन त्रुटि",ko:"권한 수정 오류",tr:"Yetki değiştirme hatası",pl:"Błąd modyfikacji uprawnień",sv:"Fel vid behörighetsändring",id:"Error mengubah izin",th:"เกิดข้อผิดพลาดในการแก้ไขสิทธิ์"},
"moderation.suspendTitle":{en:"Suspend user",pt:"Suspender usuário",fr:"Suspendre l'utilisateur",de:"Benutzer sperren",it:"Sospendi utente",nl:"Gebruiker schorsen",ja:"ユーザーを停止",zh:"暂停用户",ru:"Заблокировать пользователя",ar:"إيقاف المستخدم",hi:"उपयोगकर्ता को निलंबित करें",ko:"사용자 정지",tr:"Kullanıcıyı askıya al",pl:"Zawieś użytkownika",sv:"Stäng av användare",id:"Tangguhkan pengguna",th:"ระงับผู้ใช้"},
"moderation.suspendDesc":{en:"The user will not be able to access the forum during the suspension period.",pt:"O usuário não poderá acessar o fórum durante o período de suspensão.",fr:"L'utilisateur ne pourra pas accéder au forum pendant la période de suspension.",de:"Der Benutzer kann während der Sperrzeit nicht auf das Forum zugreifen.",it:"L'utente non potrà accedere al forum durante il periodo di sospensione.",nl:"De gebruiker kan het forum niet betreden tijdens de schorsing.",ja:"停止期間中、ユーザーはフォーラムにアクセスできません。",zh:"用户在暂停期间将无法访问论坛。",ru:"Пользователь не сможет получить доступ к форуму в период блокировки.",ar:"لن يتمكن المستخدم من الوصول إلى المنتدى خلال فترة الإيقاف.",hi:"निलंबन अवधि के दौरान उपयोगकर्ता फ़ोरम तक नहीं पहुंच पाएगा।",ko:"정지 기간 동안 사용자는 포럼에 접근할 수 없습니다.",tr:"Kullanıcı askı süresi boyunca foruma erişemeyecektir.",pl:"Użytkownik nie będzie miał dostępu do forum w czasie zawieszenia.",sv:"Användaren kommer inte att kunna komma åt forumet under avstängningsperioden.",id:"Pengguna tidak akan dapat mengakses forum selama masa penangguhan.",th:"ผู้ใช้จะไม่สามารถเข้าถึงฟอรั่มได้ในช่วงระงับ"},
"moderation.durationDays":{en:"Duration (days)",pt:"Duração (dias)",fr:"Durée (jours)",de:"Dauer (Tage)",it:"Durata (giorni)",nl:"Duur (dagen)",ja:"期間（日）",zh:"期限（天）",ru:"Длительность (дней)",ar:"المدة (أيام)",hi:"अवधि (दिन)",ko:"기간 (일)",tr:"Süre (gün)",pl:"Czas trwania (dni)",sv:"Varaktighet (dagar)",id:"Durasi (hari)",th:"ระยะเวลา (วัน)"},
"moderation.reasonPlaceholder":{en:"Explain the reason for suspension...",pt:"Explique o motivo da suspensão...",fr:"Expliquez le motif de la suspension...",de:"Erklären Sie den Grund der Sperrung...",it:"Spiega il motivo della sospensione...",nl:"Leg de reden van de schorsing uit...",ja:"停止の理由を説明してください...",zh:"说明暂停原因...",ru:"Объясните причину блокировки...",ar:"اشرح سبب الإيقاف...",hi:"निलंबन का कारण बताएं...",ko:"정지 사유를 설명하세요...",tr:"Askıya alma nedenini açıklayın...",pl:"Wyjaśnij powód zawieszenia...",sv:"Förklara anledningen till avstängningen...",id:"Jelaskan alasan penangguhan...",th:"อธิบายเหตุผลของการระงับ..."},
"moderation.processing":{en:"Processing...",pt:"Processando...",fr:"Traitement...",de:"Wird verarbeitet...",it:"Elaborazione...",nl:"Verwerken...",ja:"処理中...",zh:"处理中...",ru:"Обработка...",ar:"جاري المعالجة...",hi:"प्रोसेसिंग...",ko:"처리 중...",tr:"İşleniyor...",pl:"Przetwarzanie...",sv:"Bearbetar...",id:"Memproses...",th:"กำลังประมวลผล..."},
"moderation.suspend":{en:"Suspend",pt:"Suspender",fr:"Suspendre",de:"Sperren",it:"Sospendi",nl:"Schorsen",ja:"停止",zh:"暂停",ru:"Заблокировать",ar:"إيقاف",hi:"निलंबित करें",ko:"정지",tr:"Askıya al",pl:"Zawieś",sv:"Stäng av",id:"Tangguhkan",th:"ระงับ"},
"moderation.confirmDelete":{en:"Confirm deletion",pt:"Confirmar exclusão",fr:"Confirmer la suppression",de:"Löschung bestätigen",it:"Conferma eliminazione",nl:"Verwijdering bevestigen",ja:"削除を確認",zh:"确认删除",ru:"Подтвердить удаление",ar:"تأكيد الحذف",hi:"हटाने की पुष्टि करें",ko:"삭제 확인",tr:"Silmeyi onayla",pl:"Potwierdź usunięcie",sv:"Bekräfta borttagning",id:"Konfirmasi penghapusan",th:"ยืนยันการลบ"},
"moderation.confirmDeleteDesc":{en:"This action cannot be undone. Are you sure you want to delete this content?",pt:"Esta ação não pode ser desfeita. Tem certeza de que deseja excluir este conteúdo?",fr:"Cette action est irréversible. Êtes-vous sûr de vouloir supprimer ce contenu ?",de:"Diese Aktion kann nicht rückgängig gemacht werden. Sind Sie sicher?",it:"Questa azione non può essere annullata. Sei sicuro di voler eliminare?",nl:"Deze actie kan niet ongedaan worden gemaakt. Weet je het zeker?",ja:"この操作は元に戻せません。このコンテンツを削除してもよろしいですか？",zh:"此操作无法撤销。您确定要删除此内容吗？",ru:"Это действие нельзя отменить. Вы уверены, что хотите удалить этот контент?",ar:"لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد من حذف هذا المحتوى؟",hi:"यह कार्रवाई पूर्ववत नहीं की जा सकती। क्या आप सुनिश्चित हैं?",ko:"이 작업은 되돌릴 수 없습니다. 삭제하시겠습니까?",tr:"Bu eylem geri alınamaz. Bu içeriği silmek istediğinizden emin misiniz?",pl:"Tej akcji nie można cofnąć. Czy na pewno chcesz usunąć tę treść?",sv:"Denna åtgärd kan inte ångras. Är du säker?",id:"Tindakan ini tidak dapat dibatalkan. Apakah Anda yakin ingin menghapus?",th:"การดำเนินการนี้ไม่สามารถย้อนกลับได้ คุณแน่ใจหรือไม่?"},
"moderation.reasonOptional":{en:"Reason (optional)",pt:"Motivo (opcional)",fr:"Motif (optionnel)",de:"Grund (optional)",it:"Motivo (opzionale)",nl:"Reden (optioneel)",ja:"理由（任意）",zh:"原因（可选）",ru:"Причина (необязательно)",ar:"السبب (اختياري)",hi:"कारण (वैकल्पिक)",ko:"사유 (선택사항)",tr:"Sebep (isteğe bağlı)",pl:"Powód (opcjonalnie)",sv:"Anledning (valfritt)",id:"Alasan (opsional)",th:"เหตุผล (ไม่จำเป็น)"},
"moderation.deleteReasonPlaceholder":{en:"Reason for deletion...",pt:"Motivo da exclusão...",fr:"Motif de la suppression...",de:"Grund der Löschung...",it:"Motivo dell'eliminazione...",nl:"Reden voor verwijdering...",ja:"削除の理由...",zh:"删除原因...",ru:"Причина удаления...",ar:"سبب الحذف...",hi:"हटाने का कारण...",ko:"삭제 사유...",tr:"Silme nedeni...",pl:"Powód usunięcia...",sv:"Anledning till borttagning...",id:"Alasan penghapusan...",th:"เหตุผลในการลบ..."},
};
const targetLangs=['en','pt','fr','de','it','nl','ja','zh','ru','ar','hi','ko','tr','pl','sv','id','th'];
for(const lang of targetLangs){
  const fp=path.join(messagesDir,`${lang}.json`);
  const data=JSON.parse(fs.readFileSync(fp,'utf8'));
  const df=flatten(data);
  let ch=0;
  for(const key in K){
    if(esFlat[key]){
      const cv=df[key];
      if(cv===undefined||cv===esFlat[key]){
        if(K[key][lang]){df[key]=K[key][lang];ch++;}
      }
    }
  }
  if(ch>0){fs.writeFileSync(fp,JSON.stringify(unflatten(df),null,2)+'\n','utf8');console.log(`${lang.toUpperCase()}: ${ch}`);}
  else console.log(`${lang.toUpperCase()}: 0`);
}
console.log('Fase 2b (moderation part 2 - 61 keys) done!');
